### ISSUE TITLE
power显示已领取，但不增长

### ISSUE THREAD

**Issue by dengxuezhao** [RSSNext/Follow#1000]
### Describe the bug

一直签到，但power停在80

### Feed Info

martingale

### App Type

Web

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
You can temporarily try to refresh manually

![ScreenShot 2024-10-18 08 42 47](https://github.com/user-attachments/assets/a8f8fc5c-1149-4aa5-8be2-0a2ac8e65fb3)

**Comment by whitewatercn** [comment]
> You can temporarily try to refresh manually
> 
> ![ScreenShot 2024-10-18 08 42 47](https://private-user-images.githubusercontent.com/38493346/377674786-a8f8fc5c-1149-4aa5-8be2-0a2ac8e65fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTIzNDcsIm5iZiI6MTcyOTM5MjA0NywicGF0aCI6Ii8zODQ5MzM0Ni8zNzc2NzQ3ODYtYThmOGZjNWMtMTE0OS00YWE1LThiZTItMGEyYWM4ZTY1ZmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAyNDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZTcwY2QzYjBiMjYxN2I5OTUyMjlkMzhlMDMwZTNhNWJkZTU5ZTk0NGRhYTdiZTQ5OTJhZmEzYjdmMmUxMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NlixIx2mXq4UJDW5-ECm8BUCClRfAdCcLiUmYMPNk7A)

我也遇到过，点这个刷新就好了

**Comment by dengxuezhao** [comment]
> > You can temporarily try to refresh manually
> > ![ScreenShot 2024-10-18 08 42 47](https://private-user-images.githubusercontent.com/38493346/377674786-a8f8fc5c-1149-4aa5-8be2-0a2ac8e65fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTIzNDcsIm5iZiI6MTcyOTM5MjA0NywicGF0aCI6Ii8zODQ5MzM0Ni8zNzc2NzQ3ODYtYThmOGZjNWMtMTE0OS00YWE1LThiZTItMGEyYWM4ZTY1ZmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAyNDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZTcwY2QzYjBiMjYxN2I5OTUyMjlkMzhlMDMwZTNhNWJkZTU5ZTk0NGRhYTdiZTQ5OTJhZmEzYjdmMmUxMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NlixIx2mXq4UJDW5-ECm8BUCClRfAdCcLiUmYMPNk7A)
> 
> 我也遇到过，点这个刷新就好了

我刷新了一下，数据还是对不上。自上次购买邀请后的签到已经有240了，还是少4天的哈哈。
<img width="925" alt="image" src="https://github.com/user-attachments/assets/92a98c92-9e98-49fb-90a2-e171bd59b3ea">

**Comment by DIYgod** [comment]
Could you send me your wallet address or user ID? @dengxuezhao

**Comment by DIYgod** [comment]
I reviewed the on-chain transaction records and noticed that some transactions for purchasing invitation codes deduct several hundred power. However, I didn't find anything unusual. https://scan.rss3.io/address/0x3811d943FB59abd61c10989fAD02840bC97297B4?tab=txs
