### ISSUE TITLE
certified my self-built feed, but did not receive the 100power after certification

### ISSUE THREAD

**Issue by yuanxing008** [RSSNext/Follow#1006]
### Describe the bug

成功认证了自己的自建订阅源，但是没有收到认证后的100power

### Feed Info

https://app.follow.is/feed/69650595218752512

### App Type

Web

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
