### ISSUE TITLE
If the title contains & , it reports error

### ISSUE THREAD

**Issue by mrmign** [RSSNext/Follow#1007]
### Describe the bug

<img width="486" alt="image" src="https://github.com/user-attachments/assets/e1b9a026-1480-4310-9d86-2e10310cbeba">
### Environment

**App Version**: 0.0.1-alpha.21
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.21 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

https://engineering.linecorp.com/en/blog

### App Type

Electron / App

### Version

0.0.1-alpha.21

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is a webpage, not a RSS feed.
