### ISSUE TITLE
Subscribe to other people's collections without updating in reverse order

### ISSUE THREAD

**Issue by JohnnyWoong** [RSSNext/Follow#1008]
### Describe the bug

订阅别人创建的合集, 浏览时发现好像是按照更新时间+订阅源排序, 而不是单纯的按照更新时间排序, 不符合正常观看的排序逻辑

### Feed Info

69260144345565184

### App Type

Web

### Version

0.0.1-alpha.21

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
The current sorting is based on the time the articles were inserted into the database, which is determined by the database architecture, and it cannot be modified in the short term.
