### ISSUE TITLE
git pull 最新版，Power 页面报错 TypeError: Cannot convert null to a BigInt at BigInt

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#1012]
### Describe the bug

git pull 了最新的版本
进入 Power 页面报错
![image](https://github.com/user-attachments/assets/ec9b9ad0-1c7c-4279-9105-f1a20806d9c7)

### Feed Info

。

### App Type

Web

### Version

newest

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Sorry, you need the latest server code to access

**Comment by jerryc127** [comment]
> Sorry, you need the latest server code to access

What's the meaning? Do I need to wait for you to update the server code?

**Comment by hyoban** [comment]
Yes, waiting for the next release
