### ISSUE TITLE
New [keyword highlighting]

### ISSUE THREAD

**Issue by yestoday2009** [RSSNext/Follow#1013]
### Clear and concise description of the problem

希望RSS应用能够支持关键词高亮功能。
用户可以设置特定的关键词，当这些关键词在文章或摘要中出现时，能够自动高亮显示，帮助用户快速识别重点内容

### Suggested solution

1. 提供简单的界面，允许用户添加/编辑关键词。 
2. 允许自定义每个关键词的高亮颜色（可选，但非常实用）。 大小写是否敏感。
3. 在文章标题、摘要以及全文中自动高亮关键词。 
4. （可选）当文章中包含高亮关键词时，提供通知或其他醒目标识。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #803
