### ISSUE TITLE
"Follow is not yet supported on mobile devices" message when using a tilling window manager

### ISSUE THREAD

**Issue by 1235467** [RSSNext/Follow#1017]
### Describe the bug

When opening the web app and one other application on tilling manager, the follow web app refuse to work due to device width (in my case it says 637px). I think there's a better way to handle this. 

Suggestions: 
1. detect the web browser user agent and show a better message
2. why not just hide the side bar in this case? Add a button to recover that side bar and after user mouse leave side bar, hide it again. In this case the side bar can cover part of the content so that it looks better.

### Feed Info

None

### App Type

Web

### Version

0.0.1-alpha.21

### Operating System

Linux

### Browser Info

Firefox, 130.0.1

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by systemoutprintlnhelloworld** [comment]
cant agree  more, it is comfortable read feeds in edge sidebar rather than in a normal tab,but in this way i cant implement it

**Comment by Innei** [comment]
We plan to design a responsive page for mobile view.
