### ISSUE TITLE
my android follow didn't sync with my web version in same account

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [RSSNext/Follow#1020]
### Describe the bug

today i log in with my android follow(version 1.0.0), i forget how i get from,but once i get the invitation i sign in but it has limit the device screen width so i can't enter
but today i successfully log in,but their is nothing but a black empty in their,but my account has so many rss feed isn't sync into my android follow! 
here is the diff between web and mobile version(btw,this mobile version is not running on simulator device,its just a cast from my phone)

![image](https://github.com/user-attachments/assets/605c78ac-733d-4d1e-b938-fa2a6924c398)

### Feed Info

no more

### Reproduction Video

![反馈follow](https://github.com/user-attachments/assets/8338cf09-e5fd-4d2a-ae5d-c23add3337e7)

### App Type

Electron / App

### Version

1.0.0

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
We haven’t launched an official mobile app yet
