### ISSUE TITLE
I can’t wait to experience this product, but I don’t have an invitation code. Please send me an invitation code. I’d be very grateful. Thanks: wukongme6@gmail.com

### ISSUE THREAD

**Issue by sw2s** [RSSNext/Follow#1026]
### Clear and concise description of the problem

迫不及待的想体验这款产品，奈何没有邀请码，求送一个邀请码，万分感谢： wukongme6@gmail.com

### Suggested solution

迫不及待的想体验这款产品，奈何没有邀请码，求送一个邀请码，万分感谢： wukongme6@gmail.com

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Issue is not a place to request invitation codes, thank you
