### ISSUE TITLE
I hope I can set a filter for the subscription source.

### ISSUE THREAD

**Issue by ydniuyongjie** [RSSNext/Follow#1031]
### Clear and concise description of the problem

I hope that I can set filters for subscription sources. For example, when subscribing to a news website, I don't care about entertainment news, so I can set a filter to filter out information that I'm not interested in.

### Suggested solution

I hope that I can set filters for subscription sources. For example, when subscribing to a news website, I don't care about entertainment news, so I can set a filter to filter out information that I'm not interested in.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ydniuyongjie** [comment]
When I consult some scientific papers, I also want to block some research directions that I'm not interested in.

**Comment by ydniuyongjie** [comment]
I used the RSSowl software to set up filters for each subscription. This is a very useful feature.

**Comment by TonyRL** [comment]
#685

**Comment by DIYgod** [comment]
You can achieve this using the block rules in actions.
