### ISSUE TITLE
Automated comprehensive improvement suggestions

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1035]
### Clear and concise description of the problem

**1❏支持大小写敏感选项（区分大小写或不区分）**
描述：现在自动化条件没有区分大小写的功能，这样可能导致匹配不准确。
建议：在条件设置中添加一个选项，让用户选择是否要区分大小写？这样匹配会更准确。

**2❏规则启用/禁用切换**
问题描述：现在没有办法临时禁用某些规则，管理起来不太方便。
建议：给每个规则加个启用/禁用的开关，这样用户可以快速管理规则。

**3❏自动化入口调整**
问题描述：现在自动化功能藏在设置里，进出都很麻烦。自动化是RSS最重要的功能，使用率极高，希望能有个更方便的入口。
建议：将自动化功能入口放在主页等方便进入的地方。

![image](https://github.com/user-attachments/assets/f2b2e888-3991-4c0f-a724-bcd25146dd43)

**4❏自动化独立的UI布局**
问题描述：承接上一条，现在的自动化默认窗口很小很拥挤，每次都手动调大。调大了也不好用，因为显示太多用不到的执行动作（第五点建议会提到），和最令人难以忍受的折叠元素。
建议：为自动化提供一个专门的用户界面布局，从设置分离，新的自动化界面布局默认情况下应该简约且窗口宽大，采用双栏或三栏目设计，减少折叠元素，默认为展开。下面一条建议提供更多思路

**5❏用户按需添加执行动作**
问题描述：现在自动化界面上显示所有可用的执行动作，感觉很乱，有些动作可能根本用不到。
建议：在新建规则时，默认是空白的，增加“添加动作”按钮，让用户按需选择添加执行动作，从而简化界面，提高用户体验。

### Suggested solution

X

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
- 2 is now supported
