### ISSUE TITLE
save to Obsidian error in browser environment

### ISSUE THREAD

**Issue by cuikaipeng** [RSSNext/Follow#1038]
### Describe the bug

save to Obsidian error in browser environment
<img width="954" alt="iShot_2024-10-21_11 48 52" src="https://github.com/user-attachments/assets/d6129e86-bd9a-49e1-b99d-ced71471f74e">

I saw that this PR https://github.com/RSSNext/Follow/pull/998 has added a feat that can saving to Obsidian, but it will report an error in the browser environment. 
I think it should only be used in the client situation
I think either hide the button here or give a prompt after clicking it
If necessary, I can contribute PR

### Feed Info

this issue does not require feed info

### App Type

Web

### Version

0.0.1-alpha

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Of course, feel free to submit a PR

**Comment by cuikaipeng** [comment]
> Of course, feel free to submit a PR. Just hide it in your browser.

ok

**Comment by mydjin** [comment]
Is this issue about errors like not saving the original text? I currently use Follow to save to Obsidian, some of the original text can be saved, and some cannot be saved in reading mode.
![20241103182931](https://github.com/user-attachments/assets/559eb03a-31ca-41f1-99bf-b50bb1d01480)

**Comment by cuikaipeng** [comment]
> Is this issue about errors like not saving the original text? I currently use Follow to save to Obsidian, some of the original text can be saved, and some cannot be saved in reading mode. ![20241103182931](https://github.com/user-attachments/assets/559eb03a-31ca-41f1-99bf-b50bb1d01480)

I don't think the problem you mentioned is related to this issue. This issue is about not being able to save to Obsidian in a browser environment
