### ISSUE TITLE
a feedlink cannot be fetched

### ISSUE THREAD

**Issue by cdxiaodong** [RSSNext/Follow#1042]
### Describe the bug

https://blog.csdn.net/qq_41904294/rss/list   cannot be fetched

### Feed Info

https://blog.csdn.net/qq_41904294/rss/list 

### App Type

Web

### Version

1.0.0

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Works for me.

https://app.follow.is/feed/71106419920781312

**Comment by cdxiaodong** [comment]
只能通过访问https://app.follow.is/feed/71106419920781312 去订阅 
无论是web还是app的控件都无法去订阅它

**Comment by hyoban** [comment]
I'm not sure about your situation, but it looks like this feed was created by me after seeing this issue without any difficulty.

Anyway, you should be able to successfully subscribe to this feed now, right?

**Comment by TonyRL** [comment]
FYI, the feed URL is `https://rss.csdn.net/qq_41904294/rss/map`

**Comment by cdxiaodong** [comment]
it does work, thanks
