### ISSUE TITLE
Feed 获取错误: [GET] "http://10.1.32.41/changba/76435275?format=json": 503 Service Unavailable

### ISSUE THREAD

**Issue by jaychoubaby** [RSSNext/Follow#1043]
### Describe the bug

唱吧服务不可用

### Feed Info

76435275

### App Type

Electron / App

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This does not look like a correct userid, please see https://docs.rsshub.app/routes/social-media#%E5%94%B1%E5%90%A7

Feel free to reopen this issue with more info.

**Comment by jaychoubaby** [comment]
> This does not look like a correct userid, please see https://docs.rsshub.app/routes/social-media#%E5%94%B1%E5%90%A7
> 
> 
> 
> Feel free to reopen this issue with more info.

http://changba.com/u/76435275

这是我主页的完整地址，你可以通过它打开，我参考你给的文档看到也是如此
