### ISSUE TITLE
A problem was found in the version after the 17th. Posting and commenting in a certain RSS feed indicated high risk Behavior

### ISSUE THREAD

**Issue by Cvsly** [RSSNext/Follow#1046]
### Describe the bug

从[Nightly 0.0.1-nightly.20241020]这个版本开始，某个人订阅源内发布和评论提示高危行为（点击查看原文），安装回0.0.1-nightly.20241017或之前版本则正常
问题Rss来源：https://rss.nodeseek.com/
![Uploading image.png…]()

### Feed Info

问题Rss来源：https://rss.nodeseek.com/

### App Type

Electron / App

### Version

Nightly 0.0.1-nightly.20241020

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Cvsly** [comment]
![image](https://github.com/user-attachments/assets/f4d8d7c5-27ff-455c-a724-5e2ced8f8964)

**Comment by hyoban** [comment]
![ScreenShot 2024-10-21 19 24 05](https://github.com/user-attachments/assets/73f24799-1f29-4af7-b72e-10097d540adf)

Can not reproduce it, this may related to your network status, feel free to reopen this issue with more info.

**Comment by hyoban** [comment]
I can't register an account for this forum. It requires an invitation code. I can't try to reproduce your problem.

**Comment by DIYgod** [comment]
This prompt is not from follow, you may need to consult the administrator of this website.
