### ISSUE TITLE
Douban topic is not updated

### ISSUE THREAD

**Issue by haowenwu** [RSSNext/Follow#1048]
### Describe the bug

rss已经有新内容了，但是follow里面还是旧的，只有一条

### Feed Info

rsshub://douban/topic/84494
rsshub://douban/people/29449961/status

### App Type

Web

### Version

727BA56

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
The feed refresh time of RSSHub is 30min-180min, and the normal RSS is 15min-90min.

**Comment by haowenwu** [comment]
> The feed refresh time of RSSHub is 30min-180min, and the normal RSS is 15min-90min.

But the article in follow is about two days ago ..

**Comment by haowenwu** [comment]
> The feed refresh time of RSSHub is 30min-180min, and the normal RSS is 15min-90min.

https://app.follow.is/feed/70369401023083520
https://www.douban.com/gallery/topic/84494/?sort=new

**Comment by hyoban** [comment]
The RSS's output of guid is not unique.
