### ISSUE TITLE
The latest dev has several bugs

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#1049]
### Describe the bug

最新 dev 有 2 個 bug

1. 頂欄會被遮住/或者太靠近內容
![image](https://github.com/user-attachments/assets/57b0f8bc-d7e8-4da3-b72a-e70dee596c23)
![image](https://github.com/user-attachments/assets/8ef87f73-584a-41e9-a838-3c3fdced5021)

2.  無法滾動
![image](https://github.com/user-attachments/assets/7ec8e35c-db74-4953-af9f-ca876cc5770c)

3. 設置-訂閲源列表不應該平均攔寬，名稱應該寬度大點

![image](https://github.com/user-attachments/assets/f9d644f0-a743-46cf-bb6f-c60c56fadf9e)

4. 不清楚是不是 bug
![image](https://github.com/user-attachments/assets/cd273c8d-fdc5-4ebe-83ff-06468038a0dd)

### Feed Info

。

### App Type

Web

### Version

newest

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
- 1 fixed in https://github.com/RSSNext/Follow/pull/1051

**Comment by jerryc127** [comment]
![PixPin_2024-10-22_13-41-45](https://github.com/user-attachments/assets/0e4e25f8-e7cc-43a2-a929-13381b0b9c8e)
@hyoban 還是有點問題

**Comment by jerryc127** [comment]
第2條 我在那個區域有鼠標總結左右點擊都沒發拖動

還有一個 bug

就是 list 的連接怎麼變成了https://app.follow.is/share/lists/61348999275735040
點擊進入顯示 You have come to a desert of knowledge where there is nothing.

https://app.follow.is/list/61348999275735040?view=0 這個才是顯示正常

**Comment by hyoban** [comment]
If you want to scroll horizontally, you need to hold down shift and scroll the mouse wheel, or use the trackpad
