### ISSUE TITLE
Article citation type garbled

### ISSUE THREAD

**Issue by Looyank** [RSSNext/Follow#1053]
### Describe the bug

![image](https://github.com/user-attachments/assets/5dadcfad-eea4-4b4b-a1ad-4b0645d0c36f)

![image](https://github.com/user-attachments/assets/44362a0d-3644-4565-8f53-39fdcece3a8b)

### Feed Info

https://tumutanzi.com/archives/17445

### App Type

Electron / App

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I think this is the same as https://github.com/RSSNext/Follow/issues/1047 but I can't reproduce

**Comment by Looyank** [comment]
> I think this is the same as #1047 but I can't reproduce
>
> ! [ScreenShot 2024-10-22 10 15 36](https://private-user-images.githubusercontent.com/38493346/378654550-457aee32-b489-47db-91f5-10c676da1ce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjM4MDAsIm5iZiI6MTcyOTU2MzUwMCwicGF0aCI6Ii8zODQ5MzM0Ni8zNzg2NTQ1NTAtNDU3YWVlMzItYjQ4OS00N2RiLTkxZjUtMTBjNjc2ZGExY2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAyMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZWE2YjBlNzJhOWEzMzM4MDkyNzgzZGVjZWM0ZGNkMjBhMTEyM2Y3NDBjNzZiN2QyOTI5MjQ2MTUzN2FmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QwzXENrvVrE4RyyJlMXaJ5fXhldJB3JKQdzPD6p_4XI)


Yes, I can't reproduce it even after rebooting, I can't give more info at the moment, I'll close it.
