### ISSUE TITLE
support tiny-tiny-rss database import

### ISSUE THREAD

**Issue by write3371** [RSSNext/Follow#1055]
### Clear and concise description of the problem

support tiny-tiny-rss database import

### Suggested solution

including bookmark articles and notes that may not come from any rss subscriptions

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
You can import your subscriptions through an OPML file, which is the most common method, and I believe tiny-tiny-rss also has the function to export OPML.
