### ISSUE TITLE
Hope the desktop client has a built-in translation feature

### ISSUE THREAD

**Issue by tahitimoon** [RSSNext/Follow#1071]
### Clear and concise description of the problem

Hope the desktop client has a built-in translation feature, similar to Twitter's one-click translation, which makes it easy to view various articles and tweets

### Suggested solution

Hope the desktop client has a built-in translation feature, similar to Twitter's one-click translation, which makes it easy to view various articles and tweets

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #770
