### ISSUE TITLE
power提现到以太坊失败

### ISSUE THREAD

**Issue by Asunfly** [RSSNext/Follow#1077]
### Describe the bug

![image](https://github.com/user-attachments/assets/562426a9-ea1a-4153-b158-5e1a33d4f037)

### Environment

**App Version**: 0.0.1-nightly.20241015
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-nightly.20241015 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

### App Type

Electron / App

### Version

0.0.1-nightly.20241015

### Operating System

Windows 11

### Browser Info

Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.

**Comment by i-artist** [comment]
still withdraw error
