### ISSUE TITLE
It's just give me 16 powers Today

### ISSUE THREAD

**Issue by Ekuboh** [RSSNext/Follow#1079]
### Describe the bug

![image](https://github.com/user-attachments/assets/350fffa6-2cb5-4df3-86db-78cbbddf8e84)

### Feed Info

ID: eyeWashFood
Wallet Address: 0x8a09e014763fc871a5e5570bd082b59bc37c2d44

### App Type

Web

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
