### ISSUE TITLE
Power: Failed to fetch dynamically imported module: https://app.follow.is/assets/layout.CQG8tYYic.js

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#1080]
### Describe the bug

![image](https://github.com/user-attachments/assets/3732467c-2e31-4630-ba5c-2ff4dc43a5d9)

### Feed Info

.

### App Type

Web

### Version

newest

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It should have been fixed, try refreshing
