### ISSUE TITLE
The achievement reward was 1300, what should I do? Will it still be credited in the future?

### ISSUE THREAD

**Issue by Cvsly** [RSSNext/Follow#1082]
### Describe the bug

l领取了内测成就奖励，只显示到账120，剩下的1300没有记录，后续还会到账吗？

### Feed Info

地址 0xc17d0e63132a2026981dac73279b8f2a011bbef3

### App Type

Electron / App

### Version

 0.1.0-beta.0

### Operating System

macOS

### Browser Info

safari，Macos15

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it. https://scan.rss3.io/tx/0xd4c38a685c1d84b7c7ab63d5a977d0e7a48d4a2c349bd2d5837726b0da96a2b6
