### ISSUE TITLE
I don't care much about lists and inboxes. Can you give me a switch to turn off the one above my head? The column, it’s always there now, it’s a bit awkward

### ISSUE THREAD

**Issue by Sunsh4j** [RSSNext/Follow#1083]
### Clear and concise description of the problem

如题

### Suggested solution

如题

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
I don't understand your request. Why don't you unsubscribe it if you don't want to read it?

**Comment by Innei** [comment]
> Follow发布初期，曾有个全文搜索功能，能对所有订阅源内容进行关键字搜索，这是个很方便的功能，后来被取消了，希望可以加回。

Do you mean `CMD+k`?
