### ISSUE TITLE
Feed cannot be updated

### ISSUE THREAD

**Issue by Theo-Messi** [RSSNext/Follow#1084]
### Describe the bug

<img width="827" alt="image" src="https://github.com/user-attachments/assets/a76d9dfb-3a48-43c8-ae36-b8536159c2f9">

**This is my certified feed. I have updated the content and icon, but the refresh cannot update it.**

<img width="823" alt="image" src="https://github.com/user-attachments/assets/c34437f6-f139-4cf6-bd51-d4d5b0841e84">

**This is another site I deployed with the same content. You can get the new icons and content directly.**

### Feed Info

feed id:71853286495319040
feed url: https://share.theojs.cn/feed.rss

### App Type

Electron / App

### Version

0.1.0-beta.0

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
How long has it been since you updated?

**Comment by hyoban** [comment]
The feed has now been updated. Please note that it will take some time for changes to the feed to be applied.

![ScreenShot 2024-10-23 22 16 14](https://github.com/user-attachments/assets/d55a5af5-1dac-4219-9b0f-121900a2d1eb)
