### ISSUE TITLE
订阅视频不可看

### ISSUE THREAD

**Issue by Mangteng1994** [RSSNext/Follow#1086]
### Describe the bug

![image](https://github.com/user-attachments/assets/721592c1-2a2c-45f1-9baf-d8902488f2e9)所有视频都不可看，包括youtube

### Feed Info

https://www.bilibili.com/video/BV1wRyHYQE1d
https://www.bilibili.com/video/BV1PZyWYtEQY

### App Type

Web

### Version

0.1.0-beta.0

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by 4everwl** [comment]
同样 我想知道这个如何解决呢？
