### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#1092]
### Describe the bug

点击更新后弹出如下弹窗

![image](https://github.com/user-attachments/assets/21b47a2b-1c9e-4de8-8983-86a792f433b7)

### Feed Info

无

### App Type

Electron / App

### Version

最新版

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by harry10086** [comment]
一样，之前几个版本都是这样，而且只会删除老版本，不会安装新版本。
我都是重新安装一遍

**Comment by hexWars** [comment]
> 一样，之前几个版本都是这样，而且只会删除老版本，不会安装新版本。 我都是重新安装一遍

我之前更新其实可以，只有这次不行

**Comment by Innei** [comment]
Fixed in https://github.com/RSSNext/Follow/pull/1144
