### ISSUE TITLE
Cannot be used after the lower Mac version is automatically upgraded

### ISSUE THREAD

**Issue by mssky9527** [RSSNext/Follow#1093]
### Clear and concise description of the problem

今天让follow自动升级，升级后就升到高版本，因为高版本在低版本的MacOS上无法使用

### Suggested solution

升级前先判断系统版本或者将follow兼容低版本的MacOS

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
What is your macOS version?

**Comment by wangyi5555** [comment]
Unfortunately, catalina 10.15.7 also doesn't work with the latest version
