### ISSUE TITLE
I hope you can add custom referrer settings to solve the problem of cross-domain images

### ISSUE THREAD

**Issue by yitong2333** [RSSNext/Follow#1095]
### Clear and concise description of the problem

自建wxwxrss（微信公众号）订阅源导入到follow不显示图片
![image](https://github.com/user-attachments/assets/bd1efbac-1905-4859-b881-3de0795cd035)

### Suggested solution

希望可以加入自定义referrer设置解决图片跨域的问题

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Duplicate of #933
