### ISSUE TITLE
ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by Rvn0xsy** [RSSNext/Follow#1098]
### Describe the bug

My RSS feed cannot be updated in FOLLOW, with the error message "ON CONFLICT DO UPDATE command cannot affect row a second time".

I checked the same Issue #973, but it was not resolved.

### Environment

**App Version**: 0.1.0-beta.0
**OS**: Linux
**User Agent**: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
**Env**: web
**Browser**: Microsoft Edge

### Feed Info

https://payloads.online/index.xml

### App Type

Web

### Version

0.1.0-beta.0

### Operating System

Linux

### Browser Info

Edge 129.0.2792.89

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by chenyuxuan84** [comment]
https://pincong.rocks/feed/
this feed cannot be updated either

**Comment by cyx59** [comment]
http://www.secretchina.com/rss/term/id/1/rss.xml

**Comment by cyx59** [comment]
http://www.secretchina.com/rss/term/id/1/rss.xml
this feed can't be updated either

**Comment by cyx59** [comment]
http://www.secretchina.com/rss/term/id/1/rss.xml
this feed couldn't be updated a day after being added to Follow

**Comment by hyoban** [comment]
Fixed in server side
