### ISSUE TITLE
0.1.0-beta.0 UI bug

### ISSUE THREAD

**Issue by laivn** [RSSNext/Follow#1101]
### Describe the bug

更新到0.1.0-beta.0，阅读时候文章列表会出现相同预览，会造成不能向下切换文章，具体如视频

### Feed Info

All Feed.

### Reproduction Video

https://github.com/user-attachments/assets/672e8a36-29b7-4f9a-858c-2fbde781159f

### App Type

Electron / App

### Version

0.1.0-beta.0

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Is rebuilding the database useful?

**Comment by laivn** [comment]
> Is rebuilding the database helpful?

重建数据，还是会出现同样问题。

**Comment by laivn** [comment]
还会出现3个重复的
![CleanShot 2024-10-25 at 11 55 33@2x](https://github.com/user-attachments/assets/2ce71c34-d1b4-4ee0-832d-9b804f38508d)
