### ISSUE TITLE
How do I get this achievement?--“Product Hunt Voter“

### ISSUE THREAD

**Issue by wenfp108** [RSSNext/Follow#1104]
### Describe the bug

Will this achievement complete properly and if so how do I need to complete it

### Feed Info
NULL

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
We haven't started the Product Hunt Vote yet, and we expect to do so next week. Thank you for your support
