### ISSUE TITLE
repeat footer in `share/users` route

### ISSUE THREAD

**Issue by shulandmimi** [RSSNext/Follow#1107]
### Describe the bug

![image](https://github.com/user-attachments/assets/fb6a105b-65df-424f-8231-fa3f011bd407)

### Feed Info

https://app.follow.is/share/users/63390178523874304

### App Type

Web

### Version

latest

### Operating System

Linux

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Thanks for your feedback, it has now been fixed
