### ISSUE TITLE
Select in batches and then operate. For example, delete

### ISSUE THREAD

**Issue by zhenghuawei923** [RSSNext/Follow#1110]
### Clear and concise description of the problem

批量选择的功能没有，删除订阅很麻烦，删除整个分类的订阅源，删除后只是分类不见了，订阅源还在。

### Suggested solution

提供类似excel中的按住shift选择一个区域和按住ctrl多个选择的功能。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #272
