### ISSUE TITLE
I've encountered a problem with duplicate information.

### ISSUE THREAD

**Issue by qbbosg** [RSSNext/Follow#1111]
## Bug
The problem is shown in the figure below; there is duplicate information.

![](https://cdn.jsdelivr.net/gh/qbboo/picture@main/uPic/2024_10_24_LSfHgYgUw5Q5.png)

----

Copying the version information from the about page results in the following information.
### Environment 
**App Version**: 0.1.0-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.0-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

Feed ID : 54068749119767552
Feed url: rsshub://hackernews/news

### App Type

Electron / App

### Version

0.1.0-beta.0

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by qbbosg** [comment]
This issue suddenly doesn't reoccur; I don't understand what's going on.

**Comment by hyoban** [comment]
This should be the same issue as https://github.com/RSSNext/Follow/issues/1101 and has been fixed.
