### ISSUE TITLE
Web client feed item is added repeatedly

### ISSUE THREAD

**Issue by Devocy** [RSSNext/Follow#1125]
### Describe the bug

![image](https://github.com/user-attachments/assets/b7535512-c82a-4277-9d58-f1e11c128f95)

When the state of the feed item changes from unread to read, the state of the duplicate item also changes

### Environment

**App Version**: 0.1.0-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
**Env**: web
**Browser**: Microsoft Edge

### Feed Info

rsshub://hackernews

### App Type

Web

### Version

0.1.0-beta.0

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Devocy** [comment]
![image](https://github.com/user-attachments/assets/619db830-1c51-4c5f-a87c-1b78a32ff73e)

After I turned off the automatic translation, this situation still exists

**Comment by DIYgod** [comment]
What is the feed address you subscribed to?

**Comment by Innei** [comment]
Track in #780
