### ISSUE TITLE
RSS feed fetch fails for thewitnesshk.com with 403 Forbidden error

### ISSUE THREAD

**Issue by forkmax** [RSSNext/Follow#1133]
## Description
The RSS feed for thewitnesshk.com is failing to fetch with a 403 Forbidden error on Follow.is, while working normally on other RSS readers.

**Current Behavior:**
- Feed URL: `https://thewitnesshk.com/feed`
- Error message: `Feed fetch error: [GET] "https://thewitnesshk.com/feed": 403 Forbidden`
- Existing subscriptions to this feed have stopped updating for approximately one month

**Verification Steps:**
1. The same RSS feed URL works correctly in other RSS readers
2. Feed content is still being actively updated on the source website
3. The 403 error suggests the request is being explicitly rejected by the server

**Technical Analysis:**
The 403 Forbidden error specifically indicates that:
- The server recognizes the request but refuses to authorize it
- This might be due to:
  - Request header configurations in Follow.is

**Suggested Investigation:**
Please check:
- Request headers being sent by Follow.is
- User agent string configuration
- IP rotation or proxy settings if applicable
- Any recent changes in the feed fetching mechanism

**Additional Context:**
Since the feed works in other RSS readers but fails specifically in Follow.is, this suggests a potential server-side restriction targeting specific client characteristics rather than a general feed availability issue.

### Feed Info

Feed URL: https://thewitnesshk.com/feed

### App Type

Electron / App

### Version

0.1.0-beta.0

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by cyx59** [comment]
https://pincong.rocks/feed/
this Feed has the same error

**Comment by hyoban** [comment]
This link is blocking access from our server, and this is not a problem we can solve.

Similar to #733

**Comment by KwToPA** [comment]
我用浏览器能打开，但ttrss订阅不了官方feed

Couldn't download the specified URL: Client error: GET https://thewitnesshk.com/feed/ resulted in a 403 Forbidden response:

![Image](https://github.com/user-attachments/assets/b040e6c6-0876-4579-b495-3089bfb3deb5)
