### ISSUE TITLE
Unable to load list.

### ISSUE THREAD

**Issue by sche11** [RSSNext/Follow#1134]
### Describe the bug

> Sorry, Follow has encountered an error
Cannot read properties of null (reading 'localeCompare')
Follow has a temporary problem, click the button below to try reloading the app or another solution?

![image](https://github.com/user-attachments/assets/824bda6e-feeb-468c-8df1-006149176a71)
I am using the web version. I have tried resetting and reloading, but it doesn't work. It still jumps to this interface.

### Feed Info

https://app.follow.is/feeds/all/pending?view=0

### App Type

Web

### Version

 129.0.2792.52

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
@hyoban follow up this problem?

**Comment by hyoban** [comment]
Can you provide information about the list you are trying to load?

**Comment by sche11** [comment]
> Can you provide information about the list you are trying to load?

I once used the [FocusReader RSS Reader](https://play.google.com/store/search?q=focusreader&c=apps&hl=en_US) on the Android platform.The following are the files I exported from it.

[FocusReader.zip](https://github.com/user-attachments/files/17528647/FocusReader.zip)

**Comment by hyoban** [comment]
Maybe provide a follow feed that fails to load, or does it only happen when loading categories?

**Comment by sche11** [comment]
> Maybe provide a follow feed that fails to load, or does it only happen when loading categories?

Maybe. There are quite a few follow feeds that can't be loaded. As the number of my follow feeds keeps increasing, I usually don't take the time to check them. I can delete these unloadable feeds and try importing them again.
