### ISSUE TITLE
Support two-finger return on trackpad.

### ISSUE THREAD

**Issue by issaccv** [RSSNext/follow#1141]
### Clear and concise description of the problem

In widescreen view, opening the full text of the feed will overwrite the list view. When reading feeds, it requires multiple precise clicks of the close button, which is frustrating.

### Suggested solution

We can add touchpad gestures support, such as swiping right with two fingers to return to the list view, so that all operations such as browsing, reading, and returning can be completed on the touchpad. 

### Alternative

Two-finger return may conflict with code snippets in the feed or elements with horizontal scrolling. On these elements, horizontal scrolling should always take precedence.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Przeblysk** [comment]
On my mac the two-finger return is in effect
