### ISSUE TITLE
Code Block Render Error

### ISSUE THREAD

**Issue by wlynxg** [RSSNext/Follow#1142]
### Describe the bug

```
Minified React error #257; visit https://reactjs.org/docs/error-decoder.html?invariant=257 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

![image](https://github.com/user-attachments/assets/a27f7e73-ba9e-4bdf-a148-5ae76a3fc0da)

### Feed Info

https://app.follow.is/feeds/all/72561971801102337?type=rss&view=0

### App Type

Web

### Operating System

Windows 10

### Environment

**App Version**: 0.1.0-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
`<pre><span></span><code><span id=\"user-content-__span-0-1\"><a id=\"user-content-__codelineno-0-1\" name=\"user-content-__codelineno-0-1\" href=\"#__codelineno-0-1\" target=\"_blank\"></a><span>RUN</span><span> </span>apt-get<span> </span>update<span> </span><span>&#x26;&#x26;</span><span> </span>apt-get<span> </span>upgrade<span> </span>-y<span> </span><span>&#x26;&#x26;</span><span> </span>apt-get<span> </span>autoremove<span> </span>-y\n</span></code></pre>`

Incorrect html format for Feed parsing, embedded a tag in pre

**Comment by wlynxg** [comment]
> `\<pre\><span></span><code><span id=\"user-content-__span-0-1\"><a id=\"user-content-__codelineno-0-1\" name=\"user-content-__codelineno-0-1\" href=\"#__codelineno-0-1\" target=\"_blank\"></a><span>RUN</span><span> </span>apt-get<span> </span>update<span> </span><span>&#x26;&#x26;</span><span> </span>apt-get<span> </span>upgrade<span> </span>-y<span> </span><span>&#x26;&#x26;</span><span> </span>apt-get<span> </span>autoremove<span> </span>-y\n</span></code>\</pre\>`
> 
> Incorrect html format for Feed parsing, embedded a tag in pre

Thanks for your reply. Does this problem need to be fixed by the plugin that I use to provide the RSS feed? However, I don't see any errors in other RSS readers.

**Comment by Innei** [comment]
I think it'll good idea
