### ISSUE TITLE
Hope to support self-built fever service, ttrss

### ISSUE THREAD

**Issue by fucao** [RSSNext/Follow#1145]
### Clear and concise description of the problem

希望能支持自建的fever服务，ttrss

### Suggested solution

希望能支持自建的fever服务，ttrss

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
We are not just a simple client, but an integrated system that requires cooperation between the front and back ends.
