### ISSUE TITLE
What happened？

### ISSUE THREAD

**Issue by kyoonart** [RSSNext/Follow#1148]
### Describe the bug

What happened？
![image](https://github.com/user-attachments/assets/2630c4ba-979a-4919-80b7-a2ee9d047b1a)

### Feed Info

What happened？

### App Type

Web

### Version

1.0.0

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Try reload without cache.

**Comment by FATO44** [comment]
> Try reload without cache.

still can not login):

**Comment by abel533** [comment]
[fa573c438436ed98ef0cb83b9df43fa2649eb682](https://github.com/RSSNext/Follow/commit/fa573c438436ed98ef0cb83b9df43fa2649eb682)

似乎是这里的改动导致的。

**Comment by Innei** [comment]
> [fa573c438436ed98ef0cb83b9df43fa2649eb682](https://github.com/RSSNext/Follow/commit/fa573c438436ed98ef0cb83b9df43fa2649eb682)
> 
> 似乎是这里的改动导致的。

That's not the reason. This is a rewrite of the request for the external page. The problem may be that index.html is cached.
