### ISSUE TITLE
Severe lag

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#1149]
### Describe the bug

我的订阅较多，在个人博客分组中，订阅数量超过了100，但所有订阅加起来不超过200，在这个体量下，app端在分组展开的情况下，左侧会变得很长，这时候滚动，会变得非常卡

准确说，是展开分组并向下拉动，以及再次点击分组收起列表这两个行为会造成卡顿

### Feed Info

[null](https://app.follow.is/share/users/hexer)

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Is this something that just appeared in the current version, or was it there before?

**Comment by hexWars** [comment]
I think it’s specific to this version; to be exact, I only noticed it this morning when I woke up. Although I did add around 5 new subscriptions yesterday, the lag wasn’t this severe.

**Comment by hexWars** [comment]
you can check

https://app.follow.is/share/users/hexer

**Comment by hyoban** [comment]
You can try this version https://github.com/RSSNext/Follow/releases/tag/nightly-0.1.1-nightly.20241025

**Comment by hexWars** [comment]
![image](https://github.com/user-attachments/assets/0050337a-728d-46c5-ac4c-6c99b144f9f0)

**Comment by hyoban** [comment]
Try this one https://github.com/RSSNext/Follow/actions/runs/11529255781

**Comment by hexWars** [comment]
It seems the issue has been resolved. Thank you for your help; I will close this issue.  (*´∀人)
