### ISSUE TITLE
login failed by github

### ISSUE THREAD

**Issue by DavidYanXW** [RSSNext/Follow#1151]
### Describe the bug

登录失败，通过github
桌面程序跳转chrome浏览器后，停止在“https://app.follow.is/login?provider=github”，显示为空白页面。
chrome调试器，显示部分js资源文件404.
![2024-10-26_11-02](https://github.com/user-attachments/assets/7524de74-d0bb-4cb4-851a-2d31b44d19cb)

### Feed Info

无

### App Type

Electron / App

### Version

0.1.1-beta

### Operating System

Linux

### Browser Info

无

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by deltaR-3k** [comment]
same

**Comment by mdsnalw** [comment]
> [FOL-598 login failed by github](https://linear.app/follow-app/issue/FOL-598/login-failed-by-github)

Not able to access the workspace. 

![image](https://github.com/user-attachments/assets/3dc1df7d-84eb-4eda-af79-7ad579fd5211)

**Comment by Innei** [comment]
@DavidYanXW Try check `停用缓存` and reload the page.
![CleanShot 2024-10-26 at 1  32 20@2x](https://github.com/user-attachments/assets/d1254b24-a77d-4a06-85ff-95b6949ef96e)

**Comment by abel533** [comment]
停用缓存不起作用

**Comment by mdsnalw** [comment]
> @DavidYanXW Try check `停用缓存` and reload the page. ![CleanShot 2024-10-26 at 1  32 20@2x](https://private-user-images.githubusercontent.com/41265413/380366269-d1254b24-a77d-4a06-85ff-95b6949ef96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjI1ODgsIm5iZiI6MTcyOTkyMjI4OCwicGF0aCI6Ii80MTI2NTQxMy8zODAzNjYyNjktZDEyNTRiMjQtYTc3ZC00YTA2LTg1ZmYtOTViNjk0OWVmOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MDYwYTU4ODE0Nzk5Y2Q2YTQ2OTUwNTJlYWVhMDlhMDM5M2RkYTM5YTQ4NTc0ZmQ4YmI1ZjQ2ZmE3ODYyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P4r21OpDaW8_t9IYCC05RF3EAkgMtXE2JFLSedJQko0)

It works for me. Thank you!

![image](https://github.com/user-attachments/assets/9394af5b-7f4d-4bb2-94b1-4b95b7cd7246)

**Comment by abel533** [comment]
将所有浏览器关闭后再打开就好了。

**Comment by DavidYanXW** [comment]
> @DavidYanXW Try check `停用缓存` and reload the page. ![CleanShot 2024-10-26 at 1  32 20@2x](https://private-user-images.githubusercontent.com/41265413/380366269-d1254b24-a77d-4a06-85ff-95b6949ef96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDAyMjksIm5iZiI6MTcyOTkzOTkyOSwicGF0aCI6Ii80MTI2NTQxMy8zODAzNjYyNjktZDEyNTRiMjQtYTc3ZC00YTA2LTg1ZmYtOTViNjk0OWVmOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDEwNTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MTVkZWNjNjJlNTRhMTUxNjJjMTg3ZGQ5N2Q1NWU1ZTRlZTMwYjU0MmE4N2U5YzJlN2E3M2JkZDNmMzUyNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E1VDmFLJfViF1hPf_NEPdQRx4AP1JfqwtA0V_e5paNI)

现在已经可以登录了，尽管没有操作“停用缓存”。
