### ISSUE TITLE
After upgrading the version, there was an error

### ISSUE THREAD

**Issue by paulxjz** [RSSNext/Follow#1153]
### Describe the bug

After I upgraded from Nightly 0.1.0-nightly.20241024 to Nightly 0.1.1-nightly.20241025, I got the error。

<img width="698" alt="截图：20241026123213" src="https://github.com/user-attachments/assets/090bb4c3-e56c-4e9b-82fd-8c7eb500b812">

I've tried uninstalling and reinstalling and still get this error
English is not my native language, I'm using translation software, I may not be very accurate, please forgive me!

### Feed Info

System version is windows 11 23H2 22631.4317

### App Type

Electron / App

### Version

Nightly 0.1.1-nightly.20241025

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
@paulxjz Hi, thank you for your report, can you help me try this version? maybe it fixed. https://github.com/RSSNext/Follow/actions/runs/11529255781

**Comment by paulxjz** [comment]
> @paulxjz Hi, thank you for your report, can you help me try this version? maybe it fixed. https://github.com/RSSNext/Follow/actions/runs/11529255781

Running normally, bug has been fixed
