### ISSUE TITLE
The appearance cannot be set to dark mode

### ISSUE THREAD

**Issue by Sunsh4j** [RSSNext/Follow#1160]
### Describe the bug

外观无法设置为暗色模式
另外，希望加入自定义排序功能（自定义排序类别名以及类别名下的订阅源），信息的获取有优先级，目前存在的排序方式无法满足需求

### Feed Info

*

### App Type

Electron / App

### Version

v0.1.1-beta.0

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/pull/1157, for feature requests, please open a new issue
