### ISSUE TITLE
The icon of the subscribed feed will disappear after a while

### ISSUE THREAD

**Issue by windcykk** [RSSNext/Follow#1169]
### Describe the bug

订阅完毕的源的图标会在过一段时间消失变成默认的网站图标
也就是说我订阅的博主的头像不会被正常的显示
目前该问题仅在视频源的订阅操作下被发现

### Feed Info

rsshub://bilibili/user/video/19319172
rsshub://bilibili/user/video/407054668
rsshub://bilibili/user/video/946974

### Reproduction Video

![image](https://github.com/user-attachments/assets/96b0cce6-020a-429a-bae8-a5e30907670b)

### App Type

Web

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This part of the information is missing in the route of RSSHub. It will be fixed in the PR.
