### ISSUE TITLE
0.1.1-nightly.20241026 版本问题

### ISSUE THREAD

**Issue by Keturah-i** [RSSNext/Follow#1171]
### Describe the bug

除文章类目外，其余类目均出现未订阅内容，未读数量显示错误，未订阅类目也有数据显示

### Feed Info

![社交媒体类目](https://github.com/user-attachments/assets/057fb100-1058-4468-adba-016b7855505a)
![图片类目](https://github.com/user-attachments/assets/0c0cc63b-0eee-4b59-967c-9320bac352b6)
![音频类目](https://github.com/user-attachments/assets/6d1af426-3afd-40bd-8bb1-2dacad2a4aae)
![视频类目](https://github.com/user-attachments/assets/8e922875-dc89-4c35-90e2-7459e09c6cae)

![通知类目](https://github.com/user-attachments/assets/32c3e4bc-3c97-44cb-863a-7da9e1208ae5)

### App Type

Electron / App

### Version

0.1.1-nightly.20241026

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Can you help me try this version?

https://github.com/RSSNext/Follow/actions/runs/11545971295
