### ISSUE TITLE
i'm very like your New APP, but i need code to get gull function

### ISSUE THREAD

**Issue by MackDing** [RSSNext/Follow#1175]
### Clear and concise description of the problem

could you gime me a invitation code, thanks ,mack.ding24@gmail.com

### Suggested solution

could you gime me a invitation code, thanks ,mack.ding24@gmail.com
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/6bac2754-022e-4291-a224-49b0c1989e88">

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #1026
