### ISSUE TITLE
Support for Custom Web Page Styling to Improve User Experience

### ISSUE THREAD

**Issue by kewab** [RSSNext/Follow#1179]
### Clear and concise description of the problem

It would be highly beneficial if the app could support custom web page styling for the following purposes:

Interface Optimization: Certain websites may have default styles that hinder readability. With custom styling, users could adjust the appearance to create a more visually pleasing and user-friendly interface.

This feature could significantly enhance user experience and cater to various customization needs. Thank you for considering this!

### Suggested solution

Built-in Extension Support: Some applications built on the Chrome engine (like Electron or NW.js) offer support for Chrome extensions. This requires the app developer to enable extension functionality within the app settings. Once this feature is enabled, extensions can be loaded directly into the app, allowing users to utilize plugins for features like custom styling.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
duplicate with #256
