### ISSUE TITLE
不能添加她的订阅源

### ISSUE THREAD

**Issue by people9021** [RSSNext/Follow#1185]
### Describe the bug

![QQ20241028-023655](https://github.com/user-attachments/assets/be81f4a3-de96-44f0-a1b9-c6b5aa5f3053)

### Feed Info

https://www.instagram.com/365nichi360/

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
This is a private account and cannot be subscribed to.
