### ISSUE TITLE
WeChat public account import

### ISSUE THREAD

**Issue by miieya** [RSSNext/Follow#1189]
### Describe the bug

想要导入微信公众号的订阅源的时候，利用wewe-rss，但是导入一直无法解析，不知道如何解决

### Feed Info

http://localhost:4000/feeds/MP_WXS_2392884300.atom

### App Type

Web

### Version

63E6B95

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
We need to get and parse the feed on the server side, so local addresses are not supported
