### ISSUE TITLE
A set of unrelated subscriptions appears in all categories except articles

### ISSUE THREAD

**Issue by jdjxk** [RSSNext/Follow#1190]
### Describe the bug

除文章以外的所有类别都出现一组无关订阅，无法去除。
![image](https://github.com/user-attachments/assets/cea8be4c-dcab-41cc-9749-f7aee7543db3)

### Feed Info

无

### Reproduction Video

无

### App Type

Web

### Version

1.0.0

### Operating System

Windows 11

### Browser Info

Chromium 128.0.6613.189

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by jdjxk** [comment]
The windows client does not have this problem.

**Comment by hyoban** [comment]
Fixed now, try again.
