### ISSUE TITLE
Can it be minimized to the taskbar 能否最小化到任务栏

### ISSUE THREAD

**Issue by zhrq95** [RSSNext/Follow#1192]
### Clear and concise description of the problem

Can it be minimized to the taskbar 能否最小化到任务栏

### Suggested solution

 minimized to the taskbar 最小化到任务栏

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Duplicate of #999
