### ISSUE TITLE
Nightly 0.1.1-nightly.20241027 一直刷新

### ISSUE THREAD

**Issue by Keturah-i** [RSSNext/Follow#1206]
### Describe the bug

Nightly 0.1.1-nightly.20241027 安装后打开，文章类目正常显示，点击未订阅内容类目后，未订阅内容类目没有内容，重复刷新不停止，再次点击有订阅内容类目，内容无法显示并显示正在刷新，点击未读订阅，提示没有内容并显示正在刷新，社交媒体类目下，订阅的X订阅，移动到了图片类目下

### Feed Info

![社交媒体类目](https://github.com/user-attachments/assets/ace42765-e245-4af4-87da-d5c6c77aee7e)
![视频类目](https://github.com/user-attachments/assets/0be12f02-bbd7-48f2-a5e4-c36c2d5909ea)
![通知类目](https://github.com/user-attachments/assets/9a0736db-e0f0-4e38-895d-22dcee9b131b)
![图片类目](https://github.com/user-attachments/assets/cbb71edf-f462-43a3-84f2-e7d905d4101f)
![图片类目下 X 订阅源](https://github.com/user-attachments/assets/24985b4b-a61f-40ac-b9b7-d2f459a8f26f)
![文章类目](https://github.com/user-attachments/assets/8cc20674-3479-46fd-b497-2996c169bad9)
![文章类目下未读订阅源](https://github.com/user-attachments/assets/daf0e853-8baa-45db-b69e-6b72a8819b82)
![音频类目](https://github.com/user-attachments/assets/000270b3-d0e7-49c8-846d-a39f2fc84300)

### App Type

Electron / App

### Version

Nightly 0.1.1-nightly.20241027

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/074a60d3cf93bcede88ea4d70b07cf7480be4229, you can try the build in the latest commit
