### ISSUE TITLE
Sorry, Follow has encountered an error . 【Macos】

### ISSUE THREAD

**Issue by iHowCool** [RSSNext/Follow#1211]
### Describe the bug

see below picture.

My Mac Version
芯片 Apple M2 Pro
内存 16 GB
序列号
macOS Sequoia 15.0.1

### Feed Info

<img width="852" alt="image" src="https://github.com/user-attachments/assets/5f50dfaf-5d5f-4aad-9cff-351ce96f2c41">

### App Type

Electron / App

### Version

Follow-0.1.1-beta.1-macos-universal

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Przeblysk** [comment]
序列号去掉吧～

**Comment by iHowCool** [comment]
好的~。 昨天还用的好好的，我没关APP、今天打开电脑APP就挂了。 我点了reset 也没用，也没解决问题

**Comment by iHowCool** [comment]
嘻嘻，它自己又好了~

**Comment by hyoban** [comment]
We are unable to locate and solve the problem with this limited information. If you have more reproducible information, please feel free to open this issue again.
