### ISSUE TITLE
power detail has NaN error

### ISSUE THREAD

**Issue by HuanBaby1314** [RSSNext/Follow#1212]
### Describe the bug

![image](https://github.com/user-attachments/assets/8f1cfb72-2681-4f20-83cb-e419c95cee42)

### Feed Info

1421844398@qq.com

### App Type

Web

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/11059f639ee955a0f10cbd97cb6eed85e335fed7
