### ISSUE TITLE
Feed Get the error: [GET] "https://dodi-repacks.site/feed/": 403 Forbidden

### ISSUE THREAD

**Issue by wasdjkl** [RSSNext/Follow#1213]
### Describe the bug

This popular game repackaging site doesn't allow adding prompts. A "403 Forbidden" error message is displayed.

### Feed Info

https://dodi-repacks.site/feed/

### App Type

Web

### Version

Beta 版本 (488E8EF)

### Operating System

Windows 11

### Browser Info

Microsoft Edge 130.0.2849.56

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This link is blocking access from our server, and this is not a problem we can solve.

Similar to #733
