### ISSUE TITLE
redirected feed fails to fetch

### ISSUE THREAD

**Issue by daujyungx** [RSSNext/Follow#1214]
### Describe the bug

feed `https://taizihuang.github.io/wmyblog/rss.xml` is redirected to `https://wmyblog.site/rss.xml` , items after 2024-10-01 of feed `https://taizihuang.github.io/wmyblog/rss.xml` are not fetched.

### Feed Info

https://taizihuang.github.io/wmyblog/rss.xml

### App Type

Electron / App

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please load archived entries
![ScreenShot 2024-10-29 12 27 25](https://github.com/user-attachments/assets/170d37cc-e64f-4ac6-9126-e6d6f6ed868c)
![ScreenShot 2024-10-29 12 27 38](https://github.com/user-attachments/assets/7d46bb2e-feb2-40b4-9fa5-7cd81005fd49)
