### ISSUE TITLE
When adding a subscription, it will be better if the category can automatically match the folder that exists under the f-category according to the media type selected.

### ISSUE THREAD

**Issue by csxo** [RSSNext/Follow#1224]
### Clear and concise description of the problem

If a user creates many folders to organize his feeds, like group a,b,c,d in Articles, e,f,g,h in Social media, he can only see all folders listed and can't choose what he wants by views type to filter. 

### Suggested solution

I think we can switch category folders when changing to choose the view types (articles, social media, pics, videos, audios, notificatiions) to list the folders under each view types to get it quicker.
![Snipaste_2024-10-29_19-23-50](https://github.com/user-attachments/assets/7cc1528a-3baa-4d76-9214-796907173eda)

### Alternative

I think we can switch category folders when changing to choose the view types (articles, social media, pics, videos, audios, notificatiions) to list the folders under each view types to get it quicker.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
In fact, we intentionally show all available categories

https://github.com/RSSNext/Follow/pull/392

**Comment by csxo** [comment]
> In fact, we intentionally show all available categories
> 
> #392

Sure, thank you for your explanation.
