### ISSUE TITLE
the notification badge always exists even there is no notification

### ISSUE THREAD

**Issue by STRRL** [RSSNext/follow#123]
follow 0.0.1-alpha.1  on macOS 14.5

![image](https://github.com/RSSNext/follow/assets/20221408/9f5627a5-6561-47b1-b180-6029f1b35bf0)

**Comment by hyoban** [comment]
This should be fixed in https://github.com/RSSNext/follow/commit/e54ac4248098937fbc94d4303de7546b936f8dcd#diff-d6455805d58cd17fbe5066f9b472efe4b95abdb253f4c20bed2769aeacdef7f2R175-R179
