### ISSUE TITLE
Custom UI Font Not Applied to Text Input Fields

### ISSUE THREAD

**Issue by L33Z22L11** [RSSNext/Follow#1234]
### Describe the bug

The custom interface font is not being applied to text input fields, resulting in inconsistent font styling across the application. This affects the visual coherence and user experience, as input text appears in the default font instead of the selected custom font.

### Feed Info

1. Change the UI font in settings
2. Text input fields (e.g., in the subscription settings editor) do not reflect the new font selection

### App Type

Web

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Browser Info

Microsoft Edge 130.0.2849.56

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by L33Z22L11** [comment]
![image](https://github.com/user-attachments/assets/b197a2b6-79a3-483c-bcec-1cbb7c0b22ce)
So does toast notification.

![image](https://github.com/user-attachments/assets/eda74924-d1a3-4025-ba55-760d12c05cc2)
So does Keyboard indicator(maybe a monospace font needed).

**Comment by Innei** [comment]
Fixed in #1322
