### ISSUE TITLE
Abnormal Page Height on "View Original" Interface for Subscription Articles

### ISSUE THREAD

**Issue by L33Z22L11** [RSSNext/Follow#1236]
### Describe the bug

In the web version, a banner appears at the top of the "View Original" page, advising users that "Content may not display correctly; please download the app." This banner reduces the available height for the webpage iframe, causing elements at the bottom of the page to overflow and become hidden. This affects user experience by obstructing full visibility of the original content.

### Feed Info

https://app.follow.is/share/feeds/62533754566736896

### Reproduction Video

![image](https://github.com/user-attachments/assets/87b26a9f-7b32-4d69-b4ae-fa8567219656)

### App Type

Web

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Browser Info

Microsoft Edge 130.0.2849.56

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by abandon888** [comment]
this issue is solved,see in [link](https://github.com/RSSNext/Follow/blob/edd4f9e5a6dc041e9eae2cee5ddf4eb624527ef5/apps/renderer/src/modules/entry-content/components/SourceContentView.tsx)
