### ISSUE TITLE
Entries that have not been read for more than 1 month will be automatically converted to read

### ISSUE THREAD

**Issue by TCOTC** [RSSNext/Follow#1250]
### Describe the bug

超过1个月未读的条目会被自动转换为已读，即使我重新标记为未读，在刷新以后也会再度转换为已读。

希望：

1. 超过1个月未读的条目，在标记为未读之后不自动转换为已读
2. 提供一个选项，不将超过1个月未读的条目自动转换为已读

### Feed Info

https://app.follow.is/share/users/JeffreyChen

### Environment

**App Version**: 0.1.1-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

### App Type

Electron / App

### Version

0.1.1-beta.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by KenMercusLai** [comment]
Guess this is the same issue as #470

**Comment by hyoban** [comment]
We only provide the feature of marking entries in the timeline as unread. Expiring entries will be removed to reduce the pressure on the server and cannot be marked as unread.
