### ISSUE TITLE
The description field in the search results exceeds the boundary.

### ISSUE THREAD

**Issue by DengQingNian** [RSSNext/Follow#1251]
### Describe the bug

![QQ20241031-093202](https://github.com/user-attachments/assets/8b9ae382-0218-4a46-979f-78ef1ba6f148)

### Feed Info

-

### App Type

Electron / App

### Version

0.1.1-nightly.20241029

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Przeblysk** [comment]
![CleanShot2024-10-31at10 58 41@2x](https://github.com/user-attachments/assets/be593c34-d2fe-41d5-9fa6-662e94e9c5c7)
The beta version seems to be fine
