### ISSUE TITLE
Add shortcut key for multi selection

### ISSUE THREAD

**Issue by PrinOrange** [RSSNext/Follow#1256]
### Clear and concise description of the problem

For subscriptions list, as far it only supports do multi-selection by mouse dragging.
I suggest add a shortcut for multi selection operation

目前多选操作仅支持鼠标拖取选区。建议为多选操作加上快捷键，进一步完善。

### Suggested solution

For example,
1. `CTRL + A`, select all subscriptions for current catagory. 例如，`CTRL + A`  选取当前目录下的所有订阅
2. Click subscriptions while pressing `CRTL` key to select some subscriptions. 按下`CTRL`键的同时，点击多个订阅，可以同时选中多个订阅。就类似于Windows下文件系统的操作。

https://github.com/user-attachments/assets/ef4ba9f7-ca10-42ec-8b0c-3b5a639b09d8

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by PrinOrange** [comment]
Additional note: As for the logic of multi-select operations in the list, you can refer to the file system and keep it consistent with the file system.
For example, for "Unsubscribe", the shortcut key can be set to the `del` key instead of `CTRL+Back`, which will be more in line with the user's operating inertia.

补充说明：至于列表中的多选操作的逻辑，更多其他细节可以参考文件系统，与文件系统保持一致。
比如“取消订阅”，快捷键可以设定为`del`键，而不是`CTRL+Back`，这样会更符合用户的操作惯性。

**Comment by Innei** [comment]
@lawvs @hyoban Maybe you need to work together to get this done. Shortcuts and selection.

**Comment by hyoban** [comment]
You can use the shift key to quickly perform multiple selections, which is similar to file management.
