### ISSUE TITLE
Can I get an invitation code?

### ISSUE THREAD

**Issue by nanvon** [RSSNext/follow#126]
Great developer and handsome DIYgod, I am a warm-hearted netizen, can I get an invitation code?

**Comment by CBHXuTT** [comment]
how to get an invitation code?

**Comment by aeolus** [comment]
+1

**Comment by songlinchuifeng** [comment]
how to get an invitation code?

**Comment by psysungeng** [comment]
+1

**Comment by cliweichen** [comment]
+1

**Comment by cliweichen** [comment]
+1

**Comment by mustafaskyer** [comment]
+1 here please!

**Comment by HenryQW** [comment]
No invitations will be posted here.
Follow us on twitter https://twitter.com/follow_app_ and spread the message. We will announce when the time comes!

**Comment by baileichao** [comment]
要去twitter？关键问题是国内也没法子用twitter啊？就不能针对国内用户给个验证码么？

**Comment by 1dooooo** [comment]
去twitter也没用，私信并没有获取不到任何回复。

**Comment by baileichao** [comment]
> 去twitter也没用，私信并没有获取不到任何回复。
那这个软件的开源意义在哪里呢？只下载个软件，没有邀请码又用不了。

**Comment by lucasjinreal** [comment]
开园了一个寂寞。
私聊并没有任何回复。

邀请码就是让你去帮他们宣传的。

大概用了一下，感觉一般

**Comment by Zheap** [comment]
那确实有点鸡肋  感觉是故意让你注册的套取信息的，开源了个锤子，靠
