### ISSUE TITLE
Error in fetching feed: rsshub://douban/group/492558/latest

### ISSUE THREAD

**Issue by hhr114** [RSSNext/Follow#1270]
### Info:

Feed URL:
```
rsshub://douban/group/492558/latest
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/douban/group/492558/latest?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
https://www.douban.com/group/492558/ is empty.
