### ISSUE TITLE
Error in fetching feed: https://1069boys.net/feed

### ISSUE THREAD

**Issue by selva379** [RSSNext/Follow#1271]
### Info:

Feed URL:
```
https://1069boys.net/feed/
```

Error:
```
Feed fetch error: [GET] "https://1069boys.net/feed/": 403 Forbidden
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
This link is blocking access from our server, and this is not a problem we can solve.
