### ISSUE TITLE
[Feat] The subscription link can be configured to view the full text by default.

### ISSUE THREAD

**Issue by xgzlucario** [RSSNext/Follow#1275]
### Clear and concise description of the problem

[现状] 有些rss源里的内容是简述，需要点击链接 -> 点击查看全文 才能看到完整内容

### Suggested solution

[期望] 希望把 "点击查看全文" 步骤省略，做成rss源可配

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
This can already be achieved via action

![Image](https://github.com/user-attachments/assets/e32ee734-2452-4b7e-a14e-ac219c8510cf)
