### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/Netflix

### ISSUE THREAD

**Issue by jackchen4869** [RSSNext/Follow#1280]
### Info:

Feed URL:
```
rsshub://youtube/user/Netflix
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/user/Netflix?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
![Image](https://github.com/user-attachments/assets/4a142ffe-f27f-4534-8d8b-4258c21d0bb5)
