### ISSUE TITLE
Supports batch deletion of subscriptions

### ISSUE THREAD

**Issue by c137-pickle-rick1** [RSSNext/Follow#1284]
### Clear and concise description of the problem

现在订阅的项目不能批量删除（取消订阅）

### Suggested solution

支持列表项目多选，然后批量删除（取消订阅）

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #272

**Comment by TonyRL** [comment]
Duplicate of #1110
