### ISSUE TITLE
Error in fetching feed: https://feeder.co/discover/83d27b81f0/0xparc-org-blog

### ISSUE THREAD

**Issue by jonasqin** [RSSNext/Follow#1285]
### Info:

Feed URL:
```
https://feeder.co/discover/83d27b81f0/0xparc-org-blog
```

Error:
```
Feed 解析失败: Feed not recognized as RSS 1 or 2.
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
This is not an RSS feed URL
