### ISSUE TITLE
Error in fetching feed: https://www.cdnbus.art/

### ISSUE THREAD

**Issue by Dongmic1992** [RSSNext/Follow#1292]
### Info:

Feed URL:
```
https://www.cdnbus.art/
```

Error:
```
Feed 解析失败: Attribute without value
Line: 16
Column: 68
Char: >
```

### Environment

**App Version**: 0.1.1-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
This is not an RSS feed URL
