### ISSUE TITLE
Suggestions for Sorting and Grouping

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1302]
### Clear and concise description of the problem

Suggestions for Sorting and Grouping
add

_**Sorting**_
- New first
- Old first

_**Grouping**_
- By feed
- By date

### Suggested solution

![Image](https://github.com/user-attachments/assets/c91c875c-3f3f-49b4-bf3a-385ca40e24d0)
![Image](https://github.com/user-attachments/assets/91b2748c-5baf-44f4-8586-c17cf9eda6bb)
![Image](https://github.com/user-attachments/assets/851f5071-e02b-4a9f-b60d-9255b369bf85)

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
Track in #276
