### ISSUE TITLE
Social media model is very chaotic

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1304]
## 👇 **① Long articles can occupy an entire screen, and they are expanded by default. Sometimes, there are posts that I don't like, but I have to scroll to the bottom to reach another tweet.** 

https://github.com/user-attachments/assets/e9dfeb60-2e9c-47e5-a5da-5acedb139b2c

## 👇 **② Displaying multiple images of different sizes appears very chaotic, and there will still be a lot of whitespace.**

https://github.com/user-attachments/assets/a80eccf8-bb2c-4623-8f52-9dd879d6e4f1

## 👇 **③ Some videos cannot be played.**

https://github.com/user-attachments/assets/54ca394a-219d-465b-8055-bc48a363d981

## 👇 **④ The lack of divider lines makes it harder to distinguish between the tweets; adding some divider lines could help.**
![Image](https://github.com/user-attachments/assets/8a2689e5-8a70-4640-88e9-4154184cb9eb)

### Suggested solution

Just some user experience feedback.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
The optimization 1,2 has been done in e46b30a07fe74e1bacb234962b1542c849d2177d, 5dc6d9ee227fa714f39957ff6e744e3079a3e57d, the issue with 3 may be due to your network problem causing the video to fail to load, the proposal for 4 is currently not accepted, as adding a split line would make the UI chaotic under the current layout.

**Comment by EnterMan123** [comment]
rsshub://weibo/user/6279793937

3 你尝试播放一下视频

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/7f87c42b-965d-4947-beba-0b31137f4930)

对于超长图片是否还有优化空间

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/24d9d028-abbb-4dc4-a157-df8a6be922c1)

1 它可能会和背景文字重叠
2 我认为展开更多文字可以适当加强调色

**Comment by Innei** [comment]
ok

我优化下
