### ISSUE TITLE
Style: Inline image in title render style bug

### ISSUE THREAD

**Issue by Innei** [RSSNext/Follow#1318]
### Describe the bug

https://app.follow.is/feeds/all/75283814377545728?view=0

![Image](https://github.com/user-attachments/assets/2028fdca-9913-4998-9818-5447f0698ecd)

### Feed Info

https://app.follow.is/feeds/all/75283814377545728?view=0

### App Type

Web

### Version

0.1.2-beta.0

### Operating System

macOS

### Browser Info

N/A

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
After fix 

![Image](https://github.com/user-attachments/assets/c3615b10-f2fe-4208-bc11-881d7d4218c8)
