### ISSUE TITLE
Error in fetching feed: rsshub://rsshub/transform/html/https%3A%2F%2Fflutterfoundation.dev%2Fblog%2F/item%3D.post-list% 3Ea%26itemTitle%3D.title%26itemLink%3Da%26itemDesc%3D.description%26itemPubDate%3D.publish-date

### ISSUE THREAD

**Issue by Otto-J** [RSSNext/Follow#1323]
我尝试转换 rss 时候有奇怪的报错

![Image](https://github.com/user-attachments/assets/a35502a4-dc0b-4719-9791-5f7a7b93fdbc)

### Info:

Feed URL:
```
rsshub://rsshub/transform/html/https%3A%2F%2Fflutterfoundation.dev%2Fblog%2F/item%3D.post-list%3Ea%26itemTitle%3D.title%26itemLink%3Da%26itemDesc%3D.description%26itemPubDate%3D.publish-date
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/rsshub/transform/html/https%3A%2F%2Fflutterfoundation.dev%2Fblog%2F/item%3D.post-list%3Ea%26itemTitle%3D.title%26itemLink%3Da%26itemDesc%3D.description%26itemPubDate%3D.publish-date?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
The item selector is not correct, try `.post-list > a`
