### ISSUE TITLE
compose部署：请求被拒绝

### ISSUE THREAD

**Issue by AlanWang2333** [RSSNext/Follow#1324]
### Describe the bug

x86机器 日志 
`2024-11-02 08:25:24 thumbor:WARNING Request denied because the specified path "/" was not identified by the loader as a valid path

2024-11-02 08:25:24 thumbor:WARNING No original image was specified in the given URL

2024-11-02 08:25:24 tornado.access:WARNING 400 GET / (192.168.1.50) 3.22ms`
![Image](https://github.com/user-attachments/assets/b293ac33-37de-4459-b353-094ad0196aeb)

### Feed Info

？？？？？？？？？？？？？

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Not sure what issue you want to report, maybe you created the issue in the wrong place? If you still have questions please feel free to open it again
