### ISSUE TITLE
Error in fetching feed: http://192.168.1.200:1199/xiaohongshu/user/5fa9f795000000000101f77c/notes

### ISSUE THREAD

**Issue by i-iooi-i** [RSSNext/Follow#1330]
### Info:

Feed URL:
```
http://192.168.1.200:1199/xiaohongshu/user/5fa9f795000000000101f77c/notes
```

Error:
```
Feed 获取错误: [GET] "http://192.168.1.200:1199/xiaohongshu/user/5fa9f795000000000101f77c/notes": <no response> fetch failed
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

![Image](https://github.com/user-attachments/assets/6fdb1e16-41b2-412e-b48f-eabbdcaa9e45)

I'm using rsshub, which I created on my NAS device at home, and it uses the IP of the internal network to get subscriptions. I used TTRSS to get the subscription and it was successful, but I can't use Follow to get the subscription.

**Comment by hyoban** [comment]
This is a local address and cannot be accessed on our server. You can use RSSHub route directly.

```
rsshub://xiaohongshu/user/5fa9f795000000000101f77c/notes
```

**Comment by i-iooi-i** [comment]
But at some point, its access speed is not ideal. Do you want to support the self-built RSSHub service in the future?

> This is a local address and cannot be accessed on our server. You can use RSSHub route directly.
> 
> ```
> rsshub://xiaohongshu/user/5fa9f795000000000101f77c/notes
> ```

**Comment by hyoban** [comment]
If your RSSHub service is now accessible from the public network, you can directly fill in the corresponding feed address now.

We have plans to support custom RSSHub instance, see #363

**Comment by i-iooi-i** [comment]
> If your RSSHub service is now accessible from the public network, you can directly fill in the corresponding feed address now.
> 
> We have plans to support custom RSSHub instance, see [#363](https://github.com/RSSNext/Follow/issues/363)

It's really awesome, thank you very much, I tried to access it on the public network.
