### ISSUE TITLE
Shortcut B for open in browser didn't work.

### ISSUE THREAD

**Issue by thriller32** [RSSNext/Follow#1335]
Nothing happened when pressing B for open in browser.

And it will be so great if there is a shortcut for open in browser in background.
And it will be so great if I can customize shortcuts.

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by lawvs** [comment]
Related to https://github.com/RSSNext/Follow/issues/784

**Comment by lawvs** [comment]
Fixed in https://github.com/RSSNext/Follow/pull/1566
