### ISSUE TITLE
Error in fetching feed: https://pinchlime.com/subscribe/

### ISSUE THREAD

**Issue by haha1357** [RSSNext/Follow#1343]
### Info:

Feed URL:
```
https://pinchlime.com/subscribe/
```

Error:
```
Feed 解析失败: Feed not recognized as RSS 1 or 2.
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
This is not an RSS feed URL

**Comment by hyoban** [comment]
You can subscribe by following the instructions, such as https://pinchlime.com/atom.xml
