### ISSUE TITLE
Error in fetching feed: rsshub://douyin/user/MS4wLjABAAAACA-_BYNwvmyAs7fIW7Mddolwj9WGEdtnn_vVK2LV8lP_tBeuk5NXYB8LMfF8EbYa

### ISSUE THREAD

**Issue by wikiq** [RSSNext/Follow#1346]
### Info:

Feed URL:
```
rsshub://douyin/user/MS4wLjABAAAACA-_BYNwvmyAs7fIW7Mddolwj9WGEdtnn_vVK2LV8lP_tBeuk5NXYB8LMfF8EbYa
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/douyin/user/MS4wLjABAAAACA-_BYNwvmyAs7fIW7Mddolwj9WGEdtnn_vVK2LV8lP_tBeuk5NXYB8LMfF8EbYa?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by lawvs** [comment]
Duplicated of https://github.com/RSSNext/Follow/issues/1356

TikTok has strict anti-scraping strategies, and we will also regularly update to improve the follow user experience.
