### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/%40%E8%80%81%E8%92%8B%E5%B7%A8%E9%9D%A0%E8%B0%B1-q2j

### ISSUE THREAD

**Issue by DepressBeater** [RSSNext/Follow#1347]
### Info:

Feed URL:
```
rsshub://youtube/user/%40%E8%80%81%E8%92%8B%E5%B7%A8%E9%9D%A0%E8%B0%B1-q2j
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/user/%40%E8%80%81%E8%92%8B%E5%B7%A8%E9%9D%A0%E8%B0%B1-q2j?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/17f9c3f4-548a-41c5-91e0-4c49194d519e)

It should be OK now. If you have any problems, you can open this issue again.
