### ISSUE TITLE
Error in fetching feed: rsshub://follow/profile/68201534336230400

### ISSUE THREAD

**Issue by Allen0413cm** [RSSNext/Follow#1350]
### Info:

Feed URL:
```
rsshub://follow/profile/68201534336230400
```

Error:
```
抓取動態時發生錯誤: [GET] "http://10.1.32.41/follow/profile/68201534336230400?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
This user does not exist in follow
