### ISSUE TITLE
Error in fetching feed: https://blog.skk.moe/rss.xml

### ISSUE THREAD

**Issue by Li-Jack** [RSSNext/Follow#1359]
### Info:

Feed URL:
```
https://blog.skk.moe/rss.xml
```

Error:
```
Feed 获取错误: [GET] "https://blog.skk.moe/rss.xml": 403 Forbidden
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
You can try https://blog.skk.moe/atom.xml for now
