### ISSUE TITLE
Feed Error: Bloomberg - Green, [GET] "http://10.1.32.41/bloomberg/green?format=json": 503 Service Unavailable

### ISSUE THREAD

**Issue by siuhemhem** [RSSNext/Follow#1363]
### Error

Error Message: [GET] "http://10.1.32.41/bloomberg/green?format=json": 503 Service Unavailable

### Info

```json
{
  "type": "feed",
  "id": "71184697885915136",
  "url": "rsshub://bloomberg/green",
  "title": "Bloomberg - Green",
  "description": "Bloomberg - Green - Powered by RSSHub",
  "siteUrl": "https://www.bloomberg.com/feeds/green/sitemap_news.xml",
  "image": null,
  "errorMessage": "[GET] \"http://10.1.32.41/bloomberg/green?format=json\": 503 Service Unavailable",
  "errorAt": "2024-11-03T06:20:24.811Z",
  "ownerUserId": null,
  "tipUsers": []
}
```

### Environment

**App Version**: 0.0.1-alpha.21
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.21 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/a6d5bf45-2a8f-438a-a22a-bd80377f59de)

It should be OK now. If you have any problems, you can open this issue again.
