### ISSUE TITLE
Feed Error: 英语学记YKing, [GET] "https://nic.fra1.zeabur.app/feeds/MP_WXS_3870688342.atom": 404 Not Found

### ISSUE THREAD

**Issue by lweisheng** [RSSNext/Follow#1366]
### Error

Error Message: [GET] "https://nic.fra1.zeabur.app/feeds/MP_WXS_3870688342.atom": 404 Not Found

### Info

```json
{
  "type": "feed",
  "id": "72547615127570432",
  "title": "英语学记YKing",
  "errorAt": "2024-10-28T09:31:57.737Z",
  "errorMessage": "[GET] \"https://nic.fra1.zeabur.app/feeds/MP_WXS_3870688342.atom\": 404 Not Found",
  "url": "https://nic.fra1.zeabur.app/feeds/MP_WXS_3870688342.atom",
  "image": null,
  "siteUrl": "https://nic.fra1.zeabur.app/feeds/MP_WXS_3870688342.atom"
}
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/3a2747de-16d2-414f-8e84-2533b072594e)

It should be OK now. If you have any problems, you can open this issue again.
