### ISSUE TITLE
Error in fetching feed: https://hostloc.com/forum.php?mod=rss&fid=45&auth=****

### ISSUE THREAD

**Issue by crazy0x70** [RSSNext/Follow#1369]
### Info:

Feed URL:
```
https://hostloc.com/forum.php?mod=rss&fid=45&auth=****(This is my cookie.)
```

Error:
```
Feed 获取错误: [GET] "https://hostloc.com/forum.php?mod=rss&fid=45&auth=****": 418 
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by lawvs** [comment]
It works on my machine. It might have been blocked by the website policy temporarily. Please try again, and feel free to reopen this issue if it doesn't work.
