### ISSUE TITLE
The URL of RSS is accessible，But  fetch failed

### ISSUE THREAD

**Issue by KeyleXiao** [RSSNext/Follow#1372]
### Error

Error Message: [GET] "https://vrast.cn/atom.xml?t=1730688928809": <no response> fetch failed

### Info

```json
{
  "type": "feed",
  "id": "61724628700647464",
  "title": "Keyle's Blog",
  "errorAt": "2024-11-01T09:21:39.262Z",
  "errorMessage": "[GET] \"https://vrast.cn/atom.xml?t=1730688928809\": <no response> fetch failed",
  "url": "https://vrast.cn/atom.xml",
  "image": null,
  "siteUrl": "https://vrast.cn/atom.xml"
}
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment]
It should be fine now, https://vrast.cn/posts/64725/

**Comment by KeyleXiao** [comment]
I have already solved this problem. The following link shows the process of discovering and resolving this issue
https://vrast.cn/posts/64725/
