### ISSUE TITLE
Add href to all the urls

### ISSUE THREAD

**Issue by redreamality** [RSSNext/Follow#1373]
### Clear and concise description of the problem

As a developer using this project I want [goal / wish] so that [benefit]

![Image](https://github.com/user-attachments/assets/a1daf9b7-26c9-4ce2-a73d-0ce2045fcf93)

### Suggested solution

In the rendering module, find the urls (strings starts with https://  or http://) and modify the style to blue links.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
@hyoban Look at this, the autolink feature was removed for some reasons last time, and now this function needs to be added back.
