### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/%40splinetool

### ISSUE THREAD

**Issue by loganji** [RSSNext/Follow#1379]
### Info:

Feed URL:
```
rsshub://youtube/user/%40splinetool
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/user/%40splinetool?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/3a630af7-00e3-495d-9d26-e6042974ac4e)

It should be OK now. If you have any problems, you can open this issue again.
