### ISSUE TITLE
Error in fetching feed: rsshub://bilibili/user/dynamic/3546616569006401

### ISSUE THREAD

**Issue by wanghuasheng** [RSSNext/Follow#1381]
### Info:

Feed URL:
```
rsshub://bilibili/user/dynamic/3546616569006401
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/bilibili/user/dynamic/3546616569006401?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.0-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.0-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/0b9d453a-9b92-492e-b394-9f3e2e13c525)

It should be OK now. If you have any problems, you can open this issue again.
