### ISSUE TITLE
Error in fetching feed: https://www.kmcenter.org/feed

### ISSUE THREAD

**Issue by jialingxiao** [RSSNext/Follow#1382]
### Info:

Feed URL:
```
https://www.kmcenter.org/feed
```

Error:
```
Feed 获取错误: [GET] "https://www.kmcenter.org/feed": <no response> fetch failed
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/de86558c-5259-4eea-a700-1b2f731fcfd7)
