### ISSUE TITLE
Error in fetching feed: rsshub://youtube/playlist/https%3A%2F%2Fwww.youtube.com%2F%40TuTu

### ISSUE THREAD

**Issue by qcyy9527** [RSSNext/Follow#1393]
### Info:

Feed URL:
```
rsshub://youtube/playlist/https%3A%2F%2Fwww.youtube.com%2F%40TuTu
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/playlist/https%3A%2F%2Fwww.youtube.com%2F%40TuTu?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
If you want to subscribe to a Youtube channel, please select `Channel with username`

![Image](https://github.com/user-attachments/assets/65dc1dcb-c41e-49cd-b873-bc2b269822a8)

```
rsshub://youtube/user/%40TuTu
```

**Comment by binbho7** [comment]
OK
