### ISSUE TITLE
Error in fetching feed: https://app.follow.is/share/lists/68227244472375296?view=1

### ISSUE THREAD

**Issue by loganji** [RSSNext/Follow#1398]
### Info:

Feed URL:
```
https://app.follow.is/share/lists/68227244472375296?view=1
```

Error:
```
Feed 解析失败: Unexpected close tag
Line: 54
Column: 9
Char: >
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
This is not a RSS feed URL. If you want to follow a list, just click this follow button.
