### ISSUE TITLE
Error in fetching list: 61281182066598912

### ISSUE THREAD

**Issue by pengan95** [RSSNext/Follow#1399]
### Info:

List ID:
```
61281182066598912
```

Error:
```
Cannot add property 61281182066598912, object is not extensible
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
Can you provide more info about how to reproduce this issue?

**Comment by hyoban** [comment]
Duplicate of #1332

**Comment by pengan95** [comment]
list: https://app.follow.is/share/lists/61281182066598912 
open in browser, click "Open in App" will show this
![Image](https://github.com/user-attachments/assets/53a3a6c4-f242-41e8-bf89-39c6917695f4)

**Comment by hyoban** [comment]
Thanks, will take a look.

**Comment by hyoban** [comment]
No problem in my environment. Can you provide more info?

https://github.com/user-attachments/assets/c8519d53-f058-4a25-a174-21bbc85b4a5b

**Comment by hyoban** [comment]
Maybe with https://github.com/RSSNext/Follow/commit/3a3992d63f0f62cd37aa5accb4910ad79e3190e8#diff-9dadad1cf7b9066e2860e64f387282da001743d4d6a9bde6bc9010fe91cd2cdf and https://github.com/RSSNext/Follow/commit/7e5a79155a083a8242579dee18d019049b7ad6f5#diff-9dadad1cf7b9066e2860e64f387282da001743d4d6a9bde6bc9010fe91cd2cdf these two commits Related, @Innei can Can you help me?

**Comment by pengan95** [comment]
https://github.com/RSSNext/Follow/issues/1399#issuecomment-2456171425
Currently, I can’t reproduce this bug anymore. After successfully subscribing in the browser, it also synced with the app. Then, when I cancel the subscription and subscribe again in the app, it successfully subscribes to this list.
However, another bug appeared: although it shows a successful subscription and the refreshed subscription list includes this content, if I click refresh again, the subscription disappears on its own.

**Comment by hyoban** [comment]
Try rebuilding the database in the settings, what would that look like?

![Image](https://github.com/user-attachments/assets/e7b1186a-c010-44eb-a84f-0f081ec1cfbb)

**Comment by pengan95** [comment]
@hyoban it works, thanks a lot
