### ISSUE TITLE
Error in fetching feed: https://primitive.ventures/#writings

### ISSUE THREAD

**Issue by jonasqin** [RSSNext/Follow#1408]
### Info:

Feed URL:
```
https://primitive.ventures/#writings
```

Error:
```
Feed 解析失败: Attribute without value
Line: 1
Column: 23
Char: l
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
This is not an RSS feed URL

**Comment by lawvs** [comment]
You need to enter an RSS link. If the website does not provide RSS, you can try the following methods:

- Search on RSSHub (https://docs.rsshub.app/)
- Search others' subscriptions in Follow
![Image](https://github.com/user-attachments/assets/fb04619f-060f-4e89-a2bb-a9043b76d00a)

- Use the transform feature to convert the webpage.
![Image](https://github.com/user-attachments/assets/96b3e67a-8611-45cf-8e38-15efd583983b)
