### ISSUE TITLE
Error in fetching feed: rsshub://follow/profile/73507217578383360

### ISSUE THREAD

**Issue by lovescxs** [RSSNext/Follow#1409]
### Info:

Feed URL:
```
rsshub://follow/profile/73507217578383360
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/follow/profile/73507217578383360?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/c7271b16-3203-4a25-bac7-6e6fb2cdada4)

Can not reproduce it, feel free to reopen this issue if you still have questions
