### ISSUE TITLE
Error in fetching list: 67389023042166784

### ISSUE THREAD

**Issue by sveinzhang** [RSSNext/Follow#1411]
### Info:

List ID:
```
67389023042166784
```

Error:
```
Cannot add property 67389023042166784, object is not extensible
```

### Environment

**App Version**: 0.1.2-nightly.20241103
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241103 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `LACo6eMh6iioDMu6DWOuG`

**Comment by hyoban** [comment]
Duplicate
