### ISSUE TITLE
Error in fetching feed: rsshub://bilibili/user/dynamic/2266021

### ISSUE THREAD

**Issue by Zfengjing** [RSSNext/Follow#1412]
### Info:

Feed URL:
```
rsshub://bilibili/user/dynamic/2266021
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/bilibili/user/dynamic/2266021?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
**Env**: web
**Browser**: Microsoft Edge

**Comment by hyoban** [comment]
There should be no problem now

![Image](https://github.com/user-attachments/assets/201a97c7-87b6-444a-8ec2-d8bfa03aa7ee)
