### ISSUE TITLE
Error in fetching feed: https://https://news.nweon.com/feed

### ISSUE THREAD

**Issue by waxwell** [RSSNext/Follow#1413]
### Info:

Feed URL:
```
https://https://news.nweon.com/feed
```

Error:
```
Feed 获取错误: [GET] "https://https://news.nweon.com/feed": <no response> fetch failed
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/fe101247-1839-4a65-8cc4-98937a8cc49b)
