### ISSUE TITLE
Error in fetching feed: rsshub://zhihu/hot/total

### ISSUE THREAD

**Issue by 1214136850** [RSSNext/Follow#1427]
### Info:

Feed URL:
```
rsshub://zhihu/hot/total
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Fzhihu%2Fhot%2Ftotal": <no response> Failed to fetch
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment]
It should be OK now. If you have any problems, feel free to reopen this issue.
