### ISSUE TITLE
The title is copyable

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1428]
### Clear and concise description of the problem

https://github.com/user-attachments/assets/4b074a3e-bdab-4d22-b50a-07c5027cb699

https://github.com/user-attachments/assets/544360e1-f05e-42d4-be78-484e7ce02a78

### Suggested solution

X

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Does this help you?

![Image](https://github.com/user-attachments/assets/2a4052f6-aaca-428b-9390-545d55f8cf99)

**Comment by EnterMan123** [comment]
> Does this help you?
> 
> ![Image](https://github.com/user-attachments/assets/2a4052f6-aaca-428b-9390-545d55f8cf99)

This is good, but it lacks flexibility; sometimes, we only want to copy specific characters.

**Comment by EnterMan123** [comment]
https://github.com/user-attachments/assets/8279a869-4c24-4cae-9bac-f41d4994ce04


It’s easy to accidentally open a URL when copying text from a title. @Innei
