### ISSUE TITLE
Request for Adding Shortcut Key for Switching between Light and Dark Themes

### ISSUE THREAD

**Issue by syd111** [RSSNext/Follow#1430]
### Environment

**App Version**: 0.1.2-nightly.20241103
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241103 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `VTeme2FtMftCbt6GM-hkz`

When reading, the environment can vary between day and night. It would be helpful to have a shortcut key for toggling between light and dark themes to accommodate different lighting conditions.

**Comment by hyoban** [comment]
Doesn't setting the theme to system and then switching the system's theme solve your problem?

**Comment by syd111** [comment]
> Doesn't setting the theme to system and then switching the system's theme solve your problem?

Like Obsidian, it can quickly switch between dark and light modes. I believe this feature will be available in the future. Let's do the main function first. 
 
There is another problem. It takes a long time to display the article after clicking the follow button. The rss is already full text. Clicking the view source content will render the article immediately. But the rendering of non-original mode takes a long time. I think it is because of the conversion of text layout or other issues that consume time? 
Is this related to your server? I'm not sure if a server is required. I remember you mentioned a transit link address or something. But the current experience is very bad, and I once wanted to give up this software. 
﻿

**Comment by lawvs** [comment]
The issue of slow access is due to increased traffic recently leading to increased server load, and we are working hard to improve this problem.
