### ISSUE TITLE
Unable to disable the upgrade version prompt

### ISSUE THREAD

**Issue by paulxjz** [RSSNext/Follow#1450]
### Describe the bug

"Updated to version 0.1.2-nightly.20241106, enjoy the new features!“ This prompt cannot be closed and remains persistent. 

### Feed Info

It pops up every time you open it and does not disappear automatically.

### Environment

**App Version**: 0.1.2-nightly.20241106
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241106 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `Lh0Eq89wp7om-IPuPEJhy`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
I suggest adding a close button.

https://github.com/user-attachments/assets/92115242-71f2-4c5a-b8ac-3344c80ae2e2

**Comment by paulxjz** [comment]
> I suggest adding a close button.
> 
> https://github.com/user-attachments/assets/92115242-71f2-4c5a-b8ac-3344c80ae2e2
> 

I know this method turns off notifications, but what I'm trying to say is that it will pop up every time I open follow, it's reopening it, not opening it from the system tray

**Comment by hyoban** [comment]
Check your app version from the local storage

![Image](https://github.com/user-attachments/assets/c47abec7-402f-4313-9e8b-a51db63b9179)

**Comment by paulxjz** [comment]
> Check your app version from the local storage
> 
> ![Image](https://github.com/user-attachments/assets/c47abec7-402f-4313-9e8b-a51db63b9179)

How should I do it, how do I open this interface, are there specific steps?
