### ISSUE TITLE
Playing youtube videos prompts you to log in

### ISSUE THREAD

**Issue by b-jh** [RSSNext/Follow#1451]
### Describe the bug

播放youtube提示要登录

### Feed Info

![Image](https://github.com/user-attachments/assets/f92461ea-ddd9-46b0-b4cd-9a731c3dd8de)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by b-jh** [comment]
但是我用浏览器直接访问的话，是没问题的，能够播放youtube
________________________________
发件人: Eric Zhu ***@***.***>
发送时间: 2024年11月8日 12:38
收件人: RSSNext/Follow ***@***.***>
抄送: 李木白 ***@***.***>; Author ***@***.***>
主题: Re: [RSSNext/Follow] 播放youtube视频提示要登录 (Issue #1451)


It is caused by the proxy you are using, not by follow.

―

**Comment by b-jh** [comment]
> It is caused by the proxy you are using, not by follow.它是由您正在使用的代理引起的，而不是由跟随引起的。

但是我用浏览器直接访问的话，是没问题的，能够播放youtube

**Comment by hyoban** [comment]
You can try changing the proxy, it should solve the problem

**Comment by Eroticoo** [comment]
你好，请问你解决了吗？

**Comment by BannyLon** [comment]
2025 年都快过完了，这个错误还没解决啊！

**Comment by BannyLon** [comment]
求解决办法，
