### ISSUE TITLE
New Version Slow and Constantly Loading

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1456]
### Describe the bug

New version is very slow, constantly loading no matter what you're doing.

Is it due to the server?

https://github.com/user-attachments/assets/b6e9f453-b839-4a0d-8773-d304ad4a7738

https://github.com/user-attachments/assets/769c5a02-bd6e-4d79-bb52-eb58480affc8

![Image](https://github.com/user-attachments/assets/eaac9331-70e5-4b17-bd29-4ef733073258)

### Feed Info

X

### Environment

**App Version**: 0.1.2-nightly.20241106
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241106 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `FyJ6583c9-RRRRMwRTOca`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
The recent increase in traffic has led to higher server load, and we are working hard to address this issue.

**Comment by lawvs** [comment]
This issue should have been resolved. If it can still be reproduced, please feel free to reopen this issue.
