### ISSUE TITLE
When the telegram displays the original text, Microsoft's prompt to "open this tg link with a new app" pops up every time

### ISSUE THREAD

**Issue by light-lgh** [RSSNext/Follow#1459]
### Describe the bug

When the telegram displays the original text, Microsoft's prompt to "open this tg link with a new app" pops up every time

### Feed Info

rsshub://telegram/channel/shareAliyun

### Reproduction Video

https://github.com/user-attachments/assets/8140e4b2-0694-4b04-9bc6-45e1d0f3e13e

### Environment

**App Version**: 0.1.0-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.0-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is the behavior of telegram website itself
