### ISSUE TITLE
23qb.com/rss.xml is not fully parsed and cannot display novel URL links, images, etc.

### ISSUE THREAD

**Issue by wtongxue7** [RSSNext/Follow#1460]
### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

网站rss链接为https://www.23qb.com/rss.xml
follow只解析出了title标签,pubDate标签内容,其余内容均为正确显示

<item>
<title>盘龙，我另类超脱</title>
<link>https://www.23qb.com/book/12712/</link>
<image>
https://www.23qb.com/files/article/image/12/12712/12712s.jpg
</image>
<author>无幽无褛</author>
<pubDate>2024-08-13</pubDate>
<description>""</description>
</item>
![Image](https://github.com/user-attachments/assets/83b03192-2416-4598-be1f-3b621fea7c99)

![Image](https://github.com/user-attachments/assets/8a3083f0-9d35-401c-aeac-b3430fbd1831)

**Comment by lawvs** [comment]
The image provided by the RSS of this website is incorrect.


```xml
<item>
<title>盘龙，我另类超脱</title>
<link>https://www.23qb.com/book/12712/</link>
<image>
https://www.23qb.com/files/article/image/12/12712/12712s.jpg
</image>
<author>无幽无褛</author>
<pubDate>2024-08-13</pubDate>
<description>""</description>
</item>
```

![Image](https://github.com/user-attachments/assets/02945ec1-6a12-4006-8b1a-373931b2be6e)
