### ISSUE TITLE
Error in fetching feed: https://x.com/appwrite

### ISSUE THREAD

**Issue by x751685875** [RSSNext/Follow#1467]
### Info:

Feed URL:
```
https://x.com/appwrite
```

Error:
```
Feed 解析失败: Unexpected close tag
Line: 34
Column: 13
Char: >
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by hyoban** [comment]
This is not an RSS feed URL.
