### ISSUE TITLE
Error in fetching feed: https://rsshub.app/csdn/blog/weixin_45886869

### ISSUE THREAD

**Issue by Chi-hong22** [RSSNext/Follow#1488]
### Info:

Feed URL:
```
https://rsshub.app/csdn/blog/weixin_45886869
```

Error:
```
[GET] "https://api.follow.is/feeds?url=https%3A%2F%2Frsshub.app%2Fcsdn%2Fblog%2Fweixin_45886869": 503 
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
You can use https://rss.csdn.net/weixin_45886869/rss/map for now
