### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/%40mediastorm680

### ISSUE THREAD

**Issue by shengrui123** [RSSNext/Follow#1489]
### Info:

Feed URL:
```
rsshub://youtube/user/%40mediastorm680
```

Error:
```
抓取動態時發生錯誤: [GET] "http://10.1.32.41/youtube/user/%40mediastorm680?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
**Env**: web
**Browser**: Firefox

**Comment by TonyRL** [comment]
This channel https://www.youtube.com/@mediastorm680 does not exist.
