### ISSUE TITLE
Error in fetching feed: https://sspai.com/feed

### ISSUE THREAD

**Issue by shaomingchan** [RSSNext/Follow#1490]
### Info:

Feed URL:
```
https://sspai.com/feed
```

Error:
```
500
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
Can not reproduce https://app.follow.is/share/feeds/41359836954400795
