### ISSUE TITLE
Error in fetching feed: https://academic.oup.com/rss/site_5475/3336.xml & https://academic.oup.com/rss/site_5576/3432.xml

### ISSUE THREAD

**Issue by forkmax** [RSSNext/Follow#1497]
### Info:

Feed URL:
```
https://academic.oup.com/rss/site_5475/3336.xml
https://academic.oup.com/rss/site_5576/3432.xml

```

Error:
```
Feed failed to parse: Feed not recognized as RSS 1 or 2.
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
This website has specific anti-crawling measures. This is not something that follow server can solve.

```
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```
