### ISSUE TITLE
[Architecture] Local first

### ISSUE THREAD

**Issue by Innei** [RSSNext/follow#15]
Currently, the API needs to be available to continue using the app, perhaps a local first architecture is needed.

**Comment by DIYgod** [comment]
A server is essential in the background to fetch RSS feeds and ensure updates are not missed; relying on a local client would result in a poor experience.

Furthermore, our goal is to provide a comprehensive and user-friendly solution that includes lightweight yet vital social, sharing, and monetization features. These elements are crucial for effective product promotion and sustainability, which cannot be achieved with just a local setup.

**Comment by Innei** [comment]
I understand all this. But at the moment, if there is no network or the api is not reachable, it is not possible to read the data that has been fetched before, in this case, for example, Feeds Entity, should this data be cached locally so that it is available in this environment?

**Comment by DIYgod** [comment]
In fact, I have already cached the data into localstorage. https://github.com/RSSNext/follow/blob/b10280712a5464ed2c7ecd5271bf595cb7727a62/src/renderer/src/lib/query-client.ts#L13
Most of the APIs can be read correctly. But it doesn't seem very complete, the part that determines login has not been cached yet.
