### ISSUE TITLE
Content collected in a certain view category cannot be seen in the collection of that view . Can only be seen in collections in other view categories.

### ISSUE THREAD

**Issue by b-jh** [RSSNext/follow#1505]
### Describe the bug

在某个视图分类中收藏的内容，在该视图的收藏中看不到。只能在其他视图分类的收藏中看到。我重建数据库也不行。会不会更订阅地址修改视图有关系？

### Feed Info

rsshub://1lou/forum-11
66474944611469312

### Reproduction Video

This is a recorded video
https://vod.gfa123.com/900937259dda71ef9c665017e1e90102/79729604734f48be803301dd8f8390d2-23261a5b69528b63120f1e6383534e87-sd.mp4

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by b-jh** [comment]
这个是录制的视频
https://vod.gfa123.com/900937259dda71ef9c665017e1e90102/79729604734f48be803301dd8f8390d2-23261a5b69528b63120f1e6383534e87-sd.mp4

**Comment by b-jh** [comment]
Have you all encountered this situation before。

**Comment by hyoban** [comment]
Did you change this feed from social media view to notification view?

**Comment by hyoban** [comment]
This problem is caused by a server-side error. You can correct the view of the favorite entry by modifying the feed view.

**Comment by b-jh** [comment]
> This problem is caused by a server-side error. You can correct the view of the favorite entry by modifying the feed view.

I have tried to modify the view repeatedly in your way, many times, but only a few subscribed collections have worked properly, and the results are still not satisfactory. Will this question be revised later?

**Comment by hyoban** [comment]
Maybe try de-favoriting and then adding it again? The collection  feature should now be correct

**Comment by b-jh** [comment]
Do you mean to delete the subscription or delete the collection of this subscription? If it's deleting a collection, it would be too troublesome because there are many collections.

**Comment by b-jh** [comment]
I just deleted the subscription feed and added it again still, and my favorites are still notified there again. Also watch that video I uploaded.
Subscribe to: https://1lou/forum-11 and this is also happening.

**Comment by hyoban** [comment]
No, you need to update your view, not unfollow and follow again.

**Comment by b-jh** [comment]
How to need to update the view。

**Comment by b-jh** [comment]
我删除订阅源再订阅，并且清除浏览器缓存后问题解决了。不过
我发现了一个新bug,在我删除订阅源之前，我有这个源的4个收藏。当我删除后再订阅，发现只有1个收藏了，是不是在我删除订阅源后，收藏只保留一段时间的收藏，时间久的就不保存到服务器了？
删除订阅源的时候，收藏的内容是不是也删除了？
翻译：
See Chinese if you can read it.
The problem was solved when I deleted the subscription feed and subscribed again, and cleared my browser cache. However
I found a new bug,before I deleted the subscription source I had 4 favorites from this source. When I deleted the feed and subscribed again, I found that there is only 1 favorite. Is it possible that after I deleted the feed, the favorites are only kept for a certain period of time, and the ones that have been there for a long time are not saved to the server?
When I delete the subscription source, are the favorites also deleted?

**Comment by b-jh** [comment]
> No, you need to update the view for your subscription, not unfollow and follow again.

I tried updating the subscription feed several times without solving the problem.
