### ISSUE TITLE
Sidebar Color Inconsistency Between Web and Desktop Versions

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1509]
### Describe the bug
![Image](https://github.com/user-attachments/assets/17862e41-580a-4bf6-a29d-298cd79c727b)

![Image](https://github.com/user-attachments/assets/ad0445fb-58e2-4f2a-8d3c-ab4419150d83)
Is this the switch? It seems like there's no response.

### Feed Info

X

### Environment

**App Version**: 0.2.0-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `iEO-UlHgQHO4NQTTOjifp`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
This is by design, and there are some inconsistencies between the web and the app.

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/cb16c7de-e2d7-4d99-b5f6-08c7c89298fe)
Can you check this?

**Comment by EnterMan123** [comment]
It appears that the feature has no effect
