### ISSUE TITLE
Add info text on Migration Step for better UX

### ISSUE THREAD

**Issue by daniel0ar** [RSSNext/Follow#1514]
### Clear and concise description of the problem

The Migrate from OPML section on welcome doesn't have info on what an OPML file is or it's unclear if this is where a setup migration should happend (migrating setup from another RSS platform).
![Image](https://github.com/user-attachments/assets/4c9ec32f-0c14-45c3-a30e-8331dcec6ea9)

### Suggested solution

Add a small paragraph tag instead of the text "OPML File" that is currently displayed above the file input: "If you have used RSS before, you can export your data config to an OMPL file and import it here", as seen in the following image:
![Image](https://github.com/user-attachments/assets/2c28e8d5-0450-40dc-803a-a204bd2aebf2)
I can send a PR with this 👍🏽 

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
@hyoban What do you think?

**Comment by hyoban** [comment]
It would be nice to add a description, pr welcome
