### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/1137634210/notes

### ISSUE THREAD

**Issue by 15b883** [RSSNext/Follow#1521]
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/1137634210/notes
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/1137634210/notes?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `kUR1j687ElTLedMn9qizX`

**Comment by TonyRL** [comment]
This user https://www.xiaohongshu.com/user/profile/1137634210 does not exist.
