### ISSUE TITLE
科技日报出问题

### ISSUE THREAD

**Issue by zhaoscsc** [RSSNext/Follow#1526]
### Error

Error Message: [GET] "http://10.1.32.41/stdaily/digitalpaper?format=json": 503 Service Unavailable

### Info

```json
{
  "type": "feed",
  "id": "63118600077338629",
  "title": "科技日报",
  "errorAt": "2024-11-08T16:51:38.365Z",
  "errorMessage": "[GET] \"http://10.1.32.41/stdaily/digitalpaper?format=json\": 503 Service Unavailable",
  "url": "rsshub://stdaily/digitalpaper",
  "image": null,
  "siteUrl": "http://digitalpaper.stdaily.com/",
  "ownerUserId": null
}
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `ErK63piftsYlfAAYi9Zt3`

**Comment by hyoban** [comment]
It should be fine now, it has no error message

![Image](https://github.com/user-attachments/assets/ad7b9635-9dcf-41e8-b482-b768b11d1e73)
