### ISSUE TITLE
Error in fetching feed: https://t.me/wmir2

### ISSUE THREAD

**Issue by Missx8888** [RSSNext/Follow#1532]
### Info:

Feed URL:
```
https://t.me/wmir2
```

Error:
```
Feed 解析失败: Invalid character in entity name
Line: 6
Column: 40
Char: &
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `tOUkcbEm57oIwAoehflg9`

**Comment by hyoban** [comment]
This is not an RSS feed URL, try `rsshub://telegram/channel/wmir2`
