### ISSUE TITLE
Error in fetching feed: rsshub://nga/forum/-7

### ISSUE THREAD

**Issue by malcolmyu** [RSSNext/Follow#1533]
### Info:

Feed URL:
```
rsshub://nga/forum/-7
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/nga/forum/-7?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `OukptVYMaSvZW96GOOeq-`

**Comment by hyoban** [comment]
https://github.com/DIYgod/RSSHub/issues/10185

**Comment by hyoban** [comment]
It should be fine now, we have added the relevant configuration

![Image](https://github.com/user-attachments/assets/637668c2-baf2-47f2-a281-71ff8f22445c)
