### ISSUE TITLE
[Bug Report] AI summary generation not working after update to v0.2.0-beta.2

### ISSUE THREAD

**Issue by forkmax** [RSSNext/follow#1542]
## Description
After updating to the latest version, the AI summary feature is not functioning for any articles.

**Current Behavior:**
- AI summary generation fails for all articles
- No error message is displayed
- Feature appears to be completely non-functional

**Expected Behavior:**
- AI summaries should generate for articles directly after setting the Action function
- Feature should work as it did in previous versions

**Steps to Reproduce:**
1. Set when view = article, then all the articles should generate AI summary
2. Open any article in the View like article
4. Observe that no summary is generated

**Additional Context:**
- This issue started immediately after updating to version 0.2.0-beta.2
- Affects all articles regardless of source or content type
- No specific error messages are shown to indicate the cause

### Feed Info

All the feed

### Environment

App Version: 0.2.0-beta.2
OS: macOS
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.2 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
Env: electron
Browser: Chrome
Session Trace Id: m69NOmIY8-HsUWmc90oK6

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by ZlxmChen** [comment]
Same App Version & OS, seems that AI summary generation work well on my laptop, perhaps checkin network issue could benefit?
