### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/%40lihaoshuai

### ISSUE THREAD

**Issue by Shengjingwa** [RSSNext/Follow#1544]
### Info:

Feed URL:
```
rsshub://youtube/user/%40lihaoshuai
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/user/%40lihaoshuai?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `g28svgEFZKzHzLBdK0Cc2`

**Comment by hyoban** [comment]
It should be fine now

![Image](https://github.com/user-attachments/assets/22460268-4e34-4eae-9d07-0e6d2007060e)
