### ISSUE TITLE
Feed Error: All Content from Business Insider, 200 OK

### ISSUE THREAD

**Issue by siuhemhem** [RSSNext/Follow#1549]
### Error

Error Message: 200 OK

### Info

```json
{
  "type": "feed",
  "id": "59933051319320582",
  "url": "https://feeds.businessinsider.com/custom/all",
  "title": "All Content from Business Insider",
  "description": "All Content from Business Insider Excluding Premium",
  "siteUrl": "https://feeds.businessinsider.com/pull/bi/all?after=20&limit=20&toDate=2024-11-09T03%3A33%3A23Z",
  "image": null,
  "errorMessage": "200 OK",
  "errorAt": "2024-11-09T05:46:48.611Z",
  "ownerUserId": null
}
```

### Environment

**App Version**: 0.0.1-alpha.21
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.21 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
It should be fine now, it has no error message

![Image](https://github.com/user-attachments/assets/441c41b2-1f1f-4d9c-9423-181a60604687)
