### ISSUE TITLE
Error in fetching feed: https://www.liujunmin.com/feed.xml

### ISSUE THREAD

**Issue by bakamake** [RSSNext/Follow#1550]
### Info:

Feed URL:
```
https://www.liujunmin.com/feed.xml
```

Error:
```
Feed 获取错误: [GET] "https://www.liujunmin.com/feed.xml": <no response> fetch failed
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `DeMw8LoQ5snWtyYEdG1KB`

**Comment by hyoban** [comment]
SSL certificate problem: certificate has expired
