### ISSUE TITLE
Feed Error: arXiv每日学术速递 - 今天看啥, 200 OK

### ISSUE THREAD

**Issue by hhr114** [RSSNext/Follow#1553]
### Error

Error Message: 200 OK

### Info

```json
{
  "type": "feed",
  "id": "71831416389894144",
  "title": "arXiv每日学术速递 - 今天看啥",
  "errorAt": "2024-11-02T08:52:24.935Z",
  "errorMessage": "200 OK",
  "url": "http://www.jintiankansha.me/rss/GIZDGNRUGB6GKOLGGJTGEOBZGAYGKYLGMRTDQOLGMM4GEMZWMFTDKN3EG44DINZXGE3GKNZTGA2Q====",
  "image": "http://img.jintiankansha.me/weixin/head/Mzg4OTEwNjMzMA==",
  "siteUrl": "http://www.jintiankansha.me/column/9GhmtDHnhg",
  "ownerUserId": null
}
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `UJ6d1SKhfdFP3mhztF70i`

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/b398be40-4566-4514-a322-e63289a27545)
