### ISSUE TITLE
Error in fetching feed: rsshub://bilibili/user/dynamic/320032672

### ISSUE THREAD

**Issue by 727566105** [RSSNext/Follow#1560]
### Info:

Feed URL:
```
rsshub://bilibili/user/dynamic/320032672
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/bilibili/user/dynamic/320032672?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.2 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `t1GR792_wNWnzx5MxY1Pi`

**Comment by hyoban** [comment]
It should be fine now

![Image](https://github.com/user-attachments/assets/713a5e1b-4005-4be8-8085-5c1fa5314618)
