### ISSUE TITLE
Cannot resubscribe after unsubscribing

### ISSUE THREAD

**Issue by gotoan** [RSSNext/Follow#1565]
### Describe the bug

退订之后重新订阅一直显示已订阅状态，无法重新订阅

### Feed Info

https://www.stats.gov.cn/sj/zxfb/rss.xml

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I can't reproduce it, can you provide more information on reproduction? It would be great to have a screen recording

**Comment by gotoan** [comment]
it's okey now after waitting some minutes.
