### ISSUE TITLE
Error in fetching feed: rsshub://telegram/channel/%40U7BFUREN9BUKH7KV7NP6

### ISSUE THREAD

**Issue by Chinaljy** [RSSNext/Follow#1577]
### Info:

Feed URL:
```
rsshub://telegram/channel/%40U7BFUREN9BUKH7KV7NP6
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/telegram/channel/%40U7BFUREN9BUKH7KV7NP6?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.2 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `f2mb8Duq4oFv_0xq_7ZyL`

**Comment by hyoban** [comment]
This is not a correct telegram channel id
