### ISSUE TITLE
Error in fetching feed: rsshub://bilibili/user/dynamic/410606408

### ISSUE THREAD

**Issue by SukSuk1986** [RSSNext/Follow#1581]
### Info:

Feed URL:
```
rsshub://bilibili/user/dynamic/410606408
```

Error:
```
抓取動態時出錯: [GET] "http://10.1.32.41/bilibili/user/dynamic/410606408?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `CVNJCT1Jtx7aGGcXuapqs`

**Comment by hyoban** [comment]
There should be no problem with this feed now.

https://app.follow.is/share/feeds/79498393872578560
