### ISSUE TITLE
添加新的RSS时，提示Csrf token无效

### ISSUE THREAD

**Issue by rascalatu** [RSSNext/Follow#1595]
### Describe the bug

添加新的RSS时，提示Csrf token无效

### Feed Info

<html>
<body>

https://www.bmpi.dev/index.xml
--

<br class="Apple-interchange-newline">
</body>
</html>

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by rascalatu** [comment]
> [FOL-930 添加新的RSS时，提示Csrf token无效](https://linear.app/follow-app/issue/FOL-930/添加新的rss时，提示csrf-token无效)

it is showing "You don't have access to enter this workspace"

please support

**Comment by lawvs** [comment]
这个问题应该是网络波动引起的，应该已经恢复正常.如果还能复现，请重新打开这个 issue
