### ISSUE TITLE
Error in fetching feed: rsshub://xiaohongshu/user/a84c19420cf441b08bc8c38b2d08a77f/notes

### ISSUE THREAD

**Issue by Garlilay** [RSSNext/Follow#1603]
### Info:

Feed URL:
```
rsshub://xiaohongshu/user/a84c19420cf441b08bc8c38b2d08a77f/notes
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Fxiaohongshu%2Fuser%2Fa84c19420cf441b08bc8c38b2d08a77f%2Fnotes": <no response> Failed to fetch
```

### Environment

**App Version**: 0.0.1-nightly.20240925
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-nightly.20240925 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
The user https://www.xiaohongshu.com/user/profile/a84c19420cf441b08bc8c38b2d08a77f does not exist.
