### ISSUE TITLE
Feed Error: 小宇宙 - 发现, [GET] "https://rss.loli.mg/xiaoyuzhou": 503 Service Unavailable

### ISSUE THREAD

**Issue by Akarisz** [RSSNext/Follow#1604]
### Error

Error Message: [GET] "https://rss.loli.mg/xiaoyuzhou": 503 Service Unavailable

### Info

```json
{
  "type": "feed",
  "id": "58565927447941120",
  "title": "小宇宙 - 发现",
  "errorAt": "2024-10-28T09:54:24.255Z",
  "errorMessage": "[GET] \"https://rss.loli.mg/xiaoyuzhou\": 503 Service Unavailable",
  "url": "https://rss.loli.mg/xiaoyuzhou",
  "image": "https://www.xiaoyuzhoufm.com/apple-touch-icon.png",
  "siteUrl": "https://www.xiaoyuzhoufm.com/",
  "ownerUserId": null
}
```

### Environment

**App Version**: 0.2.1-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `7QMcFZInnRiJtu-wrqWdi`

**Comment by hyoban** [comment]
There is something wrong with the source itself

![Image](https://github.com/user-attachments/assets/9907cfca-4254-4812-865b-21861491eb3f)
