### ISSUE TITLE
The feed has been updated, but the follow cannot be refreshed

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#1609]
### Describe the bug

订阅源已更新内容，但是 follow 刷新不出来

例如 https://[rsshub.app/now/news/local](https://rsshub.app/now/news/local)

直接访问订阅源，可以看到已经有今天的新闻，
但是 follow 仍显示 19 个小时前的，在设置里重建了数据库，依旧如此

rsshub://now/news/local

![Image](https://github.com/user-attachments/assets/b5d0fe71-0767-4847-8af7-2bae96d098b8)

### Feed Info

https://[rsshub.app/now/news/local](https://rsshub.app/now/news/local)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by jerryc127** [comment]
> Fixed now

想问下，你说的修复，是你后台更新了这个rss地址，还是修复了程序上这个 bug ?

**Comment by hyoban** [comment]
Our server had some problems from last night to today, which may have affected the refresh of subscriptions. There should be no problems now.

If your subscription is not refreshed for a long time in the future, please feel free to create another issue.
