### ISSUE TITLE
Error in fetching feed: /hackernews/news

### ISSUE THREAD

**Issue by findwei** [RSSNext/Follow#1610]
### Info:

Feed URL:
```
/hackernews/news
```

Error:
```
[GET] "https://api.follow.is/feeds?url=%2Fhackernews%2Fnews": 422 
```

### Environment

**App Version**: 0.2.1-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `YKkfBori4UW2TRJujJgH8`

**Comment by hyoban** [comment]
This is not a valid feed URL
