### ISSUE TITLE
自建feed宕机修复后，follow中未能更新feed状态，仍显示ERROR

### ISSUE THREAD

**Issue by muserole** [RSSNext/Follow#1612]
### Describe the bug

自建feed宕机修复后，follow中未能更新feed状态，仍显示ERROR

### Feed Info

® Error since 20 hours ago
GET] "https://": <no response> This operation was aborted

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please provide feed information, otherwise we won't know how to solve the problem
