### ISSUE TITLE
Error in fetching feed: https://www.1993.cm/feed

### ISSUE THREAD

**Issue by lfscqk67** [RSSNext/Follow#1635]
### Info:

Feed URL:
```
https://www.1993.cm/feed
```

Error:
```
Feed 获取错误: [GET] "https://www.1993.cm/feed": 403 Forbidden
```

### Environment

**App Version**: 0.2.1-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.1-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `k1U85CUgUGWyNF6BNKC1r`

**Comment by hyoban** [comment]
This link is blocking access from our server, and this is not a problem we can solve.
