### ISSUE TITLE
Error in fetching feed: https://

### ISSUE THREAD

**Issue by joe-006** [RSSNext/Follow#1636]
### Info:

Feed URL:
```
https://
```

Error:
```
[GET] "https://api.follow.is/feeds?url=https%3A%2F%2F": 422 
```

### Environment

**App Version**: 0.1.0-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.0-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
This is not a valid feed URL.
