### ISSUE TITLE
After clicking refresh, the read articles are not hidden

### ISSUE THREAD

**Issue by songzhihui** [RSSNext/Follow#1642]
### Describe the bug

点击刷新按钮后，已读文章未隐藏

### Feed Info

隐藏已读文章

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This issue should have been fixed, if it still exists please feel free to reopen it
