### ISSUE TITLE
How can I enlarge the video on the video subscription page?

### ISSUE THREAD

**Issue by luckygit518** [RSSNext/Follow#1645]
### Clear and concise description of the problem

![Image](https://github.com/user-attachments/assets/9b9d28ed-5c38-4265-9f53-b4c5dddcb4d8)
只能按照缩略图大小播放，有方法可以放大看吗？

### Suggested solution

可以方法看

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
You should be able to click directly to view it. Can you provide feed information?

**Comment by luckygit518** [comment]
https://rsshub.artday.tech/douyin/user/MS4wLjABAAAAoEenD-rdT1Zo-JnqLjvPdD0lUhh5YsJk1AvAZYKinKY/embed=1&wrap_multimedia_in_iframe=1
点击效果：
https://github.com/user-attachments/assets/34766d7d-79e2-49c8-a0db-415c0461f625

**Comment by hyoban** [comment]
As a temporary solution, you can move it to the picture view
