### ISSUE TITLE
Error in fetching feed: https://kaiyi.cool/blog/

### ISSUE THREAD

**Issue by n95cc** [RSSNext/Follow#1646]
### Info:

Feed URL:
```
https://kaiyi.cool/blog/
```

Error:
```
Feed 解析失败: Attribute without value
Line: 0
Column: 104
Char: s
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `eXobFxrVPeA-NqdSy2-LR`

**Comment by hyoban** [comment]
This is not a valid RSS feed URL
