### ISSUE TITLE
Error in fetching feed: https://hub.rss.direct/instagram/user/sseongryul

### ISSUE THREAD

**Issue by jornihe** [RSSNext/Follow#1651]
### Info:

Feed URL:
```
https://hub.rss.direct/instagram/user/sseongryul
```

Error:
```
Feed 获取错误: [GET] "https://hub.rss.direct/instagram/user/sseongryul": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `_j-z8k2OSSeRLWsJTT0or`

**Comment by hyoban** [comment]
```
ConfigNotFoundError: Instagram RSS is disabled due to the lack of <a href="https://docs.rsshub.app/deploy/config#route-specific-configurations">relevant config</a>
```
