### ISSUE TITLE
Web version audio speedup does not work

### ISSUE THREAD

**Issue by hhr114** [RSSNext/Follow#1652]
### Describe the bug

网页版follow的音频类别下，音频的倍速调节没有作用，没有改变音频的速度快慢。

### Feed Info

https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/eb445b2f-243f-4db6-9062-ae2b0012ff27/17082071-db1a-4132-8640-ae2b0012ff3a/podcast.rss

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
我检查了一下，这个功能在我的电脑上能够正常工作，请问您使用的是什么版本，收听的是什么音频呢？

**Comment by hhr114** [comment]
> 我检查了一下，这个功能在我的电脑上能够正常工作，请问您收听的是什么音频呢？

最近好像正常了，之前要页面刷新重新缓冲才可以变速～
