### ISSUE TITLE
https://theinspirationgrid.com/?feed=rss2

### ISSUE THREAD

**Issue by dooongg** [RSSNext/Follow#1653]
### Info:

Feed URL:
```
https://theinspirationgrid.com/?feed=rss2
```

Error:
```
Feed 解析失败: Invalid character in entity name
Line: 934
Column: 28276
Char:  
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `DtB8fR1Y4Io5-tVu7NmRe`

**Comment by TonyRL** [comment]
This is not a valid RSS feed URL.
