### ISSUE TITLE
Feed Error: Farnam Street, [GET] "https://fs.blog/feed/": 403 Forbidden

### ISSUE THREAD

**Issue by buzzed12** [RSSNext/Follow#1654]
### Error

Error Message: [GET] "https://fs.blog/feed/": 403 Forbidden

### Info

```json
{
  "type": "feed",
  "id": "41359648684677160",
  "title": "Farnam Street",
  "errorAt": "2024-09-22T07:07:09.968Z",
  "errorMessage": "[GET] \"https://fs.blog/feed/\": 403 Forbidden",
  "url": "https://fs.blog/feed/",
  "image": "https://fs.blog/wp-content/uploads/2015/06/cropped-farnamstreet-80x80.png",
  "siteUrl": "https://fs.blog/",
  "ownerUserId": null
}
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `PIb17jejEPCZeEg4Hs_ve`

**Comment by hyoban** [comment]
This link is blocking access from our server, and this is not a problem we can solve.
