### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/%40TerryB

### ISSUE THREAD

**Issue by xuex1x** [RSSNext/Follow#1661]
### Info:

Feed URL:
```
rsshub://youtube/user/%40TerryB
```

Error:
```
Feed fetch error: [GET] "http://10.1.32.41/youtube/user/%40TerryB?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `3NAEoGNohxqwx4e5tskqI`

**Comment by TonyRL** [comment]
It works https://app.follow.is/share/feeds/81625107406969856.
