### ISSUE TITLE
Error in fetching feed: rsshub://youtube/user/%40TheodoreLiu-dl9db

### ISSUE THREAD

**Issue by captainstitch** [RSSNext/Follow#1663]
### Info:

Feed URL:
```
rsshub://youtube/user/%40TheodoreLiu-dl9db
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/youtube/user/%40TheodoreLiu-dl9db?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `cRNjEpBZuuiKsXe4o8MkZ`

**Comment by TonyRL** [comment]
The user https://www.youtube.com/@TheodoreLiu-dl9db does not have any content.
