### ISSUE TITLE
Error in fetching feed: https://shakaianee.top/feed/

### ISSUE THREAD

**Issue by SevenDreamer** [RSSNext/Follow#1675]
### Info:

Feed URL:
```
https://shakaianee.top/feed/
```

Error:
```
Feed 获取错误: [GET] "https://shakaianee.top/feed/": <no response> fetch failed
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `uoeW4GJaStc-BGc0jGRCi`

**Comment by TonyRL** [comment]
The site is not responding at all.
