### ISSUE TITLE
Error in fetching feed: rsshub://twitter/keyword/pixel%20art

### ISSUE THREAD

**Issue by CapStu** [RSSNext/Follow#1677]
### Info:

Feed URL:
```
rsshub://twitter/keyword/pixel%20art
```

Error:
```
Feed 获取错误: [GET] "http://10.1.32.41/twitter/keyword/pixel%20art?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Android
**User Agent**: Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/85.0.4183.92 Mobile/15E148 Safari/604.1
**Env**: web
**Browser**: Safari
**Session Trace Id**: `0pixHJVDyV0xDLSOVBKxj`

**Comment by TonyRL** [comment]
Duplicated of #740
