### ISSUE TITLE
subscription feed occasionally fails to receive new content.

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1679]
### Describe the bug

![Image](https://github.com/user-attachments/assets/1a79c6a8-95d9-4888-bf89-9e1bc710f9d1)

https://github.com/user-attachments/assets/1c706a54-3595-44d6-9abe-c55656a62a1e

这是怎么回事呢？有时候经常连续几天收不到消息，但是取消并重新订阅才能接收到新的消息。
我使用大概有一个月了，时不时会出现这个问题，出现过十几次，所有的订阅源均出现这个

### Feed Info

X

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
https://github.com/user-attachments/assets/2a1dcb9f-d841-45b3-a1e3-b3bc48af71ce


你可以看到，最后收到消息是2天前。手动刷新也无济于事，只能取消订阅，再重新订阅，然后就能收到了

**Comment by DoiiarX** [comment]
看起来没有人处理这个啊。我都换成我自己的订阅源了都不更新

**Comment by silencial** [comment]
I can confirm I get the newest feed now. But I will give it another day or two to make sure the updated feed can also be fetched.

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/2ddd152c-33c8-49c7-bf93-ef8eda52cac0)

today 15hours

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/212b412f-5b6c-47b2-bcf8-0b27e5b4c19b)

**Comment by hyoban** [comment]
Please provide feed info

**Comment by EnterMan123** [comment]
我的列表中总共30个feed已经2天没收到信息了

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/a2511230-71bb-4e09-8fc5-c8d15b5abb3c)

就在刚刚，我逐个feeds重新订阅了一下，只要重新订阅后就恢复正常？不知道到底为什么
