### ISSUE TITLE
Unable to obtain more content normally

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1681]
### Describe the bug

https://github.com/user-attachments/assets/55c04870-310d-476f-9ea3-e051f68747a2

1. 加载已存档条目的按钮消失了
2. 鼠标滑动到底部触底，无法继续加载更多内容，限制为20个条目
3. 只能点击侧边栏的空白区域，再点击订阅源才能获取新内容，每次重复此操作时只能加载额外的20个条目。

我遇到的情况，以及如何重现这个：
第一次打开Follow，随便选择一个源，滑动到列表底部时发现只能查看20个内容，并且加载已存档条目的按钮消失了。每次重复上述操作时，内容只会增加20个。

### Feed Info

任何订阅源

演示用：
https://www.ithome.com/rss/

### Environment

**App Version**: 0.2.2-nightly.20241120
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-nightly.20241120 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `54z7pCgw-_XLL8hS1dtqF`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
We have limited the number of entries for loading archives, which aligns with expectations.

**Comment by EnterMan123** [comment]
It's obviously a bug.

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/df343b10d0745a239e3b15fe11c1d3b2cd9ac3bb
