### ISSUE TITLE
Error in fetching feed: rsshub://weibo/user/1645215240

### ISSUE THREAD

**Issue by hellofreud** [RSSNext/Follow#1685]
### Info:

Feed URL:
```
rsshub://weibo/user/1645215240
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Fweibo%2Fuser%2F1645215240": <no response> Failed to fetch
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `w8HJ_D6TiAmP6yIU0KcXF`

**Comment by hyoban** [comment]
Unable to reproduce

https://app.follow.is/share/feeds/54220026497326080?view=1
