### ISSUE TITLE
Extract full content

### ISSUE THREAD

**Issue by egoist** [RSSNext/follow#169]
Some feeds like my blog don't output full content 

![CleanShot 2024-07-31 at 13 46 04@2x](https://github.com/user-attachments/assets/7dae84af-61dd-446c-aab3-95939420cc83)

Maybe you can use libraries like https://github.com/extractus/article-extractor to extract content from the URL

**Comment by Songkeys** [comment]
The RSS URL of your blog may be <https://egoist.dev/rss.xml>. Currently, we follow the raw rss.xml without additional parsing, resulting in this.

![SCR-20240731-mqbn](https://github.com/user-attachments/assets/ef472807-427c-4c40-967f-cd01e4c7c334)

Thank you for your feedback! We will see if we could use [extractus/article-extractor](https://github.com/extractus/article-extractor) or other solutions to address this issue.

**Comment by egoist** [comment]
yeah, you could include a button here that enables users to extract content if they wish.

![CleanShot 2024-07-31 at 15 47 06@2x](https://github.com/user-attachments/assets/25a1114c-2223-45b3-84ad-e0a5d542fd39)

**Comment by Innei** [comment]
@egoist Is this the feature you were hoping for?

https://github.com/user-attachments/assets/483f85a4-c6c1-42b2-9e2e-204f43213f90

**Comment by egoist** [comment]
@Innei yes exactly what i want

**Comment by Innei** [comment]
@egoist Hi, please upgrade to the latest version and try this with Electron, thanks for the feedback!
