### ISSUE TITLE
Error in fetching feed: https://www.dianyi.ng/rss.xml

### ISSUE THREAD

**Issue by Fox001AI** [RSSNext/Follow#1694]
### Info:

Feed URL:
```
https://www.dianyi.ng/rss.xml
```

Error:
```
Feed 获取错误: [GET] "https://www.dianyi.ng/rss.xml": 403 Forbidden
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `c2aevnjTlsgDLAWVag6ez`

**Comment by hyoban** [comment]
This link is blocking access from our server, and this is not a problem we can solve.

```html
<html><meta charset="utf-8" /><title></title><div></div></html>
<script> window.location.href ="/rss.xml"; </script>
```
