### ISSUE TITLE
Error in fetching feed: https://www.zhoubajie2.com/

### ISSUE THREAD

**Issue by AirGHub** [RSSNext/Follow#1695]
### Info:

Feed URL:
```
https://www.zhoubajie2.com/
```

Error:
```
Feed failed to parse: Feed not recognized as RSS 1 or 2.
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `n4H6p3-YkGjpuULSSbitL`

**Comment by hyoban** [comment]
This is not a valid RSS feed URL
