### ISSUE TITLE
Feed Error: GitHub Trending, 200 OK

### ISSUE THREAD

**Issue by hhr114** [RSSNext/Follow#1699]
### Error

Error Message: 200 OK

### Info

```json
{
  "type": "feed",
  "id": "65997577623644160",
  "title": "GitHub Trending",
  "errorAt": "2024-11-21T14:47:27.447Z",
  "errorMessage": "200 OK",
  "url": "https://37v4aha7ured6.ahost.marscode.site/github_rss",
  "image": null,
  "siteUrl": "https://github.com/trending",
  "ownerUserId": "56125045828951040",
  "owner": {
    "id": "56125045828951040",
    "name": "sure",
    "emailVerified": null,
    "image": "https://avatars.githubusercontent.com/u/152784340?v=4",
    "handle": "sure",
    "createdAt": "2024-09-10T00:24:28.678Z"
  }
}
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `A4gBEsuSW8HlfgyCWQaU7`

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/3559e97d-bdd3-4176-bbfb-fa9490fa668d)
