### ISSUE TITLE
Error in fetching feed: rsshub://telegram/channel/PTTStreamFree

### ISSUE THREAD

**Issue by kawinfisi** [RSSNext/Follow#1706]
### Info:

Feed URL:
```
rsshub://telegram/channel/PTTStreamFree
```

Error:
```
抓取動態時發生錯誤: [GET] "http://10.1.32.41/telegram/channel/PTTStreamFree?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `u8FZbbBsORaMTlxhXQ3xD`

**Comment by hyoban** [comment]
This is not a telegram channel
