### ISSUE TITLE
[Bug] 使用OPML导入时报错

### ISSUE THREAD

**Issue by versun** [RSSNext/Follow#171]
当使用Miniflux导出的opml文件进入导入时，会出现导入失败，总共142个源

我是现在网页版导入报错，然后使用mac客户端导入也报错(142 failed to import)
3分钟后，所有源会成功显示在列表中，即导入成功

**Comment by Songkeys** [comment]
感谢反馈。原因可能是数据源太多导致加载时间过长而请求超时，实际不影响导入。我们会在下个版本里解决这个问题。

Thank you for the feedback. The reason might be that the data source is too large, causing the loading time to be too long and resulting in a timeout. However, this does not affect the import. We will solve this issue in the next version.
