### ISSUE TITLE
[BUG]改变 view 中的 articles 的时候左上角的 icon 状态不会改变

### ISSUE THREAD

**Issue by EasyChris** [RSSNext/follow#172]
![image](https://github.com/user-attachments/assets/ea19f8cf-174d-4d04-bb70-920447aee125)

![image](https://github.com/user-attachments/assets/f5ee917c-5f26-4ef8-8e46-729eab762de8)

我从 articles 变为  social media ，左上角的 icon 状态不会改变

**Comment by Innei** [comment]
没能理解 "左上角的 icon 状态不会改变"，是指数字吗

**Comment by TonyRL** [comment]
FYI, those 6 icons only show the number of **unread** entries.
