### ISSUE TITLE
can support pin like float on top

### ISSUE THREAD

**Issue by ixqbar** [RSSNext/Follow#1740]
### Clear and concise description of the problem

can support pin like float on top

### Suggested solution

can support pin like float on top

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by lawvs** [comment]
Most common apps don't have the "pin on top" feature. When might you need this functionality?

**Comment by ixqbar** [comment]
Thanks for reply!
I often subscribe to developer content and sometimes read and learn while testing and verifying code results. Given the limited window space, I don't want to keep switching windows and would like to keep the code window on top.

**Comment by ixqbar** [comment]
like coteditor  

![Image](https://github.com/user-attachments/assets/1f6a4aaa-86a8-4b88-a98f-58bc7ca4b569)

**Comment by ixqbar** [comment]
iterm2 hotKey 
![Image](https://github.com/user-attachments/assets/516b45c8-c91d-4e3e-b977-661a86f67cf4)
