### ISSUE TITLE
Some feeds require login to view information. How to solve it?

### ISSUE THREAD

**Issue by masgg** [RSSNext/Follow#1747]
### Clear and concise description of the problem

有些订阅源需要登录才可以查看信息怎么解决，需要登录权限的网站，比如论坛板块不同等级账号看到的内容也不一样。

### Suggested solution

是否能在订阅时登录或者提交 cookies 呢

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
Please provide specific examples and reopen the issue
