### ISSUE TITLE
Search popup becomes transparent on Firefox

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#175]
## Environment

Windows 10 21H2, Firefox 128.0.3, web.follow.is (1af94b7)

## Steps to reproduce

1. Maximise Firefox Window
2. Open a feed entry
3. Click on search
4. Click on `?` in the bottom right corner

<details><summary>Screen recording</summary>

![firefox_2024-08-01](https://github.com/user-attachments/assets/b3ba2e58-eac7-439b-b25e-dc2b5b6eb00f)
</details>

**Comment by DIYgod** [comment]
This feature has been removed, so I will close this issue.
