### ISSUE TITLE
When clicking an image, sometimes it will jump and open in browser.

### ISSUE THREAD

**Issue by PrinOrange** [RSSNext/Follow#1757]
### Describe the bug

我注意到，有时候在RSS阅读器里，使用Readability排版的文章中，点击文章里的图片时，本意是想点击查看图片，但总是会跳到浏览器中。

比如蓝点网的订阅源 https://www.landiannews.com/feed ，随便点进去一篇带图的文章，点击一张图片。

https://github.com/user-attachments/assets/4e8944b2-1562-49f2-8baf-a1dcef9f93c0

后来，我找到了这个bug的原因：在原文的 html 中，如果图片被 `<a>` 标签包裹，那么它就会出现如上bug。如果图片没有被 `<a>` 标签包裹，就不会出现这个bug。

![Image](https://github.com/user-attachments/assets/0043c8bb-ea78-40b3-8d9f-82a5fc63514c)

一种可能的修复方法：
Readability 中读取到的正文 html 可以再进一步处理，如果检测到`img`标签被`<a>`标签嵌套，就去掉外面的`<a>`标签，避免跳到浏览器中打开的bug，这个可以使用 JSDOM 或者 Rehype Plugin 实现

### Feed Info

https://www.landiannews.com/feed

### Reproduction Video

如上所示

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `fQ66Q0pkbwZcAICC5O3KD`

**Comment by PrinOrange** [comment]
I have tried to fix this bug in pr #1760 .

**Comment by AstroNomen** [comment]
我自己的博客使用了和蓝点同样的fancybox灯箱也会遇到这个问题，我尝试用wordpress的`is_feed`判断是否RSS阅读器来避免给`img`标签添加`<a>`包裹，但是似乎也没有见效

**Comment by PrinOrange** [comment]
> 我自己的博客使用了和蓝点同样的fancybox灯箱也会遇到这个问题，我尝试用wordpress的`is_feed`判断是否RSS阅读器来避免给`img`标签添加`<a>`包裹，但是似乎也没有见效

可能是 Follow 对旧 RSS 文件缓存了，没有读取到新的 RSS 文件。
