### ISSUE TITLE
Error in fetching feed: http://127.0.0.1:4000/feeds/all.atom

### ISSUE THREAD

**Issue by 0032nan** [RSSNext/Follow#1758]
### Info:

Feed URL:
```
http://127.0.0.1:4000/feeds/all.atom
```

Error:
```
Feed 获取错误: [GET] "http://127.0.0.1:4000/feeds/all.atom": <no response> fetch failed
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `Ev9VuAh0MOC5-230w7es4`

**Comment by hyoban** [comment]
This is a local address and cannot be obtained and resolved on the Follow server.
