### ISSUE TITLE
UX Optimization: When pasting the entire URL, it supposed to auto remove the extra protocol head from clipboard.

### ISSUE THREAD

**Issue by PrinOrange** [RSSNext/Follow#1761]
### Describe the bug

在添加 RSS 的 URL 输入框，因为输入框里本身就有 `https://` 前缀。但是，如果用户复制的 URL 中如果也有 `https://` 前缀，直接粘贴时会出现冗余，还需要手动删除多余的前缀。

如下视频所示。

https://github.com/user-attachments/assets/dd4a74cb-3aaa-4523-9b03-da2a1ae027a0

可能的解决方案：监听 Input 的粘贴事件，如果粘贴时检测到剪切板里的 URL 也有 `https://`、`rsshub://` 前缀，就自动调整粘贴内容，避免多余的前缀。

### Feed Info

NULL

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by PrinOrange** [comment]
I have fixed this issue in pr #1762

**Comment by kowyo** [comment]
I noticed this as well. But later I found that actually we can paste RSS url (containing https://) directly in the `搜索` part to follow. So this issue might be unnecessary.
