### ISSUE TITLE
Error in fetching feed: rsshub://follow/profile/702909260

### ISSUE THREAD

**Issue by klein6868** [RSSNext/Follow#1764]
### Info:

Feed URL:
```
rsshub://follow/profile/702909260
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Ffollow%2Fprofile%2F702909260": <no response> Failed to fetch
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `GE2dYtqRhM6aCyXHGD-qB`

**Comment by TonyRL** [comment]
The user https://app.follow.is/share/users/702909260 does not exist.
