### ISSUE TITLE
Windows电脑下设定Follow开机自启动希望能实现静默启动，而不是每次开机启动后打开窗口。

### ISSUE THREAD

**Issue by yayoinoyume** [RSSNext/Follow#177]
我使用的系统是Windows，我非常喜欢Follow，并将它添加为了开机自启动。
但是我发现每次开机启动后，Follow都会直接打开程序界面，但我并不是每次打开电脑就要查收Follow上的信息，我希望能够添加一个静默自启动的选项，谢谢！

**Comment by lawvs** [comment]
下个版本更新之后只需要在设置中同时勾选开机自启和最小化到托盘两个选项就会默认静默启动，另外感谢你对 follow 的喜爱！

![Image](https://github.com/user-attachments/assets/621a359a-6e74-42fb-9cc0-bbe431d72bb2)
