### ISSUE TITLE
Some issues with the mobile page

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#1784]
### Describe the bug

1. 部分 dialog 內容沒有居中 （認領界面，編輯feed界面 等等）
![Image](https://github.com/user-attachments/assets/96b7d9a8-4ccb-4a88-a01b-383ae2d3c027)

2. 操作過快，會導致網頁沒有反應，具體點擊什麼地方都沒有回應

3. 音頻問題 （ 測試環境： iphone PWA 添加到桌面打開）

    1. 打開音頻，一直佔據着底部，沒有關閉按鈕，且在 iphone 底部條里
    ![Image](https://github.com/user-attachments/assets/86f19684-8149-4ca3-8249-06338747d238)
    
    2. 播放界面背景消失
    ![Image](https://github.com/user-attachments/assets/572a65fe-eb32-48ac-a625-62d951886a47)
    
    3. 上劃下滑會出現底部攔在 iphone 底部條裏
    ![Image](https://github.com/user-attachments/assets/460b3a20-90b8-47b2-bb0b-7d01f62d66b3)

### Feed Info

。

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
All have been fixed in the latest commit
