### ISSUE TITLE
Error in fetching feed: https://rsshub://telegram/channel/nicoinvestmentchannel

### ISSUE THREAD

**Issue by donttal** [RSSNext/Follow#1787]
### Info:

Feed URL:
```
https://rsshub://telegram/channel/nicoinvestmentchannel
```

Error:
```
Feed 获取错误: [GET] "https://rsshub://telegram/channel/nicoinvestmentchannel": <no response> fetch failed
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `ZS2juOa7w55YEqU-sADkP`

**Comment by hyoban** [comment]
Use `rsshub://telegram/channel/nicoinvestmentchannel`
