### ISSUE TITLE
When the font size is M and L, the last line of text in the text preview is incomplete.

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1798]
### Describe the bug

![Image](https://github.com/user-attachments/assets/6a26d6a0-89be-409d-9186-d98745a764d5)
![Image](https://github.com/user-attachments/assets/5c7cb4fb-61b4-4302-8043-8fcbf41a6562)

字体大小是M和L号的时候，正文预览末行文字只显示一半，这看起来很奇怪

### Feed Info

X

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
This is a problem with Chrome, when using multiline text truncation, if the container height is greater than the number of lines of retained text, this problem will occur.

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/9acb8298-c3c3-48ea-9eda-d208a6632479)

![Image](https://github.com/user-attachments/assets/bf39325f-29cb-48ef-8a73-2a6def8547e3)

在宽屏模式下，看起来非常诡异
