### ISSUE TITLE
Error in fetching feed: https://https://docs.rsshub.app/zh/routes/multimedia

### ISSUE THREAD

**Issue by erdong03** [RSSNext/Follow#1799]
### Info:

Feed URL:
```
https://https://docs.rsshub.app/zh/routes/multimedia
```

Error:
```
[GET] "https://api.follow.is/feeds?url=https%3A%2F%2Fhttps%3A%2F%2Fdocs.rsshub.app%2Fzh%2Froutes%2Fmultimedia": <no response> Failed to fetch
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `k_WDHtoAO43hsnJTDwmNa`

**Comment by hyoban** [comment]
This is not a valid RSS feed URL.
