### ISSUE TITLE
Error in fetching feed: https://www.ruiwen.com

### ISSUE THREAD

**Issue by Ccgsboy** [RSSNext/Follow#1800]
### Info:

Feed URL:
```
https://www.ruiwen.com
```

Error:
```
Feed 解析失败: Unencoded <
Line: 19
Column: 114
Char: \
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `wUZ5qcesF08vQb3jXW-HT`

**Comment by hyoban** [comment]
This is not an RSS feed URL
