### ISSUE TITLE
Video playback issues

### ISSUE THREAD

**Issue by mengjii** [RSSNext/Follow#1801]
### Describe the bug

当我在右键点击哔哩哔哩视频选择“view source content”选项后，在打开的页面中除了订阅的视频可以观看，在这个页面点击其他视频没有任何回应，也就是其他的在B站上的视频观看不了。。。

### Feed Info

无

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
https://github.com/user-attachments/assets/b4c69772-c1e3-4b8a-ae44-06ffc03659b6

Unable to reproduce
