### ISSUE TITLE
web version Follow left up '+' button behavior problem

### ISSUE THREAD

**Issue by qiaoqiangv** [RSSNext/Follow#1804]
### Describe the bug

System : Ubuntu 24.04 LTS - X64
Web browser : microsoft-edge-stable version 131.0.2903.63

Problem describe : 

- first press '+' button it's running good, when second press '+' button, it should has action but it's not.
- I think may be when second press '+' button, page have scroll up or may be can update a new empty search dialog box

### Feed Info

none.

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
hi, what is the expected behavior you want?

**Comment by Leapzhang** [comment]
![Image](https://github.com/user-attachments/assets/a4985b64-6080-4d1a-8b2a-38121e12c766)
点击这些订阅名称都会 跳转到add more feed

**Comment by lawvs** [comment]
This issue will be fixed in the next release
