### ISSUE TITLE
特定用户 RSS 订阅页面滚动至底部时持续抖动

### ISSUE THREAD

**Issue by yikZero** [RSSNext/follow#181]
在 Follow 软件(版本 0.0.1-alpha.1)中，查看某些特定用户的 RSS 订阅页面时，当滚动到页面底部会出现持续的抖动现象。这个问题并不影响所有用户，似乎只在特定用户的页面上发生。

## 复现步骤:

1. 打开 Follow 软件
2. 点击某个用户的头像以查看其 RSS 订阅
3. 向下滚动页面直至底部
4. 观察页面是否出现持续抖动

## 环境信息:

操作系统: macOS 14.5 (23F79)
Follow 软件版本: 0.0.1-alpha.1 (0.0.1-alpha.1)

## 补充说明:

此问题仅在查看某些特定用户的 RSS 订阅时出现，不是普遍现象
我将附上一段视频来复现这个问题

https://github.com/user-attachments/assets/7b7009b1-fdba-438d-b0e7-968a71aaa401

**Comment by Innei** [comment]
Thanks for the feedback, this issue has been fixed in the latest code pending the next release.
