### ISSUE TITLE
Custom Styles Reset After Updates

### ISSUE THREAD

**Issue by Ellioben** [RSSNext/Follow#1824]
### Describe the bug

I've encountered an issue where my custom styles are being reset to their defaults after each update. This is causing some  inconveniently for me, as I have to reapply my customizations every time there's an update.

### Feed Info

No url

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
hi, CSS styles will not be synchronized to the server but will be saved in LocalStorage, so each time you reinstall the app, they will be lost.

If you have lost LocalStorage data due to upgrading the app, this is abnormal behavior. Please describe your update method.

**Comment by Ellioben** [comment]
> hi, CSS styles will not be synchronized to the server but will be saved in LocalStorage, so each time you reinstall the app, they will be lost.
> 
> If you have lost LocalStorage data due to upgrading the app, this is abnormal behavior. Please describe your update method.

Version：MacOS 15.0.1
Upgrade Method: In-app upgrade notification at the bottom left corner of the app, and click

**Comment by Innei** [comment]
@Ellioben After you upgrade the app, is your login status retained? Or are you logged out?

**Comment by Ellioben** [comment]
> After you upgrade the app, is your login status retained? Or are you logged out?


After the app upgrade,my login status was retained.I was not logged out and did not have to log in again.

I just modified the CSS through developer mode. After upgrade ,that's reset. Do I also need to save it in some other way?

**Comment by Innei** [comment]
I'm not clear which developer mode you are referring to.

**Comment by Ellioben** [comment]
> I'm not clear which developer mode you are referring to.

View --> Toggle Developer Tools

**Comment by Innei** [comment]
In the latest version, CSS styles will also be synchronized to the server.

**Comment by Ellioben** [comment]
> In the latest version, CSS styles will also be synchronized to the server.

ok, thanks very much, BTY : Could I get an extra invitation code, please?🥺
