### ISSUE TITLE
Issue with the Unsynchronized Status of Unread Item Count

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1830]
### Describe the bug

![Image](https://github.com/user-attachments/assets/f884ec4d-6f3c-4686-9688-2297ed01c3cb)
![Image](https://github.com/user-attachments/assets/bfa0ca3c-b3b3-4d46-ab95-8236933c7da5)

1. 两处地方的未读条目数量不一致，一般来说，这是同步更新的。虽然这在手动刷新列表后解决了。

https://github.com/user-attachments/assets/a481731b-c3ce-4dcd-b04d-bf598c46ff0e

2. 跟1一样，全部已读后，条目仍保留在列表。同样是通过手动刷新解决。这种使用逻辑很奇怪

### Feed Info

X

### Environment

**App Version**: 0.2.4-nightly.20241123
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.4-nightly.20241123 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `nLqJiFfMl6ttSidVc8Qfc`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
Possibly related to #1355

**Comment by Innei** [comment]
1 fixed in 196b717a7fbdd362d9c2128223272c6616363bc5
