### ISSUE TITLE
When adding a subscription, set category optimization

### ISSUE THREAD

**Issue by imboni** [RSSNext/Follow#1833]
### Clear and concise description of the problem

添加订阅时，分类一栏目前是个单纯的文本输入框，每次设置分类时都需要手动输入，体验方面可以再优化一下

### Suggested solution

添加订阅时，建议自定义分类时，下面列出之前写过的分类tag，或者加一个热门分类tag。或者有其他更好的方案～

![Image](https://github.com/user-attachments/assets/60564957-8c81-43aa-b860-20f3f3ea7ecf)

（之前一直用免费的 Inoreader，体验一般。follow真是戳中了我，很棒！）

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
We already show the categories

![Image](https://github.com/user-attachments/assets/ae45152f-308d-4fd5-a39d-23eeaa5386c3)
