### ISSUE TITLE
range for closing the menu window by clicking on a blank area is limited

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1841]
### Describe the bug

https://github.com/user-attachments/assets/38c17836-20d4-4429-b343-afea6361ebb3

点击空白区域关闭菜单窗口的范围有限。

### Feed Info

X

### Environment

**App Version**: 0.2.4-nightly.20241125
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.4-nightly.20241125 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `V8A4SvESEf-ICmY1yyQ24`
**Renderer**: 0.2.4-nightly.20241125

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/0908acf9-5b16-47dc-87ef-af6333aa1fbc)

**Comment by Innei** [comment]
This area is the drag region for Electron (used for window dragging), and events are not listened here. This is a normal phenomenon, and the web does not have this issue.
