### ISSUE TITLE
Error: undefined is not an object (evaluating 'userInfo.image')

### ISSUE THREAD

**Issue by kowyo** [RSSNext/Follow#1852]
### Error

undefined is not an object (evaluating 'userInfo.image')

### Stack

```
SubscriptionItems@https://app.follow.is/assets/user-profile-modal-B-c4PSMe.js:63:95
Nh@https://app.follow.is/vendor/0-EeJr3raE.js:3399:8
Vk@https://app.follow.is/vendor/0-EeJr3raE.js:6342:13
Uk@https://app.follow.is/vendor/0-EeJr3raE.js:6036:13
Tk@https://app.follow.is/vendor/0-EeJr3raE.js:6030:28
Ik@https://app.follow.is/vendor/0-EeJr3raE.js:6015:9
Nk@https://app.follow.is/vendor/0-EeJr3raE.js:5746:9
Ek@https://app.follow.is/vendor/0-EeJr3raE.js:5800:30
jg@https://app.follow.is/vendor/0-EeJr3raE.js:2708:16
@https://app.follow.is/vendor/0-EeJr3raE.js:5628:28
```

### Environment

**App Version**: 0.2.4-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15
**Env**: web
**Browser**: Safari
**Session Trace Id**: `dEjoxAak-RHUv2ykR11mH`

### Sentry Trace ID
mkTd52CLKgRocWz5-yIJ8

**Comment by hyoban** [comment]
Fixed in #1759
