### ISSUE TITLE
The mobile web page list interface overlaps with the add subscription button

### ISSUE THREAD

**Issue by wdj2613** [RSSNext/Follow#1854]
### Describe the bug

如题，手机web页面点击订阅列表时，会跳转到添加订阅的页面

### Feed Info

null

### Reproduction Video
https://github.com/user-attachments/assets/ad41ffc3-2ec6-46ac-9e4d-9f1cc18ef3bd

### Environment

手机浏览器 

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Does this problem still exist?

**Comment by hyoban** [comment]
I deleted the revision for you, it should be fine now.

![Image](https://github.com/user-attachments/assets/83e56bd4-f4cf-4bf0-b3e8-854b831e1bbf)
