### ISSUE TITLE
Error in fetching feed: https://www.example.com/bilibili/user/video/482619845

### ISSUE THREAD

**Issue by Doozool** [RSSNext/Follow#1856]
### Info:

Feed URL:
```
https://www.example.com/bilibili/user/video/482619845
```

Error:
```
Feed 获取错误: [GET] "https://www.example.com/bilibili/user/video/482619845": 404 Not Found
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `OlFXvMr07l_8Frda4aJww`

**Comment by hyoban** [comment]
This is not a valid RSS feed URL
