### ISSUE TITLE
Added the option to choose the default browsing method

### ISSUE THREAD

**Issue by xhy279** [RSSNext/Follow#1857]
### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

很多内容比如公众号订阅 无法转为正确格式，作为用户更希望默认以浏览器原文方式打开。阅读模式才应该是可选项。 完全弄反了 。

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/dc33352b-f921-4257-84dd-0c882bc32e11)

Use an action for it
