### ISSUE TITLE
Immersive translation introduces English subscription content

### ISSUE THREAD

**Issue by qbmiller** [RSSNext/Follow#1859]
沉浸式翻译 引入 英文订阅内容
双语 显示

### Environment

**App Version**: 0.2.3-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `RC5Aqspwx2HCK2plvyQ2z`

**Comment by hyoban** [comment]
We already support translating content, you can set an action to do this

![Image](https://github.com/user-attachments/assets/f0f05728-5806-40bd-b3cf-8a4a5b9e52db)

**Comment by qbmiller** [comment]
can't see this option
