### ISSUE TITLE
Unable start on windows 11

### ISSUE THREAD

**Issue by zhangzhishan** [RSSNext/Follow#186]
Error is below

![image](https://github.com/user-attachments/assets/9375958b-2fb7-4330-a3fd-2d4330de1fa5)

**Comment by zhangzhishan** [comment]
still the same issue even on the newest version.
![image](https://github.com/user-attachments/assets/a6578cd8-d405-427a-bd60-7c97405fcbff)

**Comment by Innei** [comment]
From the error message, I can't find any useful information. The sentry may not initialize before the app initializes. Try to uninstall the app, and reinstall it can solve this issue?

**Comment by zhangzhishan** [comment]
I have uninstall and reinstall several times. I have several windows machines, only in one has this issue. Is there any place to find some useful debug information? After this error window, I still could see several Follow process in the Task Manager.

**Comment by Innei** [comment]
You should uninstall it completely, delete all user data, and try again.

Note: Un-release version is development app name, Follow (dev), These two are actually different apps

**Comment by zhangzhishan** [comment]
Use Everything to find all Follow related folders, delete them helps, thanks!
