### ISSUE TITLE
Error in fetching feed: https://www.youtube.com/@chaijing2023

### ISSUE THREAD

**Issue by xxf19900504** [RSSNext/Follow#1869]
### Info:

Feed URL:
```
https://www.youtube.com/@chaijing2023
```

Error:
```
Feed 解析失败: Feed not recognized as RSS 1 or 2.
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `SkfuUMjp73xISKP_g-GgB`

**Comment by hyoban** [comment]
This is not a valid RSS feed URL
