### ISSUE TITLE
Error in fetching feed: rsshub://twitter/user/http%3A%2F%2Flocalhost%3A1200%2Ftwitter%2Fuser%2Fvideocopilot

### ISSUE THREAD

**Issue by 3DJoh** [RSSNext/Follow#1879]
### Info:

Feed URL:
```
rsshub://twitter/user/http%3A%2F%2Flocalhost%3A1200%2Ftwitter%2Fuser%2Fvideocopilot
```

Error:
```
Feed fetch error: [GET] "http://10.1.32.41/twitter/user/http%3A%2F%2Flocalhost%3A1200%2Ftwitter%2Fuser%2Fvideocopilot?format=json": 503 Service Unavailable
```

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `9PQgWQFNtQ6jbOhtfIxKE`

**Comment by hyoban** [comment]
This is not a valid route
