### ISSUE TITLE
After rebuilding the database, you need to log in again

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1886]
### Describe the bug

![Image](https://github.com/user-attachments/assets/376ecdf4-55ae-4047-986a-2daa3f84d025)

重建数据库后，需要重新登录

![Image](https://github.com/user-attachments/assets/edf95ec6-b7aa-4d51-af5c-0de3f8c22375)

0.2.4-nightly.20241127 某次重建数据库，偶然出现了这个，然后进不去

### Feed Info

X

### Environment

**App Version**: 0.2.4-nightly.20241126
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.4-nightly.20241126 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `O7oqVB8e64qRjAHQf_NYn`
**Renderer**: 0.2.4-nightly.20241126

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/edf95ec6-b7aa-4d51-af5c-0de3f8c22375)

0.2.4-nightly.20241127

**Comment by Innei** [comment]
I cannot reproduce.

**App Version**: 0.2.4-nightly.1732542268
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.4-nightly.20241126 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `pGNuRkFd8Qn-Cdr-I35er`
**Renderer**: 0.2.4-nightly.1732541069-1-gd691f881

**Comment by EnterMan123** [comment]
Reinstalling the software solved this

**Comment by EnterMan123** [comment]
Uninstalling and reinstalling the software resolved the issue, and I am unable to reproduce it.
