### ISSUE TITLE
Picture view mode, click on the collection to automatically expand the name

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1894]
### Describe the bug

https://github.com/user-attachments/assets/db10bd8f-f004-41c3-91c0-74d8c63c18b3

图片视图模式，点击收藏会自动展开名称

### Feed Info

X

### Environment

0.2.4-nightly.20241127

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is as expected. The number of action buttons on the right side is different before and after collection.
