### ISSUE TITLE
Some self-generated content was not crawled by Follow

### ISSUE THREAD

**Issue by Jacky-whq** [RSSNext/Follow#1896]
### Describe the bug

![Image](https://github.com/user-attachments/assets/39102de4-91af-4d81-8cad-da13d8813eda)
![Image](https://github.com/user-attachments/assets/3cef519a-6d99-4971-98f8-33b5bd7cf155)
https://rss.jackywhq.cn/twitter/user/elonmusk这个链接在13个小时前就停止抓取了

![Image](https://github.com/user-attachments/assets/2c6ea3c7-6b5e-4d1d-ac5e-45294a7b1dde)
https://rss.jackywhq.cn/twitter/user/bbcchinese这个链接一切正常

### Feed Info

X

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Looks like it was last updated 3 hours ago

![Image](https://github.com/user-attachments/assets/c4b8fe4f-31ee-4717-aeb2-1d2bb16f07e4)
