### ISSUE TITLE
Follow whether it is possible to automatically mark everything as read when clicking on the navigation bar tab

### ISSUE THREAD

**Issue by wuTong0369** [RSSNext/Follow#1897]
### Clear and concise description of the problem

无

### Suggested solution

对于未读的某个订阅,经常打开ui的时候就看到一堆未读提醒,所以我经常做的操作是右键全部标记为已读.
对于用户来说点开栏目其实代表已经关注和获取到信息了,并不是每条消息都是重要的.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/bc8d9d59-68d1-4601-891f-876301cf39d4)

Use a silence action for it
