### ISSUE TITLE
程序为什么会修改URL协议关联，具体是用来做什么

### ISSUE THREAD

**Issue by tvsearch** [RSSNext/follow#190]
![image](https://github.com/user-attachments/assets/90286dea-8bc0-41cc-b811-c65c020a9fc5)

**Comment by QYG2297248353** [comment]
rsshub 订阅协议，放心好了，不是常规的 http 之类的，就像是迅雷 自有的迅雷协议，很常见

**Comment by Innei** [comment]
我们会定义一个 `follow://` 的协议用于 OAuth 的登录验证，以及使用 `follow://` 的 deeplink 进行快速调用 app 的某些功能
