### ISSUE TITLE
[需求] 保存单独的文章到follow，以备稍后阅读

### ISSUE THREAD

**Issue by zixude** [RSSNext/Follow#191]
一、场景：
1，在“网络上”会遇到优质文章推荐，目前follow无法保存文章，以备稍后统一阅读。
2，在”follow中“遇到文章链接，无法保存以备稍后阅读。

二、需求：
1，follow能直接提供保存文章链接的输入框；
2，单独保存的文章统一归到某类目下，如inbox；（分析说明：现有follow的Starred的含义逻辑，和indox应该区分更好，星标属于算是最终归档，inbox算是待读盒子，从信息流关系看，rss →inbox→Starred）

3，如果是follow内部的链接，可以直接右键链接“添加到inbox”；

4，（P2）从用户体验更佳的角度，可以提供诸如向Mac的右键中增加“保存到follow”这样的快捷方式，使用户在无论任何场景下，都可以快速把链接添加到follow中。（说明：本条待商议，方案可能性很多，需设计定论。）

三、再进一步说明：
如果从简化、简洁设计的角度看，inbox和starred的逻辑，应该可以合并，假设合并后叫“Archive”归档，归档的内容以“已读”或“未读”作为区分，未读等于是“inbox”，已读且未删除的等于是Starred。

上述仅为建议和思考，供参考。

示意图：
![image](https://github.com/user-attachments/assets/31e0617f-5e64-4805-9ca6-e134a71b5cea)

**Comment by DIYgod** [comment]
这个功能很有用，但我觉得这不是一个订阅工具应该做的事情，更合理的做法是你配合一个稍后再看应用来使用，Follow 目前支持把文章或者图片一键保存到这些应用中：

<img width="837" alt="image" src="https://github.com/user-attachments/assets/6d01ca07-4d04-4756-8a62-1240a9d4345e">

**Comment by zixude** [comment]
麻煩開發者關閉一下本issue，本人沒有關閉權限。
