### ISSUE TITLE
I found out today that the amount of subscription information displayed has become less, and I can’t see the website from a few days ago. Updated information. Only the most recent information is displayed. Do I need to set it up to display more subscription information?

### ISSUE THREAD

**Issue by b-jh** [RSSNext/Follow#1918]
### Describe the bug

今天发现，订阅信息显示的量变少了，看不到几天前的网站更新的信息了。只显示最近的几条信息，是不是需要哪里设置才能显示更多订阅信息？点击“加载已归档条目” 也没有更多的信息。

### Feed Info

rsshub://1lou/forum-11

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by G1t-hub** [comment]
+1，所有订阅都只能访问最近20条记录
