### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by startdup** [RSSNext/Follow#1925]
Sorry but just trying to find out how to get invite to really test it out. Thanks for your time and help!

### Environment

**App Version**: 0.2.3-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.3-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `4Yj927May4Ffd5x7eGONu`

**Comment by hyoban** [comment]
issue is not a place to apply for invitation codes
