### ISSUE TITLE
[Feature Request] Allow set proxy to visist image

### ISSUE THREAD

**Issue by aliuq** [RSSNext/Follow#196]
Some pictures cannot be accessed even using VPN. I hope you can set up a proxy to access them.

e.g. 

https://apod.nasa.gov/apod/image/2408/GloryFog_label.png

Proxy

https://dl.llll.host/https://apod.nasa.gov/apod/image/2408/GloryFog_label.png

**Comment by DIYgod** [comment]
We now have the settings for the proxy, I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
