### ISSUE TITLE
Two BUGs

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1980]
### Describe the bug

https://github.com/user-attachments/assets/85efe476-fc6b-4fe5-bf46-e33a544a44cf

1. 窗口卡死，只能关闭重启程序

https://github.com/user-attachments/assets/8f2a5f53-fa87-4004-8e00-5639d102462e

2. 打开小窗口后可以在任何位置点击鼠标右键出现全选选项

### Feed Info

X

### Environment

**App Version**: 0.2.5-nightly.20241201
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.5-nightly.20241201 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `x0ZnngnF_0pqRi5pwdoXS`
**Renderer**: 0.2.5-nightly.20241201

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
https://github.com/user-attachments/assets/561e357c-7c4e-43f8-a5e6-ba5a0c2f10d2

3.

**Comment by Innei** [comment]
Try fix in 36d235eeb8d08c841d475db2a354ad05d3f268d7
