### ISSUE TITLE
Already logged in but the login box still pops up in `pnpm run dev:web`

### ISSUE THREAD

**Issue by CanglongCl** [RSSNext/Follow#1990]
### Describe the bug

![Image](https://github.com/user-attachments/assets/57798171-db26-41c1-baec-b75adb08f24c)

When I run `pnpm run dev:web`, the app is already logged in (see feeds in background) but it still popped up login box. There is no way to close it. 

I have try clearing cache in browser, logging out in `app.follow.is`, logging out in Follow app. None of them works. 

### Feed Info

/

### Environment

Production debug with url `https://app.follow.is/__debug_proxy`

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
We have updated the oauth login library, so in the dev branch, if you use the online production environment API, you will not be able to log in.

**Comment by CanglongCl** [comment]
> We have updated the oauth login library, so in the dev branch, if you use the online production environment API, you will not be able to log in.

Any workaround?

**Comment by Innei** [comment]
No, wait for the release this week.
