### ISSUE TITLE
Twitter Feed is not updated

### ISSUE THREAD

**Issue by anneincoding** [RSSNext/Follow#1992]
### Describe the bug

[https://app.follow.is/share/feeds/41655120039539712?view=1](https://app.follow.is/share/feeds/41655120039539712?view=1)

### Validations

- [X] This issue is valid

**Comment by pseudoyu** [comment]
Working on a third-party api to get twitter feeds, may launch this week to resolve it/increase the stability.

**Comment by Boogaloo-XT** [comment]
> Working on a third-party api to get twitter feeds, may launch this week to resolve it/increase the stability.

The Twitter feed updates seem to be working fine now, which is great! Could you share which third-party API you're using?

**Comment by pseudoyu** [comment]
> > Working on a third-party api to get twitter feeds, may launch this week to resolve it/increase the stability.
> 
> The Twitter feed updates seem to be working fine now, which is great! Could you share which third-party API you're using? [@pseudoyu](https://github.com/pseudoyu)

we are currently using a private api with a team, and they haven't published it yet. I will provide updates here once they do.

**Comment by Boogaloo-XT** [comment]
> > > Working on a third-party api to get twitter feeds, may launch this week to resolve it/increase the stability.
> > 
> > 
> > The Twitter feed updates seem to be working fine now, which is great! Could you share which third-party API you're using? [@pseudoyu](https://github.com/pseudoyu)
> 
> we are currently using a private api with a team, and they haven't published it yet. I will provide updates here once they do.

Thank you so much
