### ISSUE TITLE
0.2.5-nightly.20241203

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#1998]
### Describe the bug

![Image](https://github.com/user-attachments/assets/37d16684-3634-4bcb-bb89-692b257b8807)

登录出现这个，进不去

### Feed Info

X

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by E-one-LLC** [comment]
me too

**Comment by EnterMan123** [comment]
#1886 是否有关

**Comment by EnterMan123** [comment]
另外，关于夜间版本自动更新的问题

发现此错误后我重新安装了v1202版本，但是程序会自动帮我升级到v1203版本，然后就像问题描述的一样我再次被卡住进不去。如果某个版本有重大问题的话，强制自动升级会起副作用。

**Comment by EnterMan123** [comment]
This issue has occurred in the nightly builds for three consecutive days.

**Comment by Innei** [comment]
The destructive update of the server API may cause older versions to become unavailable. This issue will be addressed by implementing version restrictions after the subsequent refactoring of the server code. During this period, we will strive to avoid similar issues as much as possible.
