### ISSUE TITLE
When adding a new follow subscription, a very narrow box appears first during page rendering.

### ISSUE THREAD

**Issue by Crazypointer** [RSSNext/Follow#2020]
### Describe the bug

When adding a new follow subscription, a very narrow box is initially rendered, as shown in the following figure, and the actual popup is loaded last.
![Image](https://github.com/user-attachments/assets/98c69215-3fb8-45f4-a880-5d01fff6c462)

### Feed Info

Any list link will exist, for example:

https://app.follow.is/share/lists/76984384004320256

### Environment

Beta 版本（440A514）

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [x] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Already fixed in dev, please wait for the next version release
