### ISSUE TITLE
[Bug] 无法Claim feed

### ISSUE THREAD

**Issue by versun** [RSSNext/Follow#204]
博客使用的wordpress，无法使用description进行认证，提示“ownership challenge failed”
目前description已改为原来的内容
![image](https://github.com/user-attachments/assets/83fc18fa-2462-4028-9244-2925b5ae0412)

**Comment by versun** [comment]
测试了2个WP的站点，均无法认证

**Comment by Innei** [comment]
你能提供你的 feed url 吗？

**Comment by versun** [comment]
https://versun.me/feed
https://54321.versun.me/feed

**Comment by Innei** [comment]
你提供的 feed 中并没有找到 claim 的信息

**Comment by versun** [comment]
@Innei 
已修改，请查看：https://versun.me/feed
谢谢

**Comment by versun** [comment]
Hi @Innei 
还需要我这边提供什么数据不

**Comment by Innei** [comment]
Fixed in the next version

**Comment by siygle** [comment]
抱歉找到這個相關的問題回報，想說現在這邊詢問一下。

想試著測試 Claim 的功能，然後測試了 RSS Tag 的方法，因為手邊剛好用了 [Feed](https://github.com/jpmonette/feed)，它有比較嚴格的產生規則，所以改走能自訂 attribute 的 JSON feed 方式，但加入了 `follow_challenge` 還是出現錯誤，不確定是誤解了 Claim 的格式，還是有其他的問題。

這是用來測試用的 feed -> https://chat.sylee.dev/feed
