### ISSUE TITLE
Can you add a "one-click to top" button on the article content page to quickly return to the title position at the top of the article to increase reading efficiency?

### ISSUE THREAD

**Issue by fkccpbaby** [RSSNext/Follow#2040]
### Environment

**App Version**: 0.2.6-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `LTluNrHcK4gyDXZIF-t-Z`

**Comment by Innei** [comment]
Add read indicator and back to top, will release in next version
