### ISSUE TITLE
Readability (original content) not working

### ISSUE THREAD

**Issue by n1njaznutz** [RSSNext/Follow#2044]
### Describe the bug

Readability not working in latest beta. Stuck with _"Fetching original content and processing..."_ and spinning wheel. 

### Feed Info

All feeds

### Reproduction Video

![Image](https://github.com/user-attachments/assets/bfc948da-8c8f-44f8-8631-7c0dbf96b688)

### Environment

**App Version**: 0.2.6-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `-yvYGp7I_AqZZZjleycDL`
**Renderer**: 0.2.6-beta.0

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by PrinOrange** [comment]
This issue was fixed in #2031
