### ISSUE TITLE
Codeblock turned into one line beacause spans are merged into one tag

### ISSUE THREAD

**Issue by fengkx** [RSSNext/Follow#205]
Expected:
<img width="902" alt="image" src="https://github.com/user-attachments/assets/f2968746-a494-4594-873b-160432e901fb">
keep the orginal html structure and style.

What follow content show:
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/b10b638a-eed9-4c53-85c5-36b6d6976ba3">

**Comment by Innei** [comment]
Hey, can you provide your feed URL?

**Comment by fengkx** [comment]
https://alampy.com/atom.xml

**Comment by Innei** [comment]
You should provide this format in your feed.

```
<pre><code class="language-ts">{code}</code></pre>
```

Otherwise, we can not parse into our ShikiRender.

**Comment by fengkx** [comment]
Try patch hexo-highlight-shiki to the format you mentioned.
<img width="766" alt="image" src="https://github.com/user-attachments/assets/896874b5-c387-49c0-82a8-0f249c18e654">

But the issue  doesn't fix.

Feed: https://www.fengkx.top/atom.xml

Shiki (codeToHtml function) doesn't output a language class by default. So I think it will affect many people using hexo-shiki-highlighter.

**Comment by Innei** [comment]
Thank you for your report, this issue is fixed in b3d32d09fd4d5b53ae1692ffdc154e8d37a77fdd, and will be released in the next version
