### ISSUE TITLE
小红书笔记打开原文异常

### ISSUE THREAD

**Issue by dearillusion** [RSSNext/Follow#2055]
### Describe the bug

![Image](https://github.com/user-attachments/assets/2276880e-c34e-45f8-8a5c-c85af8373623)
![Image](https://github.com/user-attachments/assets/4c5de28a-7b36-463e-ad4f-54976dff51f1)

### Feed Info

rsshub://xiaohongshu/user/5b8cc0472611925a1caca48a/notes
https://www.xiaohongshu.com/user/profile/5b8cc0472611925a1caca48a/

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by YatFanLan** [comment]
我也遇到了 这个问题  希望能够改进一下
