### ISSUE TITLE
Unable to claim airdrop

### ISSUE THREAD

**Issue by FelixXiong** [RSSNext/Follow#2056]
### Describe the bug

Unable to claim the airdrop.

When I use a browser to access the airdrop page, there is a problem when logging in with GitHub, and the following error message is displayed:

![Image](https://github.com/user-attachments/assets/342096f2-345c-42b7-ab4a-5231554683cd)

I tried using Chrome and Edge browsers and both gave me the same error message.

### Feed Info

Microsoft Edge-131.0.2903.70 (正式版本) (x86_64)

Google Chrome-116.0.5845.179

### Reproduction Video

https://github.com/user-attachments/assets/dede2321-a4ce-4dfe-b355-d09e1c3eaf1c

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/follow.is/commit/729928f0781dfac9b54429e499d71d9c3a3e875e, can you try again

**Comment by FelixXiong** [comment]
it's OK now，thanks.
<img width="1396" alt="Image" src="https://github.com/user-attachments/assets/92c72930-ea8c-4132-8c1b-aaf48bc6bd4a" />
