### ISSUE TITLE
I hope to use Windows 11-style scrollbars on Windows.

### ISSUE THREAD

**Issue by Malus-risus** [RSSNext/Follow#2058]
### Clear and concise description of the problem

I hope to use Windows 11-style scrollbars on the Windows platform.

### Suggested solution

As stated above

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by sixiansheng** [comment]
I concur.

**Comment by Malus-risus** [comment]
> Since the scrollbar styles are not uniform across platforms, we used a way to make the styles uniform across each platform

I just feel that the look on Windows is too much like macOS. I hope the macOS version uses the macOS style, and the Windows version adopts the Windows style.
