### ISSUE TITLE
What is the display logic for integrating the Obsidian plugin?

### ISSUE THREAD

**Issue by zJiaJun** [RSSNext/Follow#2065]
### Additional context

I tried opening many articles, but didn't see the button to save to Obsidian. The repository path has been configured. I also didn't find relevant documentation. Please tell me what its display logic is and how to make it work.

### Validations

- [x] This issue is valid

**Comment by zJiaJun** [comment]
### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `CywMfYYlj5tuiBrV03ggU`
**Renderer**: 0.2.6-beta.0

**Comment by hyoban** [comment]
- Using desktop client
- The status is enable
- Filled in the storage path
