### ISSUE TITLE
does not update with the latest entries

### ISSUE THREAD

**Issue by fghffyunbn** [RSSNext/Follow#2071]
### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `nlkqqyivAemVyruXDwvyE`

我使用zapier创建了一个RSS订阅，导入到follow后无法更新最新条目，但在其他RSS阅读器中可以显示更新。
I created an RSS subscription using Zapier, but after importing it into Follow, it does not update with the latest entries. However, it shows updates in other RSS readers.

**Comment by hyoban** [comment]
Please provide feed info

**Comment by fghffyunbn** [comment]
Resolved, thanks
