### ISSUE TITLE
[Request] Please  Put some images of UI and related stuff in main page of githhub or Gif to showcase the project in fastforward way

### ISSUE THREAD

**Issue by HakaishinShwet** [RSSNext/Follow#209]
### Additional context

Just by writing "Next generation information browser " doesnt help at all in understanding what makes it so unique, why kind of gui and features it will help and how will that make it next gen. These are some basic questions everyone will think of and many before personally downloading and testing want to see all those stuff and for that it will be much better to add some more details with images and gifs

**Comment by jspn-creative** [comment]
Alternatively, mention that the app "requires an invitation code to use" so people such as myself who ARE curious enough to download and test it out aren't immediately hit with frustration & disappointment 💔

If anyone else wants to be disappointed with slightly less frustration, they can skip the download part and check out the web app: https://web.follow.is/invitation though it is still frustrating that you have to link an account for auth before being told that an invitation code will be required.

**Comment by HakaishinShwet** [comment]
:-(

**Comment by Innei** [comment]
@jspn-creative @HakaishinShwet 

Hey. As the project is currently in the internal testing phase, we can't provide more information now, so please follow [x](https://x.com/follow_app_) for more information.

Stay tuned for more information on the project.
