### ISSUE TITLE
Is it possibile to translate the header of RSS?

### ISSUE THREAD

**Issue by shfujim** [RSSNext/Follow#2098]
### Clear and concise description of the problem

In present version, translate the RSS content is good.  In my personal some scientific jornals RSS, I often scan the headers to deside whether I should to read the contend, so I am wondering is it possiblie to add translate the headers function not only translate the contend of the RSS. 
Thanks.

### Suggested solution

Is it possibile to translate the header of RSS?

### Additional context

![Image](https://github.com/user-attachments/assets/bf8cd2fc-7eea-4e6f-961f-8aa354296b22)

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
You can do this using action

![Image](https://github.com/user-attachments/assets/c26a0235-fc19-4ef0-81b6-a9dcba1def34)

![Image](https://github.com/user-attachments/assets/8fe4a5cc-8269-4f67-aab5-753c23c9e2da)
