### ISSUE TITLE
Introduce configurable refresh times for RSS feeds

### ISSUE THREAD

**Issue by He-Xun** [RSSNext/Follow#2100]
### Clear and concise description of the problem

Currently, RSS feeds are automatically refreshed at a fixed interval. This can be inconvenient as different feeds update at varying frequencies, and users may not want all feeds to be refreshed constantly.

This pull request proposes the addition of configurable refresh times for each RSS feed.  A GUI could be implemented to allow users to easily specify the desired refresh interval for each feed, similar in functionality to a simplified crontab interface.

### Suggested solution

This would give users more control over their RSS feed management and improve the overall user experience by:

Reducing unnecessary data consumption: Only refresh feeds when necessary, saving bandwidth and resources.
Minimizing distractions: Avoid constant notifications for feeds that update infrequently.
Customizing the experience: Tailor the refresh schedule to individual needs and preferences for each feed.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
You can use boost to reduce the feed refresh time. We already dynamically set refresh time for different feeds.

**Comment by CodingByMe** [comment]
How often are feeds updated by Folo?

**Comment by thc282** [comment]
why not setting each rss channel with update time
we dont know the update time on each feeds

i have another web extension which can set and update corretly
i tried manual update, the latest feeds not show up at all
