### ISSUE TITLE
Failed to change display name

### ISSUE THREAD

**Issue by Surinrasu** [RSSNext/Follow#2145]
### Describe the bug

When I tried to change display name of my account, a pop-up message `[PATCH]"https://api.follow.is/auth-app/update-account": 404` appears in the bottom right corner

This can be reproduced on both web and macOS client

### Feed Info

Not related to a feed

### Reproduction Video

https://github.com/user-attachments/assets/02fe07eb-c237-4162-bf2f-9d0426b2ea69

### Environment

Web:

```markdown
### Environment

**App Version**: 0.2.7-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15
**Env**: web
**Browser**: Safari
**Session Trace Id**: `hejY-3eGYyTTaeJh6O2rk`
**Renderer**: 0.2.7-beta.0
```

macOS client:
```markdown
### Environment

**App Version**: 0.2.7-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.7-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `3S4UvXkv4gwhCdtZBiwkP`
**Renderer**: 0.2.7-beta.0
```

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/aeaf79522be23abb64ae940a4377a92448dfd923

**Comment by hyoban** [comment]
You can now update the profile in the web, but you have to wait for the next version on the desktop
