### ISSUE TITLE
Keyboard navigation should skip date row

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#216]
### Describe the bug

1. Click on an article item
2. Keep pressing down key and observe the article panel
<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/user-attachments/assets/be81a736-5d62-4032-acbc-4151ff65669a)
</details>

This can be replicated on both Web and Desktop client

### Feed Info

Feed URL: https://web.follow.is/feed/41178951307139072/

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Thank you for your report, this issue is fixed in #210, and will release in next version.
