### ISSUE TITLE
[i18n]: Unauthorized

### ISSUE THREAD

**Issue by Xingsheng-Zhang** [RSSNext/Follow#2165]
### Type of i18n contribution

New language support

### Language

Chinese

### Description

很多订阅显示未授权是为啥？添加自己构建的rss链接也显示未授权无法订阅

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] This issue is valid

**Comment by Xingsheng-Zhang** [comment]
已解决~

**Comment by terrywh** [comment]
> 已解决~

@Xingsheng-Zhang 怎么解决的？我升级到 0.4.3 也开始出现这种问题。。。

**Comment by terrywh** [comment]
才发现需要重新登录，大家忽略
