### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by JantyKkum** [RSSNext/Follow#2174]
### Describe the bug

when i login my account through github, it shows me a vary new account without anything and needed to be activated again, but actually i have been used follow for a while and already activated my account. 
![Image](https://github.com/user-attachments/assets/c2316bc8-0e4a-4626-9af0-a9ca2fc285b1)
![Image](https://github.com/user-attachments/assets/96de5058-13b8-4301-b985-e845baff5edb)
---
Then when I change my name to the old account name, it shows the error: [PATCH]"https://api.follow.is/auth-app/update-account": 404
![Image](https://github.com/user-attachments/assets/a1eab0da-b4b0-4ae7-af40-bb4b19a73339)
I need to get my old account back!!

### Feed Info

Old ID:Janty

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please try to adjust the email address bound to follow to the first email address bound to GitHub before logging in (setting it as the primary email address has no effect)
