### ISSUE TITLE
Account content is lost

### ISSUE THREAD

**Issue by stelvetica** [RSSNext/Follow#2175]
### Describe the bug

账号用的是github登录，显示名字为EssentialTreeTree，今天在安装follow本地时候，登录时候采用github登录，重新开始引导过程，下意识的把名字由stelvetica改为EssentialTreeTree，目前登录发现所有的订阅源和代币都没了。
现在手机上登录的账号还能正确使用。
补充：曾经错误的用过google账号登录。目前用google账号登录也是一样无订阅源和代币

### Feed Info

not feed 

### Reproduction Video

![Image](https://github.com/user-attachments/assets/a9daeba2-251f-40c4-9826-aca2d41f8efb)

### Environment

win10 浏览器

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please try to adjust the email address bound to follow to the first email address bound to GitHub before logging in (setting it as the primary email address has no effect)

We will soon support setting passwords via email.

**Comment by stelvetica** [comment]
My GitHub account has only one email address, which is also the primary email address. What should I do? Do I have to wait until email password login is supported to use it normally?
