### ISSUE TITLE
Can't change the handle and name.

### ISSUE THREAD

**Issue by Ekuboh** [RSSNext/Follow#2195]
### Describe the bug

It hints [PATCH] "https://api.follow.is/auth-app/update-account": 400

![Image](https://github.com/user-attachments/assets/6c9f7f18-676a-4710-90c4-071bd0e38038)

### Feed Info

..

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
https://github.com/RSSNext/Follow/issues/2145#issuecomment-2545597247
