### ISSUE TITLE
Error in fetching list: 87057604818760704

### ISSUE THREAD

**Issue by haoziweizhi101** [RSSNext/Follow#2199]
### Info:

List ID:
```
87057604818760704
```

Error:
```
Cannot add property 87057604818760704, object is not extensible
```

### Environment

**App Version**: 0.2.7-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.7-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `5aBhrEUzv6aLBaVNdFcB1`

**Comment by TonyRL** [comment]
Duplicate of #1399
