### ISSUE TITLE
Account data is overwritten by emptying

### ISSUE THREAD

**Issue by GuoAccount** [RSSNext/Follow#2201]
### Describe the bug

The first time I logged in with GitHub authorization on the web side, I used the invitation code to activate it on the desktop version, I imported the feed on the desktop version, and then I can see the data on the Mac web side, but when I log in with GiitHub on the mobile side, I find that it is a new account after logging in, and I am prompted to initialize some information. After a few days, the web version was logged in with github, and I found that the information was gone, and the data was all before the desktop version was not logged out, and the data was also logged in again after logging.
You should be able to retrieve the anomaly data in the database.

Both accounts are authorized to log in with the same github account, the same email address, and the account with data has a unique identifier
My account email: 348514929@qq.com
Unique identifier: 348514929

### Feed Info

My account email: 348514929@qq.com
Unique identifier: 348514929
Browser: Firefox
macOS: macOS 15.0.1 (24A348)

### Environment

Browser: Firefox
macOS: macOS 15.0.1 (24A348)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please try using email to reset your password

**Comment by GuoAccount** [comment]
> Please try using email to reset your password

Brother, I tried this way, the address sent by e-mail opens 404

![Image](https://github.com/user-attachments/assets/65958f54-6b4b-4792-961c-3fe1a29b9d6a)

**Comment by hyoban** [comment]
Do not make the link public, others can reset your password. Try prefix the link with https?

**Comment by GuoAccount** [comment]
> Do not make the link public, others can reset your password. Try prefix the link with https?

Brother, I changed the prefix to https, then the following page appeared, it seems to still not work.😭

![Image](https://github.com/user-attachments/assets/19cb093e-d5d6-4088-9ee2-f1037101875d)

**Comment by hyoban** [comment]
Oh, sorry, that's my problem. You can wait until the new version is released tomorrow and try it

**Comment by hyoban** [comment]
For now. Please try to adjust the email address bound to follow to the first email address bound to GitHub before logging in (setting it as the primary email address has no effect)

**Comment by GuoAccount** [comment]
> For now. Please try to adjust the email address bound to follow to the first email address bound to GitHub before logging in (setting it as the primary email address has no effect)

Bro, I think I'll just wait for you to release the new version. The method you mentioned earlier didn't work for me either. All I'm asking for is that the data for this account registered with [348514929@qq.com](mailto:348514929@qq.com), which has GitHub OAuth login, can still be retrieved. I don’t have any extra invitation codes left...

![Image](https://github.com/user-attachments/assets/57937e5b-dbc8-4e88-99c9-9bb107df59a2)
ß

**Comment by GuoAccount** [comment]
> For now. Please try to adjust the email address bound to follow to the first email address bound to GitHub before logging in (setting it as the primary email address has no effect)

Brother, I can reset my password now, after logging in, I found that the data are still gone, I used the invitation code to activate my previous account, there is no more invitation code, I can add the data subscription source back one by one, do you still have the invitation code, it's very important to me!

**Comment by hyoban** [comment]
Please make sure you use the correct follow account email to reset your password. Can you provide the correct follow account information?
