### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'iconClassName')

### ISSUE THREAD

**Issue by amyliu840** [RSSNext/Follow#2222]
### Error

Cannot read properties of undefined (reading 'iconClassName')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'iconClassName')

```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: macOS
**Env**: electron
**Browser**: Chrome

**Comment by TonyRL** [comment]
Duplicate of #2180
