### ISSUE TITLE
Error in fetching list: 69260144345565184

### ISSUE THREAD

**Issue by ChelsieWang** [RSSNext/Follow#2274]
### Info:

List ID:
```
69260144345565184
```

Error:
```
[GET] "https://api.follow.is/lists?listId=69260144345565184": <no response> Failed to fetch
```

### Environment

**App Version**: 0.2.7-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.7-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `D3M67p1yUoYdykLitLg9M`

**Comment by hyoban** [comment]
There should be no problem now

![Image](https://github.com/user-attachments/assets/ef33250e-cfb3-459e-8ed1-4b3552a42836)
