### ISSUE TITLE
rss, but only one is rendered in the follow

### ISSUE THREAD

**Issue by dddaniel1** [RSSNext/Follow#2275]
### Describe the bug

![Image](https://github.com/user-attachments/assets/99d3c288-d981-4930-8482-50ebf36d806c)
图上有很多内容
![Image](https://github.com/user-attachments/assets/083377dc-4926-4fda-bc24-ee5a91dfff1f)
但是follow只渲染了一条

### Feed Info

https://app.follow.is/share/feeds/92947927134831616?view=4

https://daniel2rsshub.pikapod.net/xiaohongshu/user/59299f4b50c4b402f057da23/notes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
There are currently unresolved issues in fetching Xiaohongshu notes.
