### ISSUE TITLE
youtubeTwo questions

### ISSUE THREAD

**Issue by hzc54188** [RSSNext/Follow#2299]
### Describe the bug

有的youtube视频封面无法获取，视频缩略图处于缺省状态。
有的Youtube视频无法预览，要在新标签打开。

### Feed Info

我是——你的小黄鸡，标识符是——@qq851027566。
这个id 88663347098525696 没有缩略图。
这个id 87448062282247168 没有缩略图，无法播放和预览youtube视频链接

### Reproduction Video

![Image](https://github.com/user-attachments/assets/7faf0399-6e9d-43e2-8892-b4ea8ed01698)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please make sure to use the feed from rsshub, https://app.follow.is/share/feeds/93991959927479296?view=3

```
rsshub://youtube/user/%40Larvatuba
```
