### ISSUE TITLE
Can't scroll to bottom in preference if main windows' height is too low

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#230]
### Describe the bug

Version: v0.0.1-alpha.7
OS: Windows 10 (19044)

### Steps to reproduce

1. Resize main windows' height
2. Open preference
3. Try to scroll to bottom

<details>
<summary>Screen record</summary>

![Screen record](https://github.com/user-attachments/assets/cc348dd2-87cd-4b67-a44b-bcf7a85abc23)
</details>

### Feed Info

N/A

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Nice catch.
