### ISSUE TITLE
support subscribing to novel JSON

### ISSUE THREAD

**Issue by cdxiaodong** [RSSNext/Follow#2309]
### Clear and concise description of the problem

I hope that follow-rss will support subscribing to novel JSON format feeds in the future.

### Suggested solution

The current Chinese novel websites mostly use the same framework, so it is possible to create corresponding web crawlers and feeds for this framework.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] This issue is valid

**Comment by hyoban** [comment]
json feed is already supported, for example https://ladfenemies.cc/feed?format=json

**Comment by cdxiaodong** [comment]
LINK:https://[raw.ixnic.net/XIU2/Yuedu/master/shuyuan](https://raw.ixnic.net/XIU2/Yuedu/master/shuyuan)
fine,It is unrealistic for n8n to take over the source of novel books.
