### ISSUE TITLE
Glitched accent colour

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/follow#231]
### Describe the bug

Version: v0.0.1-alpha.7
OS: Windows 10 (19044)

### Steps to reproduce

1. Open Follow (Windows is in dark mode)
2. Check the accent colour when the main window is in focus and out of focus
3. In focus: OS accent colour, hard to read unread count. Out of focus: dark grey
4. Maximise Follow and check the accent colour (which becomes black)
5. Resize Follow to back to normal
6. Check the accent colour again when the main window is in focus (black) and out of focus (black)

This issue is more problematic when the OS is set to bright mode after maximise, where everything in the sidebar is completely black.

<details>
<summary>Screen record</summary>

https://github.com/user-attachments/assets/0922904f-b6db-41fe-be49-dc34780042cd
</details>

### Feed Info

N/A

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
We use `backgroundMaterial: "mica"` in the new version of Follow.

https://learn.microsoft.com/en-us/windows/apps/design/style/mica

It seems that the material is not supported by Windows 11 or later. But I don't have a device below Windows 11 around to test different materials on different systems at the moment.

**Comment by Innei** [comment]
Maybe I can disable the use of this feature on systems lower than Windows 11

**Comment by TonyRL** [comment]
Same thing happens on Windows 11 23H2 (25941.1000)

<details>
<summary>Screen record</summary>

![vmware](https://github.com/user-attachments/assets/579ee8af-8414-45a6-8443-cada82f11462)
</details>

**Comment by Innei** [comment]
I disabled BackgroundMaterial for Windows 11 and below, and manually implemented the maximization logic for Windows 11.

**Comment by Innei** [comment]
Can you help me test it, thanks

https://github.com/RSSNext/Follow/actions/runs/10520087750/artifacts/1845576782

**Comment by TonyRL** [comment]
Accent colour now looks fine in both Windows 11 and 10 although the maximise animation is missing in Windows 11.
<details>
<summary>Windows 11</summary>

https://github.com/user-attachments/assets/fd0a92e6-7d90-4b48-9c43-fc2f2aa2f52d
</details>

**Comment by Innei** [comment]
> maximise animation is missing

Yes, because I implemented the maximization logic manually instead of using the system's

**Comment by Innei** [comment]
Is this issue resolved now?
