### ISSUE TITLE
[Bug] 无法一键已读

### ISSUE THREAD

**Issue by versun** [RSSNext/Follow#232]
### Describe the bug

如下gif显示，点击Confirm后无响应
![2024-08-24 -01-39-15](https://github.com/user-attachments/assets/e49a14a7-a18c-4650-925e-caad830d25ef)

测试Firefox for macOS 和 Edge for Windows都不行

### Feed Info

all feeds

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Fixed in f33598bb9acf870f9c07475e75b4ed5e78ed6a85
