### ISSUE TITLE
license 未正确展示

### ISSUE THREAD

**Issue by runkecheng** [RSSNext/Follow#2331]
### Describe the bug

<img width="777" alt="Image" src="https://github.com/user-attachments/assets/458001c3-dbe8-4a91-8221-30bee18757bf" />

### Feed Info

rkech

### Environment

**App Version**: 0.2.8-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.8-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `isf0Q_axAhskw_1qlmWfc`
**Renderer**: 0.2.8-beta.0

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/8a666e5f1bf2a38f52463b569f6d627129f8812b
