### ISSUE TITLE
Always "Fetching original content and processing..." in Readability for specific feeds

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#2375]
### Describe the bug

For specific feeds, "Fetching original content and processing..." is always displayed.

![Image](https://github.com/user-attachments/assets/d09db6df-e90d-4536-adc0-d51fd9daca2f)

There has been an issue about this #2044. But it has been fixed. So I think it is necessary to open a new issue.

### Feed Info

rsshub://huggingface/blog

### Environment

**App Version**: 0.2.9-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.9-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `H4g7hgIOAKiiPiS5r5tiW`
**Renderer**: 0.2.9-beta.0

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
![Image](https://github.com/user-attachments/assets/4bf0f8c2-632a-49fa-89da-6262a13e44a8)

It works for me. Readability only makes requests on the client side, please check your network.
