### ISSUE TITLE
Account cannot be logged in

### ISSUE THREAD

**Issue by wenfp108** [RSSNext/Follow#2378]
### Describe the bug

The account automatically logs out and keeps loading when you jump to the login page.

### Feed Info

https://app.follow.is/login?provider=google

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by felixsh0712** [comment]
F9314F4 Account cannot be logged in and keep logging

**Comment by zhanzekun** [comment]
meet this problem too

**Comment by xy2yp** [comment]
meet this problem too

**Comment by poer2023** [comment]
I also encountered the same problem，in thirty minutes

**Comment by Innei** [comment]
Just encountered an exception with the server. It has now been fixed, please try again.

**Comment by Naka7su** [comment]
The only sign-in options are Google or Github account and I can't continue with my email address, is this correct behavior?
