### ISSUE TITLE
Sign up by mail doesn't work

### ISSUE THREAD

**Issue by MrPandir** [RSSNext/Follow#2381]
### Describe the bug

The error lies in the CORS.
<img width="714" alt="Image" src="https://github.com/user-attachments/assets/334162cf-a980-4a0e-8efa-2a951597b4f5" />
The problem is in both the web site and the app. An empty error notification appears in the application.

### Feed Info

https://app.follow.is

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It should be fine now
