### ISSUE TITLE
[Feature Request] Open entry in the follow app

### ISSUE THREAD

**Issue by lawvs** [RSSNext/Follow#247]
### Clear and concise description of the problem

The data in an RSS feed may not be complete. For example, it might be missing comments or unable to display images, which would require visiting the original URL. If the app can seamlessly display the original webpage, I think it's a good feature.

### Suggested solution

I created a simple demo and the results were good.

https://github.com/user-attachments/assets/9be0dd0c-a5e4-4118-b2d9-a97241c9ca9b

Note, most websites do not allow being embedded as an iframe, but as an electron application, I believe this is not a problem.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
I think you can just open the original site and visit

**Comment by Innei** [comment]
@DIYgod What do you think of the feature?

**Comment by DIYgod** [comment]
I think this makes sense, users don't need to switch to other applications, similar to Reeder which also provides such a feature.
