### ISSUE TITLE
windows上follow注册为feed://链接打开程序

### ISSUE THREAD

**Issue by lossfunc** [RSSNext/Follow#249]
### Clear and concise description of the problem

我发现rsshub可以打开本地rss阅读器，但是没能设置为follow，在windows的默认应用程序中看到打开feed://链接的程序是outlook，且无法切换为follow。

### Suggested solution

none

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Fixed in https://github.com/DIYgod/RSSHub-Radar/commit/c67b28ff54510159aaa8b6bdd8428dbb44ff1c9a
