### ISSUE TITLE
Save/Export as PDF/Markdown format

### ISSUE THREAD

**Issue by zixude** [RSSNext/Follow#25]
诉求：期望将归档的文章，保存为md格式，方便长期主义的备份留存。

场景：目前很多本地RSS阅读器，例如Reeder，读了就读了，数据无法导出保存，导致很多优质文档无法备份。

分析：将所有自己归档的文章保存为md格式后，作为AI易解析的格式，方便后续检索，或在Obsidian中查看、引用。

额外补充：如果RSS阅读器未来支持高亮标注的话，高亮标注在转换为md格式时，自动转换为==highlight==的标记，就完美了，这样能完整的存档文章。

**Comment by zixude** [comment]
请求开发者帮忙删除本issue，我没有删除按钮。

**Comment by DIYgod** [comment]
We now support exporting Markdown to Obsidian. Feel free to try out this feature!
