### ISSUE TITLE
AI Summary in ¿Español?

### ISSUE THREAD

**Issue by masonfocus** [RSSNext/Follow#250]
### Describe the bug

The summary of one English article is somehow in Spanish.

<img width="694" alt="image" src="https://github.com/user-attachments/assets/559b5bd5-fbc5-4a0e-a3b1-27dadf543952">

The source is in English. My system is in Chinese. I don't know why the summary is in Spanish.

By the way, is there a way to customize the prompt of AI summary? 

### Feed Info

https://feeds.feedblitz.com/~/903708125/0/marginalrevolution~Failing-Banks.html

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by STRRL** [comment]
+1 this issue also occurred to me these days, the origin post is written in English

![image](https://github.com/user-attachments/assets/358b4690-4228-467a-8de9-9581ccb6607b)

https://lwkd.info/2024/20240918

**Comment by STRRL** [comment]
Hi @hyoban ! I appreciate as a Follow user for your great work, making Follow as a great work! 

BTW, I noticed you have marked this issue as completed, I just a little curious about the reasons and the corresponding patch, could you provide more detail about this issue? Thanks a lot! ❤️

**Comment by hyoban** [comment]
I detect the language of the content before sending it to AI, instead of letting AI summarize it according to the source language of the content.

**Comment by kowyo** [comment]
So the system prompt of AI Summary is not open source yet... I really want to know the implementation.
