### ISSUE TITLE
Inconsistent behavior after opening a video.

### ISSUE THREAD

**Issue by KenMercusLai** [RSSNext/Follow#251]
### Describe the bug

Reproduce steps:
1. Randomly open a video by clicking it
![image](https://github.com/user-attachments/assets/83abd2c4-38c1-4ff3-a83f-2b74585ccccd)

2. playing window pops up
![image](https://github.com/user-attachments/assets/555e3996-8b24-4dad-9013-302f113550ff)

3. WITHOUT doing anything, you can press ESC to quit playing.

The issue is:
Once the video area is clicked, like to pause the video, the app stops responding to ESC for quitting playback.

It happens to all sources.

### Feed Info

https://www.youtube.com/feeds/videos.xml?channel_id=UCcEPmwpXKrKzZahqjwpIAsQ

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
Based on the discussion here, I believe this issue cannot be resolved in the short term, so this issue will be closed until our upstream dependency has update or a solution is found. https://github.com/electron/electron/issues/14258
