### ISSUE TITLE
opening dropbox menu in settings will cause article re-rendered

### ISSUE THREAD

**Issue by KenMercusLai** [RSSNext/Follow#252]
### Describe the bug

https://github.com/user-attachments/assets/c08808b4-b7f6-4c29-a904-1211d4344b41

### Feed Info

https://jysperm.me/atom.xml

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Fixed, will release in the next version. Thank you for your report
