### ISSUE TITLE
Show "invalid byte sequence for encoding "UTF8": 0xb7" after adding "Github Trending" feed

### ISSUE THREAD

**Issue by lemorage** [RSSNext/Follow#253]
### Describe the bug

After adding "Github Weekly Trending" to my feed list, it showed a little bug icon on the sidebar, and the bug information said "invalid byte sequence for encoding "UTF8": 0xb7". For now, it seemed not to affect its functionality, but kind of annoying. I wonder what was wrong with it.

<img width="1198" alt="Screenshot 2024-08-31 at 15 35 39" src="https://github.com/user-attachments/assets/2ef7299b-2d47-4d3a-b928-b777b72152b5">

### Feed Info

<img width="596" alt="Screenshot 2024-08-31 at 15 36 00" src="https://github.com/user-attachments/assets/0639fba1-d323-4555-82c3-9a22ff4fd4d8">

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment]
![OkLTF8B](https://github.com/user-attachments/assets/78580984-49ef-41c4-9082-0920332204dc)

This also happens with feeds other than RSSHub.
https://blog.cloudflare.com/rss

**Comment by DIYgod** [comment]
> [nodejs/node#54521](https://github.com/nodejs/node/issues/54521) [nodejs/node#54543](https://github.com/nodejs/node/issues/54543) hopefully it will be fixed in node v22.8

I just downgraded the node version to 20, and now it's working fine. https://x.com/DIYgod/status/1830591809233588586
