### ISSUE TITLE
The `Follow` button status doesn't not update instantly when following someone

### ISSUE THREAD

**Issue by hakadao** [RSSNext/Follow#254]
### Describe the bug

After I click the `Follow` button to follow a specific twitter user on the discover page, I notice that the `Follow` button still appears as if i haven't followed the user.
It might be better to change the button to gray or another color to indicate that the user already been followed 🤔

![image](https://github.com/user-attachments/assets/6126ec07-6d09-4157-ab2b-1a3a32813594)

### Feed Info

rsshub://twitter/user/KMkota0

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by MaxtuneLee** [comment]
Tried to fix and submitted a PR, could any maintainer please help me review my PR 🥺

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/32a55ece6440f80f837adc6d558029ea5fbd6982
