### ISSUE TITLE
An "unfollow" button should be added in the view "Edit Follow"

### ISSUE THREAD

**Issue by tzbkk** [RSSNext/Follow#257]
### Clear and concise description of the problem

![1](https://github.com/user-attachments/assets/7e7a122d-3e0c-46a5-9afe-36ac25d354a9)
To edit a follow, there should not be just a "Follow" button. I think an "Unfollow" button is also needed.

### Suggested solution

![2](https://github.com/user-attachments/assets/39d7643a-45b7-475a-b319-5891d5d73f3e)
The function of the new button is as same as this one:
![3](https://github.com/user-attachments/assets/e0ee3fde-1849-4117-a45a-97f0f2024a86)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
This is a bug and has been fixed in https://github.com/RSS Next/Follow/pull/263
