### ISSUE TITLE
Can't delete category

### ISSUE THREAD

**Issue by eMUQI** [RSSNext/Follow#258]
### Describe the bug

Unable to delete category

Reproduction steps:
1. Right-click a category
2. Select "delete category"
3. Click continue
4. The category is not deleted

### Feed Info

none

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Can't reproduction, upload a video reproduction plz.

**Comment by eMUQI** [comment]
> Can't reproduction, upload a video reproduction plz.

https://github.com/user-attachments/assets/afc93371-1771-49c2-aa66-5b6045998578

**Comment by Innei** [comment]
You can't delete the default categories. Currently, when more than two feeds have the same domain name, they are automatically grouped.
