### ISSUE TITLE
Unable to retrieve content from certain podcast RSS feeds

### ISSUE THREAD

**Issue by eMUQI** [RSSNext/Follow#260]
### Describe the bug

I am trying to migrate the podcasts I subscribe to to Follow, but I noticed that certain blogs cannot retrieve content and have an icon with a wifi symbol and an exclamation mark.
Steps to reproduce:
1. Import subscriptions in bulk via OPML
2. Follow is unable to retrieve content for certain blogs, and displays an icon with a wifi symbol and an exclamation mark

### Feed Info

|  feed id   | feed url  |
|  ----  | ----  |
| 52629447588644864  | https://feeds.megaphone.fm/ADL7382912950 |
| 52629447588644865  | https://feeds.megaphone.fm/ADL8618703123 |
| 52629447588644878  | https://feeds.transistor.fm/acq2  |
| 52629447588644879  | https://omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/96C5C41E-0BC8-4661-B184-AE32006CD726/D623EF0B-3FEE-4C26-B815-AE32006CD739/podcast.rss  |

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Link to https://github.com/RSSNext/Follow/issues/253

**Comment by eMUQI** [comment]
> Link to #253

Thank you for your reply! I'd like to point out something additional: while the "follow" feature works fine for fetching subscription content in issue #253, it's not working properly for the RSS link I shared. Specifically, it's unable to pull in the subscription content from my provided RSS feed.

![image](https://github.com/user-attachments/assets/f53c19a9-ab6a-476b-b996-8d68be8f8f7d)

**Comment by DIYgod** [comment]
<img width="1661" alt="image" src="https://github.com/user-attachments/assets/490a6fa7-f2e3-4964-bf85-d8816ec4e900">

I noticed that the subscriptions you captured are now working. Could you please confirm if they are now working on your end?

**Comment by eMUQI** [comment]
> <img alt="image" width="1661" src="https://private-user-images.githubusercontent.com/8266075/363978238-490a6fa7-f2e3-4964-bf85-d8816ec4e900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTQzODMsIm5iZiI6MTcyNTQxNDA4MywicGF0aCI6Ii84MjY2MDc1LzM2Mzk3ODIzOC00OTBhNmZhNy1mMmUzLTQ5NjQtYmY4NS1kODgxNmVjNGU5MDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDE0MTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QwY2Y1ZmI1N2QxMTg5ZmJlODgyM2FkMTcwYjFiYzg5NDE3ZGU4YzI2YjBkMmRiZjEyYzAwYWNhOGRiMDc1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UqWDtCKQjQOoKkL3F_cf3Ic-rgg6dncspxtre6oQ5us">
> 
> I noticed that the subscriptions you captured are now working. Could you please confirm if they are now working on your end?

it works now, thanks!
