### ISSUE TITLE
启动时左侧菜单的异常行为

### ISSUE THREAD

**Issue by kamuiiiii** [RSSNext/Follow#280]
### Describe the bug

启动时左侧菜单最下方出现我订阅的 joshwcomeau，过一会消失（即使我取消订阅了仍会有该问题

### Feed Info

在我本机稳定复现
1. 打开 Follow
2. 观察左侧菜单

### Reproduction Video

https://github.com/user-attachments/assets/c30b6b21-a9b5-4678-a855-c96b868aa1c4

### App Type

Electron / App

### Version

v0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I think you can try rebuild database in settings, it should help
