### ISSUE TITLE
切换顶部菜单时，左侧二级菜单没有变化

### ISSUE THREAD

**Issue by kamuiiiii** [RSSNext/Follow#281]
### Describe the bug

切换顶部菜单时，左侧二级菜单没有变化

### Feed Info

1. 进入 Follow，切换一级菜单
2. 观察二级菜单

### Reproduction Video

https://github.com/user-attachments/assets/18bc1719-7072-4770-855f-0a097b759794

### App Type

Electron / App

### Version

v0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
这是一个开启了 Reduce motion 之后的 bug，暂时可以先关闭这个选项。下个版本修复。感谢反馈

**Comment by kamuiiiii** [comment]
感谢回复，另外我想补充的一个背景是，我本机上没有开启 reduce motion

**Comment by Innei** [comment]
> 感谢回复，另外可能值得补充的背景是，我本机上没有开启 reduce motion

那是因为你系统开启了 reduce motion也会影响
