### ISSUE TITLE
newwork error - entity xxx data is undefined

### ISSUE THREAD

**Issue by kaffa** [RSSNext/Follow#282]
### Describe the bug

Reproduction steps:
1. add a feed "https://kaffa.im"
2. click `Load archived entries` buttom in the second column, the extra archived entries shows.
3. click a title in archived entries, the "newwork error - entity xxx data is undefined" will show in the content view.
![image](https://github.com/user-attachments/assets/3009ddf3-0315-40c8-b68d-7ad94ea1d3ce)

### Feed Info

https://app.follow.is/feeds/41342818708527123/41342824228231313?view=0

### App Type

Web

### Version

0.0.1-alpha.10

### Operating System

Windows 10

### Browser Info

Microsoft Edge 版本 128.0.2739.54 (正式版本) (64 位) 

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Will fixed in next version
