### ISSUE TITLE
Windows下Bilibili无法播放视频

### ISSUE THREAD

**Issue by markbang** [RSSNext/Follow#284]
### Describe the bug

Windows桌面应用无法播放bilibili.com的视频

### Feed Info

1、网络连接正常，可正常获取视频封面及标题
2、已根据提示登陆bilibili账号
3、点击任意视频，弹窗后无法播放以及交互按钮点击无效

### Reproduction Video

https://github.com/user-attachments/assets/b837febf-347a-4c1a-8d2f-024bd4bfc170

### App Type

Electron / App

### Version

0.0.1-alpha.10

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by bfrontend** [comment]
> ### Describe the bug
> Windows桌面应用无法播放bilibili.com的视频
> 
> ### Feed Info
> 1、网络连接正常，可正常获取视频封面及标题 2、已根据提示登陆bilibili账号 3、点击任意视频，弹窗后无法播放以及交互按钮点击无效
> 
> ### Reproduction Video
>  2024-09-07.14-53-30.mp4 
> ### App Type
> Electron / App
> 
> ### Version
> 0.0.1-alpha.10
> 
> ### Operating System
> Windows 11
> 
> ### Browser Info
> _No response_
> 
> ### Validations
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> 
> ### Contributions
> * [ ]  I am willing to submit a PR to fix this issue
> * [ ]  I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

哪里有提示登录账号

**Comment by f4cker** [comment]
<img width="1578" alt="image" src="https://github.com/user-attachments/assets/ea2f43ff-d2a7-440c-ac12-d25cea3f9f22">
就像这样，点击详情可以看到登录按钮，但是点进去会提示浏览器不安全，无法登录。

> > ### Describe the bug
> > Windows桌面应用无法播放bilibili.com的视频
> > ### Feed Info
> > 1、网络连接正常，可正常获取视频封面及标题 2、已根据提示登陆bilibili账号 3、点击任意视频，弹窗后无法播放以及交互按钮点击无效
> > ### Reproduction Video
> > 2024-09-07.14-53-30.mp4
> > ### App Type
> > Electron / App
> > ### Version
> > 0.0.1-alpha.10
> > ### Operating System
> > Windows 11
> > ### Browser Info
> > _No response_
> > ### Validations
> > 
> > * [x]   Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> > * [x]   Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> > 
> > ### Contributions
> > 
> > * [ ]   I am willing to submit a PR to fix this issue
> > * [ ]   I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)
> 
> 哪里有提示登录账号

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.

**Comment by lazydao** [comment]
You can reopen it, the latest version still doesn't work.
### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by lxy697** [comment]
> I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.

the problem still exists in the latest version
### Environment

**App Version**: 0.2.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

and the previous version also didn't work，as i have tried the day before yesterday,i can't login google account

**Comment by lazydao** [comment]
To reply, I can now play bilibili and YouTube videos normally.
Additional explanation: I do use a global VPN.

**Comment by lxy697** [comment]
> To reply, I can now play bilibili and YouTube videos normally. Additional explanation: I do use a global VPN.

can you login youtube by google account?Mine says the brower is not safy

**Comment by lazydao** [comment]
> > To reply, I can now play bilibili and YouTube videos normally. Additional explanation: I do use a global VPN.
>
> can you login youtube by google account?Mine says the brower is not safy

I forget if I've ever logged into YouTube in follow, I just remember logging into Bilibili, so maybe YouTube doesn't need to be logged into your account?
