### ISSUE TITLE
TOC blocks scrolling and scroll bar

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#288]
### Describe the bug

1. Open a feed item with TOC
2. Keep scrolling down the article
3. Move the cursor over the TOC
4. The article stops scrolling down while the cursor is over the TOC

The TOC also blocks the scroll bar.

### Feed Info

41459996879067138: https://blog.cloudflare.com/rss

### Reproduction Video

<details>
<summary>Blocks scrolling</summary>

![Blocks scrolling](https://github.com/user-attachments/assets/96377468-e98a-4bcb-9034-8b2f1fc3493c)
</details>

<details>
<summary>Blocks scroll bar</summary>

![Blocks scroll bar](https://github.com/user-attachments/assets/691b12ad-45fa-4f89-9eee-739ddc1937ae)
</details>

### App Type

Electron / App

### Version

0.0.1-alpha.10

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
From a UX point of view, this is probably not an interaction issue.

Imagine a scenario where you understand that the HoverCard is a separate modal, and when you hover over it, only the content inside the HoverCard can be scrolled.

The ToC overlay is a HoverCard component.

You should be able to understand this when the content in the ToC is too long for the scrollbar.

**Comment by TonyRL** [comment]
Fixed in https://github.com/RSSNext/Folo/commit/e80f8a4dd34fd4e5df6f28f39a7e701204c17eb4
