### ISSUE TITLE
非UTF-8的RSS源显示乱码

### ISSUE THREAD

**Issue by kisexu** [RSSNext/Follow#290]
### Describe the bug

载入非UTF-8的RSS源时显示乱码
![SCR-20240908-bhcb](https://github.com/user-attachments/assets/e2775603-3d19-4b2c-bd75-c0de6042f1c6)
![SCR-20240908-bheh](https://github.com/user-attachments/assets/71f01306-d623-40b6-a142-02760c8c5371)

### Feed Info

https://blog.codingnow.com/atom.xml

### App Type

Electron / App

### Version

0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in follow server, will be released in the next version

**Comment by Laitr0n** [comment]
The title of feed is fixed, but the content is not working in version[v0.0.1-alpha.14].

**Comment by kisexu** [comment]
@hyoban 你好，现在订阅的标题是正常了，但是内容依旧乱码

**Comment by hyoban** [comment]
这个应该是历史的内容已经入库的原因，我看看要不要清理一下数据

**Comment by lakako** [comment]
今早尝试拉取，依然乱码

![image](https://github.com/user-attachments/assets/fa16834d-bd35-45bb-add9-c6b02aad185b)

**Comment by molingyu** [comment]
我现在第一篇是正确的 然后其他的都是乱码

除此之外 一旦切换阅读模式 就又会变成乱码
