### ISSUE TITLE
请求优化已读快捷键功能逻辑

### ISSUE THREAD

**Issue by 2019YKL** [RSSNext/Follow#293]
### Clear and concise description of the problem

首先，感谢几位开发者开发如此好用的RSS阅读软件🙏

最近陆续将其他平台的RSS订阅转移到Follow上，所以很多订阅会有大量未读消息。

软件提供了`command+shift+A`的方式快速已读，但仍需二次确认，而二次确认没有快捷键可以处理，只能用鼠标移动过去确认。

这似乎让快捷键失去了它原本的意义，如果需要使用鼠标，我移动鼠标去点两次“已读☑️”按钮反而还比快捷键来得快。

### Suggested solution

个人拙见：已读快捷键默认无需二次确认，使用快捷键后的一段时间，弹出撤回已读的选项。

![CleanShot 2024-09-08 at 11 44 06@2x](https://github.com/user-attachments/assets/61b43055-ede6-4e35-b66e-95841a4ca7b4)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
已采纳，感谢指出不合理的 UX 细节
