### ISSUE TITLE
不能订阅rss.cnbeta.com.tw

### ISSUE THREAD

**Issue by laivn** [RSSNext/Follow#299]
### Describe the bug

浏览器和netnewswire可以正常浏览和订阅，follow添加几次都不行。
![CleanShot 2024-09-09 at 10 18 22@2x](https://github.com/user-attachments/assets/4c5176d0-84dc-4ac3-8336-4c9df3d15699)

### Feed Info

https://rss.cnbeta.com.tw/

### App Type

Electron / App

### Version

v0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
There is an issue with the certificate.

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/6d273e74-86d1-4391-8c67-71a2b1e4bb81">
