### ISSUE TITLE
follow 在 Windows 非全屏状态下的 app 圆角显示不全

### ISSUE THREAD

**Issue by Sepush** [RSSNext/Follow#302]
### Describe the bug

表现：
- app 有两个角上有圆角但有白底 另外两个角没有圆角

预期：
- 是要么4个角都有圆角要么都没有

额外的信息：
- 之前在 QQ 音乐的Windows客户端上也遇到过类似情况

![image](https://github.com/user-attachments/assets/64d77111-5005-4124-b12c-dd06588ae8d3)

### Feed Info

不需要 feed info

### App Type

Electron / App

### Version

v0.0.1-alpha.10

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Arkhme** [comment]
> [Exit. siga no Windows 非全屏状态下的 aplicativo 圆角显示不全](https://linear.app/follow-app/issue/FOL-80/follow-在-windows-非全屏状态下的-app-圆角显示不全)

**Comment by Arkhme** [comment]
Serve pra nada

**Comment by DIYgod** [comment]
I this this issue has been fixed, if the problem still exists, please feel free to reopen it.
