### ISSUE TITLE
feat. 已经阅读的文章建议于未读的字体颜色有区分

### ISSUE THREAD

**Issue by debuginn** [RSSNext/Follow#304]
### Clear and concise description of the problem

feat. 已经阅读的文章建议于未读的字体颜色有区分

### Suggested solution

阅读完毕的：灰色处理一点
没有阅读的：红点提醒+黑色字体

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
If you look carefully, there is indeed a difference in color, though I admit it's not immediately obvious. 🤣

**Comment by debuginn** [comment]
@DIYgod 看了下，的确有细微差别 但是不太明显 😂 可能是我显示器有点子差
