### ISSUE TITLE
Support Podcast Chapter|支持播客章节

### ISSUE THREAD

**Issue by Jiang10086** [RSSNext/Follow#308]
### Clear and concise description of the problem

Many podcasts have chapters, allowing listeners to quickly jump to specific sections, and hosts can assign different chapter images to correspond with each section. For example, Type Chat ([RSS subscription link](https://www.thetype.com/typechat/feed/)) has this feature. The image below is a screenshot of the podcast being played on Apple Podcasts, where you can quickly navigate to the corresponding sections. You can also see that different chapters have unique images corresponding to the current podcast content.

许多播客有章节，这样可以快速跳转到特定位置，并且主播也可以为不同章节配上不同的章节插图。例如《字谈字畅》（[RSS订阅链接](https://www.thetype.com/typechat/feed/)）就具有此特性。下图是在Apple Podcast下播放此播客的截图，能快速跳转到对应位置。也能看到不同的章节配有不同的插图，以对应当前的播客内容。
No podcast chapter support.
![image](https://github.com/user-attachments/assets/c44605c0-c090-4d04-b7e6-22072a51d683)
![image](https://github.com/user-attachments/assets/b3272439-07d5-4e3d-bea7-519a83dd7787)
![image](https://github.com/user-attachments/assets/0b453ff9-486d-46c7-9488-f597affd9c33)
![image](https://github.com/user-attachments/assets/f6739d10-b4eb-4a40-aea3-1af79ea688ba)

### Suggested solution

Support podcast chapters.
支持播客章节

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
We can identify the time in the content, but I didn't find any time information in the example you provided.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1c8c40d6-4e34-4143-ad34-f7df66de2db6">
