### ISSUE TITLE
界面元素自定义选项

### ISSUE THREAD

**Issue by QiongBan** [RSSNext/Follow#310]
### Clear and concise description of the problem

现有不同字体大小无法灵活调节界面元素，其中来源与时间的字体与大小和标题正文相比过小，难以分辨；标题与正文在文章栏存在因为固定高度而导致可能省略正文甚至部分标题的情况，或者部分文本未能完全展示（见下图）。
<img width="336" alt="image" src="https://github.com/user-attachments/assets/3d7c3155-094b-4b1c-ba59-a9246ecac6c7">

### Suggested solution

这些问题部分可以通过自定义 Feed 显示名称解决，但最关键的还是对用户开放自定义界面元素的选项，如：来源、标题、正文、时间字体与大小，自定义 Feed 名称，文章栏高度（可选默认显示行数），阅读界面页边距等。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyongnim** [comment]
求一个邀请码

**Comment by DIYgod** [comment]
Duplicate of #256
