### ISSUE TITLE
添加不同文章打开方式并作为默认

### ISSUE THREAD

**Issue by QiongBan** [RSSNext/Follow#311]
### Clear and concise description of the problem

当前 App 中打开一篇文章的默认逻辑应该是原始内容，但是部分 Feed 如 https://sobooks.cc/feed 需要通过点击上方 Readability 查看原文才能得到完整内容且 AI Summary 局限于原始内容，当要查看的文章较多时，会造成较多重复的操作影响内容的获取。
<img width="718" alt="image" src="https://github.com/user-attachments/assets/0bd7651d-7292-4ab7-9cfe-425a8113cb80">

### Suggested solution

提供可设置为默认的多种打开方式：全文模式、新闻简报、内置网页、应用内浏览器、跳转至外部浏览器等。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tongjanseeton19** [comment]
> ### Clear and concise description of the problem
> 
> 当前 App 中打开一篇文章的默认逻辑应该是原始内容，但是部分 Feed 如 https://sobooks.cc/feed 需要通过点击上方 Readability 查看原文才能得到完整内容且 AI Summary 局限于原始内容，当要查看的文章较多时，会造成较多重复的操作影响内容的获取。
> <img width="718" alt="image" src="https://github.com/user-attachments/assets/0bd7651d-7292-4ab7-9cfe-425a8113cb80">
> 
> ### Suggested solution
> 
> 提供可设置为默认的多种打开方式：全文模式、新闻简报、内置网页、应用内浏览器、跳转至外部浏览器等。
> 
> ### Alternative
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
> 
> ### Validations
> 
> - [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by looechao** [comment]
希望能有一个像Fluent Reader 里那样的设置订**阅源默认打开方式**的功能
![image](https://github.com/user-attachments/assets/25e162b4-4f6d-4f1d-a7f4-8207e8bb51a2)

**Comment by hyoban** [comment]
You can use Actions for it.

![ScreenShot 2024-10-07 19 26 44](https://github.com/user-attachments/assets/b8938220-c85f-4cc3-bb97-a22f71e74be1)

**Comment by hyoban** [comment]
Reopen for considering other options

**Comment by looechao** [comment]
> You can use Actions for it.您可以使用操作来实现它。
> 
> ![ScreenShot 2024-10-07 19 26 44](https://private-user-images.githubusercontent.com/38493346/374149943-b8938220-c85f-4cc3-bb97-a22f71e74be1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDA5MDMsIm5iZiI6MTcyODMwMDYwMywicGF0aCI6Ii8zODQ5MzM0Ni8zNzQxNDk5NDMtYjg5MzgyMjAtYzg1Zi00Y2MzLWJiOTctYTIyZjcxZTc0YmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDExMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTYxNTA4NzJkODg1YzljOTAwN2VkZjVlNmI0NDkyMDhlZDVhMWY1ODZmM2ZhMTFjOGM3NDU3OTYwMGRlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4N9E0GriTNYQR3HOdIGw6ffYqZ7_kuv0SseTD_u1o8E)

学到了，感谢您的回复

**Comment by LincZero** [comment]
@hyoban Saving the configuration actually failed. Except for this option, other Settings can be saved successfully.

![图片](https://github.com/user-attachments/assets/21a48618-464b-427b-90fb-f812767181b9)

version: https://github.com/RSSNext/Follow/actions/runs/11396486345 [windows-latest](https://github.com/RSSNext/Follow/actions/runs/11396486345/artifacts/2072185853)

**Comment by hyoban** [comment]
Need to wait for the next server release version

**Comment by LincZero** [comment]
Thank you, I overlooked that this might require server support.
