### ISSUE TITLE
youtube或者bilibili视频不能直接播放，提示需要登录播报

### ISSUE THREAD

**Issue by ZWiley** [RSSNext/Follow#318]
### Clear and concise description of the problem

登录后可以播报

### Suggested solution

登录后可以播报

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
#284

**Comment by Leon666735** [comment]
This browser or app may not be secure.

Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by f4cker** [comment]
> This browser or app may not be secure.
> 
> Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

@DIYgod I'm still facing this `not secure` issue with `Beta Version(63E6B95)`, should I update to nightly version?

**Comment by xpetrichor** [comment]
> I this this issue has been fixed, if the problem still exists, please feel free to reopen it.

@DIYgod The latest version v0.1.2-beta.0 still has this issue. ![Image](https://github.com/user-attachments/assets/8b895a0d-9ca3-45c7-8a65-c4d4e406e959)
