### ISSUE TITLE
Is backend open source?

### ISSUE THREAD

**Issue by wanghanzhen** [RSSNext/follow#34]
I can't login when running locally and it seems that login relies on a backend server.

**Comment by DIYgod** [comment]
No, the backend is not open source, and the project cannot run locally yet. If there are any further changes, we will notify you promptly.

**Comment by SnowingFox** [comment]
> No, the backend is not open source, and the project cannot run locally yet. If there are any further changes, we will notify you promptly.

Do you have any open source plan?
