### ISSUE TITLE
头像修改保存不了

### ISSUE THREAD

**Issue by edutfree** [RSSNext/Follow#358]
### Describe the bug

web，个人资料 avatar 修改图像链接，提示保存成功，但是刷新后会变回未修改的默认值。

### Feed Info

nc

### App Type

Web

### Version

v0.0.1-alpha.10

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Should be fixed in https://github.com/RSSNext/Follow/commit/55b7868f2e2aa3c01468e1268e3436485491ee1a
