### ISSUE TITLE
Twitter/X 对帖子添加star后无法在starred列表中显示

### ISSUE THREAD

**Issue by Gordennn** [RSSNext/Follow#364]
### Describe the bug

Twitter/X 对帖子添加star后无法在starred列表中显示

### Feed Info

Twitter/X 对帖子添加star后无法在starred列表中显示

### App Type

Electron / App

### Version

0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It cannot reproduce. Please provide a reproduction to reopen the issue. Thanks.
