### ISSUE TITLE
Request to develop an Apple TV version of Follow

### ISSUE THREAD

**Issue by ltanme** [RSSNext/Follow#366]
### Clear and concise description of the problem

As a developer using this project I want an Apple TV version of Follow that only displays subscribed video creators and rejects the original recommended videos so that users can have a more focused viewing experience without being distracted by unwanted recommendations.

### Suggested solution

In the display module of the Apple TV version of Follow, we could implement a filtering mechanism that only shows the videos from subscribed creators and blocks the display of original recommended videos. This could be achieved by checking the source of each video and only allowing those from the subscribed creator list to be displayed.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
We have no plans to do this, community contributions are welcome
