### ISSUE TITLE
Use Tauri instead of electron

### ISSUE THREAD

**Issue by LeoMartinDev** [RSSNext/Follow#367]
### Clear and concise description of the problem

Electron apps are well known to be huge and laggy due to the embedded chromium engine.

### Suggested solution

Tauri allows to develop web apps as desktop applications but uses webviews available on each platform.
It allows smaller bundles and better performances thanks to its Rust backend.
With Tauri 2.0, you can now make mobile applications, which is something planned for Follow.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
For the sake of development experience and UI compatibility issues, webview compatibility for each platform is not optimistic.

With the wave of AI, even very small apps download huge ontology models, and most users are impervious to the size of an app.

Moreover, we have tried to optimize the size of the app.
