### ISSUE TITLE
follower过多无法展开

### ISSUE THREAD

**Issue by a186232641** [RSSNext/Follow#370]
### Clear and concise description of the problem

![1](https://raw.githubusercontent.com/a186232641/images/master/img/202409130718058.png)
例如：腾讯共享文档在线阅读人数过多时会用+4来显示

### Suggested solution

点击+3将关注的人展开为列表，方便查看关注者关注了哪些信息源

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tangbl2000** [comment]
你好，有邀请码吗
