### ISSUE TITLE
刷新后数量显示异常

### ISSUE THREAD

**Issue by leylatop** [RSSNext/Follow#371]
### Describe the bug

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/d906be12-6604-413c-80e8-85dbe463b53f">

刷新过后
1. 软件内与程序坞中数量显示不一致
2. feed内不显示未读数量

### Feed Info

null

### App Type

Electron / App

### Version

O.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by tangbl2000** [comment]
你好，有推荐码吗

**Comment by hyoban** [comment]
This issue should have been fixed. If it still exists, please feel free to open this issue again.
