### ISSUE TITLE
快捷键不能Refetch

### ISSUE THREAD

**Issue by laivn** [RSSNext/Follow#376]
### Describe the bug

快捷键不能Refetch，需要点Refetch或者reload(⌘+R)

https://github.com/user-attachments/assets/809481ea-9680-4a6d-a589-43166b5c6180

### Feed Info

ALL

### App Type

Electron / App

### Version

v0.0.1-alpha.10

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by tangbl2000** [comment]
你好，有邀请码吗

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
