### ISSUE TITLE
邀請碼花費Power數量不正確

### ISSUE THREAD

**Issue by SliverKeigo** [RSSNext/Follow#378]
### Describe the bug

![CleanShot 2024-09-13 at 15 36 20@2x](https://github.com/user-attachments/assets/1c4a0408-f535-454d-bb20-fb74544debc4)
如圖

### Feed Info

54806504248473600

### App Type

Web

### Version

v0.0.1-alpha.11

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [] I am willing to submit a PR to fix this issue
- [] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
https://x.com/follow_app_/status/1834476704053821484

**Comment by SliverKeigo** [comment]
> https://x.com/follow_app_/status/1834476704053821484

![CleanShot 2024-09-13 at 15 55 01](https://github.com/user-attachments/assets/00c07e4f-6c1d-4153-83b8-2c69ed784ec2)
现有的 $POWER 余额沒有 𝗫𝟭𝟬

**Comment by DIYgod** [comment]
Hi, this address has the correct balance in the chain: https://scan.rss3.io/address/0x92138dEdAa598343CcD42B5993db22dF1c569c89

Our refreshing API might be unstable, but the current record should have been updated. Could you check the display again?
