### ISSUE TITLE
Hovering over the entries being marked as read.

### ISSUE THREAD

**Issue by GeorgeLifinRell** [RSSNext/Follow#380]
### Describe the bug

Hovering over the entries of a particular field marks it as read. It should be like a click on that particular entry should mark it as read.

### Feed Info

###To reproduce the issue
1, Refresh for new entries or mark the existing entries as unread
2, Hover over the unread entries

### Reproduction Video

https://github.com/user-attachments/assets/f1636cf9-fa39-4719-ba07-6cf21698d2cc

### App Type

Web

### Version

 3050ad0

### Operating System

macOS

### Browser Info

Safari and Brave

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by ischanx** [comment]
it is a setting for user
![image](https://github.com/user-attachments/assets/9cd88035-8e02-4e7d-a067-846d31a20c02)
