### ISSUE TITLE
follow别人订阅的弹窗未展示，只看得到遮罩

### ISSUE THREAD

**Issue by FatDoge** [RSSNext/Follow#381]
### Describe the bug

follow别人订阅的弹窗未展示，只看得到遮罩

### Feed Info

https://app.follow.is/feeds/folder-%F0%9F%97%BB%20Forums/57372700845872128?view=0

### Reproduction Video

![img_v3_02em_b4791f9b-0bb3-45ae-96b1-1163a629b6dg](https://github.com/user-attachments/assets/14872cc1-6b02-4e09-82af-6fa9a91be8e4)

### App Type

Web

### Version

0.0.1-alpha.11

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by FatDoge** [comment]
重新安装了老版本，确认是新版本引入的。最后正常版本：`0.0.1 alpha.10`
问题存在web和客户端

**Comment by Innei** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/d81c2b5791fcf1284809b68dd68b4067581cdb44#diff-0019041978d81818065487595c7f0e2eed597f87767b8462f727d1c269b00601
