### ISSUE TITLE
相对路径 URL 的图片无法被正确加载

### ISSUE THREAD

**Issue by ArcticLampyrid** [RSSNext/Follow#382]
### Describe the bug

如题，相对路径 URL 的图片无法被正确加载

![image](https://github.com/user-attachments/assets/25d24d46-1c3f-4541-9cf2-653db34801c6)

它应该被修正为 `https://alampy.com/2024/08/08/deploy-tailscale-derp-on-nat-rcs/port-mapping.png`，但实际上浏览器尝试访问 `https://app.follow.is/2024/08/08/deploy-tailscale-derp-on-nat-rcs/port-mapping.png`

### Feed Info

https://app.follow.is/feeds/43158356160720896/44336187601855488?view=0

### App Type

Web

### Version

Early Access (3050AD0)

### Operating System

Linux

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Li-Jack** [comment]
图片无法正确加载
![CleanShot 2024-09-13 at 22 19 33@2x](https://github.com/user-attachments/assets/bbceb8d7-3f02-457c-832e-f3c2a976ff6b)
实际文章页面
![CleanShot 2024-09-13 at 22 20 35@2x](https://github.com/user-attachments/assets/b8bc825c-50d7-4969-bd33-1cb39d23c4f1)
---
网站RSS：
http://tubaozi.top/index.xml
