### ISSUE TITLE
Provide an option for private follow when importing opml

### ISSUE THREAD

**Issue by ttttmr** [RSSNext/Follow#384]
### Clear and concise description of the problem

Follow to a single RSS can optionally have private follow. Hope that such an option is also provided when importing opml.

### Suggested solution

Provide import options on the import side, such as: private follow. Other options can be added later.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
We encourage user connections to enhance the platform's quality and popularity, as this is a key feature and expectation of our application. Therefore, we regret to inform you that we will not implement the requested function. However, if you prefer, you can separately adjust the settings.
