### ISSUE TITLE
添加reddit频道

### ISSUE THREAD

**Issue by jack-wz** [RSSNext/Follow#386]
### Clear and concise description of the problem

能使用reddit频道的订阅内容

### Suggested solution

添加reddit频道的订阅内容

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Follow can indeed subscribe to [Reddit](https://www.reddit.com/r/linux/new/).

![Follow](https://github.com/user-attachments/assets/fc1bf457-b804-4508-a2aa-4bdfefd16a7f)

**Comment by DIYgod** [comment]
Duplicate of #346
