### ISSUE TITLE
集成增加notion

### ISSUE THREAD

**Issue by jack-wz** [RSSNext/Follow#387]
### Clear and concise description of the problem

集成增加notion功能

### Suggested solution

集成增加notion功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by 2019YKL** [comment]
+1 期待这个功能。

**Comment by muserole** [comment]
+1 期待这个功能。

**Comment by DIYgod** [comment]
Duplicate of #161
