### ISSUE TITLE
建议侧边栏可以浮动

### ISSUE THREAD

**Issue by laivn** [RSSNext/Follow#394]
### Clear and concise description of the problem

建议侧边栏可以设置浮动形式，类似arc浏览器的侧边栏样式。

### Suggested solution

![CleanShot 2024-09-14 at 16 07 22@2x](https://github.com/user-attachments/assets/9a1ff4fb-c7b0-45f5-a918-40e70ccbd390)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
`cmd+b`

**Comment by Innei** [comment]
![Uploading CleanShot 2024-09-14 at 4 .16.17@2x.png…]()
