### ISSUE TITLE
Cannot drag the window when maxmized.

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#420]
### Describe the bug

After maximizing Follow's window, the window cannot be moved by dragging the title bar.

### Feed Info

No

### App Type

Electron / App

### Version

Early Access [3050AD0]

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
This issue should have been resolved. If it can still be reproduced, feel free to reopen this issue.
