### ISSUE TITLE
Readability with garbled characters

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#421]
### Describe the bug

Some feeds will be garbled when loaded using Readability.

![image](https://github.com/user-attachments/assets/da832fce-a7f6-454a-8567-d60a9588e79c)

### Feed Info

https://blog.sciencenet.cn/rss.php?uid=63255

### App Type

Electron / App

### Version

Early Access [3050AD0]

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This should have been fixed

![ScreenShot 2024-10-22 16 01 56](https://github.com/user-attachments/assets/25cccc24-f76f-4cb9-bbe2-c22113bcfd6e)
