### ISSUE TITLE
请求支持“逆序浏览”功能

### ISSUE THREAD

**Issue by joyoner** [RSSNext/Follow#425]
### Clear and concise description of the problem

针对RSS阅读器提出"逆序浏览"的需求是有一定必要性的,主要有以下几点考虑:
满足特定用户需求。一些用户可能希望按时间顺序阅读内容,从最早的文章开始,逐步了解某个主题或作者的发展历程。
用于研究和归档目的。对于想要系统性研究某个领域发展历程的用户来说,按时间顺序浏览内容更有帮助。
提供更灵活的阅读体验。让用户可以根据自己的偏好选择正序或逆序浏览,增加阅读器的灵活性。
便于回顾历史内容。对于长期订阅的RSS源,逆序浏览可以方便用户回顾早期的重要内容。

### Suggested solution

功能描述:
在RSS阅读器界面添加一个"逆序浏览"的开关或选项。
开启逆序浏览后,文章列表按发布时间从早到晚排序,最早的文章显示在顶部。
保留现有的未读/已读标记功能,但顺序相反。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TCOTC** [comment]
同样需要，与 `滚动时标记为已读` 配合使用

**Comment by hujh818** [comment]
+1

**Comment by hyoban** [comment]
Duplicate of #276

Let's track this issue there.
