### ISSUE TITLE
Youtube 订阅无封面

### ISSUE THREAD

**Issue by qqyule** [RSSNext/Follow#427]
### Describe the bug

Youtube 订阅无封面
![image](https://github.com/user-attachments/assets/ae08955f-5fe9-4ef1-a7c3-41621094a1a3)

### Feed Info

https://www.youtube.com/feeds/videos.xml?channel_id=UC1QNflfH5JObGdMufYmJABw

### App Type

Electron / App

### Version

0.0.1-alpha.11

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
YouTube 官方提供的就是没有，推荐使用 RssHub 来订阅。
