### ISSUE TITLE
the information website cannot use rss

### ISSUE THREAD

**Issue by RayWoo** [RSSNext/Follow#429]
### Describe the bug

the information website cannot use rss

### Feed Info

https://www.theinformation.com/subscriber_feed

https://theinformation.zendesk.com/hc/en-us/articles/218351328-RSS-feeds-Instapaper-and-Pocket

### App Type

Web

### Version

0.0.1-alpha.11

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
We currently do not support RSS addresses that require authentication.

<img width="577" alt="image" src="https://github.com/user-attachments/assets/359b0f57-64d2-4bf5-a299-73ca682b6025">
