### ISSUE TITLE
(arch)linux版本更新后无法登陆

### ISSUE THREAD

**Issue by a15355447898a** [RSSNext/Follow#434]
### Describe the bug

更新后提示需要登陆,然后登陆一直登陆不上 

浏览器转跳follow后,follow还是显示需要登陆

上一个版本并没有这个问题

### Feed Info

并不需要

### Reproduction Video

https://github.com/user-attachments/assets/61991f7e-87da-4ec8-a64e-a8e849ed0c93

### App Type

Electron / App

### Version

0.0.1_alpha.11-1

### Operating System

Linux

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This should be fixed in https://github.com/RSSNext/Follow/commit/a281f58a811213d933585280238fec4088ad7749, you can try https://github.com/RSSNext/Follow/actions/runs/10919920072

**Comment by a15355447898a** [comment]
I've tried the latest version of follow, but it still has issues

![image](https://github.com/user-attachments/assets/39569d53-3418-4aee-ace9-ff395c30ed93)

Uninstalling and then reinstalling did not help
