### ISSUE TITLE
[i18n]: added zh-hk language support

### ISSUE THREAD

**Issue by zhenp** [RSSNext/Follow#435]
### Type of i18n contribution

New language support

### Language

zh-hk

### Description

added zh-hk language support

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhenp** [comment]
{
  "about.changelog": "更新日誌",
  "about.feedbackInfo": "{{appName}} ({{commitSha}}) 正處於開發早期階段。如果您有任何反饋或建議，請隨時在我們的 GitHub 上 <OpenIssueLink>提交問題</OpenIssueLink> <ExternalLinkIcon />。",
  "about.iconLibrary": "所使用的圖標庫版權由 <IconLibraryLink /> <ExternalLinkIcon /> 所有，不得重新分發。",
  "about.licenseInfo": "{{appName}} 是且將永遠是一個免費且開源的項目。它遵循 {{license}} 授權。",
  "about.sidebar_title": "關於",
  "about.socialMedia": "社群媒體",
  "actions.actionName": "操作 {{number}}",
  "actions.action_card.add": "新增",
  "actions.action_card.all": "全部",
  "actions.action_card.block_rules": "封鎖規則",
  "actions.action_card.custom_filters": "自訂過濾條件",
  "actions.action_card.enable_readability": "啟用閱讀模式",
  "actions.action_card.entry_options.all": "全部",
  "actions.action_card.entry_options.author": "作者",
  "actions.action_card.entry_options.content": "內容",
  "actions.action_card.entry_options.order": "順序",
  "actions.action_card.entry_options.title": "標題",
  "actions.action_card.entry_options.url": "網址",
  "actions.action_card.feed_options.category": "類別",
  "actions.action_card.feed_options.feed_url": "摘要 URL",
  "actions.action_card.feed_options.site_url": "網站 URL",
  "actions.action_card.feed_options.title": "標題",
  "actions.action_card.feed_options.view": "View",
  "actions.action_card.field": "欄位",
  "actions.action_card.from": "從",
  "actions.action_card.generate_summary": "使用 AI 生成摘要",
  "actions.action_card.name": "名稱",
  "actions.action_card.operation_options.contains": "包含",
  "actions.action_card.operation_options.does_not_contain": "不包含",
  "actions.action_card.operation_options.is_equal_to": "等於",
  "actions.action_card.operation_options.is_greater_than": "大於",
  "actions.action_card.operation_options.is_less_than": "小於",
  "actions.action_card.operation_options.is_not_equal_to": "不等於",
  "actions.action_card.operation_options.matches_regex": "匹配正則表達式",
  "actions.action_card.operator": "運算符",
  "actions.action_card.rewrite_rules": "重寫規則",
  "actions.action_card.then_do": "然後執行…",
  "actions.action_card.to": "到",
  "actions.action_card.translate_into": "翻譯成",
  "actions.action_card.value": "值",
  "actions.action_card.when_feeds_match": "當摘要匹配時…",
  "actions.newRule": "新增規則",
  "actions.save": "儲存",
  "actions.saveSuccess": "🎉 操作已儲存。",
  "actions.sidebar_title": "操作",
  "actions.title": "操作",
  "appearance.code_highlight_theme": "程式碼高亮主題",
  "appearance.content": "內容",
  "appearance.content_font": "內容字體",
  "appearance.custom_font": "自定義字體",
  "appearance.fonts": "字體",
  "appearance.general": "一般",
  "appearance.guess_code_language.description": "使用模型來推斷未標記程式碼區塊的主要程式語言",
  "appearance.guess_code_language.label": "推測程式碼語言",
  "appearance.misc": "Misc",
  "appearance.modal_overlay.description": "顯示模態覆蓋層",
  "appearance.modal_overlay.label": "顯示模態覆蓋層",
  "appearance.opaque_sidebars.label": "不透明側邊欄",
  "appearance.reader_render_inline_style.description": "允許渲染原始 HTML 的行內樣式。",
  "appearance.reader_render_inline_style.label": "渲染行內樣式",
  "appearance.reduce_motion.description": "減少元素的動畫效果以提升效能並降低能耗。",
  "appearance.reduce_motion.label": "減少動畫",
  "appearance.save": "儲存",
  "appearance.show_dock_badge.label": "顯示為 Dock 徽章",
  "appearance.sidebar_show_unread_count.label": "在側邊欄中顯示",
  "appearance.sidebar_title": "外觀",
  "appearance.text_size": "文字大小",
  "appearance.theme.dark": "深色",
  "appearance.theme.label": "主題",
  "appearance.theme.light": "淺色",
  "appearance.theme.system": "系統",
  "appearance.title": "外觀",
  "appearance.ui_font": "介面字體",
  "appearance.unread_count": "未讀計數",
  "general.app": "App",
  "general.data_persist.description": "本地儲存數據以啟用離線訪問和本地搜尋。",
  "general.data_persist.label": "離線時保持資料",
  "general.group_by_date.description": "按日期分組項目",
  "general.group_by_date.label": "按日期分組",
  "general.language": "語言",
  "general.launch_at_login": "登入時啟動",
  "general.mark_as_read.hover.description": "滑鼠懸停時自動將條目標記為已讀。",
  "general.mark_as_read.hover.label": "滑鼠懸停時標記為已讀",
  "general.mark_as_read.render.description": "當單層級條目（例如社群媒體貼文、圖片、影片瀏覽）進入視圖時自動標記為已讀。",
  "general.mark_as_read.render.label": "顯示時標記為已讀",
  "general.mark_as_read.scroll.description": "當條目捲動離開視圖時自動標記為已讀。",
  "general.mark_as_read.scroll.label": "滾動時標記為已讀",
  "general.privacy_data": "隱私與數據",
  "general.rebuild_database.button": "重新構建",
  "general.rebuild_database.description": "如果您遇到渲染問題，重新構建資料庫可能可以解決。",
  "general.rebuild_database.label": "重新構建資料庫",
  "general.rebuild_database.title": "重新構建資料庫",
  "general.rebuild_database.warning.line1": "重新構建資料庫將會清除您所有的本地資料。",
  "general.rebuild_database.warning.line2": "您確定要繼續嗎？",
  "general.send_anonymous_data.description": "選擇傳送匿名遙測數據，您將幫助改善 Follow 的整體使用體驗。",
  "general.send_anonymous_data.label": "傳送匿名資料",
  "general.show_unread_on_launch.description": "啟動時顯示未讀內容",
  "general.show_unread_on_launch.label": "啟動時顯示未讀內容",
  "general.sidebar_title": "一般",
  "general.timeline": "時間軸",
  "general.unread": "未讀",
  "general.voices": "聲音",
  "integration.eagle.enable.description": "顯示\"將媒體保存到 Eagle\"按鈕（如果可用）。",
  "integration.eagle.enable.label": "啟用",
  "integration.eagle.title": "Eagle",
  "integration.instapaper.enable.description": "顯示\"保存到 Instapaper\"按钮（如果可用）。",
  "integration.instapaper.enable.label": "啟用",
  "integration.instapaper.password.label": "密碼",
  "integration.instapaper.title": "Instapaper",
  "integration.instapaper.username.label": "Instapaper 使用者",
  "integration.readwise.enable.description": "顯示\"保存到 Readwise\"按钮（如果可用）。",
  "integration.readwise.enable.label": "啟用",
  "integration.readwise.title": "Readwise",
  "integration.readwise.token.description": "您可以在這裡獲取它",
  "integration.readwise.token.label": "Readwise 存取令牌",
  "integration.sidebar_title": "整合功能",
  "integration.tip": "提示：您的敏感資料儲存於本地，不會上傳到伺服器。",
  "integration.title": "整合功能",
  "invitation.activate": "啟用",
  "invitation.codeOptions.betaUser": "1. 尋找邀請您的測試版用戶。",
  "invitation.codeOptions.discord": "2. 加入我们的 Discord 伺服器，偶而獲得贈品。",
  "invitation.codeOptions.xAccount": "3.關注我們的 X 帳號，不定期有贈品。",
  "invitation.confirmModal.cancel": "取消",
  "invitation.confirmModal.confirm": "您想繼續嗎？",
  "invitation.confirmModal.continue": "繼續",
  "invitation.confirmModal.message": "產生邀請碼將會花費您 {{INVITATION_PRICE}} <PowerIcon>Power</PowerIcon>。",
  "invitation.confirmModal.title": "確認",
  "invitation.earlyAccess": "Follow 目前處於 <strong>早期開發</strong>狀態，需要邀請碼才能使用。",
  "invitation.earlyAccessMessage": "😰 抱歉，關注目前處於搶先體驗階段，需要邀請碼才能使用。",
  "invitation.generateButton": "產生邀請碼",
  "invitation.generateCost": "您可以花費 {{INVITATION_PRICE}} <PowerIcon>Power</PowerIcon> 為您的朋友產生邀請碼。",
  "invitation.getCodeMessage": "您可以通過以下方式獲取邀請碼：",
  "invitation.newInvitationSuccess": "🎉 邀請碼已產生, 邀請碼已複製",
  "invitation.noInvitations": "沒有邀請",
  "invitation.notUsed": "為使用",
  "invitation.sidebar_title": "邀請",
  "invitation.tableHeaders.code": "代碼",
  "invitation.tableHeaders.creationTime": "建立時間",
  "invitation.tableHeaders.usedBy": "使用者",
  "invitation.title": "邀請碼",
  "profile.avatar.label": "大頭貼",
  "profile.handle.description": "您的唯一識別碼",
  "profile.handle.label": "Handle",
  "profile.name.description": "您的公開顯示名稱。",
  "profile.name.label": "顯示名稱",
  "profile.sidebar_title": "個人資料",
  "profile.submit": "送出",
  "profile.title": "配置文件設定",
  "profile.updateSuccess": "個人資料已更新。",
  "titles.about": "關於",
  "titles.actions": "指令",
  "titles.appearance": "外觀",
  "titles.general": "一般",
  "titles.integration": "整合",
  "titles.invitations": "邀請",
  "titles.power": "Power",
  "titles.profile": "個人資料",
  "titles.shortcuts": "快捷鍵",
  "wallet.address.title": "您的地址",
  "wallet.balance.title": "您的餘額",
  "wallet.balance.withdrawable": "可提取",
  "wallet.balance.withdrawableTooltip": "可提取的 Power 包括你收到的贊助和充值的 Power。",
  "wallet.claim.button.claim": "領取每日 Power",
  "wallet.claim.button.claimed": "今日已領取",
  "wallet.claim.tooltip.alreadyClaimed": "您今天已經領取過了。",
  "wallet.claim.tooltip.canClaim": "立即領取您的 {{amount}} 每日 Power！",
  "wallet.create.button": "建立錢包",
  "wallet.create.description": "建立一個免費錢包以接收 <PowerIcon /> <strong>Power</strong>，可用於獎勵創作者，也可以因您的內容貢獻而獲得獎勵。",
  "wallet.power.dailyClaim": "您每天可以領取 {{amount}} 個免費 Power，可用於在 Follow 上贊助 RSS 項目。",
  "wallet.power.description": "Power 是 {{blockchainName}} 區塊鏈上的一種 <Link>ERC-20 代幣</Link>。",
  "wallet.sidebar_title": "Power",
  "wallet.transactions.amount": "數量",
  "wallet.transactions.date": "日期",
  "wallet.transactions.from": "發送至",
  "wallet.transactions.noTransactions": "無交易紀錄",
  "wallet.transactions.title": "交易紀錄",
  "wallet.transactions.to": "接收自",
  "wallet.transactions.tx": "交易",
  "wallet.transactions.type": "類型",
  "wallet.transactions.types.burn": "burn",
  "wallet.transactions.types.mint": "mint",
  "wallet.transactions.types.purchase": "purchase",
  "wallet.transactions.types.tip": "tip",
  "wallet.transactions.types.withdraw": "withdraw",
  "wallet.transactions.you": "您",
  "wallet.withdraw.addressLabel": "您的以太坊地址",
  "wallet.withdraw.amountLabel": "數量",
  "wallet.withdraw.availableBalance": "您的錢包中有 <Balance></Balance> 可提取 Power。",
  "wallet.withdraw.button": "提取",
  "wallet.withdraw.error": "提取失败：{{error}}",
  "wallet.withdraw.modalTitle": "提取 Power",
  "wallet.withdraw.submitButton": "送出",
  "wallet.withdraw.success": "提取成功！"
}

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
