### ISSUE TITLE
Error in fetching feed: rsshub://smzdm/keyword/%E5%86%85%E5%AD%98

### ISSUE THREAD

**Issue by fanpest** [RSSNext/Follow#436]
### Info:

Feed URL:
```
rsshub://smzdm/keyword/%E5%86%85%E5%AD%98
```

Error:
```
[GET] "https://api.follow.is/feeds?url=rsshub%3A%2F%2Fsmzdm%2Fkeyword%2F%25E5%2586%2585%25E5%25AD%2598": <no response> Failed to fetch
```

### Environment

**App Version**: 0.0.1-alpha.11
**OS**: Linux
**User Agent**: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

**Comment by DIYgod** [comment]
It might have been the network instability during that time, but it is accessible now.

<img width="709" alt="image" src="https://github.com/user-attachments/assets/48f870e0-4593-4edf-b345-03863fa13988">
