### ISSUE TITLE
The Wall Street Journal Chinese version RSS subscription failed

### ISSUE THREAD

**Issue by onlylhf** [RSSNext/Follow#437]
### Describe the bug

<img width="580" alt="image" src="https://github.com/user-attachments/assets/f7925658-8267-4efd-91ab-3c3d0f7185b8">

### Feed Info

rss: https://cn.wsj.com/zh-hans/rss

### App Type

Web

### Version

v0.0.1-alpha.11

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I cannot access this RSS address.

<img width="942" alt="image" src="https://github.com/user-attachments/assets/6ae2d910-ccf7-4230-9def-168ffcd30574">

**Comment by DIYgod** [comment]
I cannot access this RSS address.

<img width="898" alt="image" src="https://github.com/user-attachments/assets/fe83f7d4-6c46-4d5f-a57c-cab1c17d85d4">
