### ISSUE TITLE
更新rss ，再次订阅 显示title 和链接还是之前的内容

### ISSUE THREAD

**Issue by Carrie999** [RSSNext/Follow#440]
### Describe the bug

https://blog-rss.vercel.app/rss 这是我的blog rss ，然后订阅了自己的 rss，有问题又更改了title和链接，但是还是显示第一次的title和链接，
![image](https://github.com/user-attachments/assets/aff29737-5007-431c-be01-347d33d12059)

### Feed Info

https://blog-rss.vercel.app/rss

### App Type

Web

### Version

0.0.1-a12

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Carrie999** [comment]
https://app.follow.is/feed/58440410033243136?view=0  web is not right

**Comment by DIYgod** [comment]
The update will occur during the next refresh; it won't happen immediately. I see it has already been updated.
