### ISSUE TITLE
[UI/UX] 09.16 Optimize Summary

### ISSUE THREAD

**Issue by Innei** [RSSNext/Follow#442]
Accessibility:

- The interactivity of the current elements is unclear. This is reflected in: Buttons or Links not displaying the pointer as a pointer in certain scenarios, and there is no UI feedback when the elements are interacted with.

- For Buttons: the cursor is not a pointer, but the element should have interactive feedback.

- For Links: the cursor can be default, but it should be a pointer in the `_blank` scenario. It should also be accompanied by interactive feedback for the element.

- Accessibility settings: options can be added (e.g., linear), whether the cursor defaults to pointer or default.

- Common forms of feedback for interactive elements include: content highlighting, button sinking, reduced transparency of content, adding underlines, etc.

\* The above design scenarios: User Profile on external pages, Feed detail.

UI Disconnection:

- In the Feed detail of external pages, the UI/UX format is disconnected from the interaction of other pages with the same format, such as the user profile.

This is manifested in the inconsistent application of cursor styles. The interactive behavior of list items is inconsistent.

---

无障碍：
- 目前元素的可交互性不明确。表现在：Button 或者 Link 在部分场景下指针没有展示为 pointer，其次元素在被交互时没有 UI 反馈。
  - Button 时：指针不为 pointer，但是应当有元素的可交互反馈
  - Link 时：指针可以为 default，但是需要注意在 `_blank` 场景下应该为 pointer。同时应该伴随有元素的可交互反馈
  - 无障碍设定：可增加选项（比如 linear），cursor 默认使用 pointer 还是 default

- 常见的可交互元素反馈展现形式为：内容高亮，按钮下沉，内容减少透明，增加下划线等等

\* 上述设计场景：外部页面的 User Profile, Feed detail

UI 割裂：

- 外部页面的 Feed detail, UI/UX 的形式与相同形式其他页面，如 user profile 的交互割裂。

其表现为，cursor 的样式应用不统一。list item 的交互行为不一致。

![76111726488233_ pic](https://github.com/user-attachments/assets/408adbd9-2b95-4bc2-9d47-0472a74d1ac3)

![76011726488121_ pic](https://github.com/user-attachments/assets/6625154c-3e08-48ea-bf7a-aa9304fcd68d)

Reference Interaction: Linear
![CleanShot 2024-09-16 at 8  16 35@2x](https://github.com/user-attachments/assets/fc0389f3-2fe5-489c-937c-1ef3706f6695)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
