### ISSUE TITLE
win10 点击左下角升级，软件被删除，但是新的没有安装

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#448]
### Describe the bug

win10 点击左下角出现的升级，关闭软件，点击软件图标，显示捷径找不到，找不到软件，旧的被删掉了，新的没有安装

在 AppData\Local\Follow\pending 找到安装档

### Feed Info

no

### App Type

Electron / App

### Version

newest

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by huanfe1** [comment]
同样情况

**Comment by ztkuaikuai** [comment]
+1🥺

**Comment by jerryc127** [comment]
@DIYgod @Innei 
能優先解決這個問題麽

剛看到有更新了，點擊左下角的升級，又把軟件卸載了，新的又沒有安裝。
還是得找安裝包安裝

**Comment by xiaole3349** [comment]
+1

**Comment by DIYgod** [comment]
I have not been able to reproduce this issue, but I have [tried to fix it](https://github.com/RSSNext/Follow/commit/965544beef41f9c6549c64cd4f53e1a3935259ad). Will this problem still occur in the latest version?

**Comment by Innei** [comment]
Need more information, if there are any questions, we can reopen this issue
