### ISSUE TITLE
Window maximize issue after update - unable to restore.

### ISSUE THREAD

**Issue by cyz-lst** [RSSNext/Follow#449]
### Describe the bug

 After the latest Windows update, maximized windows cannot be restored to their original size.

### Feed Info

![image](https://github.com/user-attachments/assets/aa018130-2c3a-478c-8e12-66d2f9140115)

### App Type

Electron / App

### Version

v0.0.1-alpha.13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
This issue should have been resolved. If it can still be reproduced, feel free to reopen this issue.
