### ISSUE TITLE
Social media don't display fully

### ISSUE THREAD

**Issue by Lyunvy** [RSSNext/Follow#457]
### Describe the bug

When social media content is too long, the content does not display completely.

### Feed Info

https://rsshub.app/telegram/channel/XiaoZhangDuBao
https://www.solidot.org/index.rss
...

### Reproduction Video

https://rsshub.app/telegram/channel/XiaoZhangDuBao
![image](https://github.com/user-attachments/assets/8ae610b4-0409-4b45-bc33-a84c88eae07c)
![image](https://github.com/user-attachments/assets/51bf4aa9-0ed9-4bda-855d-ebbe5fed380a)

https://www.solidot.org/index.rss
![image](https://github.com/user-attachments/assets/3433426e-2c1f-4bab-98ff-64306dc7bfb6)
![image](https://github.com/user-attachments/assets/3b042a0b-bac7-496f-9664-4e86de4fa2de)

### App Type

Web

### Version

预览版本(12BC55C)

### Operating System

Windows 11

### Browser Info

Chromium 118.0.5993.159

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is by design

https://github.com/RSSNext/Follow/blob/6a5676684920f06f391b35c858c872ab2a4036fd/src/renderer/src/modules/entry-column/Items/social-media-item.tsx#L58
