### ISSUE TITLE
无法导入 YouTube 频道

### ISSUE THREAD

**Issue by Ivor-NCUT** [RSSNext/Follow#464]
### Describe the bug

<img width="608" alt="image" src="https://github.com/user-attachments/assets/019f22fa-145a-4948-bf22-aab9b56e71c2">

<img width="592" alt="image" src="https://github.com/user-attachments/assets/288a9e72-8d9b-4839-a6a7-556a0c7a3f57">

### Feed Info

https://youtu.be/aF--PmtqLWQ?si=O5D26YZXuBRz1bUh

### App Type

Web

### Version

Follow-0.0.1-alpha.12-macos-universal

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
@20VC
