### ISSUE TITLE
The custom RSS URL seems cached.

### ISSUE THREAD

**Issue by unimu-cic** [RSSNext/Follow#467]
### Describe the bug

Deployed a custom RSS service, but it went down about 6 days ago, Follow shows `Error since 6 days ago, [GET] "https://custom-rss-service.com": 502 Bad Gateway`, but then I fixed the custom service error, Follow can not update the latest result.

<img width="608" alt="image" src="https://github.com/user-attachments/assets/923fe7da-be5d-4773-8ef6-fbd6a9dc0100">

### Feed Info

https://we-rss-hub.zeabur.app/feeds/MP_WXS_3907632262.atom

### App Type

Electron / App

### Version

0.0.1-alpha.13

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Works for me. Can you try to unfollow and follow again?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6ada4438-7285-4c01-bb65-c8fda5ded451">

If the problem persists, please feel free to open this issue again
