### ISSUE TITLE
Show All/Show Unread doesn't work

### ISSUE THREAD

**Issue by KenMercusLai** [RSSNext/Follow#468]
### Describe the bug

The Show All/Show Unread doesn't change the view as expected.

As shown in the screen recording, all items are read except for one in the Youtube folder. Clicking Show All/Show Unread button doesn't change the view as expected.

### Feed Info

Any

### Reproduction Video

https://github.com/user-attachments/assets/22eb4f8d-a177-4a96-86c9-1d730652b6dc

### App Type

Electron / App

### Version

0.0.1-alpha.13

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
This issue should have been resolved. If it can still be reproduced, feel free to reopen this issue.
