### ISSUE TITLE
Missing referer header in feed image request causing load error of Anti-hotlinking rss feed's image

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#469]
### Describe the bug

The Referer header is not set in the image loading request. This causes some RSS feeds that are protected against hotlinking to be unable to display images normally. For example, the very famous sspai

![image](https://github.com/user-attachments/assets/3c32b097-7735-461e-906e-daa04325b868)

### Feed Info

rsshub://sspai/index

### App Type

Electron / App

### Version

0.0.1-alpha.13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
