### ISSUE TITLE
feat: user profile page should display userId property

### ISSUE THREAD

**Issue by TecSong** [RSSNext/Follow#480]
### Clear and concise description of the problem

On the search page, we could use userId to search for users, but on myself or on another profile page, I can't see my ID. Only when I share my profile, I see my ID in the url; it doesn't make sense.
<img width="554" alt="image" src="https://github.com/user-attachments/assets/5cdf06d5-9fe6-4e37-a97d-1a35b89de50c">
<img width="697" alt="image" src="https://github.com/user-attachments/assets/67d33833-d329-4760-a910-bc06a11edc43">

### Suggested solution

show ID on all user profile page

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Some users have not set their handle, so they are not displayed. Now the follow button has been added to the user page, which should solve this problem.
