### ISSUE TITLE
[API][atom] unrelated item

### ISSUE THREAD

**Issue by xc2** [RSSNext/Follow#492]
### Describe the bug

I was importing an atom link and found an unrelated item being imported

### URL

```
https://github.com/RSSNext/Follow/releases.atom
```

### Unexpected item

`data[1]` is nothing related to the feed.

```
{
  "feed": {
    "title": "GitHub - User Activities"
  },
  "docs": "https://docs.rsshub.app/routes/programming"
}
```

### App Type

Web

### Version

0.0.1-alpha.13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Can not reproduce it now, feel free to reopen this issue if you still have questions.
