### ISSUE TITLE
[API][atom] invalid feed description

### ISSUE THREAD

**Issue by xc2** [RSSNext/Follow#493]
### Describe the bug

I was importing an atom URL and found the description in the result is not string but `{"$":{"type":"text"}}` which crashed the discover page

<img width="718" alt="image" src="https://github.com/user-attachments/assets/6ae79918-5fd6-470f-a68a-7e7d02e9229d">

### Feed Info

https://www.xuezhao.space/feed/atom/

### Unexpected field

`data[0].feed.description` is

```
{
  "$": {
    "type": "text"
  }
}
```

### App Type

Web

### Version

0.0.1-alpha.13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is the same as https://github.com/RSSNext/Follow/issues/690. It should have been fixed.
