### ISSUE TITLE
使用google帐号或者github帐号登录，都提示我使用初始帐号登录

### ISSUE THREAD

**Issue by Z46I4W5476SJA** [RSSNext/Follow#496]
### Describe the bug

2024-09-19 早上   我一次注册    出现了服务器问题  导致我无法使用谷歌登录  然后我又顺手点了github登录     然后我谷歌或者github使用的都是谷歌邮箱 chouxiang222@gmail.com   后来服务器正常了     我登录时候   提示我To confirm your identity, sign in with the same account you used originally.  希望帮忙解决

### Feed Info

https://api.follow.is/auth/signin?error=OAuthAccountNotLinked

### App Type

Web

### Version

1.0.0

### Operating System

macOS

### Browser Info

chrome  版本 128.0.6613.138（正式版本） (arm64)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
尝试清除浏览器页面数据或者使用无痕模式试试？

**Comment by Z46I4W5476SJA** [comment]
> 尝试清除浏览器页面数据或者使用无痕模式试试？

尝试了清理缓存、无痕模式、换梯子节点、换了三台电脑  依然存在这个问题   很奇怪   感觉是我在服务器异常的时间去注册  然后导致的这个异常的问题

**Comment by Innei** [comment]
> 尝试清除浏览器页面数据或者使用无痕模式试试？

OAuthAccountNotLinked: If the email on the account is already linked, but not with this OAuth account

**Comment by Innei** [comment]
https://github.com/nextauthjs/next-auth/discussions/2808

**Comment by Innei** [comment]
![CleanShot 2024-09-19 at 12  35 44@2x](https://github.com/user-attachments/assets/5fc6c5ff-103d-4102-ba95-55c895230337)

**Comment by Z46I4W5476SJA** [comment]
> ![CleanShot 2024-09-19 at 12  35 44@2x](https://private-user-images.githubusercontent.com/41265413/368842484-5fc6c5ff-103d-4102-ba95-55c895230337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjcwNjksIm5iZiI6MTcyNjcyNjc2OSwicGF0aCI6Ii80MTI2NTQxMy8zNjg4NDI0ODQtNWZjNmM1ZmYtMTAzZC00MTAyLWJhOTUtNTVjODk1MjMwMzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGUxZWZhMzc0ZjAxMzc3ZDBlYTM2MDdhZTMzMTZmYmYxNDBiMWRiYmExNmVmYzFkZTY1MzU5ODJjYzJhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kDaWI9-i4y5sC4r3n1EeV1AzRH3PFDJq8C3fqDlr1gE)

你好  你说的这些我看了   这里面说道了不能同时使用两个相同帐号去认证   但是我现在已经这么操作了 并且我也断开了github的认证    去使用谷歌帐号登录  依然提示我这个   所以我现在如何去做呢？非常感谢

**Comment by Innei** [comment]
I had this problem once, but I was able to solve it by manipulating the database directly and deleting another email account.

It's not the right way, but I don't know what else to do other than manipulate the database directly.

@DIYgod Maybe there's another way?

**Comment by Z46I4W5476SJA** [comment]
> I had this problem once, but I was able to solve it by manipulating the database directly and deleting another email account.
> 
> It's not the right way, but I don't know what else to do other than manipulate the database directly.
> 
> @DIYgod Maybe there's another way?

非常感谢你的帮忙    我直接把我的github绑定的邮箱改了一个  然后可以正常认证登录了  但是我的谷歌邮箱应该是永远没办法使用了   除非删除数据库这条数据

**Comment by incubator4** [comment]
> 


> > I had this problem once, but I was able to solve it by manipulating the database directly and deleting another email account.
> > It's not the right way, but I don't know what else to do other than manipulate the database directly.
> > @DIYgod Maybe there's another way?
> 
> 非常感谢你的帮忙 我直接把我的github绑定的邮箱改了一个 然后可以正常认证登录了 但是我的谷歌邮箱应该是永远没办法使用了 除非删除数据库这条数据

`chouxiang222@gmail.com` 已经清掉了

**Comment by Z46I4W5476SJA** [comment]
> > 
> 
> > > I had this problem once, but I was able to solve it by manipulating the database directly and deleting another email account.
> > > It's not the right way, but I don't know what else to do other than manipulate the database directly.
> > > @DIYgod Maybe there's another way?
> > 
> > 
> > 非常感谢你的帮忙 我直接把我的github绑定的邮箱改了一个 然后可以正常认证登录了 但是我的谷歌邮箱应该是永远没办法使用了 除非删除数据库这条数据
> 
> `chouxiang222@gmail.com` email 的这个 user 我给你清掉了

非常感谢🙏  已经可以了   果然还是得数据库删了才能解决

**Comment by okxaas** [comment]
okxaas@gmail.com 可以帮我清除一下吗，我遇到了同样的问题

**Comment by ChinaMoli** [comment]
@incubator4 你好，我也遇到了相同问题，可以帮我处理一下吗？[admin@wums.cn](mailto:admin@wums.cn)
![image](https://github.com/user-attachments/assets/0ead402c-c3ee-4153-bb92-0fcc6f60b64e)

**Comment by DIYgod** [comment]
Once this issue arises, simply switch to the correct login provider, no action is needed on our server.

In the next version, I will enable `allowDangerousEmailAccountLinking`. Since both Google and GitHub require email verification, there are no security concerns.
