### ISSUE TITLE
添加订阅地址出错

### ISSUE THREAD

**Issue by Lianglw** [RSSNext/Follow#497]
### Describe the bug

![image](https://github.com/user-attachments/assets/3ca530e2-535e-4b70-bdb9-c4bdb743b205)

### Feed Info

添加订阅地址出错

### App Type

Electron / App

### Version

预览版本(12BC55C)

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
The URL in your screenshot is not right
