### ISSUE TITLE
Feed date is not displayed correctly in some RSS sites on the `follow` side

### ISSUE THREAD

**Issue by const7** [RSSNext/Follow#509]
### Describe the bug

I imported feeds from an OPML file a few days ago. However, I noticed that some feeds display the import date instead of the correct date from the RSS data (including inside the specific feed detail, like the second screenshot), while others show the date correctly.

Incorrect case example:
![image](https://github.com/user-attachments/assets/ea1f2e20-9046-4149-aba5-55ba49b17a34)
![image](https://github.com/user-attachments/assets/7b3cef5b-361e-488b-9ed3-dd6c57188c8e)

## Incorrect case examples

- https://www.cell.com/trends/cognitive-sciences/inpress.rss
- https://www.nature.com/nrpsychol.rss
- https://www.pnas.org/action/showFeed?type=searchTopic&taxonomyCode=topic&tagCodeOr=psych-soc&tagCodeOr=psych-bio

### App Type

Web

### Version

v0.0.1-alpha.13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It should work now. Can you try again?

![ScreenShot 2024-09-20 16 47 27](https://github.com/user-attachments/assets/a3469018-7d1c-4fc1-ad3d-32135e473504)

**Comment by hyoban** [comment]
Will be fixed in the next version.
