### ISSUE TITLE
Render error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by curatings** [RSSNext/Follow#519]
### Describe the bug

`Render error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules`
最近好几个订阅都会出现这个报错信息

### Feed Info

rsshub://xiaoyuzhou/podcast/5e280faa418a84a0461f9bfe

### App Type

Web

### Version

v0.0.1-alpha.13

### Operating System

macOS

### Browser Info

Chrome Version 103.0.5060.134 (Official Build) (x86_64)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Unable to reproduce, stop using your chrome plugin to troubleshoot
