### ISSUE TITLE
添加小红书feed到 社交媒体 ，无限拉取

### ISSUE THREAD

**Issue by hype1type** [RSSNext/Follow#529]
### Describe the bug

添加该feed后，会一直拉取最新内容，如视频所示

### Feed Info

https://rsshub.app/xiaohongshu/user/593032945e87e77791e03696/notes

### App Type

Electron / App

### Version

0.0.1 a13

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
经过排查，这是 RSSHub 小红书路由最近的 guid 获取方式变化导致的重复项进入数据库，不是无限拉取

https://github.com/DIYgod/RSSHub/commits/master/lib/routes/xiaohongshu/user.ts
