### ISSUE TITLE
User not fund, but i can't update handle field using this value

### ISSUE THREAD

**Issue by stuchilde** [RSSNext/Follow#530]
### Describe the bug

![image](https://github.com/user-attachments/assets/aa9ce12b-6438-4dd2-8f46-b7fdc23076b3)

![image](https://github.com/user-attachments/assets/036ecfb9-445c-4b10-b219-98755773869a)

### Feed Info

unrelated

### App Type

Electron / App

### Version

0.0.1-alpha.13

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
handle is not id

**Comment by stuchilde** [comment]
how to set id field?

**Comment by stuchilde** [comment]
<img width="172" alt="image" src="https://github.com/user-attachments/assets/700ea37b-84ad-49db-921f-6014fc91fd06">

Amazing. Why update evan succeed today? @hyoban
