### ISSUE TITLE
知乎专栏无法follow

### ISSUE THREAD

**Issue by laughing0622** [RSSNext/Follow#540]
### Describe the bug

知乎专栏无法follow

### Feed Info

知乎专栏无法follow

### App Type

Electron / App

### Version

0.0.1-alpha13

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please provide Feed Info
