### ISSUE TITLE
Invitation code redemption failure

### ISSUE THREAD

**Issue by resetsix** [RSSNext/Follow#551]
### Describe the bug

Problem with Power balance redemption invitation code: The balance was deducted but no invitation code was generated

### Feed Info

I can't find the feed id

### Reproduction Video

<img width="582" alt="图片" src="https://github.com/user-attachments/assets/c50e818c-c8df-41ae-8e82-b7fca0a5085c">

### App Type

Electron / App

### Version

0.0.1-alpha.13

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
After our inspection, we determined that today's server release caused this issue.

You can @DIYgod in our Discord server, and I will compensate you with an invitation code.

**Comment by resetsix** [comment]
> After our inspection, we determined that today's server release caused this issue.
> 
> You can @DIYgod in our Discord server, and I will compensate you with an invitation code.

thank u
