### ISSUE TITLE
阅读模式下自动翻译无法生效

### ISSUE THREAD

**Issue by Lv-0** [RSSNext/Follow#553]
### Describe the bug

阅读模式下自动翻译无法生效

### Feed Info

<img width="968" alt="截屏2024-09-22 14 58 07" src="https://github.com/user-attachments/assets/eb47f6b7-4a0e-40b3-9186-bd4a4f27f078">

### App Type

Web

### Version

0.0.1-alpha.14

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Vitowong00** [comment]
不在阅读模式下，可以自动翻译？？？怎么实现啊？

**Comment by Lv-0** [comment]
> 不在阅读模式下，可以自动翻译？？？怎么实现啊？

actions可以设置

**Comment by Vitowong00** [comment]
> > 不在阅读模式下，可以自动翻译？？？怎么实现啊？
> 
> actions可以设置

不能翻译全文把？ 只能翻译标题？

**Comment by hyoban** [comment]
暂时不支持文章内容的翻译
