### ISSUE TITLE
List 标题可为空，为空后 Follow 崩溃

### ISSUE THREAD

**Issue by rokcso** [RSSNext/Follow#555]
### Describe the bug

创建了一个新的 List 后发现无法删除 List（没有找到删除操作），然后将 List 的标题改为空，可以保存，但是 List 仍然没有删除，随后 Follow 就挂了，一直在下图页面，刷新、重开、重置本地数据库均无法恢复。

可能是因为 List 标题为空后获取标题长度报错。

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/b8c49825-8c72-414a-a3c3-f2b0e8b36148">

### Feed Info

无。

### App Type

Electron / App

### Version

0.0.1-alpha.14

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by rokcso** [comment]
重装 App 后依然报错，然后尝试登录网页版，也出现了同样的报错

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f33f6412-1259-4ca7-874a-b43aeeb869d5">

**Comment by Innei** [comment]
Fixed .15, please upgrade
