### ISSUE TITLE
今天早上follow崩溃了 生成邀请码失败 但是power币已经扣除了  我的id

### ISSUE THREAD

**Issue by cdxiaodong** [RSSNext/Follow#556]
### Describe the bug

今天早上follow崩溃了 生成邀请码失败 但是power币已经扣除了  我的id https://app.follow.is/profile/54054793303016448

### Feed Info

https://app.follow.is/profile/54054793303016448

### App Type

Electron / App

### Version

lastest

### Operating System

Windows 11

### Browser Info

https://app.follow.is/profile/54054793303016448

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by GO-PIO** [comment]
same issue.profile url:https://app.follow.is/profile/@Prefer

**Comment by DIYgod** [comment]
After our inspection, we determined that today's server release caused this issue. 

You can `@DIYgod` in our Discord server, and I will compensate you with an invitation code.
