### ISSUE TITLE
Alpha.14 cannot render `<pre>` code blocks and `<img>` correctly

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#558]
### Describe the bug

![image](https://github.com/user-attachments/assets/169c1696-109f-4a95-81c8-0a3b268f6166)

### Feed Info

https://51.ruyo.net/feed/

### App Type

Electron / App

### Version

Alpha.14

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Hotfixed. Upgrade to .15 plz

**Comment by cesaryuan** [comment]
> Hotfixed. Upgrade to .15 plz

Thanks, but I think black background like .13 is better.

The .15 render like below:
![image](https://github.com/user-attachments/assets/15315ac1-a9bc-45cc-83cb-95c0eb9be157)
