### ISSUE TITLE
未激活状态下 无法切换账户

### ISSUE THREAD

**Issue by NikkorW** [RSSNext/Follow#559]
### Describe the bug

我之前用的内测版本，今天更新了新版。更新完第一时间登陆，但是不小心使用了没有激活的邮箱登录，然后我的页面状态一直停留在输入激活码状态。无法退出现有错误账号。

### Feed Info

无

### App Type

Web

### Version

V0.01-alpha14

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by wen1701** [comment]
一样的情况，似乎登录的session是通过api获取的，我最后是用fiddle拦截了api，返回了一个空json，最后才重新登录的：D

**Comment by Innei** [comment]
最新版已经加上了登出按钮了

**Comment by wen1701** [comment]
> 最新版已经加上了登出按钮了

登出按钮点击后卡白屏，尝试等待，但是一直没有返回，也不会无响应。
![图片](https://github.com/user-attachments/assets/5323db7c-70d3-4981-846e-b6782aa8247b)

**Comment by Innei** [comment]
Fixed in the latest version.
