### ISSUE TITLE
pc 有三個地區語言無法切換，web 正常

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#564]
### Describe the bug

pc 有三個地區語言無法切換，web 正常

![image](https://github.com/user-attachments/assets/3f576308-53d0-4cb6-ab59-fa5c3064ffd4)

### Feed Info

。

### App Type

Electron / App

### Version

alpha 15

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Will fixed in next version
