### ISSUE TITLE
Failed to call achievement api

### ISSUE THREAD

**Issue by stuchilde** [RSSNext/Follow#566]
### Describe the bug

Failed to call achievement api
api request url: https://api.follow.is/achievement?type=all
response message: Cannot read properties of undefined (reading 'name')

### Feed Info

Unrelated

### Reproduction Video

<img width="1571" alt="image" src="https://github.com/user-attachments/assets/12f74f97-319a-4066-ad7d-19a8aa088055">

### App Type

Electron / App

### Version

0.0.1-alpha.15

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by GeorgeLifinRell** [comment]
Is there any more details on this issue, I'm willing to work on this.

**Comment by stuchilde** [comment]
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/53279ee4-764c-4783-be5a-b5f10a9438f9">

**Comment by stuchilde** [comment]
call api three times. every time waiting about 5s.

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
