### ISSUE TITLE
【Bug】Win11 安装安装桌面程序报错

### ISSUE THREAD

**Issue by yaolifeng0629** [RSSNext/Follow#569]
## 操作步骤
1. 下载桌面程序
2. 双击安装，出现弹窗如下图错误信息，（必现）
![1727000228234](https://github.com/user-attachments/assets/67b4e873-254e-44d1-ac01-0d37bc91a9cc)

### Feed Info

如上

### App Type

Electron / App

### Version

0.0.1-alpha.16

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I have not been able to reproduce this issue, have you solved it?

**Comment by yaolifeng0629** [comment]
For now, not yet. I have tried many times. But I can try the latest version again tonight to see if it will reproduce

**Comment by TonyRL** [comment]
It would be better if you can provide your PC specs.

**Comment by yaolifeng0629** [comment]
@DIYgod @TonyRL 

The latest version has been successfully installed and the issue has not been reproduced (it may have been caused by a previous issue with a lower version, but it's okay)
