### ISSUE TITLE
在windows 10中不能正确加载gif图片

### ISSUE THREAD

**Issue by xiaole3349** [RSSNext/Follow#584]
### Describe the bug

gif图接收到后不能被正确加载。

### Feed Info

60899003761446912

### Reproduction Video

![图片](https://github.com/user-attachments/assets/54382fe4-7a2f-4221-807c-340080b34356)
![图片](https://github.com/user-attachments/assets/ce04f061-cfff-46c4-b2df-27b56406e4a4)

### App Type

Electron / App

### Version

0.0.1-alpha.16

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
The height of the image was fetched incorrectly

**Comment by hyoban** [comment]
Fixed. You should be able to load GIFs correctly in the future.
