### ISSUE TITLE
安卓app增加下滑刷新和文件夹一键已读

### ISSUE THREAD

**Issue by berrythinking** [RSSNext/Follow#585]
### Clear and concise description of the problem

![736e870c49df794512e34649a16a03b](https://github.com/user-attachments/assets/ab502c45-e350-4ef5-9403-ba7028332e88)
希望增加下图这样的悬浮按钮，一键将文件夹内所以文章已读
![d55c6b53daf831471aa3a5ddbac85a6](https://github.com/user-attachments/assets/36da7077-05cb-4cb7-b070-c6766de7fa9d)

### Suggested solution

增加一键已读按钮，增加下滑刷新

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
请在正确的位置报告 issue

**Comment by Linon419** [comment]
从哪里下载的安卓版老哥，release看不到
