### ISSUE TITLE
Hpoi 添加失败

### ISSUE THREAD

**Issue by Feng-YiJing-Dao** [RSSNext/Follow#589]
### Describe the bug

Hpoi 添加失败
![image](https://github.com/user-attachments/assets/2799c6db-7b7a-44c1-9388-1ae791761f85)
![image](https://github.com/user-attachments/assets/2168d6dd-2ea1-46f4-b7ba-ca4f23997946)

### Feed Info

HPOI，41966

### App Type

Electron / App

### Version

beta16

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
发现它有两种 id：
- https://www.hpoi.net/works/41966
- https://www.hpoi.net/hobby/all?works=8063304

应该使用 8063304

@pseudoyu 应该在 RSSHub 文档中加一下说明或者使用某种方式兼容

**Comment by pseudoyu** [comment]
> 发现它有两种 id：
> 
> * https://www.hpoi.net/works/41966
> * https://www.hpoi.net/hobby/all?works=8063304
> 
> 应该使用 8063304
> 
> @pseudoyu 应该在 RSSHub 文档中加一下说明或者使用某种方式兼容

已解决，兼容了两种形式的 work id
