### ISSUE TITLE
建议自动化规则中 多个”指定条件“ 时，增加指定条件”或“ 的逻辑

### ISSUE THREAD

**Issue by TangQi001** [RSSNext/follow#592]
### Clear and concise description of the problem

当多个指定条件时，系统判定为符合两个条件才能使用规则
但是当我不需要对两个订阅源使用阅读模式时，这个时候我添加了两个指定条件
![image](https://github.com/user-attachments/assets/4fbdc2de-4543-46e6-b300-a24d055b2d55)
然而发现条件不起作用，我尝试使用一个条件，发现是有效的
在这种情况下，我只能另外开一个规则才能够实现两个订阅源不使用阅读模式
我认为这是繁琐的，当订阅源多了之后，就需要五六个甚至十几个规则

### Suggested solution

在指定多个条件中增加”或”的逻辑，而不是只有“且”的逻辑

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
related #659
