### ISSUE TITLE
获取Threads - User timeline 失败

### ISSUE THREAD

**Issue by Vitowong00** [RSSNext/Follow#593]
### Describe the bug

获取用户id himalayaapp 和 hecaitou 都是失败
<img width="653" alt="image" src="https://github.com/user-attachments/assets/bea03993-bd7f-48e9-a879-1e1fa55f4ce3">
<img width="644" alt="image" src="https://github.com/user-attachments/assets/78e63f44-6b79-47f9-a831-807609ca4357">

但是获取zuck是成功的，
<img width="635" alt="image" src="https://github.com/user-attachments/assets/577ced84-f879-48d8-bc43-2275a3a47ef0">
<img width="620" alt="image" src="https://github.com/user-attachments/assets/97b75606-7077-4fc0-bca0-0d4a144f6924">

### Feed Info

https://rsshub.app/threads/himalayaapp

### App Type

Electron / App

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Vitowong00** [comment]
<img width="904" alt="image" src="https://github.com/user-attachments/assets/a849e15f-42e5-44b4-a8e1-9094b8f1d50d">

**Comment by DIYgod** [comment]
I created an issue for RSSHub: https://github.com/DIYgod/RSSHub/issues/16910
