### ISSUE TITLE
记住 category 的打开和收起状态

### ISSUE THREAD

**Issue by sogoo** [RSSNext/Follow#602]
### Clear and concise description of the problem

1. 切换 view 的时候都会自动收起打开状态 category，每次浏览都要多次点击打开 category 有点频繁，
2. 同网站下有多个订阅源的话，默认按照网站分类或自建分类，无法不加入分类置于订阅源根目录之下。

### Suggested solution

1. 有一个可以记住打开和收起状态的选项。
2. 分类里给一个根目录项。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Przeblysk** [comment]
现在 category 的打开状态是由 [FeedCategoryImpl ](https://github.com/RSSNext/Follow/blob/dev/apps/renderer/src/modules/feed-column/category.tsx#L55) open State 控制的，如果要记住的话 是不是要在 Store 中保存? 还有一个问题是 category 在多个 tab 下的打开状态是否要独立？
