### ISSUE TITLE
Questions about adding telegram channels

### ISSUE THREAD

**Issue by stevenlee1009** [RSSNext/Follow#603]
### Describe the bug

网址https://rsshub.app/telegram/channel/TossIPhoneChannel,This is my channel address, I cannot add it to follow, because my channel is not included by RSSHUB. Please help solve it,

### Feed Info

https://t.me/TossIPhoneChannel

### Reproduction Video

![Uploading 截屏2024-09-23 21.29.59.p
![截屏2024-09-23 21 29 59](https://github.com/user-attachments/assets/393a0d0f-8402-4807-aa95-898efbfeb7f6)
ng…]()

### App Type

Web

### Version

0.0.1-alpha.16

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by KarasuShin** [comment]
![CleanShot 2024-09-24 at 09 47 27@2x](https://github.com/user-attachments/assets/a8deae98-bdfe-48cb-a944-684945d0446f)

**Comment by stevenlee1009** [comment]
Dear follow Team

First of all, thank you for your reply, I have tried this method!

As shown in the picture above, there is no problem with this telegram channel address, please help! Channel telegram address: https://t.me/TossIPhoneChannel <https://t.me/TossIPhoneChannel>

I like your follow very much. In addition, could you give me an IOS APP called testflight? The email address is: ***@***.*** ***@***.***>

Best wishes!
Thank you very much!

**Comment by hyoban** [comment]
https://t.me/s/TossIPhoneChannel does not work for me

**Comment by stevenlee1009** [comment]
Didn't you see the screenshot? It can work!


发自我的 iPhone

> 在 2024年9月24日，11:11，Stephen Zhou ***@***.***> 写道：
> 
> https://t.me/s/TossIPhoneChannel does not work for me

**Comment by hyoban** [comment]
- https://t.me/s/TossIPhoneChannel will be redirected to https://t.me/TossIPhoneChannel
- https://t.me/s/awesomeDIYgod will not be redirected and can display content

Please note the difference

**Comment by stevenlee1009** [comment]
你是中国的开发者啊，那就好沟通了，那我的频道地址为什么会被重定向呢，然后打开就少了/s/呢，我要怎么解决这个问题呢，解决了这个重定向问题才可以把频道添加到follow里面去是么？麻烦你了！

还有一个问题就是添加的订阅，我添加了翻译中文的规则，只有标题栏的正文和内容显示中文，点开文章，也只有标题和AI总结是中文，正文还是英文，这是我规则没有设定好的原因么？如图：

**Comment by stevenlee1009** [comment]
兄弟，我怎么解决解决这个问题呢，能不能交我下啊！晚上我把频道用户名改短了也不行！身边的朋友只要搜索telegram频道用户名就可以添加，我的搜索也搜索不到！期待你的回复！谢谢！发自我的 iPhone在 2024年9月24日，13:13，望宏 李 ***@***.***> 写道：﻿你是中国的开发者啊，那就好沟通了，那我的频道地址为什么会被重定向呢，然后打开就少了/s/呢，我要怎么解决这个问题呢，解决了这个重定向问题才可以把频道添加到follow里面去是么？麻烦你了！还有一个问题就是添加的订阅，我添加了翻译中文的规则，只有标题栏的正文和内容显示中文，点开文章，也只有标题和AI总结是中文，正文还是英文，这是我规则没有设定好的原因么？如图：<截屏2024-09-24 13.11.21.png>2024年9月24日 11:56，Stephen Zhou ***@***.***> 写道：

https://t.me/s/TossIPhoneChannel will be redirected to https://t.me/TossIPhoneChannel
https://t.me/s/awesomeDIYgod will not be redirected and can display content
Please note the difference—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by hyoban** [comment]
- Telegram has restricted access to this channel and there is nothing Follow and RSSHub can do about it.
- We are also paying attention to policy changes and other methods on the TG platform. If there is a solution in the future, we will update it.
- It is recommended that you contact Telegram Support directly, but this may not result in anything (For example https://t.me/NewlearnerChannel/13449).

**Comment by stevenlee1009** [comment]
Okay, I'll send an email to Telegram to try it out. Thank you for your reply!发自我的 iPhone在 2024年9月27日，12:10，Stephen Zhou ***@***.***> 写道：﻿

Telegram has restricted access to this channel and there is nothing Follow and RSSHub can do about it.
We are also paying attention to policy changes and other methods on the TG platform. If there is a solution in the future, we will update it.
It is recommended that you contact Telegram Support directly, but this may not result in anything (For example https://t.me/NewlearnerChannel/13449).
