### ISSUE TITLE
建议添加批量删除功能以改善OPML文件导入后的用户体验

### ISSUE THREAD

**Issue by Akuma-real** [RSSNext/Follow#604]
### Clear and concise description of the problem

使用此项目时，我从其他RSS阅读器导入了一个OPML文件，但该文件未能正常工作。因此，我需要逐个手动删除每一项内容，这个过程相当耗时。如果有一个批量删除功能，能够一次性删除多个条目，将大大提升用户体验。相信其他从RSS阅读器导入OPML文件的用户也可能遇到类似问题。

### Suggested solution

在当前的条目管理模块中，可以提供一个批量选择和删除的功能。例如，在导入条目列表界面，用户可以多选条目，并通过一个"批量删除"按钮进行操作。这样可以大大简化导入出错后的清理流程。

### Alternative

可以提供一个导入预览功能，允许用户在导入前查看OPML文件的内容，并选择是否全部导入或部分导入，以减少错误操作后的清理负担。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #272.
