### ISSUE TITLE
Senior Tester Engineer need code

### ISSUE THREAD

**Issue by mackding123** [RSSNext/Follow#607]
### Clear and concise description of the problem

hi there, I'm Senior Tester Engineer need code, may I have a code to full Testing Follow. Tks

### Suggested solution

Extremely passionate about software testing. 10 years of experience in software quality assurance, continuous test delivery. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
You can get an invitation code in the following ways:

- Looking for any alpha test user to invite you.
- Join our Discord server for occasional giveaways.
- Follow our X account for occasional giveaways.
