### ISSUE TITLE
Social Media can not show full content, especially GitHub activities

### ISSUE THREAD

**Issue by zwpaper** [RSSNext/Follow#609]
### Describe the bug

![CleanShot 2024-09-24 at 16 21 26@2x](https://github.com/user-attachments/assets/76d1185f-d338-4ae9-99ec-f50a88589472)

but it works great if add it as articles

![CleanShot 2024-09-24 at 16 20 54@2x](https://github.com/user-attachments/assets/b008f338-c14b-4ec5-a8f2-b64491800c99)

### Feed Info

all feed in type GitHub activities, twitter also can only part of the message

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
The Social Media view will modify the entry content, such as removing images from the content, so it is not suitable for displaying GitHub activities. You can consider using Notification
