### ISSUE TITLE
Customizable Feed Update Notifications

### ISSUE THREAD

**Issue by Chikedor** [RSSNext/Follow#612]
### Clear and concise description of the problem

Implement a notification system for feed updates so users can stay informed about new content in their selected feeds without constantly checking the app.

### Suggested solution

1. Add a notification system that triggers when selected feeds are updated
2. Allow users to choose which feeds should send notifications
3. Provide an option to set a maximum number of notifications per day
4. Integrate with the device's native notification system for a seamless experience

### Alternative

Smart Notification System: Implement an AI-driven notification system that learns from user behavior. It analyzes which feeds users interact with most frequently and automatically adjusts notification priorities. This system could send fewer, more targeted notifications based on user interests and reading patterns.

### Additional context

There's some sources you need to keep track ASAP, almost instantly, and there are others that you can look from time to time. This feature would enhance user engagement by keeping users informed of new content. The ability to customize which feeds trigger notifications and set a maximum limit addresses potential issues with notification fatigue.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
We have now provided a notification feature in actions. I think this this issue has been resolved, if the problem still exists, please feel free to reopen it.
