### ISSUE TITLE
无法完成订阅源所有者成就

### ISSUE THREAD

**Issue by Yeatesss** [RSSNext/Follow#620]
### Describe the bug

目前已经拥有一个所有者认证的rss,但是成就中依旧是1/0
![image](https://github.com/user-attachments/assets/c9c29ede-4c6a-462f-b2c9-a3947af97844)

### Feed Info

61588286886990848

### App Type

Electron / App

### Version

E2BA869

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Passi0n1** [comment]
蹲，同样无法完成RSS认证成就

**Comment by ljnchn** [comment]
同样遇到
