### ISSUE TITLE
什么时候 app 能够支持“沉浸试翻译“ 英文订阅没有翻译确实很头疼。

### ISSUE THREAD

**Issue by gaoxundang** [RSSNext/Follow#621]
### Clear and concise description of the problem

什么时候 app 能够支持“沉浸试翻译“ 英文订阅没有翻译确实很头疼。

### Suggested solution

什么时候 app 能够支持“沉浸试翻译“ 英文订阅没有翻译确实很头疼。

### Alternative

什么时候 app 能够支持“沉浸试翻译“ 英文订阅没有翻译确实很头疼。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by luo-chuan** [comment]
有类似功能的浏览器插件是[immersive translate](https://go.immersivetranslate.com/) 。

另外，rss app “[PoweReader](https://powereader.app/guide/)” 已实现了该功能。

| ![image](https://github.com/user-attachments/assets/bac5e0e9-b386-43a2-acd8-0b7baf2af0cb) | ![image](https://github.com/user-attachments/assets/2a313cc7-539e-4ba5-a497-4d9d5e507c8d) |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/37c1ea87-778d-4850-9e3b-9eca9e179b27) | ![image](https://github.com/user-attachments/assets/f244f244-7ba3-4d09-9981-f9ba6191772d) |

**Comment by cesaryuan** [comment]
> 现在有翻译功能嘛，为啥英文文章还是没有翻译

在自动化里设置规则
![image](https://github.com/user-attachments/assets/0dc84bb4-b443-4581-82f4-86d683de71f7)

**Comment by luo-chuan** [comment]
可以保留标题原文吗？现在标题只显示译文。@cesaryuan

**Comment by cesaryuan** [comment]
> 可以保留标题原文吗？现在标题只显示译文。[@cesaryuan](https://github.com/cesaryuan) [@hyoban](https://github.com/hyoban)

我不是开发者，感觉可以新开一个issue

**Comment by luo-chuan** [comment]
> 我不是开发者，感觉可以新开一个issue

已提issue： https://github.com/RSSNext/Follow/issues/1779
