### ISSUE TITLE
Consolidate Multiple RSS Feeds from the Same Domain into a Single Subscription

### ISSUE THREAD

**Issue by zkl2333** [RSSNext/Follow#623]
### Clear and concise description of the problem

  As a user of this RSS reader, I have noticed that some blogging platforms provide multiple RSS feeds under the same domain, such as:

  - `domain.com/rss`
  - `domain.com/feed`
  - `domain.com/atom`

  When I attempt to verify ownership of these feeds, they are treated as separate subscriptions. This complicates subscription management and can lead to redundancy.

### Suggested solution

In the subscription management module, implement a feature that recognizes multiple RSS feeds under the same domain as a single subscription. Alternatively, allow these feeds to share the same ownership verification, simplifying the verification process and improving user experience.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
We will now transfer the feed with 301 and 302 redirects to the new feed, but without such associations, it will be difficult to determine if they are the same feed or have a new address.

I think this is also a more suitable approach for website administrators.
