### ISSUE TITLE
订阅信息不能及时同步

### ISSUE THREAD

**Issue by thirteenkai** [RSSNext/Follow#624]
### Describe the bug

订阅信息不能及时同步，延迟好几个小时

### Feed Info

55140951451793408

### App Type

Web

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by ljiang0315** [comment]
我也出现类类似的问题，同步信息较慢，公众号订阅

**Comment by hyoban** [comment]
目前订阅在服务端刷新的时间为半小时到三个小时不等，我们将会减少非 rsshub 源的刷新间隔到十五分钟至一个半小时
