### ISSUE TITLE
该feed无法获取

### ISSUE THREAD

**Issue by fwrite0920** [RSSNext/Follow#626]
### Describe the bug

feed xml无法获取

### Feed Info

https://toughcoder.net/atom.xml

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I can't access this feed locally either, it shows the certificate is invalid.

**Comment by fwrite0920** [comment]
yes，I change https://toughcoder.net/atom.xml to http://toughcoder.net/atom.xml， it‘s ok ，thank you.
