### ISSUE TITLE
Halo 自带 Rss 获取订阅源出错

### ISSUE THREAD

**Issue by HellShuro** [RSSNext/Follow#628]
### Describe the bug

Halo 自带 Rss 获取订阅源出错

### Feed Info

http://daoxuanshan.xyz/rss.xml

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
![ScreenShot 2024-09-25 17 32 25](https://github.com/user-attachments/assets/3f4ff4b6-ea2e-4120-91c8-a5a8efd481ec)
