### ISSUE TITLE
RSS 2.0 无法解析

### ISSUE THREAD

**Issue by ChihGodlee** [RSSNext/Follow#630]
### Describe the bug

https://www.uber.com/en-TW/blog/taipei/engineering/rss/
无法解析

### Feed Info

https://www.uber.com/en-TW/blog/taipei/engineering/rss/

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

macOS

### Browser Info

ARC

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I can not parse this feed using other RSS readers either

![ScreenShot 2024-09-25 18 05 33](https://github.com/user-attachments/assets/a6274ab7-73e1-4391-95e7-079a2a3f2d9b)
