### ISSUE TITLE
logout failed

### ISSUE THREAD

**Issue by stuchilde** [RSSNext/Follow#635]
### Describe the bug

it shows white page. when click logout

### Feed Info

![image](https://github.com/user-attachments/assets/32dc8ea9-ece2-4f36-9bc1-3598d491c059)

### App Type

Electron / App

### Version

Follow-0.0.1-alpha.17-windows-x64

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by stuchilde** [comment]
![image](https://github.com/user-attachments/assets/3f65dd8b-db32-4e6a-a5b6-8fd651589b99)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
