### ISSUE TITLE
Follow cannot render the code block correctly, but Inoreader can render it.

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#640]
### Describe the bug

There is an article in which Follow cannot render the code block correctly, but Inoreader can render it.

![image](https://github.com/user-attachments/assets/984f00c7-c945-470b-83de-33001f596389)

### Feed Info

https://seekiu.github.io/feeds/all.atom.xml

This feed item in it: [用 matplotlib 画出规范的论文插图](https://seekiu.github.io/2016/mpl-for-publish.html)

### App Type

Electron / App

### Version

Alpha.17

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
![ScreenShot 2024-09-27 10 11 01](https://github.com/user-attachments/assets/9c7488c5-d634-4fdf-af47-b849c0308303)
