### ISSUE TITLE
win11 客户端：发现-导入直接白屏，且无法返回，只是kill进程重新启动

### ISSUE THREAD

**Issue by JasonGod** [RSSNext/Follow#641]
### Describe the bug

win11 客户端：发现-导入直接白屏，且无法返回，只是kill进程重新启动
version： 0.0.1 -nightly.20240924

### Feed Info

/

### App Type

Electron / App

### Version

0.0.1-nightly.20240924

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
fixed in 23d6988a63ce6ecdce562fb632fe85823082d38b
