### ISSUE TITLE
希望添加“一次性选择多个订阅源然后取消订阅的功能”

### ISSUE THREAD

**Issue by songyp0505** [RSSNext/Follow#644]
### Clear and concise description of the problem

导入了一个有一百个订阅源的文件，但是有很多都没法工作，发现是网址的问题，于是开始取消订阅，但是后来发现只能一条一条的取消订阅，不能多选，很难受，我现在还没取消完，希望能增加这个功能，谢谢

### Suggested solution

添加多选的功能，或者是批量取消订阅的功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #272
