### ISSUE TITLE
AP News feeds not working

### ISSUE THREAD

**Issue by kyleranitar** [RSSNext/Follow#645]
### Describe the bug

Just started to tinker and got an error in fetching feed. Tried with other categories "election-2024" and it didn't work as well.

![Screenshot on 2024-09-26 at 16 00 32@2x](https://github.com/user-attachments/assets/35ae9faf-46d7-4e31-ace2-2328aa1d5653)

### Feed Info

![Screenshot on 2024-09-26 at 16 04 28@2x](https://github.com/user-attachments/assets/642b08c6-b1fc-414d-9a98-64a1f28d56c5)

### App Type

Web

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
https://rsshub.app/apnews/topics/election-2024
