### ISSUE TITLE
关于tg一些图片频道无法加载图片

### ISSUE THREAD

**Issue by ran3344** [RSSNext/Follow#647]
### Describe the bug

最近的两条消息可以加载图片，历史消息加载不了图片
![image](https://github.com/user-attachments/assets/36c3d9c1-daf7-4e27-93d2-79f7b398e52d)

### Feed Info

rsshub://telegram/channel/botmzt

### App Type

Web

### Version

0.0.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is because the entry's content will not be refreshed, the previous image address has expired. It will be solved in the next version.
