### ISSUE TITLE
如何强制刷新自己的博客订阅数据

### ISSUE THREAD

**Issue by cn-kali-team** [RSSNext/Follow#648]
### Describe the bug

我在添加我自己的订阅源后，发现我没有开启rss的全文，导致只爬到了标题和描述信息，在follow中不能看到全文，请问如何强制更新上面的数据，我现在已经开启rss全文了，重新添加还是只有标题和描述。

### Feed Info

62078636574572544
https://blog.kali-team.cn/atom.xml

### App Type

Web

### Version

0.0.1-aplha.17

### Operating System

Linux

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
In the next version, when refreshing the feed, entry content can be updated
