### ISSUE TITLE
在成就里认证订阅源后领取 100Power后，当天就无法领取每日签到的 20Power 了

### ISSUE THREAD

**Issue by nanvon** [RSSNext/Follow#650]
### Describe the bug

如题，当我在成就里认证订阅源后领取 100Power后，当天就无法领取每日签到的 20Power 了，会显示“今日已领取”，但其实今天的 20 并没有领到

### Feed Info

null

### App Type

Electron / App

### Version

0.0.1-nightly.20240924

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by nanvon** [comment]
如果需要截图，我可以提供交易记录截图

**Comment by hyoban** [comment]
Related #694

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
