### ISSUE TITLE
nature只能显示标题，不能将完整的文章显示出来

### ISSUE THREAD

**Issue by TonyKingWJX** [RSSNext/Follow#651]
### Describe the bug

nature只能显示标题，不能将完整的文章显示出来
![PixPin_2024-09-26_21-59-08](https://github.com/user-attachments/assets/ebafc176-e98f-4eef-9585-c4b8f66f0d4b)

### Feed Info

tonykingwjx

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
可以试试点击 header 上的星星✨图标进入阅读模式
