### ISSUE TITLE
Add ability to show full description in Pictures View

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#652]
### Clear and concise description of the problem

The current picture view only shows pictures and captions, not the rest of the text description.

However, in some feeds, text description plays a great role in supplementing the image. Some introduce the prompt of the image, and some introduce the data source and detailed information of the image. At this time, there is no way for the user to view this information. For example feed: https://rsshub.cesaryuan.top/voronoiapp/popular/most-popular

### Suggested solution

Click on the image to display the complete description.
![image](https://github.com/user-attachments/assets/85338e4e-4da2-4944-b747-f046225f22ea)
      

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
Done 29f2c0ca41badb34b001ac9dff91c1e2b600a71f

<img width="1624" alt="Screenshot 2024-09-27 at 4 41 33 AM" src="https://github.com/user-attachments/assets/9ea44a86-8be4-4d82-912c-6d8638387e06">

**Comment by cesaryuan** [comment]
> Done [29f2c0c](https://github.com/RSSNext/Follow/commit/29f2c0ca41badb34b001ac9dff91c1e2b600a71f)

Thanks for you excellant work! 

I cloned and tried. It only work in Pictures View's Masonry view now, but not work in Grid view.

![recording](https://github.com/user-attachments/assets/5bc8dc47-5c19-4a20-a526-719554beb301)
