### ISSUE TITLE
获取订阅源错误

### ISSUE THREAD

**Issue by xenia1111** [RSSNext/Follow#653]
### Describe the bug

获取订阅源错误

### Feed Info

<img width="666" alt="image" src="https://github.com/user-attachments/assets/2919d360-8769-4423-80dc-0cc6bfccb1a5">

### App Type

Electron / App

### Version

不确定，最新版本

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
This is not an accessible address https://news.ycombinator.com/Y%20Combinator
