### ISSUE TITLE
X (Twitter) 订阅失效

### ISSUE THREAD

**Issue by xwshan** [RSSNext/Follow#656]
### Describe the bug

- 用Follow里面的X (Twitter)关键词订阅，第一天可以正常使用，第二天全部失效。取消订阅，重新订阅仍然失效。随后过两天，又可以订阅了。
- 不止我一人，出现这种情况。

### Feed Info

X (Twitter) 随便用什么关键词订阅都行 😄 

### App Type

Electron / App

### Version

0.0.1 alpha.17

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by mintisan** [comment]
是这样么楼主
<img width="253" alt="image" src="https://github.com/user-attachments/assets/d784f6f9-fdbd-4ebd-b6eb-53838dbcdfe7">

**Comment by xwshan** [comment]
对的。你这好像是某个用户。
我是用关键词的，然后飘红。有的时候，某个关键词，要输入多次，才能发现订阅。
![image](https://github.com/user-attachments/assets/b8cda7f3-2632-4cad-adc7-9134bcca3703)

**Comment by hyoban** [comment]
We cannot guarantee that Twitter-related feeds are always available. We will restore it as soon as possible after a service problem. You can try again later.
