### ISSUE TITLE
Telegram Channel  503 Service Unavailable. I can't claim it.

### ISSUE THREAD

**Issue by xream** [RSSNext/Follow#657]
### Describe the bug

1. Telegram Channel shows "503 Service Unavailable". It has no cover and no recent messages.
![image](https://github.com/user-attachments/assets/ea44d78e-945c-474e-9e55-6a9ebc95f177)

2. I can't claim it.
![image](https://github.com/user-attachments/assets/f1edd0d9-eb98-4077-bc1c-29b17e0e5d3a)

### Feed Info

rsshub://telegram/channel/zhetengsha
55438372655431680

### App Type

Electron / App

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Error: Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: https://t.me/s/zhetengsha

**Comment by hyoban** [comment]
- Telegram has restricted access to this channel and there is nothing Follow and RSSHub can do about it.
- We are also paying attention to policy changes and other methods on the TG platform. If there is a solution in the future, we will update it.
- It is recommended that you contact Telegram Support directly, but this may not result in anything (For example https://t.me/NewlearnerChannel/13449).
