### ISSUE TITLE
分类展开状态和顶部全部展开收起状态不一致问题

### ISSUE THREAD

**Issue by Przeblysk** [RSSNext/Follow#668]
### Describe the bug

因为分类中的每一个展开状态是独立存在的 [category](https://github.com/RSSNext/Follow/blob/dev/apps/renderer/src/modules/feed-column/category.tsx#L55)。当单独操作分类的展开状态时，顶部的全局展开状态就可能会有不一致的问题出现。

如果要解决这个问题是否要考虑下 https://github.com/RSSNext/Follow/issues/602 一起解决。

### Feed Info

""

### Reproduction Video

https://github.com/user-attachments/assets/847a7430-49d8-4248-ae01-79155d97ef34

### App Type

Web

### Version

0.0.1-alpha.17

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Do you want to work on them?

**Comment by Przeblysk** [comment]
> Do you want to work on them?

My idea is to store an open state in the Store for each category under each View, so that each View's open state can be independent.
I'm not sure if my idea and change is what Follow wants.

**Comment by hyoban** [comment]
I think that's basically the case.

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/cb2078da70ac93add77aee9da83d5687c4b8b9c8
