### ISSUE TITLE
[bug]通过点击目录中的小标题无法跳转到文章对应位置

### ISSUE THREAD

**Issue by SymmFz** [RSSNext/Follow#671]
### Clear and concise description of the problem

将鼠标移至文章的右侧会显示一个目录，显示文章的各级小标题。目前点击小标题会回到文章顶部，而不是跳转到小标题对应位置。

希望支持通过点击目录中的小标题跳转到文章对应位置。

### Suggested solution

通过点击文章右侧目录中的任意小标题，跳转到文章的对应位置

### Additional context

![Clip_2024-09-27_20-44-21](https://github.com/user-attachments/assets/a8fa1532-d864-4507-acda-4bc0236d8ea8)
通过点击文章右侧目录中的任意小标题，跳转到文章的对应位置

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
https://github.com/user-attachments/assets/3011dd9d-6bf0-432c-9d53-ba82884feb94

I can not reproduce, please provide a reproducible feed.

**Comment by hyoban** [comment]
Not work on `rsshub://sspai/index`

**Comment by SymmFz** [comment]
> Not work on `rsshub://sspai/index`

浏览器上对于同一篇文章，有时点击小标题能够正常跳转，有时则只能回到文章顶部。
另外，对同一篇文章而言，点击小标题得到的结果可能会发生变化，例如我在少数派的[这篇文章](https://sspai.com/post/92388)中有时能够跳转到对应位置，刷新后再点击小标题则可能只能回到顶部。

在 windows 版本，我从未遇到能够正常跳转到对应位置的情况，点击小标题只能回到文章顶部。

下面这些源都是在 windows 下一直无法正常跳转的，也许可以帮助复现：
```
rsshub://woshipm/popular
https://www.appinn.com/feed/
https://weekly.tw93.fun/rss.xml
```

**Comment by SymmFz** [comment]
> > Not work on `rsshub://sspai/index`
> 
> 浏览器上对于同一篇文章，有时点击小标题能够正常跳转，有时则只能回到文章顶部。 另外，对同一篇文章而言，点击小标题得到的结果可能会发生变化，例如我在少数派的[这篇文章](https://sspai.com/post/92388)中有时能够跳转到对应位置，刷新后再点击小标题则可能只能回到顶部。
> 
> 在 windows 版本，我从未遇到能够正常跳转到对应位置的情况，点击小标题只能回到文章顶部。
> 
> 下面这些源都是在 windows 下一直无法正常跳转的，也许可以帮助复现：
> 
> ```
> rsshub://woshipm/popular
> https://www.appinn.com/feed/
> https://weekly.tw93.fun/rss.xml
> ```

这个源 `https://antfu.me/feed.xml` 在 windows 和 web 都可以正常的跳转到文章对应位置。

**Comment by hyoban** [comment]
This is related to whether the entry content has a value at the beginning. If there is no initial value, everything is normal.

It looks like the `$headings` in the Toc component didn't get updated in time, causing the calculated distances to be incorrect (all 0).

```tsx
export const Toc: Component = ({ className }) => {
  const markdownElement = useContext(MarkdownRenderContainerRefContext)

  const $headings = useMemo(
    () =>
      (markdownElement?.querySelectorAll("h1, h2, h3, h4, h5, h6") || []) as HTMLHeadingElement[],
    [markdownElement],
  )
}
```

I tried for a long time and didn't find a suitable fix. Ask @Innei for help.
