### ISSUE TITLE
认证过的源会自动失效

### ISSUE THREAD

**Issue by versun** [RSSNext/Follow#676]
### Describe the bug

认证过的源会自动失效，重新认证后，出现新的ID，但原来的数据依旧存在，且不会迁移
源地址：54321.versun.me/feed
旧认证地址：https://app.follow.is/feed/42119882150293504
新认证地址：https://app.follow.is/feed/54807548014042114
![2024-09-27 -22-42-44](https://github.com/user-attachments/assets/7e27ddd1-1af2-45b3-abfc-2305db58cc0b)

### Feed Info

htttps://54321.versun.me/feed

### App Type

Web

### Operating System

macOS

### Browser Info

Firefox

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Feeds are distinguished by URL. We now only update the feed's subscription based on the redirect of the request address.
