### ISSUE TITLE
bilibili UP主动态订阅失败

### ISSUE THREAD

**Issue by allenli178** [RSSNext/Follow#680]
### Describe the bug

bilibili UP主动态订阅失败

### Feed Info

<img width="583" alt="image" src="https://github.com/user-attachments/assets/e2b4721a-e7c9-46ab-920a-2b4279a87824">

### App Type

Electron / App

### Version

0.0.1-alpha.18

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It should be fine now

![ScreenShot 2024-09-29 10 37 27](https://github.com/user-attachments/assets/a1febcc5-1803-450b-8fd5-eb5cdf069242)

**Comment by allenli178** [comment]
👌
