### ISSUE TITLE
订阅认证显示

### ISSUE THREAD

**Issue by comeweb** [RSSNext/Follow#681]
### Describe the bug

Hi 今天刚刚注册好使用follow 订阅好友网站发现会出现认证图标错误 且windows程序应用和网页版都会出现错误

目前我搜索issue里面没有反馈这个bug的 如果有的话 十分抱歉

当我订阅好友博客，/feed/后面加上斜杠不会显示 认证图标 如果可以 我想邀请一位好友也体验follow 请问可以多给一个邀请码吗

![ed1c8d16250ee9ffc4183b930707d56f](https://github.com/user-attachments/assets/9ca182ee-abf4-461b-9151-8fb8a1ee4cc8)
删除订阅后去掉斜杠/ 即可正常显示 这里感觉可以适配一下 不知道算不算bug 
![df733fa00f82621e433e1ae856081f43](https://github.com/user-attachments/assets/e4a40b4e-e02a-42dc-967b-7537bb04d39d)

### Feed Info

https://www.vlo.cc/feed
https://www.vlo.cc/feed/

### App Type

Electron / App

### Version

OA89C22

### Operating System

Windows 10

### Browser Info

Edge 版本 129.0.2792.65 (正式版本) (64 位)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Feeds are distinguished by URL. We currently do not have a complete solution for merging the same feeds.
