### ISSUE TITLE
MacOS下多次编辑，编辑窗口弹出失败

### ISSUE THREAD

**Issue by Mar1usSo** [RSSNext/Follow#682]
### Describe the bug

# MacOS下多次编辑，编辑窗口弹出失败
需要`cmd`+`R`重新加载后，再编辑，才能成功进入编辑页面

### Environment

**App Version**: 0.0.1-alpha.18
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.18 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

和feed无关

### Reproduction Video

[follow编辑失败.mov.zip](https://github.com/user-attachments/files/17172415/follow.mov.zip)

### App Type

Electron / App

### Version

0.0.1-alpha.18

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Can not reproduce
