### ISSUE TITLE
tg频道出现503错误

### ISSUE THREAD

**Issue by Readfere** [RSSNext/Follow#691]
### Describe the bug

无论是官方源还是第三方自建源都提示503错误
<img width="164" alt="vkojmwhg a21" src="https://github.com/user-attachments/assets/3665b1f0-c598-4b8c-8ccf-5964075589d6">

rsshub://telegram/channel/app_snitch
https://rsshub.imlg.co/telegram/channel/app_snitch

### Feed Info

55811658622611456
rsshub://telegram/channel/app_snitch

### App Type

Electron / App

### Version

0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

Chrome

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
#603 #507

https://t.me/s/app_snitch

- Telegram has restricted access to this channel and there is nothing Follow and RSSHub can do about it.
- We are also paying attention to policy changes and other methods on the TG platform. If there is a solution in the future, we will update it.
- It is recommended that you contact Telegram Support directly, but this may not result in anything (For example https://t.me/NewlearnerChannel/13449).
