### ISSUE TITLE
每日登陆领取的20Power未到账，提示今日已领取，且缺失交易记录

### ISSUE THREAD

**Issue by zdx0122** [RSSNext/Follow#694]
### Describe the bug

之前每天都会自动到账20Power，9月28日未自动到账，且点击领取后，提示今日已经领取，但也未到账，缺少9月28日的20Power

地址：0x4acf46d83f11e725c0edf3937989d29dc2f4c49e

缺失今日登陆的20Power截图：
![image](https://github.com/user-attachments/assets/bdd9ed9e-4cd7-44ba-bc29-28ad6f98c0df)

### Feed Info

地址：0x4acf46d83f11e725c0edf3937989d29dc2f4c49e
https://scan.rss3.io/address/0x4acf46d83f11e725c0edf3937989d29dc2f4c49e?tab=token_transfers

### App Type

Web

### Version

v0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

Microsoft Edge 版本 129.0.2792.65 (正式版本) (64 位)

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
