### ISSUE TITLE
twitter订阅无法过滤回复

### ISSUE THREAD

**Issue by banshaobao** [RSSNext/Follow#696]
### Describe the bug

twitter订阅无法过滤回复

### Feed Info

https://rsshub.app/twitter/user/DIYgod/routeParams=exclude_replies
https://rsshub.app/twitter/user/DIYgod/exclude_replies

### App Type

Web

### Version

v0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

chrome 129

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by banshaobao** [comment]
![image](https://github.com/user-attachments/assets/0f9cc252-ba76-4ccd-9ba0-f01dd50eae6a)

**Comment by hyoban** [comment]
We do not support RSSHub's routing parameters, you can use Action to filter replies

https://x.com/follow_app_/status/1833115615370019236
