### ISSUE TITLE
instagram图片加载错误

### ISSUE THREAD

**Issue by comeweb** [RSSNext/Follow#697]
### Describe the bug

本机科学上网与未连接情况一致 

部分订阅博主会出现图片错误情况 报错类似于下图，封面正常，但是点击进去会出现报错

类似很多博主都会出现这种情况 有些直接会乱码
![image](https://github.com/user-attachments/assets/f71d9f04-7c06-4d70-a569-492901e9ad9e)
![image](https://github.com/user-attachments/assets/53078aa9-c5c2-4dea-903e-fd9f3fd23fed)
![image](https://github.com/user-attachments/assets/56c42db9-3be1-4de6-9967-83a2c4e930db)

### Feed Info

rsshub://picnob/user/xinel_simpson
rsshub://picnob/user/alanshao1

### Reproduction Video

Not yet

### App Type

Electron / App

### Version

预览版本(0A89C22)

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/033887693bc805d3217a4251447bb1e7da00db9a
