### ISSUE TITLE
豆瓣小组图片无法加载

### ISSUE THREAD

**Issue by banshaobao** [RSSNext/Follow#699]
### Describe the bug

豆瓣小组图片无法加载，按下F12，可以看到大量重试请求
![image](https://github.com/user-attachments/assets/af9c900c-a902-4015-9536-8b51519e61cf)
打开原链接。图片是秒加载的
![image](https://github.com/user-attachments/assets/4d78fb16-23b0-48df-9cb2-fba5f8f57fcc)

### Feed Info

https://rsshub.app/douban/group/648102/essence

### App Type

Web

### Version

v0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

chrome 129

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by banshaobao** [comment]
排查了一下。
follow这边请求的图片链接是
https://img1.doubanio.com/view/group_topic/l/public/p662652870.jpg
而豆瓣使用的图片链接是
https://img1.doubanio.com/view/group_topic/l/public/p662652870.webp

**Comment by banshaobao** [comment]
我想是由于请求的图片格式不一样导致的

**Comment by banshaobao** [comment]
加载豆瓣的webp格式的图片是秒开的。而请求jpg是一点一点刷出来的

**Comment by hyoban** [comment]
I think this is a problem with douban. When I access the image directly, it loads very slowly too.

![ScreenShot 2024-09-29 09 14 26](https://github.com/user-attachments/assets/b04ae0b2-887b-4af4-883f-896d26ed9e2f)

**Comment by zxhd863943427** [comment]
经过测试，douban对跨域流量做了限速，使用curl的测试如下：
```
curl  "https://img1.doubanio.com/view/group_topic/l/public/p662652870.webp" -H "Referer: https://www.douban.com/" --output 1.webp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  233k  100  233k    0     0   397k      0 --:--:-- --:--:-- --:--:--  399k
curl  "https://img1.doubanio.com/view/group_topic/l/public/p662652870.webp" --output 1.webp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  233k  100  233k    0     0  10183      0  0:00:23  0:00:23 --:--:--  8874
```

**Comment by hyoban** [comment]
> 经过测试，douban对跨域流量做了限速

The new image proxy service should solve this problem.

We are doing an AB Test for the new image proxy service, you may be able to browse images normally after the full release.

https://github.com/user-attachments/assets/a59664f8-6ef5-4f6f-ab99-d677d1af4b55

**Comment by banshaobao** [comment]
我平常主要是使用web版。这个在web版有修复吗

**Comment by hyoban** [comment]
It works on the web too.

**Comment by banshaobao** [comment]
> 排查了一下。 follow这边请求的图片链接是 https://img1.doubanio.com/view/group_topic/l/public/p662652870.jpg 而豆瓣使用的图片链接是 https://img1.doubanio.com/view/group_topic/l/public/p662652870.webp

关于格式问题。请问下为什么要把webp改为jpg呢。为什么不使用原图链接呢。这个是出于什么考量呢

**Comment by banshaobao** [comment]
等会我录制一个关于豆瓣在follow的视频。在web上目前并没有得到改善

**Comment by banshaobao** [comment]
https://github.com/user-attachments/assets/6ee84fbb-ada5-44b4-8b36-c87514bf5b2d

**Comment by banshaobao** [comment]
视频已上传
