### ISSUE TITLE
When managing subscription feeds in the list, the input box is not cleared after adding a new feed.

### ISSUE THREAD

**Issue by Przeblysk** [RSSNext/Follow#701]
### Clear and concise description of the problem

When managing subscription feeds in the list, the input box is not cleared after adding a new feed.

https://github.com/user-attachments/assets/ef44aed4-6041-4953-869f-11765c053d91

### Suggested solution

cleared after adding a new feed

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
I put the necessary dlls in the archive
