### ISSUE TITLE
【Bug 必现】无法领取 Power 币，浏览器和客户端都提示已经领取过了，但刷新还是之前的数量

### ISSUE THREAD

**Issue by 19980617** [RSSNext/Follow#703]
### Describe the bug

![Clip_2024-09-29_10-15-45](https://github.com/user-attachments/assets/1197fb31-4a91-459e-b845-fc71a1f108d0)

### Environment

**App Version**: 0.0.1-alpha.18
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

### Reproduction Video

1. 点击领取按钮
2. 底部一直出现已领取
3. 刷新、清除缓存，无痕、客户端都尝试过，还是相同问题

### App Type

Web

### Version

0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

Chrome/129.0.0.0

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Related #694

**Comment by 19980617** [comment]
@hyoban 这个bug 啥时候修复呢？😊 要不然领取不了 power 币啊，已经耽误我四天了😂

**Comment by allenli178** [comment]
我也遇到了同样的问题，刚领两天，第三天领取失败了😂

**Comment by leylatop** [comment]
The same to me

**Comment by leylatop** [comment]
接口报错400
