### ISSUE TITLE
部分订阅源无法获取全文

### ISSUE THREAD

**Issue by luo-chuan** [RSSNext/Follow#711]
### Describe the bug

比如下面这两个订阅源，本来只有摘要，点击“阅读模式”后就一直转圈。我设置了代理，并且浏览器能打开原网页。换成别的rss阅读器，比如Qireader就一切正常，几秒就加载完成了。
![63ee3b82cf84f910f44d38a456852fe8](https://github.com/user-attachments/assets/fcf0af1e-ae6b-4c19-a955-8d64b9eaec52)
下图是Qireader：
![3d6dc9243d372295f04a3f888a4e302b](https://github.com/user-attachments/assets/d6a18fb9-3bdf-4209-b07c-dadaae2b6c30)

### Feed Info

`https://www.cbc.ca/webfeed/rss/rss-world`
`https://rss.nytimes.com/services/xml/rss/nyt/World.xml`

### App Type

Electron / App

### Version

0.0.1-alpha.18

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Can not reproduce 

https://github.com/user-attachments/assets/164425eb-4a8b-42ab-81f7-e0102ae7a428
