### ISSUE TITLE
希望能够添加空格键滚动右侧的内容区域

### ISSUE THREAD

**Issue by chenzhiwei** [RSSNext/Follow#712]
### Clear and concise description of the problem

浏览器默认是空格键向下滚动页面，Shift+空格键是向上滚动页面

### Suggested solution

希望最右则的内容区域可以支持空格与Shift+空格键进行页面滚动

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ericyzhu** [comment]
It seems to have been completed in https://github.com/RSSNext/Follow/commit/baa66feaf19416d2b9e5efe6b79f6af1b3966404

**Comment by chenzhiwei** [comment]
thank you!
