### ISSUE TITLE
图片请使用原图链接。而不是由follow额外代理

### ISSUE THREAD

**Issue by banshaobao** [RSSNext/Follow#713]
### Describe the bug

图片请使用原图链接。而不是由follow额外代理

举个例子
follow使用的链接：
https://thumbor.follow.is/unsafe/fit-in/700x0/https%3A%2F%2Fimg.ithome.com%2Fnewsuploadfiles%2F2024%2F9%2F051bd028-51f1-40b6-b1f7-533e88ee14ca.png%3Fx-bce-process%3Dimage%2Fformat%2Cf_auto
原图链接：
https://img.ithome.com/newsuploadfiles/2024/9/051bd028-51f1-40b6-b1f7-533e88ee14ca.png?x-bce-process=image/format,f_auto

理由：
1. 应该由前端来限制图片显示大小。猜想follow使用图片代理的目的是为了限制图片的宽度为700像素。但是限制图片的显示大小应该由前端来处理，而不是服务器处理
2. 更快展示图片。由于follow服务器在美国，目前这种服务器代理的做法会延长显示图片的时间，是用户感知级别的。原本很多可以直接访问的图片，现在却要额外经过服务器代理
3. 避免不必要的机场流量消耗。目前图片由follow代理，follow服务器在美国，对于大陆用户来说，这些图片的流量要消耗用户的机场流量，原本可以直接访问的图片却需要科学上网了。

### Feed Info

https://www.ithome.com/rss/

### App Type

Web

### Version

v0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

chrome 129

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Direct access to the image may not be accessible, in many cases the CDN of the original image will block references from other applications, which is called anti-stealing chain.

1. use the proxy way, can be a certain degree to bypass the original picture access restrictions

2. Optimize the size of the image to improve the performance of rendering, if you directly render a large picture, then face a large number of pictures in the scene, there will be a very serious phenomenon of frame dropping.

3. Our main service area is not in mainland China, we will not optimize the network in mainland China.

**Comment by banshaobao** [comment]
@Innei 
1. 对于大陆用户来说，现在的痛点是图片显示过慢，图片需要经过follow的代理。大陆用户并不需要follow来优化大陆的网络，我们的诉求是原链接访问图片。比如inoreader就是原链接访问图片。或许follow也可以在设置里增加一个开关来设置是否原链接访问图片
2. 防盗链的问题可以用扩展程序或其他手段来处理。该问题用户可以自己处理，follow无需关心该问题。

**Comment by banshaobao** [comment]
![image](https://github.com/user-attachments/assets/eea853e1-d739-49ee-aeb5-855984b6e80f)
![image](https://github.com/user-attachments/assets/8a1c0215-feca-4ee1-9f2a-08f73d68b58a)
inoreader的做法

**Comment by banshaobao** [comment]
1. 使用原图链接
2. 设置referer为null

关于防盗链，我认为这是更好的做法。针对其他异常网址再另外处理。而不是像现在这样统一使用服务器代理。
原本rss的目的是为了减少获取信息的成本，而现在这种做法却违背了这一初衷

**Comment by banshaobao** [comment]
![1cce62a2dc37f603eb11c458fc104724](https://github.com/user-attachments/assets/9a4c945e-d12d-40a3-93df-f942d15cd9a9)
对大陆用户来说，目前的体验是非常糟糕的。我们本可以做的很好

**Comment by Innei** [comment]
@hyoban What are your thoughts?

**Comment by hyoban** [comment]
I think it may be better to use a whitelist when loading images on the client. For images that cannot be loaded directly on the web page or client, or we know that the size of the image is relatively large, access it through a proxy.

**Comment by banshaobao** [comment]
1. 【设置】里增加是否使用图片代理或使用原图链接的开关，让用户来决定。
2. 当使用原图链接访问图片时，默认设置referer为null，【设置】里可以自定义指定域名的referer。(解决防盗链问题)

这样怎么样？
或者仅针对【文章】视图使用原图链接，因为【文章】视图的图片较少，一篇文章的图片数量一般不到五张。

**Comment by DIYgod** [comment]
I think we can use image proxies for thumbnails in the list and use the original image in the content details.

There will be no hotlink protection issues in the desktop client, it may appear in the web app, but it doesn't matter.

**Comment by zxhd863943427** [comment]
In reality, there are still forums that implement hotlink protection. For example, you can take a look at :

```
rsshub://dxy/bbs/profile/thread/8335054
rsshub://txrjy/fornumtopic
```

Additionally, many of the content on https://docs.rsshub.app/routes/multimedia may also be subject to hotlink protection. This is the reason for this [issue](https://github.com/RSSNext/Follow/issues/672).

**Comment by banshaobao** [comment]
目前有进展吗或者支持时间

**Comment by DIYgod** [comment]
Done https://github.com/RSSNext/Follow/commit/d4d43451dec839b64239e1835b2ac1a1aa2478be

**Comment by banshaobao** [comment]
经测试，v0.1.2-beta.0版本图片无感刷新。大陆用户狂喜。感谢开发者做出的努力。
