### ISSUE TITLE
如何在网页中领取20 free power

### ISSUE THREAD

**Issue by zhjh0521** [RSSNext/Follow#715]
### Clear and concise description of the problem

由于这两天电脑不在身边，只有手机，有没有办法通过网页签到？

### Suggested solution

有对应的页面签到嘛，谢谢

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by banshaobao** [comment]
手机使用网页版签到即可，如果提示不支持需要缩放网页

**Comment by zhjh0521** [comment]
> 手机使用网页版签到即可，如果提示不支持需要缩放网页

网址是啥啊？

**Comment by banshaobao** [comment]
> > 手机使用网页版签到即可，如果提示不支持需要缩放网页
> 
> 网址是啥啊？

https://app.follow.is

**Comment by zhjh0521** [comment]
> > > 手机使用网页版签到即可，如果提示不支持需要缩放网页
> > 
> > 
> > 网址是啥啊？
> 
> https://app.follow.is
太感谢了
