### ISSUE TITLE
Action过滤失效

### ISSUE THREAD

**Issue by banshaobao** [RSSNext/Follow#722]
### Describe the bug

Action过滤失效
Action如图：
![image](https://github.com/user-attachments/assets/9b20d14e-d46d-4313-992a-e9490b73806b)
实际效果：
![image](https://github.com/user-attachments/assets/c7f0f026-618a-41ff-a807-5931c70beb49)

### Feed Info

https://github.com/RSSNext/Follow/releases.atom

### App Type

Web

### Version

v0.0.1-alpha.18

### Operating System

Windows 11

### Browser Info

chrome 129

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It works for future entries or you can try resubscribing
