### ISSUE TITLE
切换内容视图时由于网络延迟会导致A内容在B视图里面展示

### ISSUE THREAD

**Issue by weekend-project-space** [RSSNext/Follow#724]
### Describe the bug

建议通过监控路由等措施用AbortController 进行请求中止

### Feed Info

x

### App Type

Web

### Version

 0.0.1-alpha.18 

### Operating System

Linux

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
