### ISSUE TITLE
社交媒体对长文支持不佳

### ISSUE THREAD

**Issue by weekend-project-space** [RSSNext/Follow#725]
### Clear and concise description of the problem

长文无法展示全

### Suggested solution

点击文章时可以将文章弹框展示所有内容

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/553ba7d61f48d94b7dd2fa89538ec8bd68956d1b
