### ISSUE TITLE
小提议 增加 置顶或者排序功能

### ISSUE THREAD

**Issue by comeweb** [RSSNext/Follow#730]
### Clear and concise description of the problem

在我使用的过程中发现 好像缺少了置顶 或者 排序的功能 如果有很抱歉？可能我并没有使用到，但是我找了很久...

用户订阅的时候，或许是先订阅比较熟悉且喜欢看的，在熟悉的添加完后，才会慢慢添加小众的喜好，例如我或许会在Bilibili的关注列表里翻动，是否有值得订阅的UP主。

然而没有置顶功能，可能会导致，所有喜欢且想看的UP都被搁置在了最下面。

因此想提议增加 置顶或者排序功能

### Suggested solution

增加 置顶 或 排序功能 可以应用于目录排序 也可以进行目录内订阅的内容排序

增加“特别关心”？

或许想精准进行排序，可以通过输入数字来进行升序降序？（之前在某个应用里有看到，忘记了

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
Duplicate of #276
