### ISSUE TITLE
知网期刊的rss用不了

### ISSUE THREAD

**Issue by lszddz** [RSSNext/Follow#733]
### Describe the bug

知网是给期刊提供了rss功能的，提供的rss放到zotero里还能订阅，但在follow里订阅不了。例如这个网址：
https://navi.cnki.net/knavi/rss/HYWX

### Feed Info

rt。

### App Type

Electron / App

### Version

0.0.1 alpha18

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by yzy1228682367** [comment]
顶一下。或者希望可以支持对部分订阅源实现本地网络刷新。

**Comment by yzy1228682367** [comment]
> 知网会拒绝所有国外IP的请求，会返回一个错误页面。 希望开发者能够添加国内代理支持。 参见：[关于中国知网RSS订阅的支持 · Issue #89 · oxyry/qireader · GitHub](https://github.com/oxyry/qireader/issues/89) time: 2024/10/1 16:22:15

顶一下。或者希望可以支持对部分订阅源实现本地网络刷新。

**Comment by DIYgod** [comment]
This link is blocking access from our server, and this is not a problem we can solve.
