### ISSUE TITLE
Import OPML files support drag and drop operations directly.

### ISSUE THREAD

**Issue by newraina** [RSSNext/Follow#734]
### Clear and concise description of the problem

![CleanShot 2024-10-01 at 21 00 53@2x](https://github.com/user-attachments/assets/7df5f19d-8066-4121-8833-9b4156622bdb)

Right now, the only way to pick files is by clicking on the dashed box; dragging and dropping files into it isn't an option.

### Suggested solution

Supports drag-and-drop file functionality.

If possible, I'd be happy to submit a PR :)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
pr welcome
