### ISSUE TITLE
post内容图片最大化展示

### ISSUE THREAD

**Issue by acevsok** [RSSNext/Follow#736]
### Clear and concise description of the problem

我用过不少rss阅读软件
最后选择了ttrss。他的文章中的图片自动铺满整个可视范围，不用单独去点击看图，增加阅读效率

### Suggested solution

post内容图片最大化展示

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
For example?

**Comment by acevsok** [comment]
![blog11](https://github.com/user-attachments/assets/9ea40a9f-b211-4db0-a751-a24fd700061f)
这个图片能直接看清内容现实，不用再次点击。自动原始图片大小展示

**Comment by acevsok** [comment]
tt-rss的默认主题效果。

**Comment by acevsok** [comment]
![blog3](https://github.com/user-attachments/assets/959dac55-eec7-41bc-bf50-16958b2c2831)
这个是想要的图片效果，直接最大化，不用额外点击操作。

**Comment by acevsok** [comment]
![blog2](https://github.com/user-attachments/assets/29db853c-8b3e-4b27-8b68-05cf694fe9aa)
follow确实 排版还行。如图
but 空白了大部分的区域。不实用。

**Comment by acevsok** [comment]
文字设计规范
1.行宽

我们可以想象一下：如果一行文字过长，视线移动距离长，很难让人注意到段落起点和终点，阅读比较困难；如果一行文字过短，眼睛要不停来回扫视，破坏阅读节奏。

因此我们可以让内容区的每一行承载合适的字数，来提高易读性。

传统图书排版每行最佳字符数是55—75，实际在网页上每行字符75—85更流行。中文在14号字体时，建议35—45个文字。
查到这个。
打破不了就算了。
后续要开放插件哈。

**Comment by acevsok** [comment]
我去了真书大的开本字数多。小的字数少，
只有微信那种不考虑用户体验的，网页版才遵守教条，他那个网页版做那么差，链接那么长，就完全没动脑子，倒逼用户用它的移动版。
如图，微信网页版的用户体验。她想象的用户都是竖屏的，分辨率都是1080*1920的。是的连1920*1080都不是的。
![微信](https://github.com/user-attachments/assets/9f76f968-1450-4062-b794-207f8d386c7f)
