### ISSUE TITLE
深度用户。三栏影响正文显示，除非是双屏估计才行。

### ISSUE THREAD

**Issue by acevsok** [RSSNext/Follow#738]
### Clear and concise description of the problem

三栏虽然首次阅读效果不错。适合好久不打开快速看标题。
若果每天都看，完全双栏就可以。直接看内容快速略过。可以增加样式的切换功能，适配各种用户。

### Suggested solution

三栏虽然首次阅读效果不错。适合好久不打开快速看标题。
若果每天都看，完全双栏就可以。直接看内容快速略过。可以增加样式的切换功能，适配各种用户。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #395

**Comment by Innei** [comment]
按下 `CMD+B` 切换两栏布局。

---

Press `CMD+B` to switch the two-column layout.

**Comment by acevsok** [comment]
pc win10ltsc  按了ctrl+ B 窗口+B  都没有任何反应，输入法切换后也是没反应的。

**Comment by TonyRL** [comment]
Try `[` instead.

**Comment by acevsok** [comment]
ctrl+[  win+[  ?

**Comment by acevsok** [comment]
只有[ 这个 懂了.
虽然显示的是文章列表和文政详情页.也算是两栏吧.谢谢.
