### ISSUE TITLE
获取订阅源出错

### ISSUE THREAD

**Issue by jisongniu** [RSSNext/Follow#744]
### Describe the bug

正在导入ins的订阅。成功了快10个之后，显示：
Feed 获取错误: [GET] "http://10.1.32.41/picnob/user/%20albarrancabrera?format=json": 503 Service Unavailable

bg：
- 我的网络是正常能够访问ins的
- 连续尝试了好几个都失败了

device & version
Environment  **App Version**: 0.0.1-alpha.18 **OS**: macOS **User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.18 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36 **Env**: electron **Browser**: Chrome

### Feed Info

albarrancabrera

luka.khabelashvili

[samalive](https://www.instagram.com/samalive)

### App Type

Web

### Version

0.0.1-alpha.18

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
This link is incorrect, you should not add `@` before username.
