### ISSUE TITLE
Some other readers can subscribe to the feed without following the recognizable feed

### ISSUE THREAD

**Issue by ydivho12123** [RSSNext/Follow#751]
### Describe the bug

https://www.digforfire.net/?feed=rss2
This follow cannot be subscribed, qireader, feeder, inoreader, etc. can be subscribed normally

### Feed Info

https://www.digforfire.net/?feed=rss2

### App Type

Web

### Version

v0.0.1-alpha.18

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I think this is because the site blocks access from the follow server, similar to https://github.com/RSSNext/Follow/issues/733

**Comment by DIYgod** [comment]
This link is blocking access from our server, and this is not a problem we can solve.

<img width="664" alt="image" src="https://github.com/user-attachments/assets/fddb09fd-f4d8-41d3-b4d9-0b156f3be05c">
