### ISSUE TITLE
xiaohongshu订阅失败

### ISSUE THREAD

**Issue by allen-freedom** [RSSNext/Follow#753]
### Describe the bug

无法订阅，显示503

### Feed Info

![Snip20241003_81](https://github.com/user-attachments/assets/d8d8a4fd-0649-467d-b7ff-226bdb3b9be2)

### App Type

Electron / App

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
956074646 is not a valid xiaohongshu user-id

**Comment by shiyiya** [comment]
Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/598d1caf82ec39134673246e/notes?format=json": 503 Service Unavailable

> 956074646 is not a valid xiaohongshu user-id
