### ISSUE TITLE
拖动订阅源分类或排序

### ISSUE THREAD

**Issue by gitwuneng** [RSSNext/Follow#759]
### Clear and concise description of the problem

无法通过拖动订阅源进行分类

### Suggested solution

在订阅源列表中，通过拖动或者单选、点选、框选等方式对订阅源进行分类或排序

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by acevsok** [comment]
支持 用户体验提升。

**Comment by hyoban** [comment]
Duplicate of #272, let’s track it there
