### ISSUE TITLE
Image is grey in Pictures View

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#764]
### Describe the bug

As shown in the video, in picture view, when you click on the details page of an item, the picture cannot be displayed and is always gray.

### Feed Info

rsshub://voronoiapp/latest

### Reproduction Video

https://github.com/user-attachments/assets/328d1a27-b57f-4d70-a17c-a8ec2baeb763

### App Type

Web

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by cesaryuan** [comment]
This bug is introduced in 14c7028347b22eb1cf768d5c3a4c20ffe9497b93, which set the img maxWidth and maxHeight. But the media's width and height is zero (I don't know why it is 0, this is the result returned by /entries api)

![image](https://github.com/user-attachments/assets/525e8f7b-57d5-4d21-91c9-e1be24ba95ee)

**Comment by Innei** [comment]
@hyoban Follow up this plz
