### ISSUE TITLE
文章列表鼠标划过设为已读改为鼠标单击设为已读。

### ISSUE THREAD

**Issue by gitwuneng** [RSSNext/Follow#774]
### Clear and concise description of the problem

文章列表鼠标划过设为已读改为鼠标单击设为已读。

### Suggested solution

文章列表鼠标划过设为已读改为鼠标单击设为已读。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
You can turn it off in settings

![ScreenShot 2024-10-06 09 17 22](https://github.com/user-attachments/assets/12bf3eaa-ce30-4513-b3af-f2f8bdfbbc8a)
