### ISSUE TITLE
Threads 目前會出錯

### ISSUE THREAD

**Issue by Raymondhou0917** [RSSNext/Follow#776]
### Describe the bug

抓取動態時發生錯誤: [GET] "http://10.1.32.41/threads/raymond0917?format=json": 503 Service Unavailable

![CleanShot 2024-10-06 at 09 31 28@2x](https://github.com/user-attachments/assets/fd01cc79-4a00-42e3-ab13-60cdf759d402)

### Feed Info

https://www.threads.net/@raymond0917

### App Type

Electron / App

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
