### ISSUE TITLE
自定义获取新内容的自动刷新间隔

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#777]
### Clear and concise description of the problem

提供一个设置界面，用户可以根据个人需求自定义订阅源内容的刷新间隔

可选的刷新间隔为：5、10、15、20、25、30、40、50、60、120、180、360、480、1440 分钟（即一天）。

类似于下图的效果：
![image](https://github.com/user-attachments/assets/ad779c0d-1a36-4fed-a2f4-c12b21f92bef)

### Suggested solution

- **用户可以更改默认的刷新频率，也可以单独为特定的订阅源设置不同的自动刷新时间（右键编辑订阅源即可调节）**
- 该功能界面应简单易用，能快速找到并更改此设置

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by acevsok** [comment]
刚需。支持.

**Comment by DIYgod** [comment]
This is impossible to implement in a multi-user architecture, which would add an unacceptable cost to the server.

**Comment by mailela** [comment]
> [FOL-356 自定义设置自动扫描新内容的时间](https://linear.app/follow-app/issue/FOL-356/自定义设置自动扫描新内容的时间)

me too
