### ISSUE TITLE
Cannot login when developing in electron `pnpm run dev`.

### ISSUE THREAD

**Issue by cesaryuan** [RSSNext/Follow#778]
### Describe the bug

I want to add a feature to Follow running in electron, so I ran `pnpm run dev`. But when I click `Log in with Github`, it will prompt that it cannot connect to `http://localhost:3000/auth/error`, I checked the ports that the process is listening on, and indeed there is no 3000.

![image](https://github.com/user-attachments/assets/39db90d3-f4f4-411c-853d-465d106174c0)

This is the log of `pnpm run dev`:
```
E:\desktop\Follow [fix-zero-size ≡]> pnpm run dev

> Follow@0.0.1-alpha.19 dev E:\desktop\Follow
> electron-vite dev

vite v5.4.7 building SSR bundle for development...
✓ 1840 modules transformed.
dist/main/multipart-parser-DuTErqOc.js      6.68 kB
dist/main/index-BrYzvZG-.js                48.01 kB
dist/main/index-Cbk4dfWk.js               379.89 kB
dist/main/index.js                      2,704.05 kB
✓ built in 3.68s

build the electron main process successfully

-----

vite v5.4.7 building SSR bundle for development...
✓ 2 modules transformed.
dist/preload/index.mjs  2.82 kB
✓ built in 10ms

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...


[main] env loaded: {
  VITE_WEB_URL: 'http://localhost:5173',
  VITE_API_URL: 'http://localhost:3000',
  VITE_IMGPROXY_URL: 'http://localhost:2873',
  VITE_INBOXES_EMAIL: '@follow.re'
}
10:08:59.256 (main) > http://localhost:5173
(node:2352) ExtensionLoadWarning: Warnings loading extension at C:\Users\cesar\AppData\Roaming\Follow (dev)\Follow\extensions\lmhkpmbekcpmknklioeibfkpmmfibljd:
  Permission 'notifications' is unknown or URL pattern is malformed.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(Use `electron --trace-warnings ...` to show where the warning was created)
Added Extension:  Redux DevTools
Added Extension:  React Developer Tools
10:09:03.188        > Follow: Next generation information browser https://github.com/RSSNext/follow
10:09:03.189        > Initialize Follow...
10:09:03.194        > migration took 5ms
10:09:03.194        > hydrateSettings took 4ms
10:09:03.195        > setting sync took 5ms
10:09:03.195        > i18n took 4ms
10:09:03.351        > hydrateDatabaseToStore took 156ms
10:09:03.351        > Initialize Follow done, 162ms
10:09:04.096        > App is ready 4790ms
10:09:04.099        > App is ready 4792ms
10:09:04.197        > dayjs loaded:  zh-cn
10:09:04.197        > dayjs loaded:  zh-cn
```

This is my `.env` file:
```
VITE_WEB_URL=http://localhost:5173
VITE_API_URL=http://localhost:3000
VITE_IMGPROXY_URL=http://localhost:2873
VITE_SENTRY_DSN=
VITE_BUILD_TYPE=production
VITE_POSTHOG_KEY=
```

### Feed Info

None

### App Type

Electron / App

### Version

latest

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
```
vite v5.4.8 building SSR bundle for development...
✓ 2 modules transformed.
dist/preload/index.mjs  2.82 kB
✓ built in 19ms

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...
```

**Comment by cesaryuan** [comment]
> ```
> vite v5.4.8 building SSR bundle for development...
> ✓ 2 modules transformed.
> dist/preload/index.mjs  2.82 kB
> ✓ built in 19ms
> 
> build the electron preload files successfully
> 
> -----
> 
> dev server running for the electron renderer process at:
> 
>   ➜  Local:   http://localhost:5173/
>   ➜  Network: use --host to expose
> 
> start electron app...
> ```

@hyoban . Hi, can you tell me what this means? what should I do?

**Comment by hyoban** [comment]
Oh, I see your problem, you should use `VITE_API_URL=https://api.follow.is`

**Comment by hyoban** [comment]
At the same time, you may also want to take a look at https://github.com/RSSNext/Follow/issues/672
