### ISSUE TITLE
搜索订阅时显示订阅源最后接收消息的时间及近期有效性

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#781]
### Clear and concise description of the problem

搜索订阅源时，目前无法看到该源的最近更新状态。为了帮助用户判断订阅源的活跃性，建议增加一个功能，在搜索结果中显示每个订阅源最后接收消息的时间，并指示该源是否在近期有效（活跃）。

### Suggested solution

- 帮助用户快速判断订阅源的活跃状态，避免订阅已失效或长时间不更新的源
- 提升订阅源管理的效率，优化内容获取的精准度

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
Duplicate of #782
