### ISSUE TITLE
Blog Post Duplication When Subscrib: All Posts Except Latest Appear Twice

### ISSUE THREAD

**Issue by yikZero** [RSSNext/Follow#783]
### Describe the bug

When I use the follow feature to go through the normal process of subscribing to my own blog, all posts except for the most recent one appear twice.

rss realization method reference: [https://docs.astro.build/en/guides/rss/](https://docs.astro.build/en/guides/rss/)

![Roominess blog Duplication](https://github.com/user-attachments/assets/b62ba8ff-c198-4e15-af13-bd1fb8d1b298)

### Feed Info

Feed ID: [41480342800647168](https://app.follow.is/feed/41480342800647168)

Feed URL: [https://ro.yikzero.com/rss.xml](https://ro.yikzero.com/rss.xml)

### Reproduction Video

https://github.com/user-attachments/assets/37a2c069-51fd-4a88-84ab-46aa2fe027cd

### App Type

Web

### Version

0.0.1-alpha.19

### Operating System

macOS

### Browser Info

**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 **Env**: web **Browser**: Chrome

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
![ScreenShot 2024-10-06 11 40 23](https://github.com/user-attachments/assets/6e9f1ace-05e1-43f3-a886-278659343a87)

You recently modified the article slug, and a different guid appears.

**Comment by yikZero** [comment]
Yes, this was an adjustment I made recently. I changed all article links from /posts/[slug] to /blog/[slug], and /posts/[slug] has been redirected to /blog/[slug]. Currently, you can't see any links starting with /posts in the RSS feed. Or is there a way to refresh the cache?

I've already dealt with it and it's still a duplicate, so that's not right, is it?  :《

@hyoban

**Comment by yikZero** [comment]
And I don't see the duplicate issue coming up on the Follow list page of my RSS blog:

https://app.follow.is/feed/41480342800647168

![RoShot 2024-10-06 at 11 57 13@2x](https://github.com/user-attachments/assets/9911577d-01ca-4f60-bf14-bc56697c09e1)

**Comment by hyoban** [comment]
Previous entries are already in the database, we don't detect which entries are duplicates of existing entries based on content, this is how RSS works
