### ISSUE TITLE
v0.0.1-alpha.19 的在浏览器打开快捷键失效

### ISSUE THREAD

**Issue by Sunsh4j** [RSSNext/Follow#784]
### Describe the bug

如题

### Feed Info

*

### App Type

Electron / App

### Version

v0.0.1-alpha.19

### Operating System

Windows 10

### Browser Info

chrome

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
@lawvs Since the last time we replaced the open in browser logic with view content source, the shortcut is not working according to the current shortcut implementation logic. The reason is that the entry action is not bound. Do you have any ideas for this?

**Comment by lawvs** [comment]
In https://github.com/RSSNext/Follow/pull/655, the "Open in New Tab" action in the toolbar has been replaced with "View Source Content," causing this issue. I will try to fix it after discussing the new shortcut design.

**Comment by Innei** [comment]
On windows, the meta key mapping should point to ctrl, this is a design error, I'll fix it later.

**Comment by Innei** [comment]
> When wide mode is enabled and the appearance is set to dark mode, there is an issue when clicking on an article.
> 
> ![image](https://private-user-images.githubusercontent.com/43169575/374638657-d6738dd4-48d1-4d02-8e33-5a7eda929b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDQwMDIsIm5iZiI6MTcyODQwMzcwMiwicGF0aCI6Ii80MzE2OTU3NS8zNzQ2Mzg2NTctZDY3MzhkZDQtNDhkMS00ZDAyLThlMzMtNWE3ZWRhOTI5YjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE2MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NTE3NWE4OWYxNmI1MzBiMzUwNWJlNGVhOGUzM2IwZTc2ZDgzNjY5MjY4NTBlYTY5YzhiODAzNDUwYWY1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n609M9I2lsX0WZ5pyhKAdfBWkYQYPWz3DLL6ueqXGQ4)

This bug is already fixed in nightly version

**Comment by xuzhe1224** [comment]
+1  0.0.1-nightly.20241016 Mac 版本，依旧无效

**Comment by Innei** [comment]
@whitewater 👀

**Comment by hikerpig** [comment]
Mac 客户端 依旧无效

### Environment

**App Version**: 0.1.1-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.1-beta.1 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by lawvs** [comment]
Fixed in https://github.com/RSSNext/Follow/pull/1566
