### ISSUE TITLE
v0.0.1-alpha.19 视频订阅页面不能滚动，且订阅的链接不能多次编辑

### ISSUE THREAD

**Issue by xiantiao** [RSSNext/Follow#794]
### Describe the bug

订阅的链接只能编辑订阅一次，再次编辑就不显示编辑页面，需要退出程序才能再次编辑，再次编辑也只能编辑一次

### Feed Info

无

### App Type

Electron / App

### Version

v0.0.1-alpha.19

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
