### ISSUE TITLE
在mac端，编辑弹窗会闪退

### ISSUE THREAD

**Issue by leylatop** [RSSNext/Follow#802]
### Describe the bug

在mac端command+q强制退出再重启后，第二次编辑订阅，编辑弹窗会闪退。第一次编辑订阅时，弹窗是正常的，后续就再也不正常了

### Feed Info

系统 macos Monterey Version 12.5.1 (21G83)

### App Type

Electron / App

### Version

0.0.1-alpha.19

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
