### ISSUE TITLE
桌面客户端的网络代理没有工作

### ISSUE THREAD

**Issue by icealtria** [RSSNext/Follow#807]
### Describe the bug

![image](https://github.com/user-attachments/assets/3837ab2a-568e-4c7f-acd6-a9ad3e02b7c8)
尝试过 `http://127.0.0.1:7890` `socks://127.0.0.1:7890` `socks5://127.0.0.1:7890`
重启软件后，我观察代理软件的客户端，发现没有任何跟 follow.is 有关的连接。

### Feed Info

no

### App Type

Electron / App

### Version

v0.0.1-alpha.19

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
为了防止用户填写格式错误导致 follow 无法使用，proxy 选项有比较严格的格式校验，你可以试试直接填入 `socks5://127.0.0.1:7890`
