### ISSUE TITLE
cannot subscribe 

### ISSUE THREAD

**Issue by foxvip** [RSSNext/Follow#809]
### Describe the bug

can not subscribe ID: 61044248531784704

### Feed Info

Feed 获取错误: [GET] "http://10.1.32.41/follow/profile/61044248531784704?format=json": 503 Service Unavailable

### App Type

Electron / App

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TonyRL** [comment]
This user does not exist https://app.follow.is/profile/61044248531784704.

**Comment by foxvip** [comment]
how about this: https://app.follow.is/list/61044248531784704

**Comment by foxvip** [comment]
https://app.follow.is/list/61044248531784704

**Comment by TonyRL** [comment]
It works.

<details><summary>Screenshot</summary>

![Follow](https://github.com/user-attachments/assets/97d405d9-83b2-44d6-96df-dbd91d07cc0e)
</details>
