### ISSUE TITLE
一些 UI 和操作上的 BUG / Some UI and operational bugs

### ISSUE THREAD

**Issue by jerryc127** [RSSNext/Follow#811]
### Describe the bug

一些 UI 和操作上的 BUG

1.  翻译过后的标题， 标题上的 hover 显示原标题溢出，显示不完全
![image](https://github.com/user-attachments/assets/b49a763a-879e-4ca3-8e83-a970e957e193)

2. 宽模式下，列表上的标题 hover 显示原标题宽度过小
![image](https://github.com/user-attachments/assets/7aa0dbed-2cc7-4438-99cf-8fee81669def)

3. 自己的个人档案下，分类右边的展开/收缩图标 溢出屏幕外
![image](https://github.com/user-attachments/assets/fde7c13e-f53c-4b57-a1b2-1d0b9f868022)

4. 当分类标题过长时，会导致所有的展开/收缩图标会被挤出屏幕外
![image](https://github.com/user-attachments/assets/f2bfa515-dc56-4f68-9f04-cafe7427852e)

5. pc应用程序夜间模式下，偶尔会出现文章页背景颜色异常
![image](https://github.com/user-attachments/assets/ff0b6950-db22-472c-8722-61c4974bc4e8)

6. 列表日期这里会显示 [object object], 而且只在语言是香港繁体的情况下才会出现，其它语言下都正常
![image](https://github.com/user-attachments/assets/3ba8fb2d-62f7-4460-af17-132bbf06f14e)

7. pc 应用程序的分享是还没做还是 bug ?
![image](https://github.com/user-attachments/assets/b40d7ace-0af6-4f82-9f24-0f97bbe40f35)

8. pc 应用程序标记全部为已读的动效和位置有问题
![recording](https://github.com/user-attachments/assets/aa577447-8923-4f1c-b19b-473226094419)

9. pc 应用程序，媒体点击大图，右下角的两个按钮无法点击
![image](https://github.com/user-attachments/assets/cf354c07-e4b5-49e7-aada-80735f6fccd5)

10.  win10 点击左下角升级，软件被删除，但是新的没有安装 https://github.com/RSSNext/Follow/issues/448
11. 弹出框顶部与软件顶部重合时，弹出框顶部关闭按钮点击无反应 https://github.com/RSSNext/Follow/issues/577

....

3 - 4 我看了下，可以把这个 div 的 `display: table` 去掉，给 h3 加个 truncate 就可以解决这个问题，但是我没找到这个style是谁添加的 
![image](https://github.com/user-attachments/assets/c53f1085-34f2-4597-ba3c-b7862fc7af65)

---

Some UI and operational bugs

1. The translated title, the hover on the title shows that the original title overflows and the display is incomplete.
![image](https://github.com/user-attachments/assets/b49a763a-879e-4ca3-8e83-a970e957e193)

2. In wide mode, hovering the title on the list shows that the width of the original title is too small.
![image](https://github.com/user-attachments/assets/7aa0dbed-2cc7-4438-99cf-8fee81669def)

3. Under your own profile, the expand/collapse icon on the right side of the category overflows the screen.
![image](https://github.com/user-attachments/assets/fde7c13e-f53c-4b57-a1b2-1d0b9f868022)

4. When the category title is too long, all expand/collapse icons will be squeezed out of the screen.
![image](https://github.com/user-attachments/assets/f2bfa515-dc56-4f68-9f04-cafe7427852e)

5. In the night mode of the PC application, the background color of the article page may occasionally appear abnormal.
![image](https://github.com/user-attachments/assets/ff0b6950-db22-472c-8722-61c4974bc4e8)

6. [object object] will be displayed here in the list date, and it will only appear when the language is Hong Kong Traditional. It will be normal in other languages.
![image](https://github.com/user-attachments/assets/3ba8fb2d-62f7-4460-af17-132bbf06f14e)

7. Is the sharing of PC applications not done yet or is it a bug?
![image](https://github.com/user-attachments/assets/b40d7ace-0af6-4f82-9f24-0f97bbe40f35)

8. There is a problem with the animation and position of the PC application marking all as read
![recording](https://github.com/user-attachments/assets/aa577447-8923-4f1c-b19b-473226094419)

9. In PC applications, when clicking on the media to enlarge the picture, the two buttons in the lower right corner cannot be clicked.
![image](https://github.com/user-attachments/assets/cf354c07-e4b5-49e7-aada-80735f6fccd5)

10. Click upgrade in the lower left corner of win10, the software is deleted, but the new one is not installed https://github.com/RSSNext/Follow/issues/448
11. When the top of the pop-up box coincides with the top of the software, there is no response when clicking the close button at the top of the pop-up box https://github.com/RSSNext/Follow/issues/577

....

3 - 4 I took a look and found that this problem can be solved by removing the `display: table` from this div and adding a truncate to h3, but I didn’t find out who added this style.
![image](https://github.com/user-attachments/assets/c53f1085-34f2-4597-ba3c-b7862fc7af65)

### Feed Info

.

### App Type

Web

### Version

newest

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Can you provide more information on repro 3?

**Comment by jerryc127** [comment]
> ~Can you provide more information on repro 3? Or is it the same problem as 4?~
> 
> * 1,2 fixed in [58d251e](https://github.com/RSSNext/Follow/commit/58d251e6e40f3b41d99528411d2a90e65bd519da)
> * 3,4 fixed in [3edee63](https://github.com/RSSNext/Follow/commit/3edee63a5a9f691481c8532ba524d541ca09c539)
> * 5 fixed in [6697ff5](https://github.com/RSSNext/Follow/commit/6697ff58b30a1f4838fdca3820c725457ec483d4)
> * 6 fixed in [892ceb2](https://github.com/RSSNext/Follow/commit/892ceb2269ec553049c86a8b295c0a08e5649b04)
> * 7 fixed in [c520448](https://github.com/RSSNext/Follow/commit/c52044884770dcb9292f53e0d269e54d5561e51b)
> 
> I can't reproduce 8

windows 11

![recording](https://github.com/user-attachments/assets/75394391-376f-4358-be8e-9d2d7bc9955e)

**Comment by Innei** [comment]
> ~Can you provide more information on repro 3? Or is it the same problem as 4?~
> 
> * 1,2 fixed in [58d251e](https://github.com/RSSNext/Follow/commit/58d251e6e40f3b41d99528411d2a90e65bd519da)
> * 3,4 fixed in [3edee63](https://github.com/RSSNext/Follow/commit/3edee63a5a9f691481c8532ba524d541ca09c539)
> * 5 fixed in [6697ff5](https://github.com/RSSNext/Follow/commit/6697ff58b30a1f4838fdca3820c725457ec483d4)
> * 6 fixed in [892ceb2](https://github.com/RSSNext/Follow/commit/892ceb2269ec553049c86a8b295c0a08e5649b04)
> * 7 fixed in [c520448](https://github.com/RSSNext/Follow/commit/c52044884770dcb9292f53e0d269e54d5561e51b)
> * 9 fixed in [b18e4a2](https://github.com/RSSNext/Follow/commit/b18e4a2bd4f4266e4e44da17b3deac9826570322)
> 
> ~I can't reproduce 8~

8: Windows has a `paddingTop` for the title bar which is a constant `ElECTRON_CUSTOM_TITLEBAR_HEIGHT`

**Comment by jerryc127** [comment]
> > ~Can you provide more information on repro 3? Or is it the same problem as 4?~
> > 
> > * 1,2 fixed in [58d251e](https://github.com/RSSNext/Follow/commit/58d251e6e40f3b41d99528411d2a90e65bd519da)
> > * 3,4 fixed in [3edee63](https://github.com/RSSNext/Follow/commit/3edee63a5a9f691481c8532ba524d541ca09c539)
> > * 5 fixed in [6697ff5](https://github.com/RSSNext/Follow/commit/6697ff58b30a1f4838fdca3820c725457ec483d4)
> > * 6 fixed in [892ceb2](https://github.com/RSSNext/Follow/commit/892ceb2269ec553049c86a8b295c0a08e5649b04)
> > * 7 fixed in [c520448](https://github.com/RSSNext/Follow/commit/c52044884770dcb9292f53e0d269e54d5561e51b)
> > * 9 fixed in [b18e4a2](https://github.com/RSSNext/Follow/commit/b18e4a2bd4f4266e4e44da17b3deac9826570322)
> > 
> > ~I can't reproduce 8~
> 
> 8: Windows has a `paddingTop` for the title bar which is a constant `ElECTRON_CUSTOM_TITLEBAR_HEIGHT`

也许可以优化下动画效果，你可以看到在消失之前，停顿了一会

**Comment by jerryc127** [comment]
@hyoban 宽屏模式下，文章页标题，翻译原文的 tooltip 不显示
不是宽屏模式下，正常显示
![image](https://github.com/user-attachments/assets/91f1e03b-7512-4312-ade8-8ab72e6f7970)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/71abbc9b8e0954b0ef6b4d65709b40222b8acc81
