### ISSUE TITLE
Power 领取接口500

### ISSUE THREAD

**Issue by leylatop** [RSSNext/Follow#814]
### Describe the bug

![image](https://github.com/user-attachments/assets/984d9f65-738c-4c57-af35-15334d516ccc)

### Feed Info

领取Power接口500，客户端和浏览器端都是500

### App Type

Web

### Version

0.0.1-alpha.19

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by JiuRanYa** [comment]
Same problem.

**Comment by Takagoz** [comment]
Same problem.

**Comment by SHLE1** [comment]
Same problem.

**Comment by Bruce-1988** [comment]
+1

**Comment by Bruce-1988** [comment]
![image](https://github.com/user-attachments/assets/e2b0b548-f84f-4817-bc07-656ff147c729)

**Comment by qiuyueovo** [comment]
I am in the same situation now, it has been two days. Occasionally I can claim it successfully, but I have not actually claimed the power.

**Comment by JaminYe** [comment]
Same problem.

**Comment by CQyanglinbo** [comment]
me too,but at afternoon,i relogin,then i can get the power rightly. why?

**Comment by Innei** [comment]
We have fixed this problem. You can try again now.

**Comment by JaminYe** [comment]
That didn't fix it, and now it can't be receive anymore

**Comment by qiuyueovo** [comment]
> We have fixed this problem. You can try again now.

Yes, I already claimed it yesterday. No problem. But this morning I tried to claim it but failed. It was the same problem as yesterday. Unable to claim it. This claim is very unstable.

**Comment by qiuyueovo** [comment]
> > We have fixed this problem. You can try again now.
> 
> Yes, I already claimed it yesterday. No problem. But this morning I tried to claim it but failed. It was the same problem as yesterday. Unable to claim it. This claim is very unstable.

I just tried it again. It worked. But I tried it many times today. It is not stable.

**Comment by JiuRanYa** [comment]
I have been not received power for almost two days.

![image](https://github.com/user-attachments/assets/2b1ff607-4f1d-48f5-9ae8-dd09c6a117b5)

**Comment by hexWars** [comment]
![image](https://github.com/user-attachments/assets/534742e9-4d40-4dad-a7dc-e4fe899231dc)
I encountered a similar situation as well. After clicking the button, it keeps spinning, or it shows that the power has been successfully claimed, but the actual power amount doesn't change. The button to claim the daily power is still clickable.

**Comment by qiuyueovo** [comment]
> ![image](https://private-user-images.githubusercontent.com/61684793/375912633-534742e9-4d40-4dad-a7dc-e4fe899231dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTY5NTUsIm5iZiI6MTcyODY5NjY1NSwicGF0aCI6Ii82MTY4NDc5My8zNzU5MTI2MzMtNTM0NzQyZTktNGQ0MC00ZGFkLWE3ZGMtZTRmZTg5OTIzMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAxMzA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDkyMTQ0MDE4ZmJkMjViZDlkMjI1ZDFhM2FkMTIyM2EwMjliYjRhZTJkNjBkM2RmM2FmYmY1OWY3ZDg1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oGlbTEeQeCRLwBQ7YjmtC7VGioVkT2WgmcKLduCLJF0) I encountered a similar situation as well. After clicking the button, it keeps spinning, or it shows that the power has been successfully claimed, but the actual power amount doesn't change. The button to claim the daily power is still clickable.

Yes, I'm having this problem again.

**Comment by leylatop** [comment]
I think it's because there are more people  get power in every morning and the server is unstable.

**Comment by qiuyueovo** [comment]
Now I feel that the location for receiving power is very unstable

**Comment by qiuyueovo** [comment]
I'll try again after some time.

**Comment by markyun** [comment]
me too ，现在还是这样

**Comment by markyun** [comment]
invitations 接口

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
