### ISSUE TITLE
UI glitches

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#816]
### Describe the bug

1. Open the Discover page
2. Scroll down the page
3. Observe the title bar carefully. (There's a full white bar above the Mica Discover bar. Similarly, it is a black bar in the dark mode.)
5. Hover routes with long name. (The grids wiggle)

### Environment

**App Version**: 0.0.1-alpha.19
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.19 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

N/A

### Reproduction Video

<details>
<summary>Screen recording</summary>

![Follow](https://github.com/user-attachments/assets/a9875652-acbf-4112-9bdf-ccd1ca67db56)
</details>

### App Type

Electron / App

### Version

0.0.1-alpha.19

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/f5f521300f59a0194a349342d2990e2c5d4bfd63
