### ISSUE TITLE
认证订阅源，但成就领取不了

### ISSUE THREAD

**Issue by Looyank** [RSSNext/Follow#819]
### Environment

**App Version**: 0.0.1-nightly.20241008
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-nightly.20241008 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

*

### Reproduction Video

https://github.com/user-attachments/assets/d313a9a0-31a5-4db3-aa81-300c5811491b

### App Type

Electron / App

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Bruce-1988** [comment]
+1

**Comment by mytudan** [comment]
我也遇到了

**Comment by hexWars** [comment]
I also met, too

**Comment by duoluodexiaoxiaoyuan** [comment]
> ### Describe the bug
> ### Environment
> **App Version**: 0.0.1-nightly.20241008 **OS**: macOS **User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-nightly.20241008 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36 **Env**: electron **Browser**: Chrome
> 
> ### Feed Info
> 
> ### Reproduction Video
>  Recording.at.2024-10-09.11.02.19.mp4 
> ### App Type
> Electron / App
> 
> ### Version
> 0.0.1
> 
> ### Operating System
> macOS
> 
> ### Browser Info
> _No response_
> 
> ### Validations
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> 
> ### Contributions
> * [ ]  I am willing to submit a PR to fix this issue
> * [ ]  I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

解决了嘛

**Comment by BlackBerry009** [comment]
> > ### Describe the bug
> 
> > ### Environment
> 
> > **App Version**: 0.0.1-nightly.20241008 **OS**: macOS **User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-nightly.20241008 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36 **Env**: electron **Browser**: Chrome
> 
> > 
> 
> > ### Feed Info
> 
> > 
> 
> > ### Reproduction Video
> 
> >  Recording.at.2024-10-09.11.02.19.mp4 
> 
> > ### App Type
> 
> > Electron / App
> 
> > 
> 
> > ### Version
> 
> > 0.0.1
> 
> > 
> 
> > ### Operating System
> 
> > macOS
> 
> > 
> 
> > ### Browser Info
> 
> > _No response_
> 
> > 
> 
> > ### Validations
> 
> > * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> 
> > * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> 
> > 
> 
> > ### Contributions
> 
> > * [ ]  I am willing to submit a PR to fix this issue
> 
> > * [ ]  I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)
> 
> 
> 
> 解决了嘛

retry more times can be successful

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
