### ISSUE TITLE
微信公众号内容，Readability排版异常

### ISSUE THREAD

**Issue by zhongdabaicaide** [RSSNext/Follow#821]
### Describe the bug

微信公众号内容，Readability排版异常，无法在应用内查看。

### Feed Info

zhu zhu

### App Type

Electron / App

### Version

62ADEB7

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Please provide feed information

**Comment by zhongdabaicaide** [comment]
导入微信公众号OPML文件时发生[
![Uploading 1728486528019.png…]()
](url)

**Comment by hyoban** [comment]
We need feed information to reproduce and fix the problem. Please feel free to open this issue again when feed information is provided.
