### ISSUE TITLE
订阅x的内容显示不完整且排版不对

### ISSUE THREAD

**Issue by Looyank** [RSSNext/Follow#829]
### Describe the bug

图片位置不对，且内容有被截断的问题。

<img width="844" alt="image" src="https://github.com/user-attachments/assets/8ff3d88d-4b1e-418e-9751-24843e1f72cd">

![image](https://github.com/user-attachments/assets/10f83a36-65af-480a-ab79-efba2750627f)

https://x.com/hellosuoha/status/1843795887702851674

### Environment

**App Version**: 0.0.1-nightly.20241008
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-nightly.20241008 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### App Type

Electron / App

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by BlackBerry009** [comment]
浏览原推文 是有展开的的功能的，看起来是 /entries 接口 content 和 description 只获取了预览的信息，没有直接拿详情展示。

**Comment by hyoban** [comment]
Social media pictures are always at the bottom

**Comment by hyoban** [comment]
https://github.com/DIYgod/RSSHub/issues/12360

**Comment by TonyRL** [comment]
Closed in https://github.com/DIYgod/RSSHub/pull/17596
