### ISSUE TITLE
Unable to subscribe to the official rss of the Wall Street Journal

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#839]
### Describe the bug

follow无法订阅华尔街日报官方的rss，但此rss链接在其他rss软件中工作正常

### Feed Info

https://cn.wsj.com/zh-hans/rss

### App Type

Electron / App

### Version

v0.0.1-alpha.19

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EnterMan123** [comment]
The same situation applies to ithome.com.

**Comment by hyoban** [comment]
I think this is because the site blocks access from the follow server, similar to https://github.com/RSSNext/Follow/issues/733

**Comment by DIYgod** [comment]
This link is blocking access from our server, and this is not a problem we can solve.
