### ISSUE TITLE
無法生成邀請碼

### ISSUE THREAD

**Issue by larryjclai** [RSSNext/Follow#841]
### Describe the bug

嘗試生成邀請碼，但顯示錯誤訊息 500

### Environment
**App Version**: 0.0.1-alpha.19
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.19 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

非 feed

### Reproduction Video

https://share.cleanshot.com/GJzTF7jY

### App Type

Electron / App

### Version

0.0.1-alpha.19

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
