### ISSUE TITLE
Blocking words have been added, but are still visible in categorized entries

### ISSUE THREAD

**Issue by EnterMan123** [RSSNext/Follow#849]
### Describe the bug

![image](https://github.com/user-attachments/assets/2d97ee38-6900-4cd1-8ce2-3efd758e11b5)

尽管已经添加了屏蔽词，并且在列表中有效地屏蔽了相关的文章，但在点击加载已归类条目后，所有已屏蔽的条目仍然出现，与其他没有触发屏蔽词的条目混合在一起。

是我的使用方式有问题吗？还不太清楚follow运作方式
我之前使用的其他软件设定了阻止规则是直接永久删除文章的

### Feed Info

X

### App Type

Electron / App

### Version

v0.0.1-alpha.19

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
It doesn't work with archived content

**Comment by EnterMan123** [comment]
![Image](https://github.com/user-attachments/assets/21bc18ae-e427-471b-b417-f944ebd219ca)

I have set up many filtering rules, but the current version automatically loads archived entries. When I scroll down, I still come across many articles I don't want to see. It seems the filtering function has lost its purpose. Can you completely remove these filtered entries? Or is there another solution to this issue?

**Comment by hyoban** [comment]
Filters only apply to the timeline. When content is removed from the timeline and archived, what you see is the archived entry, which is the same for every user.
