### ISSUE TITLE
Dynamic update feed

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#850]
### Clear and concise description of the problem

我有一个freshrss，平常都在上面看咨询，一般来说都是在上面添加订阅源，手动导入到follow还是比较麻烦且耗时的

### Suggested solution

我希望从freshrss中的API接口，动态实时更新rss订阅列表，就类似[ReadYou](https://github.com/Ashinch/ReadYou)中，集成了freshrss的API

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ICan1DO** [comment]
我也有这个需求，希望可以接入freshrss的api，毕竟freshrss的一些css脚本提取功能还挺好用的

**Comment by DIYgod** [comment]
I don't quite understand this requirement. Since you are using freshrss, why do you still need to sync subscriptions to follow?

**Comment by hexWars** [comment]
When I raised this issue, FreshRSS was still my main reader, but now Follow has replaced it.

However, FreshRSS still has many useful features, such as:

    Viewing subscriptions that haven’t been updated for 3 months, 6 months, or over a year
    Tagging functionality
    Article statistics (such as count, word count, etc.)
    Estimated reading time for articles
    Customizing the number of cached articles (currently set to 20 in Follow)

...

I use all of these features, so I’d be very happy if Follow plans to add any of them in the future.

Follow is an amazing product; Thank you.

I’ll be closing this issue now.
