### ISSUE TITLE
The visual effect of reading status is not obvious enough

### ISSUE THREAD

**Issue by imdlan** [RSSNext/Follow#858]
### Clear and concise description of the problem

**使用橘色小圆点来区分阅读状态 UI 效果不够明显**，原因有二：

1. 橘色小圆点放在列表（无论是文字列表，还是图文列表）的标题前显的比较密集并且对阅读标题是一种干扰；
2. 由于橘色小圆点比较小，用它来标识已读，未读状态并不明显；

### Suggested solution

**移除橘色小圆点来标识已读，未读状态，改用已读标题变灰来区分已读，未读状态。**

_Reeder 的已读，未读状态比较舒服，自然，体验好，如下图：_

![image](https://github.com/user-attachments/assets/0303d898-58f0-49c6-9a57-a07787c9507a)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
> 改用已读标题变灰来区分已读
 
We previously abandoned this UI implementation. Perhaps it needs to be discussed again. cc @DIYgod

**Comment by imdlan** [comment]
“如无必要，勿增实体”，这里用橘色小圆点来区分阅读状态，即密集，辨识度又不高，如下图：

_文字列表：看过的和没有看过的订阅就差一个小圆点，打开一个列表左侧重复一列小圆点，密集恐惧_ 

![image](https://github.com/user-attachments/assets/7ab7336e-a083-47f1-a092-1b26d5e1abfa)

_图文列表：更没法看了，简直找不到哪个点了，哪个没点，只能用顶部右侧未读筛选按钮了_

![image](https://github.com/user-attachments/assets/6ead8bbb-bc58-4333-8a5d-02f2d5055ec6)
