### ISSUE TITLE
Automatically create article categories and cannot delete the category

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#865]
### Describe the bug

在我从freshrss中导入后，文章会分组，这个行为是正常的

但是不确定是什么情况下，自动创建了一个新的分组`Github.io`，部分订阅跑到这个分组下，如果我想要删除该组，点击删除分类后，该分类依旧存在

### Feed Info

![image](https://github.com/user-attachments/assets/da253f30-57fb-456d-b763-1ced33237c4c)
![image](https://github.com/user-attachments/assets/1b24025d-b1f6-4d55-8e21-27bb944e037d)

删除无效

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This is automatically grouped by domain name

**Comment by hexWars** [comment]
> This is automatically grouped by domain name

Question 1: It automatically jumps out of the group, which I find very strange. 
Question 2: For subscriptions without a group, if the number is more than one, will they be automatically assigned to the domain group by default?

I speculate that the behavior of automatically exiting the group might be related to me scrolling through a large number of unread subscriptions from top to bottom.

**Comment by chenyucheng0503** [comment]
请问下如何导入FreshRss，可以跟freshrss同步收藏等信息吗？

**Comment by hyoban** [comment]
Let me try to answer it. 

- If a subscription has a category set, it will always be grouped according to this category.
- If it does not set a category, it will be grouped according to the website's domain. That is, if the number of identical domains exceeds one, they will be automatically grouped.

Now you should no longer be able to delete the default categories by domain.
