### ISSUE TITLE
Feed title and description cannot be updated

### ISSUE THREAD

**Issue by Eliot00** [RSSNext/Follow#877]
### Describe the bug

RSS的XML里title没更新，Follow爬过一次后就固定成初始名称不能改了

### Feed Info

https://app.follow.is/feed/67437090448621568

### App Type

Web

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
How long has it been since the modification?

**Comment by Eliot00** [comment]
> How long has it been since the modification?

Almost 3 hours.
