### ISSUE TITLE
为什么我这个源，一直被置顶啊?

### ISSUE THREAD

**Issue by markyun** [RSSNext/Follow#879]
### Describe the bug

如图：
<img width="689" alt="image" src="https://github.com/user-attachments/assets/12cdbe78-5590-4c21-acfe-6c1c38d19f93">
 
点击源进去，时间是对的，识别的不对。 源：https://web.dev/static/blog/feed.xml 
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/9d9ae8ea-064b-4dca-9339-409f1215be26">

### Feed Info

https://web.dev/static/blog/feed.xml

### App Type

Web

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I think this is because the feed set the wrong time for the first time, and then modified it correctly, but Follow paused the logic of updating content, and the time remained as before.

**Comment by jerryc127** [comment]
我也关注了这个订阅源
这篇文章的rss里时间是2025年 
所以就一直在顶上了

**Comment by hyoban** [comment]
Fixed now
