### ISSUE TITLE
No response after clicking to subscribe to the list, and follow points will be deducted multiple times after repeated clicks.

### ISSUE THREAD

**Issue by GeekyWizKid** [RSSNext/Follow#881]
### Describe the bug

<img width="561" alt="image" src="https://github.com/user-attachments/assets/26f23a8e-3aaa-4c85-8f4e-403a735b6602">
订阅列表时点击无响应，重复点击后大约过了几分钟发现重复扣款 看现象有点像消费队列成功了 但是没有做订阅状态的验证

### Feed Info

https://app.follow.is/list/67441780613535744?view=3 这是当时的订阅链接

### App Type

Electron / App

### Version

0.0.1-nightly.20241008

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by youaremywind** [comment]
Me too. How do I get my points back?

**Comment by markyun** [comment]
me too

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
