### ISSUE TITLE
When generating invitation codes, 202 power should only generate 2 invitation codes, prompt It can generate 3. In fact, when generating the third one, it prompts that the power is not enough.

### ISSUE THREAD

**Issue by jianjiade** [RSSNext/Follow#882]
### Describe the bug

生成邀请码的时候，202个power应该只能生成2个邀请码，提示可以生成3个，实际上生成第3个的时候，提示power不够
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/0d439a4e-b133-4a92-8fe9-e386c8846cc8">

看了下是接口返回的时候，可以生成3个。
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/eaeca830-594c-4b37-9af0-79da398126f3">

### Environment

**App Version**: 0.0.1-alpha.19
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

### App Type

Web

### Operating System

macOS

### Browser Info

Chrome

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This refers to the maximum number of invitation codes you can generate based on usage time, regardless of the number of powers you have.
