### ISSUE TITLE
Some RSS feeds cannot load full content text

### ISSUE THREAD

**Issue by PrinOrange** [RSSNext/Follow#887]
### Describe the bug

Some RSS subscription sources cannot load the full text. In the loaded RSS data, only the title and summary text were read, and the full content text content can not be loaded. 
![image](https://github.com/user-attachments/assets/34c1a4cc-e139-49ec-b719-844ec5a1f019)

But I tried other RSS readers(like QiReader) and they were all able to load the full content text.

![image](https://github.com/user-attachments/assets/4525b922-75ed-4bce-86b6-2bde3d217f79)

### Feed Info

Here is the rss feed link https://dreams.plus/rss.xml

### App Type

Web

### Version

0.0.1-alpha.19

### Operating System

Windows 11

### Browser Info

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This RSS itself does not output full-text content. You can use the Follow desktop client to enable readability.
