### ISSUE TITLE
图片模式下，点开shopify的RSS图片没法加载

### ISSUE THREAD

**Issue by miholover** [RSSNext/Follow#890]
### Describe the bug

![image](https://github.com/user-attachments/assets/f016440b-b706-430f-a919-1a21c28bcc43)
图片模式下，点开shopify的订阅图片没法加载

### Feed Info

https://whitefoxboutique.com/collections/midi-skirts.atom

### App Type

Electron / App

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
For https://whitefoxboutique.com/collections/new-arrivals.atom , I can load the image fine.

![ScreenShot 2024-10-12 11 48 28](https://github.com/user-attachments/assets/5ea7bd37-b459-4388-818f-1f7d8e18ee6d)

You can check the actual image link it loads via f12.
