### ISSUE TITLE
Unable to create category

### ISSUE THREAD

**Issue by Fan-Bob** [RSSNext/Follow#893]
### Describe the bug

Unable to add new categories Article options No entry

### Feed Info

any

### App Type

Electron / App

### Version

latest

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I don't understand your issue. Could you please describe it in detail or provide a picture?
