### ISSUE TITLE
Recommendation: Add a blocking prompt when using "Mark all as read" for selected categories.

### ISSUE THREAD

**Issue by Norvon** [RSSNext/Follow#897]
### Clear and concise description of the problem

![image](https://github.com/user-attachments/assets/d17d68ef-6087-4b3a-8666-08ffea024587)

在选择分类的时候使用 "全部标记为已读“  导致整个分类下文章全部已读。

### Suggested solution

建议在选择分类使用 “全部标记为已读” 时添加阻断性提示，可以避免误触发的时候导致全部已读。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
