### ISSUE TITLE
/invitations/new  接口一直 403错误，账号是刚刚登录的。

### ISSUE THREAD

**Issue by markyun** [RSSNext/Follow#900]
### Describe the bug

<img width="938" alt="image" src="https://github.com/user-attachments/assets/3cd536ab-27fd-4ac8-940d-3f1fc7f6230c">

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/e580e030-2aa0-41a8-9f11-1da77c433bde">

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/1d0a1ba3-afd3-486a-a6a8-08e57011dc47">

### Feed Info

null

### Reproduction Video

null

### App Type

Web

### Version

0.0.1

### Operating System

macOS

### Browser Info

null

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by imrayyu** [comment]
same here looks like something wrong with settings. the rss still working

**Comment by resticDOG** [comment]
Same issue here

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
