### ISSUE TITLE
[bug] When the [mark as read when hovering] option is enabled, moving the mouse over the first subscription causes Follow to continuously mark the feed as read.

### ISSUE THREAD

**Issue by Ice-Hazymoon** [RSSNext/Follow#901]
### Describe the bug

When the [mark as read when hovering] option is enabled, moving the mouse over the first subscription causes Follow to continuously mark the feed as read.

### Environment

**App Version**: 0.0.1-alpha.20
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.20 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### Feed Info

-

### Reproduction Video

https://github.com/user-attachments/assets/c1aa505b-b14d-433e-b222-8290e14601cb

### App Type

Web

### Version

0.0.1-alpha.20

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by leohooho** [comment]
新版本真的太吓人 没有测试吗

**Comment by Dengwii** [comment]
我也碰到了，卸载了之后安装19版本，再升级到20，莫名就好了
