### ISSUE TITLE
0.0.1-alpha.20 why cancel Power feature?

### ISSUE THREAD

**Issue by BlackBerry009** [RSSNext/Follow#903]
### Describe the bug

<img width="189" alt="image" src="https://github.com/user-attachments/assets/419362c8-35f1-48e2-8f82-bdd958a21e13">

### Feed Info

.

### App Type

Electron / App

### Version

0.0.1

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by missuo** [comment]
<img width="262" alt="image" src="https://github.com/user-attachments/assets/d5bbf975-7786-41ac-b9dd-cb4a787e368c">

**Comment by BlackBerry009** [comment]
> <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/55200481/375938066-d5bbf975-7786-41ac-b9dd-cb4a787e368c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTk0NzgsIm5iZiI6MTcyODcxOTE3OCwicGF0aCI6Ii81NTIwMDQ4MS8zNzU5MzgwNjYtZDViYmY5NzUtNzc4Ni00MWFjLWI5ZGQtY2I0YTc4N2UzNjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZWE0ZWZkODM1YTQ4NDhlYzQ4N2YzZDgzZDQyNjI1NTRjYWI0NjJhMDYzNjZjOTU5YTQ5ZjIwMWQ5MmMwYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p4QCnEjekjzPGvEDnBAMk7yQkgKyebGLfulxSVV-6M4">

fine, the page is crashed when I open it..
