### ISSUE TITLE
Error getting feed

### ISSUE THREAD

**Issue by whrss9527** [RSSNext/Follow#905]
### Describe the bug

订阅这个 [rss](https://whrss.com/feed) 时，预览解析出错，但是查看提示对应位置，未发现无效字符
在 web 端也出现了这个问题
<img width="607" alt="image" src="https://github.com/user-attachments/assets/f36aaf46-7f1c-4f51-8602-c35c461dc08e">

### Feed Info

https://whrss.com/feed

### App Type

Electron / App

### Version

0.0.1-nightly.20241011

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
I think there is something wrong with the output of this source itself and therefore cannot be parsed by [rss-parser](https://github.com/rbren/rss-parser)

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwhrss.com%2Ffeed
