### ISSUE TITLE
小红书订阅源头获取出错

### ISSUE THREAD

**Issue by eyaeya** [RSSNext/Follow#907]
### Describe the bug

小红书订阅源头获取出错，返回503

### Feed Info

Feed 获取错误: [GET] "http://10.1.32.41/xiaohongshu/user/957155806/notes?format=json": 503 Service Unavailable

### Environment

**App Version**: 0.0.1-alpha.20
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.20 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### App Type

Electron / App

### Version

0.0.1-alpha.20

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this user does not exist. https://www.xiaohongshu.com/user/profile/957155806
