### ISSUE TITLE
严重的问题, 新建邀请码的power被吞了, 花了100power然后邀请码也没生成

### ISSUE THREAD

**Issue by Ekuboh** [RSSNext/Follow#914]
### Describe the bug

![image](https://github.com/user-attachments/assets/91ed356f-9871-42fb-8827-ebc98eb37447)

### Feed Info

id: quibblehat
url: https://app.follow.is/profile/@quibblehat

### App Type

Web

### Operating System

Windows 10

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
A few days ago, we experienced rapid user growth, which led to blockchain concurrency issues. We have since upgraded the contract to address this problem.

Could you mention me on Discord? I'll send you a new invitation code.

**Comment by xy-galaxy** [comment]
补偿回来了吗？
