### ISSUE TITLE
Can't import the OPML file, and hints `500`

### ISSUE THREAD

**Issue by Ekuboh** [RSSNext/Follow#915]
### Describe the bug

Can't import the OPML file, it hints 500

### Feed Info

Ekuboh

### App Type

Web

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Fixed tonight, have a try
