### ISSUE TITLE
power refresh all disappear

### ISSUE THREAD

**Issue by boxsuny** [RSSNext/Follow#916]
### Describe the bug

领取每日power后，到达100power，去mint邀请码，软件提示不够，我退出再进去，也是提示不够，我点击刷新，就没啦，变成0power。

### Feed Info

<img width="874" alt="截屏2024-10-13 08 36 30" src="https://github.com/user-attachments/assets/4c05f1c0-eb1d-4b13-9d81-920f2e729a42">
<img width="804" alt="截屏2024-10-13 08 36 25" src="https://github.com/user-attachments/assets/ec2c6d05-b1dc-43d4-8c5e-ff75c158311d">
<img width="771" alt="截屏2024-10-13 08 36 19" src="https://github.com/user-attachments/assets/682b44d9-85ea-4e1a-8e43-eaa915d592a4">
<img width="854" alt="截屏2024-10-13 08 36 05" src="https://github.com/user-attachments/assets/000cb695-f1c4-4a05-8f45-300139ac7597">
<img width="875" alt="截屏2024-10-13 08 35 21" src="https://github.com/user-attachments/assets/aad9d7c2-0a40-4ff1-88e3-2cba3c0ae469">

### App Type

Electron / App

### Version

0.0.1-alpha.20

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
I think this this issue has been fixed, if the problem still exists, please feel free to reopen it.
