### ISSUE TITLE
Can not see "View Source Content" button

### ISSUE THREAD

**Issue by shenxiangzhuang** [RSSNext/Follow#920]
### Describe the bug

Can not see "View Source Content" button.

PS: When I first add this feed, which do not contain the url info. So I fix the feed xml file and add it again. But I still can not find the "View Source Content" button for the blogs.

### Feed Info

https://datahonor.com/beer/feed_rss_created.xml

### App Type

Electron / App

### Version

0.0.1-alpha.20

### Operating System

Linux

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
I think the old entries were cached by the server, and the new entries will not have this issue.

**Comment by shenxiangzhuang** [comment]
> I think the old entries were cached by the server, and the new entries will not have this issue.

Thanks for your reply! Is there any way to resolve this problem? I want the old entries can also be linked.

**Comment by hyoban** [comment]
We have temporarily disabled entry updates because this will bring greater pressure on the server.
