### ISSUE TITLE
{"code":500,"message":"No number after minus sign in JSON at position 1"}

### ISSUE THREAD

**Issue by MichaelXoXo** [RSSNext/Follow#921]
### Describe the bug

将 inoreader 订阅源导出后的 opml 文件尝试导入 follow，结果一直失败，报错：
```
{"code":500,"message":"No number after minus sign in JSON at position 1"}
```

### Feed Info

inoreader 导出的 opml 文件

### App Type

Web

### Version

 0.0.1-alpha.21

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by EuDs63** [comment]
尝试导入TinyTinyRSS到出的opml文件也会报同样的错

**Comment by DIYgod** [comment]
Fixed in https://github.com/RSSNext/follow-server/pull/127/commits/5d94f45b989d344a97f8eab3f9dce157620adf41
