### ISSUE TITLE
opml cannot be imported

### ISSUE THREAD

**Issue by zhl111** [RSSNext/Follow#922]
### Describe the bug

The opml file for my tiny tiny rss won't import follow without any other prompts!

### Feed Info

![image](https://github.com/user-attachments/assets/727771cc-26d8-482a-ac54-6218f6b38138)

### App Type

Web

### Version

1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Fixed tonight, have a try!

**Comment by hyoban** [comment]
This is the current limit. You can create up to 500 feeds.
