### ISSUE TITLE
The code blocks generated by highlight.js will be messed up in the layout by Readability.

### ISSUE THREAD

**Issue by PrinOrange** [RSSNext/Follow#928]
### Describe the bug

We noticed that some RSS source articles use [highlight.js](https://highlightjs.org/) to generate code blocks. However, these article rendered by Follow will mess up its layout.

For example, I have a RSS Feed https://dreams.plus/rss.xml 
The article [Box-Muller transformation](https://dreams.plus/blog/2024-09-12-box-muller-transformation#code-implementation) , 

We have a code block
![image](https://github.com/user-attachments/assets/15df2502-e0a6-461d-8f0f-b8d7e2d98f5e)

Firstly, we noted that codeblocks generated by hightlight.js has its features, in original html, its code-block is in form

```html
<code class="hljs language-typescript">
    <span class="hljs-keyword">function</span> 
    <span class="hljs-title function_">randInterval</span>(
    <span class="hljs-params"></span>): 
    <span class="hljs-built_in">number</span> {
    <span class="hljs-keyword">return</span> 
    <span class="hljs-title class_">Math</span>.
    <span class="hljs-title function_">random</span>();}
    <!-- ... Other codes -->
```

Only token `function`,`randInterval`,`number` could be wrapped in span tag, other symbols such as parentheses, curly brackets, and dots will be placed directly after the span tag.

So this will lead to a problem. After the code block is recognized by Follow's Readability, not only will the brackets not be recognized, but the code layout will also be messed up.

![image](https://github.com/user-attachments/assets/398bdb35-6819-41e4-abb1-e7d52614a27a)

At first, I suspected that it was a Readability's bug rather than a Follow, so I use the built-in Readability in Firefox to debug.

![image](https://github.com/user-attachments/assets/f87f65e4-ebc4-468a-bc52-8b8f4a3eaf14)

But the code layout displayed by the built-in Readability of Firefox is normal. So now we can rule out the possibility that it is a Readability's bug.

I also verified the code blocks from other blogs. [Take diygod's article for example](https://diygod.cc/unified-markdown),

![image](https://github.com/user-attachments/assets/0cbddabc-6c0d-4516-b859-2134e4c7fa95)

His code blocks were generated by shiki.js, and does not encounter this problem

![image](https://github.com/user-attachments/assets/1e81db11-fd70-4e69-a576-f28aa8451405)
![image](https://github.com/user-attachments/assets/6a03ff7f-7287-40e8-8538-111792d97c45)

So my guess now is that there might be a problem with the way Follow handles the code blocks generated by highlight.js. Only code blocks generated by highlight.js will suffer from this problem.

### Feed Info

https://diygod.cc/unified-markdown
https://dreams.plus/blog/2024-09-12-box-muller-transformation

https://[diygod.cc/feed](https://diygod.cc/feed)
https://[dreams.plus/rss.xml](https://dreams.plus/rss.xml)

**App Type:** Electron / App

**Version:** 0.0.1-alpha.21

**Operating System:** Windows 10

**Browser Info: ** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
The built-in Readability in Firefox and Follow using Readability to extract content are not the same thing.

NetNewsWire also cannot display the content you expected.

![ScreenShot 2024-10-14 11 47 58](https://github.com/user-attachments/assets/957bd300-ff9f-4c8b-aa3b-dc6887607ba7)

You should wrap the `code` with `pre` correctly.
