### ISSUE TITLE
Subscription limit exceeded

### ISSUE THREAD

**Issue by milan-chen** [RSSNext/Follow#930]
### Clear and concise description of the problem

When I make a new subscription, it says Subscription limit exceeded. Will the quantity be expanded in the future?

### Suggested solution

11

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TonyRL** [comment]
Duplicate of #1164

**Comment by hyoban** [comment]
We already have plans to allow users to expand the number of subscriptions they can create, but for now, you can't create more than 500 subscriptions
