### ISSUE TITLE
Inconsistent follower count and authentication status for the same feed

### ISSUE THREAD

**Issue by WCY-dt** [RSSNext/Follow#932]
### Describe the bug

Both https://app.follow.is/feed/63462130930273280?view=0 and https://app.follow.is/feed/68562803982861312?view=0 access the same feed: https://blog.ch3nyang.top/feed.xml, and the same feedId and userId can be seen in both. However, they show different follower counts and authentication statuses.

### Feed Info

https://app.follow.is/feed/63462130930273280?view=0
https://app.follow.is/feed/68562803982861312?view=0

### App Type

Electron / App

### Operating System

Windows 11

### Browser Info

Edge

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
In fact, they come from different sources, https vs http

```
http://blog.ch3nyang.top/feed.xml
https://blog.ch3nyang.top/feed.xml
```
