### ISSUE TITLE
The public account article layout experience is 0, and it cannot be opened in recent days, let alone Typesetting

### ISSUE THREAD

**Issue by momosirr** [RSSNext/Follow#937]
### Clear and concise description of the problem

公众号文章排版体验为0，最近几天又打不开了，更别说排版了

### Suggested solution

优化排版体验

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
I cannot find out which feed you are subscribed to, so I cannot solve this problem for now.
