### ISSUE TITLE
Consider adding a "Read it later" feature.

### ISSUE THREAD

**Issue by codemetic** [RSSNext/Follow#938]
### Clear and concise description of the problem

Sometimes I have backlogs and want to read some of posts later, or I would like to read these posts of different priorties.
So I might need a temporary lists to store them, to "read it later"

### Suggested solution

I prefer to add a "read it later" button for post items, and a list to store them.

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
We will not develop our own "Read it later" feature, but we are continuously adding integrations with third-party services, including "Read it later" services.
