### ISSUE TITLE
推特的feed不更新

### ISSUE THREAD

**Issue by georgechui** [RSSNext/Follow#939]
### Describe the bug

推特的feed不更新了，刷新也看不到，抓取到的是3天前的推文了

### Feed Info

rsshub://twitter/media/follow_app_

### Reproduction Video

![image](https://github.com/user-attachments/assets/b3be1c5c-8ae4-4cdf-9acb-1a3b9bb9a81d)

### App Type

Web

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Should be fixed now

**Comment by tommyjiang** [comment]
I still have this no twitter update problem.

**Comment by Boogaloo-XT** [comment]
same problem here

**Comment by Boogaloo-XT** [comment]
此问题仍然存在，请看此链接：[https://app.follow.is/share/feeds/41655120039539712?view=1](https://app.follow.is/share/feeds/41655120039539712?view=1)  ，已经好多天不更新了

**Comment by edgarho** [comment]
still the same problem
