### ISSUE TITLE
台前调度切换窗口时明显卡顿

### ISSUE THREAD

**Issue by ZhaoSheng2000** [RSSNext/Follow#947]
### Describe the bug

系统：macOS 13.5.1 (22G90)
问题描述：打开台前调度后，从Follow切换到任意其他app（将Follow从台前切换到app），窗口切换动画不流畅，淡出效果有明显卡顿以及掉帧。其他app间切换正常。
能否复现：必现

### Feed Info

https://app.follow.is/profile/56601130128711680

### App Type

Web

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Innei** [comment]
Can you provide a screen record?

**Comment by yuan-jiajun** [comment]
yeah，I also meet this issue，I think it is a very uncomfortable experience for users
Duplicate of https://github.com/RSSNext/Follow/issues/1168
