### ISSUE TITLE
如何唤起客户端并弹出订阅 How to evoke the client and pop up the subscription

### ISSUE THREAD

**Issue by QYG2297248353** [RSSNext/Follow#949]
### Clear and concise description of the problem

我自己的网站，我想添加一个 `订阅到Follow` 按钮
但是我不知道如何实现调用follow的方法

比如说，我站点的rss地址：[https://blog.lifebus.top/feed](https://blog.lifebus.top/feed)
我希望实现的效果：
用户点击订阅按钮，尝试唤起客户端：
有客户端：弹出尝试打开应用Follow（浏览器行为），打开后直线显示订阅弹窗
![image](https://github.com/user-attachments/assets/261492b9-d988-486d-bd00-3436ed693b82)
没有客户端：打开web页面，显示订阅弹窗或者提示登录或者是rss展示页面

这个地址也可以是Follow的订阅源地址：https://app.follow.is/feed/61356157677517824

> https://blog.lifebus.top/feed 与 https://app.follow.is/feed/61356157677517824 是一个订阅源
>
> 仅仅是地址不同

## 机器翻译 (Machine translation)

For my own website, I would like to add a "Subscribe to Follow" button
But I don't know how to implement the following method

For example, the RSS address of my site: [https://blog.lifebus.top/feed] (https://blog.lifebus.top/feed)
The effect I hope to achieve:
The user clicks the Subscribe button and attempts to evoke the client side:
There is a client side: pop-up tries to open the application Follow (browser behavior), after opening, the subscription pop-up window is displayed in a straight line
![image] (https://github.com/user-attachments/assets/261492b9-d988-486d-bd00-3436ed693b82)
No client side: open the web page, display the subscription pop-up window or prompt login or rss display page

This address can also be the Follow feed address: https://app.follow.is/feed/61356157677517824

> https://blog.lifebus.top/feed is a feed with https://app.follow.is/feed/61356157677517824 
> 
> Just the address is different

### Suggested solution

我希望能有文章告诉开发者如何使用

比如：网页嵌入 Follow 按钮

## 机器翻译 (Machine translation)

I hope there can be articles telling developers how to use 
 
For example: Embedding the Follow button on the web page

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
```
follow://add?url=xxx
```

https://github.com/DIYgod/RSSHub-Radar/blob/1477c8cc075d8230a9617e438a6f466c6a95dbfe/src/lib/quick-subscriptions.ts#L20-L27

**Comment by QYG2297248353** [comment]
> ```
> follow://add?url=xxx
> ```

感谢大佬

**Comment by QYG2297248353** [comment]
唉，还是不行，仅仅只能唤起客户端
```url
follow://add?url=blog.lifebus.top/feed
```

### 机器翻译 (Machine translation)
Alas, it still doesn't work, just arouse the client
```url
follow://add?url=blog.lifebus.top/feed
```


### Environment

**App Version**: 0.0.1-alpha.21
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.21 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by QYG2297248353** [comment]
```
follow://add?url=blog.lifebus.top/feed
follow://add?url=https://blog.lifebus.top/feed
follow://add?url=blog.lifebus.top
follow://add?url=https://blog.lifebus.top/feed
follow://add?url="https://blog.lifebus.top/feed"
```

@hyoban 
我也是把能尝试的都尝试了，效果仅仅是打开 Follow 客户端

I also tried everything I could, and the effect was just to open the Follow client

**Comment by hyoban** [comment]
https://github.com/user-attachments/assets/7a28e390-ff17-4133-98af-3af738a63609

It works for me, please check your version

**Comment by QYG2297248353** [comment]
好神奇，浏览器的地址栏就不行？

Amazing, the address bar of the browser doesn't work?

![image](https://github.com/user-attachments/assets/831fa1f7-1cee-420c-bb27-82c11bff474b)


我尝试降低版本试试
I tried lowering the version to try

**Comment by QYG2297248353** [comment]
> It works for me, please check your version

似乎我的所有Windows 客户端都不能完成此操作
仅只能唤起客户端

Windows 信息
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2023/‎7/‎17
操作系统版本	22631.4317
体验	Windows Feature Experience Pack 1000.22700.1041.0

机器翻译 (Machine translation)

It seems that all my Windows clients cannot accomplish this 
Only evoke clients 
 
Windows Information 
Version Windows 11 Professional 
Version No. 23H2 
Installation date 2023/7/17 
Operating system version 22631.4317 
体验	Windows Feature Experience Pack 1000.22700.1041.0

**Comment by QYG2297248353** [comment]
@hyoban 

确认了，windows 客户端无法唤起 Add Feed 页面


https://github.com/user-attachments/assets/f7db42dc-8af8-4750-9dd4-21c9efa83bd0


https://github.com/user-attachments/assets/dc80181c-270a-46f7-ab10-155e69a82bc2
