### ISSUE TITLE
About xml too large to be imported

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#954]
### Describe the bug

我希望导入 https://kagi.com/api/v1/smallweb/feed/ 
但是由于该订阅太过巨大，以至于无法导入follow（准确说，是多次尝试导入后，导入成功，但无法正常显示订阅，显示为空）
我之前试过其他的软件，均无法订阅，如果可以的话，希望可以支持大容量的订阅，或者明确说明多大的订阅无法导入

### Feed Info

https://kagi.com/api/v1/smallweb/feed/ 

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by DIYgod** [comment]
It works for me, so I will sssume this this issue has been fixed, if the problem still exists, please feel free to reopen it.

<img width="677" alt="image" src="https://github.com/user-attachments/assets/491f2003-01d3-4f61-8bb6-a58199242a65">
