### ISSUE TITLE
The original text cannot be retrieved from the self-built wewe rss

### ISSUE THREAD

**Issue by Mijiu190** [RSSNext/Follow#955]
### Describe the bug

wewe rss 的订阅是link形式的，需要解析link然后再对link内容进行获取

### Feed Info

https://werss.imijiu.top/feeds/MP_WXS_3934234519.atom

### App Type

Electron / App

### Version

0.0.1

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by cyx951211** [comment]
现在有解决么？ 我也遇到同一个问题了

**Comment by hyoban** [comment]
https://github.com/user-attachments/assets/878bc445-b0f9-44bc-9d10-5eef56795903

In the next version, you can achieve this through `view source content` action

**Comment by cyx951211** [comment]
> 屏幕截图.2024-10-18.10.42.29.mp4 
> 在下一个版本中，你可以通过`view source content`操作来实现

今天更新了### Environment

**App Version**: 0.1.0-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.0-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome 版本  

`view source content`这个如何设置  wewe rss 的订阅

**Comment by hyoban** [comment]
I'm guessing these two are not the same problem? Are you having problems importing wewe RSS feed? Please open an new issue and describe your problem.

**Comment by Mijiu190** [comment]
我已经更新至0.1.0，但仍然存在问题，无法像你录屏那样点击就可以查看，仍然需要一个个手动去点查看原文才行，默认还是跳转普通页面如图
![Uploading PixPin_2024-10-25_22-48-59.gif…]()

**Comment by Mijiu190** [comment]
我已经更新至0.1.0，但仍然存在问题，无法像你录屏那样点击就可以查看，仍然需要一个个手动去点查看原文才行，默认还是跳转普通页面如图
![Uploading PixPin_2024-10-25_22-48-59.gif…](http://image.imijiu.top/PixPin_2024-10-25_22-48-59.gif)

**Comment by Mijiu190** [comment]
http://image.imijiu.top/PixPin_2024-10-25_22-48-59.gif
