### ISSUE TITLE
It is recommended to add a button to open with a browser in the upper right

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#956]
### Clear and concise description of the problem

个人习惯于使用网页阅读，现在的版本，需要复制url到浏览器打开

### Suggested solution

我希望在文章的右上角多加一个按钮，点击后直接在浏览器打开

相关issue: #311

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Innei** [comment]
双击 Entry Colmun 的条目或者点击 Entry Content 的标题不能满足你的需求吗？

**Comment by Innei** [comment]
![CleanShot 2024-10-15 at 7  23 59@2x](https://github.com/user-attachments/assets/c182b623-a3ca-45f4-b9e0-00c6536f08f8)

**Comment by hexWars** [comment]
嗷，我不清楚可以这样，谢谢，我将关闭这个issue
