### ISSUE TITLE
When watching a video, if you minimize the window and then open it again, the video will automatically close.

### ISSUE THREAD

**Issue by PrinOrange** [RSSNext/Follow#966]
### Describe the bug

When watching a video, if you minimize the window and then open it again, the video will automatically close. In this case, not only will you lose your video playing progress, but you will also be unable to find which video you just watched right away.

I hope that when I am playing a video, when I minimize the window and then open it again, the video interface will not close.

### Feed Info

rsshub://youtube/user/%40xiao_lin_shuo

### Reproduction Video

https://github.com/user-attachments/assets/d7821eb0-c5ab-4429-9777-74957d21189e

### App Type

Electron

### Version

0.0.1-alpha.21

### Operating System

Windows 10

### Browser Info

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by PrinOrange** [comment]
The picture viewer also has this problem


https://github.com/user-attachments/assets/3b2d5ad1-4b99-4eda-aa55-71be036af4b5

**Comment by hyoban** [comment]
Is this a Windows-only issue?

**Comment by PrinOrange** [comment]
Yes, this bug appears on Windows platform as far. 
And, it is currently found that this bug is only triggered in Electron client. There is no such bug in browser.
