### ISSUE TITLE
power被吞：生成邀请码未成功且power被扣除 & 成就的power显示已领取，实际未发放

### ISSUE THREAD

**Issue by neigesei** [RSSNext/Follow#971]
### Describe the bug

![image](https://github.com/user-attachments/assets/86d60658-4e75-4818-b2f0-90fbd8bde0c8)
![image](https://github.com/user-attachments/assets/c0c9ad85-e0e5-44c7-94c0-c32395c3fc50)
![image](https://github.com/user-attachments/assets/6b9f7eca-058f-4544-8869-edb1a61458bc)

### Environment
**App Version**: 0.0.1-alpha.21
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome

### App Type

Web

### Version

0.0.1-alpha.21

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by xy-galaxy** [comment]
我也刚被吞了，一直刷新也没发放

**Comment by Jinx23333** [comment]
我也是，被吞了！

**Comment by xy-galaxy** [comment]
有方法解决吗？

**Comment by hanzhenlin** [comment]
我刚提的，也被吞了

**Comment by baselin** [comment]
Me too, I was swallowed!

**Comment by anbell2** [comment]
me too

**Comment by Follow-Ai** [comment]
pls I need Invitation code  thanks!

**Comment by xream** [comment]
被吞了 200

**Comment by HoseaDev** [comment]
Me too, I was swallowed!

**Comment by DIYgod** [comment]
Please DM me on Discord for compensation if it has already been deducted. The new transaction has hotfixed this issue. If it still occurs after this message, please let me know.
