### ISSUE TITLE
When will mobile devices be supported in the future?

### ISSUE THREAD

**Issue by In2Star** [RSSNext/Follow#972]
### Clear and concise description of the problem

因为目前Follow只支持PC设备，不是很方便的在通勤时查看所订阅的RSS，请问未来有准备支持移动设备IOS/Android吗？

### Suggested solution

提供适用于移动设备的网页或者相应APP

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Mobile support is planned

**Comment by tylerdurden4285** [comment]
The Android share worldwide is 72%. Please release an adroid app / apk
