### ISSUE TITLE
ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by iceprosurface** [RSSNext/Follow#973]
### Describe the bug

<img width="485" alt="image" src="https://github.com/user-attachments/assets/d2c6f130-5047-42f0-aabc-d6837c748b7e">

### Feed Info

https://iceprosurface.com/rss-full.xml

### App Type

Electron / App

### Version

Follow-0.0.1-alpha.21-macos-universal(F690E6E)

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by crabpi** [comment]
https://feeds.feedburner.com/bbc/top
https://feeds.feedburner.com/bbc/world
these feeds have same issue

**Comment by Rvn0xsy** [comment]
我也出现了同样的问题 :)

**Comment by hyoban** [comment]
The feeds at the given address should have returned to normal. If you still encounter problems, please provide feed info.

![ScreenShot 2024-10-24 10 54 55](https://github.com/user-attachments/assets/5178727b-206c-4c3e-aeda-c432465689f1)
