### ISSUE TITLE
Some feed urls parse failed

### ISSUE THREAD

**Issue by InfiniteOpen** [RSSNext/Follow#979]
### Describe the bug

Thoese feed urls can't subscribed failed, like that
![Snipaste_2024-10-16_16-28-05](https://github.com/user-attachments/assets/6f750aed-7428-4e29-8f24-85c5b3232174)

### Feed Info

https://adityatelange.in/blog/index.xml
https://5stars217.github.io/feed.xml

### App Type

Web

### Version

v0.0.1-alpha.21

### Operating System

Windows 10

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Works for me.

- https://app.follow.is/feed/69290504644699136
- https://app.follow.is/feed/69290504644699137
