### ISSUE TITLE
Description auto-updated after authentication

### ISSUE THREAD

**Issue by HelloJackZhao** [RSSNext/Follow#986]
### Clear and concise description of the problem

I accidentally replaced the Description before authentication, resulting in the current feed source showing the feedid + userid###.
<img width="419" alt="image" src="https://github.com/user-attachments/assets/a4efc97f-9002-40a4-8a61-73b8d4ed8842">

### Suggested solution

Automatically update the Description of the subscription source.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
This description is read from RSS, and it will automatically update here after you update the RSS.
