### ISSUE TITLE
订阅报错

### ISSUE THREAD

**Issue by az0ne** [RSSNext/Follow#991]
### Describe the bug

订阅报错
![image](https://github.com/user-attachments/assets/ea716f82-d72e-4ade-9131-5ec93fea3cfc)

### Feed Info

http://10.1.32.41/reuters/breakingviews/china?format=json

### App Type

Electron / App

### Version

Follow/0.0.1-alpha.21 

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by mrmign** [comment]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/295e981c-99b9-4317-acfc-ce779fb5f53d">

**Comment by rockyyu66** [comment]
<img width="581" alt="image" src="https://github.com/user-attachments/assets/ee941843-1be5-4bd1-8269-7a230ed5bece">

**Comment by walkonbothsides** [comment]
Misskey 和 baraag.net 都提示503

**Comment by pseudoyu** [comment]
Reuters route error is caused by wrong params. According to the table the `breakingviews` section/category doesn't have any sub topic, so we should only use `/reuters/breakingviews` route.

Now the topic filed in Follow can be empty and you can fill the filed with refer to <https://docs.rsshub.app/routes/popular#category-topic-author>

**Comment by pseudoyu** [comment]
> <img alt="image" width="502" src="https://private-user-images.githubusercontent.com/1880532/377699138-295e981c-99b9-4317-acfc-ce779fb5f53d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTUzNzMsIm5iZiI6MTczMDE5NTA3MywicGF0aCI6Ii8xODgwNTMyLzM3NzY5OTEzOC0yOTVlOTgxYy05OWI5LTQzMTctYWNmYy1jZTc3OWZiNWY1M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMDk0NDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBiZTQzMTU2NjFjNjM0YTQyZGYwZDE5MzlhMGJiYzNhM2ExNDMzNzliZTJiNWJhODZiNWMwMzQyZDcwODI5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AnGCKP9OeFFUWsncs7F2tdtS5d8rC_a_xUqIzDKlvBY">

It's not from RSSHub source. Reddit has very strict restrictions on RSS feeds. You may want to consider using a proxy or other methods to avoid these restrictions.

**Comment by pseudoyu** [comment]
> Misskey 和 baraag.net 都提示503

Can you provide the specific routes?

I tried Misskey routes and they work well.

![CleanShot 2024-10-29 at 17 06 53@2x](https://github.com/user-attachments/assets/c85aaa1b-cc3d-4e2c-8043-f41b1a83c5ca)

**Comment by walkonbothsides** [comment]
> > Misskey 和 baraag.net 都提示503
> 
> Can you provide the specific routes? @walkonbothsides
> 
> I tried Misskey routes and they work well.
> 
> ![CleanShot 2024-10-29 at 17 06 53@2x](https://private-user-images.githubusercontent.com/69753389/381076911-c85aaa1b-cc3d-4e2c-8043-f41b1a83c5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDA4NTQsIm5iZiI6MTczMDIwMDU1NCwicGF0aCI6Ii82OTc1MzM4OS8zODEwNzY5MTEtYzg1YWFhMWItY2MzZC00ZTJjLTgwNDMtZjQxYjFhODNjNWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExMTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzljYTkzNDQwMzY4ZWIzMmJiNGMyMDVlZDE3NzFjNjY2MTYzZTMwOWFhODBmNjM4ZGJmYmI0ZTA3ZTRhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CkBky9lgHiAldWgzxFrsArcrBOXw7rg3sOv3AEpAuZ4)

Hello I tried misskey and baraag several minutes ago and they surely work well now, maybe fixed. thanks. 
But now official X userline still don't work.

**Comment by pseudoyu** [comment]
> Hello I tried misskey and baraag several minutes ago and they surely work well now, maybe fixed. thanks. But now official X userline still don't work.

Yes, X has strict restricts so it's not very stable now. We will try to find solutions.
