### ISSUE TITLE
follow Unread count shows error

### ISSUE THREAD

**Issue by hexWars** [RSSNext/Follow#992]
### Describe the bug

打开app后，顶部的
![image](https://github.com/user-attachments/assets/11beb7a6-5e1f-43e4-8263-2c9aa26208f5)
应该显示未读数量对吧，但是实际上，文章几乎一直是0，除非我手动标记文章为未读，我感觉是刷新有问题

以及，下方的订阅分组：
![image](https://github.com/user-attachments/assets/b7807e50-ae6e-41b1-93cf-d7dbbca0ec2b)
理论上应该显示未读的数量的:
![image](https://github.com/user-attachments/assets/fa6cce80-fd46-4f25-b511-ea5df8c9c470)
但是我已经两三天没见过右侧的数字了

我不确定web端是否也有这样的问题

### Environment

**App Version**: 0.0.1-alpha.21
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.21 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

### App Type

Electron / App

### Operating System

Windows 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hexWars** [comment]
我补充一下，这个不显示的原因，可能和我同时拥有多个list（包括私有公有，付费和免费list）有关

**Comment by hyoban** [comment]
Can you check your action settings to see if the silence option is enabled?

![ScreenShot 2024-10-18 09 06 09](https://github.com/user-attachments/assets/82ab54cc-e7f2-48a1-a601-b862fa889973)

**Comment by hexWars** [comment]
是的，我发现我开启了slience（哭

我将关闭这个issue

**Comment by hexWars** [comment]
谢谢你的帮助，祝follow越来越好
