### ISSUE TITLE
In the subscription editing interface, the category list cannot be scrolled using the mouse wheel.

### ISSUE THREAD

**Issue by Sunsh4j** [RSSNext/Follow#993]
### Describe the bug

In the selected area, scrolling with the mouse wheel is not possible; movement can only be achieved by holding the scrollbar pointed to by the arrow.
![20241017_115255_882_copy](https://github.com/user-attachments/assets/e74ed51d-1325-4b68-b0ed-67610f2669c6)

### Feed Info

*

### App Type

Electron / App

### Version

v0.0.1-alpha.21

### Operating System

Windows 11

### Browser Info

chrome

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by xhuajin** [comment]
fix in https://github.com/RSSNext/Follow/commit/5330d49919e580b5af935d9b57267036fc693e6f
