### ISSUE TITLE
The power of the invitation code has been swallowed. How to solve this problem? Is there any compensation in return?

### ISSUE THREAD

**Issue by xy-galaxy** [RSSNext/Follow#997]
申请了个邀请码，power被吞了，目前有什么解决方案吗？能补偿回来吗？

**Comment by boxsuny** [comment]
我也遇到啦，点击生成，但是power消失也没码，四天前反馈，现在也没回复

**Comment by hyoban** [comment]
see https://github.com/RSSNext/Follow/issues/971#issuecomment-2415840540
