### ISSUE TITLE
I want to support pallet minimization

### ISSUE THREAD

**Issue by maxfrees** [RSSNext/Follow#999]
### Clear and concise description of the problem

I want to support pallet minimizationI want to support pallet minimization

### Suggested solution

I want to support pallet minimization

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DIYgod** [comment]
What is pallet minimization?

**Comment by hyoban** [comment]
Do you mean minimizing to the system tray on windows?

**Comment by maxfrees** [comment]
Yes, zoom out to the bottom right corner of Windows

**Comment by maxfrees** [comment]
Just like WeChat, tapping the x will take you to the bottom right corner instead of closing the app directly
